### ISSUE TITLE
Email forgot password

### ISSUE THREAD

**Issue by dhanykoe** [crocodic-studio/crudbooster#10]
![password](https://cloud.githubusercontent.com/assets/5835632/17455002/33159646-5bdd-11e6-92f7-91b52c7b7ef0.jpg)
When trying forgot password, i have received an email but without new password, only showing 
password : 
try to login but password already changed.

**Comment by fherryfherry** [comment]
have you already tried for the second time?

**Comment by dhanykoe** [comment]
yes... i tried 3-4 times, new password still nothing/blank

**Comment by fherryfherry** [comment]
please download the latest crudbooster
