### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data

### ISSUE THREAD

**Issue by dandandan1983** [crocodic-studio/crudbooster#101]
CREATE / EDIT module. Step 3 Form Display. Then i change type of any column and select any type of field , i get an error in firefox:

![errot](https://cloud.githubusercontent.com/assets/1750383/21468570/696c3380-ca32-11e6-90dd-5e5ce12e7b40.png)

I use laravel 5.3.16 and just your crudBooster

**Comment by dandandan1983** [comment]
I fixed this problem.

step3.blade.php
216-217 row
remove
>	            //$.get("{{CRUDBooster::mainpath('type-info')}}/"+v,function(response) {
>	            //	var data = JSON.parse(response);
add	
			$.getJSON("{{CRUDBooster::mainpath('type-info')}}/"+v,function(data) {

**Comment by fherryfherry** [comment]
bug fixed at master
