### ISSUE TITLE
can't download pdf file, on upload Input Type

### ISSUE THREAD

**Issue by wisnupri** [crocodic-studio/crudbooster#1017]
when I click the Download File link,

error appears
Sorry, the page you are looking for could not be found.
1/1 NotFoundHttpException in RouteCollection.php line 161:

pdf file successfully uploaded to folder \storage\app

help me, thanks

File:
![screenshot_1](https://user-images.githubusercontent.com/19657805/35089366-55426e28-fc69-11e7-9ef9-3a34f048a1e4.jpg)
Download Link:
![screenshot-2018-1-18 bbpi erp detail surat tugas](https://user-images.githubusercontent.com/19657805/35089368-5581a6a6-fc69-11e7-84e1-53d23d9578ab.png)
Problem:
![screenshot-2018-1-18 http localhost](https://user-images.githubusercontent.com/19657805/35089369-55c5a964-fc69-11e7-9d4e-041f393ef4ee.png)

**Comment by Ade-Yohanes** [comment]
How To Display Document - download file in in detail view?

i'm show download document on table collom but can't donwnload file?
