### ISSUE TITLE
Call to undefined function Unisharp\Laravelfilemanager\controllers\get_my_id()

### ISSUE THREAD

**Issue by dandandan1983** [crocodic-studio/crudbooster#102]
I create a module. I set a field as $this->form[] = ["label"=>"Member Photo","name"=>"img_path","type"=>"filemanager","filemanager_type"=>"image"];
Then i fill data into module click "choose a file" and i get 

Whoops, looks like something went wrong.
1/1 FatalErrorException in LfmController.php line 123: Call to undefined function Unisharp\Laravelfilemanager\controllers\get_my_id()
    in LfmController.php line 123

added:

> Barryvdh\DomPDF\ServiceProvider::class,

> Maatwebsite\Excel\ExcelServiceProvider::class,

> Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class,

> Intervention\Image\ImageServiceProvider::class,

> crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class,

And 

'PDF'  => Barryvdh\DomPDF\Facade::class,
'Excel' => Maatwebsite\Excel\Facades\Excel::class,
'Image' => Intervention\Image\Facades\Image::class,
'CRUDBooster' => crocodicstudio\crudbooster\helpers\CRUDBooster::class,

I use laravel 5.3.16 and just your crudBooster

![error](https://cloud.githubusercontent.com/assets/1750383/21468600/c5d0d224-ca33-11e6-8499-93e9fc76c61f.png)

**Comment by mrkabbaj** [comment]
add this to Helper.php

```
if(!function_exists('get_my_id')){
	function get_my_id()
	{
		return \Auth::user()->id;
	}
}
```

**Comment by FaizalAmiruddinR2** [comment]
where is Helper.php ?

**Comment by mrkabbaj** [comment]
@FaizalAmiruddinR2 
/vendor/crocodicstudio/crudbooster/src/helpers/Helper.php

**Comment by fherryfherry** [comment]
hi thank you for your attention, i have fixed this problem at master, or wait for new release

**Comment by FaizalAmiruddinR2** [comment]
ok thanks
