### ISSUE TITLE
Modify API params

### ISSUE THREAD

**Issue by nyel-dev** [crocodic-studio/crudbooster#1024]
**Currently creating API using crudbooster API generator. How do I create an API params if the parameter I would to create is not a column of the selected table? Hope someone will help. Really need this badly.** 

@fherryfherry @imanghafoori1 @salihkiraz @davodavodavo3 @wa7eedem 

THANKS IN ADVANCE GUYS

**Comment by nyel-dev** [comment]
Found it. CB offers custom/not in table parameter

**Comment by abenzakour** [comment]
Where did you found it?  Is there a documentation of api part?  

Can you give me an example?

**Comment by ada27** [comment]
can you show me, how to set the param from any table ?
