### ISSUE TITLE
API Authentication issue

### ISSUE THREAD

**Issue by ed-r4d1cal** [crocodic-studio/crudbooster#1026]
When i try to make a request on a API resourse with wrongs header params i get the following response

<img width="949" alt="schermata 2018-01-24 alle 18 41 54" src="https://user-images.githubusercontent.com/20775774/35347728-4cb68ee8-0136-11e8-86ca-22ddbab5522b.png">

But the response show a list of valid token! If i copy and past the server_token in the X-Authorization-Token i get the authorization

<img width="929" alt="schermata 2018-01-24 alle 18 41 38" src="https://user-images.githubusercontent.com/20775774/35347895-bf9d0428-0136-11e8-9968-95f053c15d2f.png">

I hope I'm wrong but this seems to be a serious security problem because anybody can get authorization without know the secret key

**Comment by numlock1052** [comment]
I agree i am testing crudbooster and i have exactly same problem, and when i use the secret key it's not work correctly i think the test of the key it's wrong.
