### ISSUE TITLE
404 admin not found

### ISSUE THREAD

**Issue by abu7elo** [crocodic-studio/crudbooster#103]
Hi All,

I have installed CRUDBOOSTER with Laravel Framework version 5.3.28 by following the site guide 
"http://crudbooster.com/doc/5.3/installation".

Everything is installed correctly, but when i navigate to /admin route i have got 404 error page.

"Server Logs"

`./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    Failed to download psr/http-message from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing psr/http-message (1.0.1)
    Cloning f6561bf28d520154e4b0ec72be95418abe6d9363

    Failed to download guzzlehttp/psr7 from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing guzzlehttp/psr7 (1.3.1)
    Cloning 5c6447c9df362e8f8093bda8f5d8873fe5c7f65b

    Failed to download intervention/image from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing intervention/image (2.3.8)
    Cloning 4064a980324f6c3bfa2bd981dfb247afa705ec3c

    Failed to download intervention/imagecache from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing intervention/imagecache (2.3.3)
    Cloning 7936b90e695daee1aafbd25221815352ef97bcbc

    Failed to download unisharp/laravel-filemanager from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing unisharp/laravel-filemanager (1.6.2)
    Cloning 124f07151dd47343583848ebfd4f047cd4ca9bd0

    Failed to download phpoffice/phpexcel from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing phpoffice/phpexcel (1.8.1)
    Cloning 372c7cbb695a6f6f1e62649381aeaa37e7e70b32

    Failed to download tijsverkoyen/css-to-inline-styles from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing tijsverkoyen/css-to-inline-styles (2.2.0)
    Cloning ab03919dfd85a74ae0372f8baf9f3c7d5c03b04b

    Failed to download maatwebsite/excel from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing maatwebsite/excel (2.1.8)
    Cloning d9c398f7eba0ac9caf9c104dd0d55bd6a5ff231e

    Failed to download phenx/php-svg-lib from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing phenx/php-svg-lib (0.1)
    Cloning b419766515b3426c6da74b0e29e93d71c4f17099

    Failed to download phenx/php-font-lib from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing phenx/php-font-lib (0.4)
    Cloning b8af0cacdc3cbf1e41a586fcb78f506f4121a088

    Failed to download dompdf/dompdf from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing dompdf/dompdf (v0.7.0)
    Cloning 5c98652b1a5beb7e3cc8ec35419b2828dd63ab14

    Failed to download barryvdh/laravel-dompdf from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing barryvdh/laravel-dompdf (v0.7.0)
    Cloning 9b8bd179262ad6b200a11edfe7b53516afcfc42a

    Failed to download crocodicstudio/crudbooster from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini
    Now trying to download from source
  - Installing crocodicstudio/crudbooster (v5.3.0.3)
    Cloning 045fcf111b06125b197972cbb9746f412cbdb546

intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
unisharp/laravel-filemanager suggests installing ext-imagick (to use Imagick based image processing.)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled class file has been removed.
root@DEV-TAKHZEEN:/var/www/html/test# nano config/app.php 
root@DEV-TAKHZEEN:/var/www/html/test# php artisan vendor:publish
Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Copied File [/vendor/barryvdh/laravel-dompdf/config/dompdf.php] To [/config/dompdf.php]
Copied File [/vendor/maatwebsite/excel/src/config/excel.php] To [/config/excel.php]
Copied File [/vendor/unisharp/laravel-filemanager/src/config/lfm.php] To [/config/lfm.php]
Copied Directory [/vendor/unisharp/laravel-filemanager/public] To [/public/vendor/laravel-filemanager]
Copied Directory [/vendor/unisharp/laravel-filemanager/src/views] To [/resources/views/vendor/laravel-filemanager]
Copied File [/vendor/intervention/image/src/config/config.php] To [/config/image.php]
Copied File [/vendor/intervention/imagecache/src/config/config.php] To [/config/imagecache.php]
Copied File [/vendor/crocodicstudio/crudbooster/src/configs/crudbooster.php] To [/config/crudbooster.php]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/localization] To [/resources/lang]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/assets] To [/public/vendor/crudbooster]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/database] To [/database]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/laravel-filemanager] To [/vendor/unisharp/laravel-filemanager]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/laravel-filemanager/public] To [/public/vendor/laravel-filemanager]
Copied File [/vendor/crocodicstudio/crudbooster/src/userfiles/views/vendor/crudbooster/type_components/readme.txt] To [/resources/views/vendor/crudbooster/type_components/readme.txt]
Copied File [/vendor/crocodicstudio/crudbooster/src/userfiles/controllers/CBHook.php] To [/app/Http/Controllers/CBHook.php]
Copied File [/vendor/crocodicstudio/crudbooster/src/userfiles/controllers/AdminCmsUsersController.php] To [/app/Http/Controllers/AdminCmsUsersController.php]
Publishing complete for tag []!
root@DEV-TAKHZEEN:/var/www/html/test#  php artisan vendor:publish --provider="crocodicstudio\crudbooster\CRUDBoosterServiceProvider" --force
Copied File [/vendor/crocodicstudio/crudbooster/src/configs/crudbooster.php] To [/config/crudbooster.php]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/localization] To [/resources/lang]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/assets] To [/public/vendor/crudbooster]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/database] To [/database]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/laravel-filemanager] To [/vendor/unisharp/laravel-filemanager]
Copied Directory [/vendor/crocodicstudio/crudbooster/src/laravel-filemanager/public] To [/public/vendor/laravel-filemanager]
Copied File [/vendor/crocodicstudio/crudbooster/src/laravel-filemanager/src/config/lfm.php] To [/config/lfm.php]
Copied File [/vendor/crocodicstudio/crudbooster/src/laravel-filemanager/src/views/script.blade.php] To [/resources/views/vendor/laravel-filemanager/script.blade.php]
Copied File [/vendor/crocodicstudio/crudbooster/src/userfiles/views/vendor/crudbooster/type_components/readme.txt] To [/resources/views/vendor/crudbooster/type_components/readme.txt]
Publishing complete for tag []!
root@DEV-TAKHZEEN:/var/www/html/test# php artisan migrate --seed
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2016_08_07_145904_add_table_cms_apicustom
Migrated: 2016_08_07_150834_add_table_cms_dashboard
Migrated: 2016_08_07_151210_add_table_cms_logs
Migrated: 2016_08_07_152014_add_table_cms_privileges
Migrated: 2016_08_07_152214_add_table_cms_privileges_roles
Migrated: 2016_08_07_152320_add_table_cms_settings
Migrated: 2016_08_07_152421_add_table_cms_users
Migrated: 2016_08_07_154624_add_table_cms_moduls
Migrated: 2016_08_17_225409_add_status_cms_users
Migrated: 2016_08_20_125418_add_table_cms_notifications
Migrated: 2016_09_04_033706_add_table_cms_email_queues
Migrated: 2016_09_16_035347_add_group_setting
Migrated: 2016_09_16_045425_add_label_setting
Migrated: 2016_09_17_104728_create_nullable_cms_apicustom
Migrated: 2016_10_01_141740_add_method_type_apicustom
Migrated: 2016_10_01_141846_add_parameters_apicustom
Migrated: 2016_10_01_141934_add_responses_apicustom
Migrated: 2016_10_01_144826_add_table_apikey
Migrated: 2016_11_14_141657_create_cms_menus
Migrated: 2016_11_15_132350_create_cms_email_templates
Migrated: 2016_11_15_190410_create_cms_statistics
Migrated: 2016_11_17_102740_create_cms_statistic_components
Please wait updating the data...
Seeded: Cms_usersSeeder
Seeded: Cms_modulsSeeder
Seeded: Cms_privilegesSeeder
Seeded: Cms_privileges_rolesSeeder
Seeded: Cms_settingsSeeder
Seeded: CmsEmailTemplates
Updating the data completed !`

Please help me.

**Comment by rebootcode** [comment]
This looks like some of the packages were failed to download. Re-install package again and make sure none of the packages failed to download.

**Comment by igronus** [comment]
The same problem for me. Versions are: crocodicstudio/crudbooster: 5.4.0.10, php: 7.0.22, laravel: 5.5.18. Using apache. Other things from laravel works correctly.

**Comment by BognarB** [comment]
same for me

**Comment by abu7elo** [comment]
@BognarB 

Enable re-write mod for Apache server 
Check your virtual host file and make sure to allow from All
