### ISSUE TITLE
wysiwyg field type content not properly displayed on a child field

### ISSUE THREAD

**Issue by rperdomo** [crocodic-studio/crudbooster#104]
I used a wysiwyg type for the child description field on the child module, it works just fine:
![wysiwyg002](https://cloud.githubusercontent.com/assets/3058595/21533151/8c4a4e6e-cd25-11e6-966b-5efe6edad5f6.png)

Then I added a child type to the parent module using the previous child module as sub-module, but when I click to see the details, the wysiwyg type doesn't render properly, instead of that, is shows the HTML raw code:  
![wysiwyg001](https://cloud.githubusercontent.com/assets/3058595/21533113/4abbdf58-cd25-11e6-866c-998290b1322c.png)

**Comment by fherryfherry** [comment]
thanks, bug fixed at master
