### ISSUE TITLE
How to change the text of the logo to a picture

### ISSUE THREAD

**Issue by nyel-dev** [crocodic-studio/crudbooster#1041]

**Comment by Nsobi** [comment]
edit the picture/logo the replace to this path if your using xampp change the root folder of your application
in my case below you can change intelportal
C:\xampp\htdocs\intelportal\vendor\crocodicstudio\crudbooster\src\assets\assets\logo_crudbooster.png

**Comment by nyel-dev** [comment]
is it gonna be fine if I edit the vendor files of crudbooster?

**Comment by Nsobi** [comment]
Its fine i tried in three webapplications works fine until now
