### ISSUE TITLE
Add and Edit Some Of Form Field (textfield) From Another Database

### ISSUE THREAD

**Issue by esdayehezkiel** [crocodic-studio/crudbooster#1051]
Hi, i want to add and edit data using more than one database in one form. How to do this? I'm trying this one (https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-inject-postdata.md) but not working.

FYI : 
CrudBooster 5.4
Laravel 5.5

Thank You.

**Comment by nyel-dev** [comment]
You can use hook methods for adding, editing, and deleting. 
In those methods, you can insert new data or edit data from a different DB using Eloquent or raw SQL
