### ISSUE TITLE
How to host this project on shared hosting 

### ISSUE THREAD

**Issue by aadhilpm** [crocodic-studio/crudbooster#1054]
- Operating system (name, version and architecture)
- Web server (name, version and architecture)
- Browser (name, version and architecture)
- CRUDBooster version
- Laravel version
- What is the problem?
- How should it happen? What was the expected behavior?
- Tell how to reproduce the problem step by step
- If possible, take screenshots or send snippets of code

**Comment by rallisf1** [comment]
You need to finish it locally and then you can host it anywhere with php 5.6+ and mysql, shared hosting or not. The disadvantage is when you need to make db or package updates you need to do it locally and reupload as you can't use artisan/composer on shared hosting.

**Comment by aadhilpm** [comment]
I tried that but getting HTTP ERROR 500 or Blank white screen

**Comment by rallisf1** [comment]
check the web server (apache?) error logs then

**Comment by azarzaza** [comment]
when new updates came you have to upload the updated file in shared hosting and make route for running artisan command like this 

`Route::get('/cc',function(){
     Artisan::call('cache:clear');
    echo 'success';
});
Route::get('/ccc', function() {
    Artisan::call('config:cache');
    echo 'success cache';
});
Route::get('/op', function() {
    Artisan::call('optimize');
    echo 'success optimize';
});
Route::get('/vc', function() {
    Artisan::call('view:clear');
    echo 'success view clear';
});
`

**Comment by aadhilpm** [comment]
I tried with laravel 5.4 worked fine!
