### ISSUE TITLE
Cancelling the flow of POST in API

### ISSUE THREAD

**Issue by nyel-dev** [crocodic-studio/crudbooster#1056]
My current flow is I have data to POST to the database. But I need to check first if that user exists on the database,. How do I implement this? How do I cancel the flow of API if the user does not exist?

**Comment by fherryfherry** [comment]
You can put your code of validation at hook_before method, in the related api controller
Override the response api by using like 
```php
function hook_before(&$postdata) {
    <!--Your validation code here-->
     if(condition) {
       $resp = response()->json(['api_status'=>0,'api_message'=>'Your own message']);
       $resp->send();
       exit;
     }
}
```
