### ISSUE TITLE
Bug fix on admin_template.blade.php

### ISSUE THREAD

**Issue by fsclaro** [crocodic-studio/crudbooster#1058]
- Operating system Mac High Sierra - x64
- Web server Apache, 2.4
- Browser Safari, 11.0.3
- CRUDBooster version 5.4.0.13
- Laravel version 5.5
- What is the problem? I found a bug on file admin_template.blade.php at lines 113 ~ 114. The lines are:

@if($ib['onMouseOever']) onMouseOever='return {{$ib["onMouseOever"]}}' @endif
@if($ib['onMoueseOut']) onMoueseOut='return {{$ib["onMoueseOut"]}}' @endif

And the correct will be:

@if($ib['onMouseOver']) onMouseOver='return {{$ib["onMouseOver"]}}' @endif
@if($ib['onMouseOut']) onMouseOut='return {{$ib["onMouseOut"]}}' @endif

Tks

**Comment by imanghafoori1** [comment]
@fsclaro 
Thanks for reporting.
Can you help us debugging the dev-master branch ?
