### ISSUE TITLE
Privileges per user and column 

### ISSUE THREAD

**Issue by thierry-sterrenburg** [crocodic-studio/crudbooster#106]
Thanks for the great application. While exploring the application, I was wondering if it possible to connect certain rows in a table to one role and the next row to another role. This will lead to user specific visibilty of parts of the table. Besides I want to grant some users to edit only one column in the table. Are those two features implemented or do I need to do some custom configuration under the hood.

Thanks in advance.

**Comment by fherryfherry** [comment]
Sorry you can't, but you can modify by using hook method
http://crudbooster.com/doc/5.3/hook-method - **hook_row_index**
