### ISSUE TITLE
How to export to excel

### ISSUE THREAD

**Issue by nyel-dev** [crocodic-studio/crudbooster#1063]

**Comment by rallisf1** [comment]
In module wizard, step 4 last option is "Show Button Export", make it TRUE and save. Then you can click the export button at top of your table in the index view of the module to export.

**Comment by topo79** [comment]
@rallisf1 Exporting to xls is getting me the following error when I open the exported file:

![image](https://user-images.githubusercontent.com/30064865/43976404-6debf742-9cae-11e8-842c-d166f7d1fb31.png)

I created another function for a different export needs that I have using this same library and it is not generating any error, cant find on CB the problem... 

I am using latest php, laravel and CB on windows 2016
