### ISSUE TITLE
Do not create tables in the database :

### ISSUE THREAD

**Issue by avlima** [crocodic-studio/crudbooster#1064]
Great design, pity that when we think of crud generator it comes to mind that the system would create the tables, which is not the case.

Crud generator that needs tables already created in the database? ends up losing the title of generator of crud then :(

**Comment by rallisf1** [comment]
Well, it is still CRUD, just the Create part is not from the gui and you use artisan from the command line. Plus it's free and opensource, don't expect it to be perfect.

**Comment by imanghafoori1** [comment]
New ideas are welcome.
Please make proposal and clearly define what you think about it.
or contribute to the project source code directly.
Thanks
