### ISSUE TITLE
Image files not opening ?

### ISSUE THREAD

**Issue by azarzaza** [crocodic-studio/crudbooster#1069]
i have worked small project admin panel is separated 
main website is separated 
in this main site i have create a sub directory and copy paste the public folder(admin) file in the website 
and change the bootstrap path, both admin and website in same path ,but admin is in root folder for security purpose 
my problem is when access the upload image through admin path its opening but opening through website path small images opening little bit more sizes image not open 

here i attached the image for reference 
![web](https://user-images.githubusercontent.com/23259321/37117772-2674f554-2278-11e8-96ba-cacd35043d50.PNG)
this is from website 
![admin](https://user-images.githubusercontent.com/23259321/37117803-45ec7132-2278-11e8-9ee7-9aa362e68b4b.PNG)
this from admin

why should not access the other files in from the website path

**Comment by paceobed** [comment]
Please check your imagr patch

**Comment by azarzaza** [comment]
i have solved this problem 
we have to create a symlink for for storage folder then it should be work
