### ISSUE TITLE
boolean input form

### ISSUE THREAD

**Issue by newbie15** [crocodic-studio/crudbooster#107]
harusnya untuk input tipe boolean di database form bisa otomatis memilih ke radio button, dimana radio button bisa di set label ataupun valuenya karena tidak semua kasus label dan valuenya sama.

**Comment by fherryfherry** [comment]
Hi
Ya saat ini tipe boolean ataupun enum tidak tersedia

Ya tetap bisa mengubah value dan label nya via form scafolding nya.
Silahkan baca segment form scafolding.
Pada tanggal 3 Jan 2017 17.20, "newbie15" <notifications@github.com>
menulis:

**Comment by newbie15** [comment]
sementara ini saya rubah boolean ke string, kemudian pakai radio button.

terima kasih penjelasannya.

apa tidak ada doc versi indonesianya? kalaupun agak kesulitan buat doc versi english yang lengkap dan detail step-by-step bisa lah minta tolong untuk buatkan ke komunitas. crocodic studio buat versi indonesia aja.

**Comment by fherryfherry** [comment]
Ada versi indonesia nya coba lihat lagi toolbar atas kanan
Pada tanggal 4 Jan 2017 09.23, "newbie15" <notifications@github.com>
menulis:

**Comment by newbie15** [comment]
oke terima kasih banyak..
