### ISSUE TITLE
Problems when trying to unckeck privileges

### ISSUE THREAD

**Issue by andreshg112** [crocodic-studio/crudbooster#1074]
- Operating system (name, version, and architecture)
Zorin OS 12.3 (64 bits) (It's based on Ubuntu 16.04)

- Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.2.1 mod_perl/2.0.8-dev Perl/v5.16.3 

- Firefox Quantum 58.0.2 (64-bit). It also happens on Chromium Versión 64.0.3282.167 (Build official) Built on Ubuntu, running on Zorin 12 (64 bits)

- CRUDBooster v5.4.0.14

- Laravel 5.5.39

- What is the problem?
1. Try to uncheck "Ver" for "Archivos de implicados". (It doesn't work)
2. Correctly unchecked "Leer" and "Actualizar" for "Fotografías de placas". (It does)
3. Try to uncheck all for "Infracciones". (It doesn't)
![2018-03-28 20-03-56](https://user-images.githubusercontent.com/15859884/38064538-11edbefc-32c4-11e8-924a-1fe3f77dfb49.gif)

- How should it happen? What was the expected behavior?
1. Unchek "Ver" for "Archivos de implicados".
2. It worked.
3. Uncheck all for "Infracciones".

I've tested with two different and new projects (v5.4.0.13, v5.4.0.14 and v5.4.0.16).
However, It works perfectly with https://crudbooster.com/store/crudbooster-sample, even if I do `composer update`. I noticed that It has CRUDBooster v5.3.2.17

**Comment by andreshg112** [comment]
Now I have another problem when I try to uncheck "Gestión de usuarios", It doesn't change.
![image](https://user-images.githubusercontent.com/15859884/37248259-4a8a2278-249b-11e8-8f7a-9ddb80a2e184.png)

**Comment by andreshg112** [comment]
These are the problems in a Gif:
1. Try to uncheck "Ver" for "Archivos de implicados". []
2. Correctly unchecked "Leer" and "Actualizar" for "Fotografías de placas". [x]
3. Try to uncheck all for "Infracciones". []
![2018-03-28 20-03-56](https://user-images.githubusercontent.com/15859884/38064538-11edbefc-32c4-11e8-924a-1fe3f77dfb49.gif)

**Comment by andreshg112** [comment]
@imanghafoori1 @fherryfherry

**Comment by andreshg112** [comment]
If I copy the controller from v5.3 to v5.4, It works.

If I don't want to change the whole controller, It works when I change this:
```php
public function postEditSave($id)
{
    // ...
    $priv = Request::input("privileges");
    
    // Added the next line
    DB::table("cms_privileges_roles")->where("id_cms_privileges",$id)->delete();
    
    if ($priv) {
        // ...
    }
}
```

**Comment by andreshg112** [comment]
I created a pull request. I hope it helps!
https://github.com/crocodic-studio/crudbooster/pull/1105

**Comment by Devamit2016** [comment]
how to keep modified controller file in laravel app/http/controllers?
