### ISSUE TITLE
在PHP7.2有问题

### ISSUE THREAD

**Issue by bun520** [crocodic-studio/crudbooster#1077]
因为7.2 的 count()验证更加严格 所以在增加菜单的时候会出现下面的问题
具体文件是 vendor/crocodicstudio/crudbooster/src/views/sidebar.blade.php  34行

Warning:  count(): Parameter must be an array or an object that implements Countable

谢谢～

**Comment by fherryfherry** [comment]
Yeap that is issue on php 7.2,, we have to check the variable is exist before use count() function

**Comment by andreshg112** [comment]
Created a pull request for this:
https://github.com/crocodic-studio/crudbooster/pull/1106
