### ISSUE TITLE
Problem with making a graded select boxes in A form (parent select->child select

### ISSUE THREAD

**Issue by mommand** [crocodic-studio/crudbooster#1097]
I have two tables main categories and sub-categories. I want to pick data from child select based on parent select, it doesn't pick the data. here is my code:
$this->form[] = ['label'=>'Course Type','name'=>'category','type'=>'select','validation'=>'required','width'=>'col-sm-6','datatable'=>'course_categories,category_name'];
			$this->form[] = ['label' => 'Course Category', 'name' => 'sub_categories','type' =>'select','width'=>'col-sm-6','datatable'=>'course_sub_categories,sub_category_name','parent_select'=>'category'];
![screen shot 2018-03-26 at 4 12 14 pm](https://user-images.githubusercontent.com/4653953/37904277-82c90704-3110-11e8-9139-ce1d873cdaf4.png)
Anyone help me?

**Comment by juniorgeba** [comment]
sub_categories tem que esta na tabela courses_categories

**Comment by mommand** [comment]
Thank you, it works now, the problem was with the field name.
