### ISSUE TITLE
Why wysiwyg is not show in newest version?

### ISSUE THREAD

**Issue by phpcmsapp** [crocodic-studio/crudbooster#1099]
- Operating system (win10)
- Web server (apache 2.4)
- Browser (chrome65)
- CRUDBooster v5.4.0.16
- Laravel 5.5
- i choose the field in wysiwyg type is not show in add/edit form
- on CRUDBooster v5.4.0.15 no problem

**Comment by vicbear** [comment]
Rename "summemote.min.js" to "summemote.js" on the path "/public/vendor/crudbooster/assets/summernote/"

**Comment by imanghafoori1** [comment]
fixed
Thanks for reporting.
