### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php when fresh install

### ISSUE THREAD

**Issue by harimayco** [crocodic-studio/crudbooster#11]
![TokenMismatchException](http://image.prntscr.com/image/a70bb185ffa845b38eff92f0c7f19647.png)
web server info : 
- Apache
- PHP Version 5.6.14
- run with php artisan command port 8000

http://localhost:8000/execute.php?type=save_db return 500 (Internal Server Error) : TokenMismatchException in VerifyCsrfToken.php

**Comment by fherryfherry** [comment]
Bug fixed

**Comment by harimayco** [comment]
still facing this error after git pull :grey_question:

**Comment by kristiardyguntoro** [comment]
You will also get this error even if you did fresh install a CB based app when you are logged in into other CB based app. The solution is whether to open other CB based app in other browser or logged out from your current application to log in into other CB based app
