### ISSUE TITLE
FatalThrowableError in SettingsController.php line 77:

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#110]
FatalThrowableError in SettingsController.php line 77:
Call to undefined function crocodicstudio\crudbooster\controllers\first_row()

	function getDeleteFileSetting() {
			$id = g('id');
			$row = first_row('cms_settings', $id);
			if(Storage::exists($row->content)) Storage::delete($row->content);
			DB::table('cms_settings')->where('id',$id)->update(['content'=>NULL]);
			CRUDBooster::redirect(Request::server('HTTP_REFERER'),trans('alert_delete_data_success'),'success');
	}

#>> Errors shows when trying to remove/delete logo from Application settings.. please help.

**Comment by fherryfherry** [comment]
Bug fixed at master

**Comment by tomatoe45** [comment]
Thanks so much.
