### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by juniorgeba** [crocodic-studio/crudbooster#1101]
How to create a notification for certain users?

![01](https://user-images.githubusercontent.com/36745303/37982570-58c19a9a-31c7-11e8-83d5-d647ac47eee6.png)

**Comment by juniorgeba** [comment]
In which controller do I put the code?

**Comment by jdredondo** [comment]
from where you want to generate the notification

**Comment by jdredondo** [comment]
here it is [Helpers](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/helpers.md)

**Comment by imanghafoori1** [comment]
Ok it seems to be solved.

**Comment by imanghafoori1** [comment]
@jdredondo Could you please help in debugging the dev-master branch ?

**Comment by jdredondo** [comment]
of course @imanghafoori1
