### ISSUE TITLE
Command "optimize" is not defined.

### ISSUE THREAD

**Issue by andreshg112** [crocodic-studio/crudbooster#1104]
- Operating system (name, version, and architecture)
Zorin OS 12.3 (64 bits) (It's based on Ubuntu 16.04)

- Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.2.1 mod_perl/2.0.8-dev Perl/v5.16.3 

- Firefox Quantum 58.0.2 (64-bit). It also happens on Chromium Versión 64.0.3282.167 (Build official) Built on Ubuntu, running on Zorin 12 (64 bits)

- CRUDBooster v5.4.0.16

- Laravel 5.6.14
- What is the problem?
Command "optimize" is not defined.
- How should it happen? What was the expected behavior?
No error after installing. I think that the problem happens because Laravel 5.6 doesn't support "optimize" command. So, in a next release of CRUDBooster it could be removed if Laravel version is >= 5.6.
- Tell how to reproduce the problem step by step
`php artisan crudbooster:install`
- If possible, take screenshots or send snippets of code
![image](https://user-images.githubusercontent.com/15859884/38066040-b5622b84-32cb-11e8-81af-109033c26521.png)

**Comment by andersondeoliveiramachado** [comment]
https://laravel-news.com/laravel-5-6-removes-artisan-optimize
