### ISSUE TITLE
http://crudbooster.com/doc/5.3/installation errors

### ISSUE THREAD

**Issue by Thunderpoet** [crocodic-studio/crudbooster#111]
SEQUENCE of Steps 1 & 2 & 3 is wrong:

1. Open a terminal, navigate to the folder you created porjek laravel. Run the following command:

$ composer require crocodicstudio/crudbooster=5.3.0.*

2. Add the following class provider dependency on config file / app.php
Barryvdh\DomPDF\ServiceProvider::class,
Maatwebsite\Excel\ExcelServiceProvider::class,
Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class,
Intervention\Image\ImageServiceProvider::class,
crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class,

3. Add the following facades in section "Facades" config file / app.php
'PDF' => Barryvdh\DomPDF\Facade::class,
'Excel' => Maatwebsite\Excel\Facades\Excel::class,
'Image' => Intervention\Image\Facades\Image::class,
'CRUDBooster' => crocodicstudio\crudbooster\helpers\CRUDBooster::class,

PROBLEM:
Step 1 Can Not be Run and Work BEFORE Step 2 and 3

SOLUTION:

Steps 2. and 3 should be Step 1 & 2
Step 1 should be Step 3

User should change app.php and save those lines FIRST before running Terminal.
Also One More NOTE: app.php now names "Facades" as "aliases"

**Comment by fherryfherry** [comment]
It should not be a problem and the steps in the documentation is correct
