### ISSUE TITLE
Installation failing on Crudbooster intervention/imagecache

### ISSUE THREAD

**Issue by Thunderpoet** [crocodic-studio/crudbooster#112]
PHP version: 7.0.12 with php.ini modules installed such as these--
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_gd2.dll

But crudbooster installation can not get past these errors about "intervention/image 2.*.* "
![crudbooster-composer-problem-dec9-17](https://cloud.githubusercontent.com/assets/15911806/21781742/1dc24c90-d6b1-11e6-9ff0-65b55a242b46.JPG)

**Comment by aramirez92** [comment]
You need install ext-file info. Try restarting the service and run composer again.
