### ISSUE TITLE
When many menus start with the same word, both are actives

### ISSUE THREAD

**Issue by andreshg112** [crocodic-studio/crudbooster#1126]
- Operating system (name, version, and architecture)
Zorin OS 12.3 (64 bits) (It's based on Ubuntu 16.04)

- Web server (name, version, and architecture)
Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.2.1 mod_perl/2.0.8-dev Perl/v5.16.3 

- Browser (name, version, and architecture)
-- Firefox Quantum 59.0.2 (64-bit)

- CRUDBooster version
v5.4.0.16

- Laravel version
5.5.40

- What is the problem?
When many menus start with the same word, both are actives.

- How should it happen? What was the expected behavior?
Just one menu should be active.

- Tell how to reproduce the problem step by step
Create two menus named "Direcciones" and "Direcciones validadas". Then go to "Direcciones validadas". Both links are active.

- If possible, take screenshots or send snippets of code
![image](https://user-images.githubusercontent.com/15859884/38176130-0ccbe816-35af-11e8-9fed-a23af8fc0798.png)

I notice that the problem happens because of the asterisk in the condition Request::is($child->url_path."\*\") in line 41 in the archive vendor/crocodicstudio/crudbooster/src/views/sidebar.blade.php
![image](https://user-images.githubusercontent.com/15859884/38176165-9e2fcd18-35af-11e8-8e08-31efbb160d99.png)
"admin/direcciones*" matches "admin/direcciones" == true
"admin/direcciones*" matches "admin/direcciones_validadas" == true

**Comment by andreshg112** [comment]
I created a pull request for this: https://github.com/crocodic-studio/crudbooster/pull/1124/commits

**Comment by jdredondo** [comment]
if you delete the asterisk, the submodules of the main module will not be highlighted, for example, when you are "editing" the menu will not be active

**Comment by andreshg112** [comment]
I found a way for solving it changing the condition in the line 41:
`Request::is($child->url_path .= !ends_with(Request::decodedPath(), $child->url_path) ? "/*" : "" )`

I don't really like how it looks but it works for every menu and submenu with their actions.
 @fherryfherry, @jdredondo, What do you think?

**Comment by andreshg112** [comment]
Created a new pull request (https://github.com/crocodic-studio/crudbooster/pull/1155)
@fherryfherry , It's solved!
