### ISSUE TITLE
BUG: Not able to see routes list

### ISSUE THREAD

**Issue by Muhammadinaam** [crocodic-studio/crudbooster#113]
when i run command `php artisan route:list` it gives error as shown below:

![bug](https://cloud.githubusercontent.com/assets/22542738/21796986/3b34f412-d72e-11e6-8d89-041d97f5959f.png)

**Comment by fherryfherry** [comment]
bug fixed at master, or wait for new release

**Comment by Muhammadinaam** [comment]
How can I install master version through composer???

When I saw this bug, I installed it through following command:

`$ composer require crocodicstudio/crudbooster=5.3.0.*`

**Comment by fherryfherry** [comment]
Hi just update i have release new version
Pada tanggal 10 Jan 2017 20.09, "Muhammadinaam" <notifications@github.com>
menulis:

**Comment by Muhammadinaam** [comment]
Thanks
