### ISSUE TITLE
Parse error: syntax error, unexpected '!', expecting ',' or ';'

### ISSUE THREAD

**Issue by jdredondo** [crocodic-studio/crudbooster#1145]
- Operating system (name, version and architecture) Windows 10 Pro
- Web server (name, version and architecture) Apache 2.4.23
- Browser (name, version and architecture) Chrome Versión 65.0.3325.181 (Build oficial) (64 bits)
- CRUDBooster version 5.4.6
- Laravel version 5.5
- What is the problem? Parse error: syntax error, unexpected '!', expecting ',' or ';' (View: /var/www/gredco/vendor/crocodicstudio/crudbooster/src/views/default/type_components/text/component.blade.php)
- How should it happen? What was the expected behavior? 
- Tell how to reproduce the problem step by step
- If possible, take screenshots or send snippets of code
![2018-04-13 1](https://user-images.githubusercontent.com/22225860/38752737-ec83ff72-3f21-11e8-9946-7fa0cbf0498c.png)
@imanghafoori1 Can you solve this issue in the next version?

**Comment by imanghafoori1** [comment]
@jdredondo I think it should be fixed in the 5.4.7
It was my mistake while translating it.
You can contact me in telegram: `@imanghafoori`
If you want to collaborate for the dev-master also.

Thank you
