### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by namgay1** [crocodic-studio/crudbooster#1158]
i have install crudbooster, but i am getting only vender folder only. 
![ins](https://user-images.githubusercontent.com/19284079/39464637-81f1789c-4d40-11e8-8a5c-425a88d8ceec.PNG)
![install](https://user-images.githubusercontent.com/19284079/39464643-84019af4-4d40-11e8-9486-0f1b49ec2c93.PNG)

**Comment by namgay1** [comment]
i have even used your sample also, but its giving error while login:

![capture](https://user-images.githubusercontent.com/19284079/39471705-6e1a0bd8-4d66-11e8-8f13-7ebfabae1fd7.PNG)

**Comment by imanghafoori1** [comment]
Please mention the things you are using:

laravel version
php version
crudbooster version

**Comment by akacemy** [comment]
Hello,
what steps you flooded to create your installation,
please provide your composer.json content.
