### ISSUE TITLE
Error installing dev-master version on api_generator_routes

### ISSUE THREAD

**Issue by akacemy** [crocodic-studio/crudbooster#1159]
Hello,

when installing dev-master version it gives error: 

Illuminate\Foundation\ComposerScripts::postAutoloadDump 
> @php artisan package:discover  In api_generator_routes.php line 40;

the origin of error is the file: crudbooster/src/Modules/ApiGeneratorModule/api_generator_routes.php on line 40 (Comma left after: 'AdminApiGeneratorController@postExportData')

Route::post('api-generator/export-data', 'AdminApiGeneratorController@postExportData',)->name('AdminApiGeneratorControllerPostExportData');

it should be: 
Route::post('api-generator/export-data', 'AdminApiGeneratorController@postExportData')->name('AdminApiGeneratorControllerPostExportData');

then the package install successfully.

Hope this will help.

**Comment by imanghafoori1** [comment]
Fixed, Thanks

**Comment by akacemy** [comment]
you are welcome.

**Comment by imanghafoori1** [comment]
dev-master is under active development.
all bug reports are welcome,
