### ISSUE TITLE
Foreign key names

### ISSUE THREAD

**Issue by HACKHERS** [crocodic-studio/crudbooster#117]
I'm very confused why should we use id on primary keys. For example my tables

Channels:
channel_id - primary
name 
password 

Questions:
question_id
channel_id
question

You can see the foreign key here Question.channel_id -> Channels.channel_id

How should I name my foreign key ?

**Comment by fherryfherry** [comment]
To generalized you should use "id" as primary key

Join Example : 
`join channels on channels.id = channel_id`

**Comment by HACKHERS** [comment]
I don't really understand the answer. 

> Make sure your foreign key in table format “id_{tableName}” . E.g: id_posts

Dont you

**Comment by dikobagda** [comment]
You should rename "channel_id" to "id"
