### ISSUE TITLE
Grammatical/spelling errors in English documentation

### ISSUE THREAD

**Issue by alystair** [crocodic-studio/crudbooster#118]
In http://crudbooster.com/doc/5.3/installation

> "Open a terminal, navigate to the folder you created porjek laravel. Run the following command:"

Should read 
>"Open a terminal and run the following comment in your Laravel project folder:"

In http://crudbooster.com/doc/5.3/configuration

> "CRUDBooster configuration files with the file name "crudbooster.php" in the config folder.
> There are some names that configurations can be set according to your kebutuh, among others, as follows:"

should read:

> CRUDBooster's configuration file, "crudbooster.php" is located within the "config" folder.

The second line can be removed entirely because it's self-evident the document is regarding the various options. Furthermore, in the "desc" area of the table is really excessive and should be cleaned up...  I don't have time to go over the complete documentation.

**Comment by fherryfherry** [comment]
thank you

**Comment by fherryfherry** [comment]
thank you
