### ISSUE TITLE
Hi!... I can't edit - save, in the edit form!

### ISSUE THREAD

**Issue by nixonmorillo** [crocodic-studio/crudbooster#1188]
- Operating system (Ubuntu 17.10, 64bits)
- CRUDBooster 5.4
- Laravel 5.6
- What is the problem??: i can't edit - save after in my crud... I make the migration of my tables, and i get this error!... Thanks 4 all!
![error](https://user-images.githubusercontent.com/9157743/40514390-937d627a-5f6e-11e8-8241-a734a93c1a0b.png)

**Comment by JulyanoF** [comment]
hey @nixonmorillo whats up!?
did you solve the error? I'm getting the same
