### ISSUE TITLE
Call to undefined function Unisharp\Laravelfilemanager\middleware\get_my_id()

### ISSUE THREAD

**Issue by TnCoders** [crocodic-studio/crudbooster#119]
im facing this problem:

FatalThrowableError in MultiUser.php line 14:
Call to undefined function Unisharp\Laravelfilemanager\middleware\get_my_id()

I created a Table name Sldiers.
![1](https://cloud.githubusercontent.com/assets/24681177/21865951/74be88b8-d848-11e6-96d7-7dee847ea443.PNG)
![2](https://cloud.githubusercontent.com/assets/24681177/21865953/74c51f34-d848-11e6-83fc-caf45d7f30c0.PNG)
![3](https://cloud.githubusercontent.com/assets/24681177/21865952/74c27bbc-d848-11e6-91f1-deee767635fe.PNG)

and when i Click on The File input Manager in The Module "Sliders" It Give me error

**Comment by fherryfherry** [comment]
bug fix at master, wait for new release or update from the master
