### ISSUE TITLE
How to add another button in the form? 

### ISSUE THREAD

**Issue by nyel-dev** [crocodic-studio/crudbooster#1193]
I am trying to do customization on a form and I would like to add a new button. Is there a way on how to do this please?

**Comment by aziez** [comment]
SAME

**Comment by nyel-dev** [comment]
Hi @aziez. This is a fairly old issue that I submitted months ago. Adding button depends on where do you want to put it. If you want to add button to the top of the page alongside the add button, you must do this:

`$this->index_button[] = ["label"=>"Print Report","icon"=>"fa fa-print","url"=>CRUDBooster::mainpath('print-report')];`


If you want to add button for every row alongside edit, view, or delete button, this is the one you need:

`$this->addaction[] = ['label'=>'Set Paid','icon'=>'fa fa-money','color'=>'warning','url'=>CRUDBooster::mainpath('set-paid').'/[id]','showIf'=>'[status] == "belum lunas"'];`

**Comment by squidv3** [comment]
> Hi @aziez. This is a fairly old issue that I submitted months ago. Adding button depends on where do you want to put it. If you want to add button to the top of the page alongside the add button, you must do this:
> 
> `$this->index_button[] = ["label"=>"Print Report","icon"=>"fa fa-print","url"=>CRUDBooster::mainpath('print-report')];`
> 
> If you want to add button for every row alongside edit, view, or delete button, this is the one you need:
> 
> `$this->addaction[] = ['label'=>'Set Paid','icon'=>'fa fa-money','color'=>'warning','url'=>CRUDBooster::mainpath('set-paid').'/[id]','showIf'=>'[status] == "belum lunas"'];`

in which folder do you put your print-report @nyel-dev
