### ISSUE TITLE
image upload is not working 

### ISSUE THREAD

**Issue by harimayco** [crocodic-studio/crudbooster#12]
![upload not working](http://image.prntscr.com/image/9bfea287cf6247468e06a97c9a1942f0.png)
and also with tinymce image uploader.
![upload not working](http://image.prntscr.com/image/7d2f253abb5d4c33b1b9ac506a77d3a6.png)

I tried to upload an image but,
the photo url is stored in the database.
but not in the uploads folder.

**Comment by fherryfherry** [comment]
1. image can be found at storage/app/
2. make sure the routes.php is up to date.

**Comment by harimayco** [comment]
ahh,
you're right.
it needs php_fileinfo php extension. i need to edit my php.ini file.

Thank you

**Comment by izzu7** [comment]
hi @fherryfherry how do we change the routes.php to solve the issue 
i am having the same issue where the images are being uploaded to storage/app/  but in the backend the url is related to public/uploads/

![issue](https://cloud.githubusercontent.com/assets/417882/22849300/0f89757e-f022-11e6-884b-9e77adb9ed32.png)

**Comment by lsmoro** [comment]
Hi @izzu7, did you get solve this issue? I'm facing the same... let me know if you got it.
Tks, Lorena.

**Comment by izzu7** [comment]
For me the issue was because i was accessing it using the virtual host set up in windows hosts files like domain.dev/public/admin , it works fine if i access it using localhost/public/admin ,your issue might be different

**Comment by douglasjosenieves** [comment]
TAMPOCO ME CARGA LAS FOTOS Y JS Y CSS . CUANDO HAGO LA INSTALACION DE CERO TODO FUNCIONA BIEN PERO CUANDO MIGRO EL PROYECTO NO ME CARGA

**Comment by douglasjosenieves** [comment]
LISTO SOLUCIONADO ..! PARA TODOS DESPUES DE 2 DIAS SIN DORMIR 


LO HICE EN WINDOWS II2 Y LO MISMO EN XAMPP 

1) LA CARPETA PUBLIC/UPLOAD (NOOOO ES UNA CARPETA COMO TAL . ES ALGO COMO UN ACCESO DIRECTO A ) \storage\app . SI VEZ EL ICONO DE LA CARPETA ES RARO NO ES IGUAL QUE UNA CARPETA NORMAL .

TIENES QUE HACER COMO UN ESPEJO ENTRE LAS DOS CARPETAS PUBLIC/UPLOAD Y \storage\app

YO LO HICE EN CMD CONSOLA DE WINDOWS 
EL CODIGO DEL COMANDO ES: 
mklink /D "D:\Parallels\Plesk Panel\Vhosts\cohenyaguirre2.tk\httpdocs\public\uploads"
"D:\Parallels\Plesk Panel\Vhosts\cohenyaguirre2.tk\httpdocs\storage\app"

mklink crea un vínculo simbólico

SALUDOS Y ESPERO QUE LES SIRVA.

**Comment by 5lineofcode** [comment]
update your CBController like this.
we also have unique file name.

![image](https://user-images.githubusercontent.com/43805298/55874501-bdee4880-5bbc-11e9-9efa-17e7acee963e.png)
