### ISSUE TITLE
Many Questions

### ISSUE THREAD

**Issue by TnCoders** [crocodic-studio/crudbooster#120]
Hi All Thank's I have a couple of question and i dopnt fide a chat or any place to ask these questions ;

So Please allow me to put them here:

**Module Generator**

**1. Table**

When i try to create a Module in the Module Generator it ask me to select a Table First ?
So how it is possible Because i dont find a way to Create on via The crudbooster.

**2.  Step 2 - Table Display**

what is this fields ?

Join (Optional) Field Name Shown

and **CallbackPHP**

**Comment by fherryfherry** [comment]
1. CRUDBooster doest not have database tool
2. Table Display is a feature that you may control the dashboard table of a module. For more you may see the documentation
