### ISSUE TITLE
Error 419 - /public/admin/menu_management/save-menu

### ISSUE THREAD

**Issue by brunotda** [crocodic-studio/crudbooster#1200]
- OS.:CENTOS
- Browser: Chrome
- CRUDBooster 5.4
- Laravel 5.6
- What is the problem?
![menu_management](https://user-images.githubusercontent.com/15007670/41489784-8cccc50a-70c7-11e8-9f8a-30f05426e32a.png)

**Comment by brunotda** [comment]
Solved last update

**Comment by brunotda** [comment]
In linux server show error.
![error_menu](https://user-images.githubusercontent.com/15007670/41551712-182e71f6-7303-11e8-9e3a-f10300ac351e.png)

**Comment by raphael-ramos** [comment]
The same problem happens to me.

**Comment by brunotda** [comment]
csrf-token solved.
