### ISSUE TITLE
Send Attachements ( pdf export )  to mail

### ISSUE THREAD

**Issue by abenzakour** [crocodic-studio/crudbooster#1201]
Operating system (Ubuntu 16.01)
Web server (Apache 2)
Browser (Chrome)
CRUDBooster version 5.4.16
Laravel version 5.5
What is the problem?

I want to send ( export as pdf ) by email in attachement file, 
I saved the pdf to tmp folder, then I use this code to send it  but I got this error message : 
```

$filename="Rapport_Enquete_N_185454";
$pth=storage_path("app/enquetes/".$filename.'.pdf'); 
$filpdf= \Swift_Attachment::fromPath($pth);

// I tried this too   $filpdf = new \Swift_Attachment(file_get_contents($pth), 'filename.pdf', 'application/pdf');


$data = ['name'=>'Someone']; 
$config= ['to'=>'Someone@gmail.com','data'=>$data,'template'=>'order_success','attachments'=>[$filpdf]];

CRUDBooster::sendEmail($config);


```

![0628a6bb-8749-454a-9b22-fff995c34210](https://user-images.githubusercontent.com/3093754/41498614-6d0c3daa-7161-11e8-89c9-661ca694d0f2.jpg)

**Comment by hillgp** [comment]
pode ser permissão de leitura/escrita de pasta/arquivo.

**Comment by abenzakour** [comment]
up

**Comment by abenzakour** [comment]
Solved using 

$message->attachData

Tanks to 
[https://laracasts.com/discuss/channels/laravel/sending-email-with-a-pdf-attachment](url)
