### ISSUE TITLE
Route [AdminCmsUsersControllerGetAdd] not defined

### ISSUE THREAD

**Issue by rebootcode** [crocodic-studio/crudbooster#122]
after click module generator to step2, it show error

Route [AdminCmsUsersControllerGetAdd] not defined  , Another user related issue ( #129 , #123 & #93  )

I am using latest version of CrudBooster. Just installed today using composer command line :- 

`composer require crocodicstudio/crudbooster=5.3.0.*`

**Comment by rebootcode** [comment]
Any update ?

**Comment by sajidsheik** [comment]
![image](https://cloud.githubusercontent.com/assets/7164020/22328558/ee72a766-e3e2-11e6-9606-9012b78fa4aa.png)

after logging i'm getting this error

**Comment by fherryfherry** [comment]
still in investigation

**Comment by akktis** [comment]
I've gotten the same Issue, is actually append when you try create a "users" module,

if you want to fixe it you have to remove your module from DB and the controller. then recreate your module with another name

**Comment by sajidsheik** [comment]
thanks for the reply but I'm using angular js so I won't crud booster again

**Comment by fherryfherry** [comment]
As @akktis said this problem caused when you create the module from CB table "cms_users", so in the future, the official table from CB will be delete from list table of module generator

For broken CB, because this bug, you should delete the data from cms_moduls, cms_menus, and replace/add  AdminCmsUsersController into app/Http/Controller

**Comment by fherryfherry** [comment]
update to latest version

**Comment by mgakif** [comment]
i added this array into vendor/crocodicstudio/crudbooster/src/routes.php

$master_controller=[
        0 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/AdminController.php",
        1 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/ApiController.php",
          2 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/ApiCustomController.php",
          3 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/CBController.php",
          4 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/Controller.php",
          5 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/EmailTemplatesController.php",
          6 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/FileController.php",
          7 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/LogsController.php",
          8 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/MenusController.php",
          9 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/ModulsController.php",
          10 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/NotificationsController.php",
          11 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/PrivilegesController.php",
          12 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/SettingsController.php",
          13 => "home/ummetorg/public_html/vendor\crocodicstudio\crudbooster\src/controllers/StatisticBuilderController.php",
            ];
because i was getting "glob() has been disabled for security reasons;"
you should also change "home/ummetorg/public_html"
