### ISSUE TITLE
AdminCmsUsersControllerGetAdd

### ISSUE THREAD

**Issue by mov580** [crocodic-studio/crudbooster#123]
I installed the last version on LARAVEL 5.3 . When I try to create a module and hit next step I get the following error:

"Route [AdminCmsUsersControllerGetAdd] not defined. (View: /Applications/MAMP/htdocs/lara3/vendor/crocodicstudio/crudbooster/src/views/sidebar.blade.php) (View: /Applications/MAMP/htdocs/lara3/vendor/crocodicstudio/crudbooster/src/views/sidebar.blade.php) (View: /Applications/MAMP/htdocs/lara3/vendor/crocodicstudio/crudbooster/src/views/sidebar.blade.php)"

**Comment by rebootcode** [comment]
The project is dead.

**Comment by fherryfherry** [comment]
update to latest version
