### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#124]
The Response content must be a string or object implementing __toString(), "object" given.

When Trying to click the notifications lists from table.. how to fixed it?

TIA

**Comment by rskonieczka** [comment]
@tomatoe45 
Replace
 `return redirect($row->to);  ` > `return redirect($row->url);  ` in  `NotificationsController.php`

**Comment by tomatoe45** [comment]
Well Thank you so much.. it fixed now. thanks.. Your great!!

**Comment by fherryfherry** [comment]
Thank You

**Comment by fherryfherry** [comment]
update to latest version
