### ISSUE TITLE
Trying to open users list in backend - wrong table name

### ISSUE THREAD

**Issue by ritenn** [crocodic-studio/crudbooster#1246]
As in topic when I try to open users list from backend menu I get error 

Doctrine \ DBAL \ DBALException
Invalid table name specified:

It's fresh install of Lravel, CRUD

**Comment by ah33** [comment]
Same with me, but after I trace, something change at helper CRUDBooster.php (vendor\crocodicstudio\crudbooster\src\helpers) line 890 , new function at 916.

You can at this validation script default return for new function
 if (! $table) {
             return 'id';
        }
at line 918.

It's work for me.
Thx
