### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by muhlisabdi** [crocodic-studio/crudbooster#1251]
- Operating system win 10
- Web server xampp
- Browser chrome
- CRUDBooster 5.4.15
- Laravel version 5.6
If insert to many to many return NULL on primarykey current table in relationship table,
For example if add menu in menu management, after add id_cms_priveledges return NULL on relationship table

I think $id need to assign first in CBController.php within function postAddSave, because $id return as NULL

Maybe the solition is replacing:
DB::table($this-table)->insert($this->arr); 
With:
$id=DB::table($this-table)->insertGetId($this->arr);

**Comment by picepice** [comment]
Did you solve it? Im having a problem also in many to many..

**Comment by muhlisabdi** [comment]
Yes,it tested in mysql,  just find file in src/controller/CBController.php

Replace line 1144
DB::table($this->table)->insert($this->arr);

With
$id=DB::table($this->table)->insertGetId($this->arr);

And replace line 1219
$this->hook_after_add($this->arr[$this->primary_key]);

With:
$this->hook_after_add($id);

**Comment by picepice** [comment]
I dont have any error but the problem is now on privilege menu..  

Sorry you do not have privilege to access this area !

Ive tried Route and module but only super admin can access even it added on db the priviledge
