### ISSUE TITLE
Hook_after_add  returned id is null

### ISSUE THREAD

**Issue by akkhan20** [crocodic-studio/crudbooster#1256]
cb version: 5.4

Hook_before_add is working fine and data is being added to database but hook_after_add returns the id as null, what can be the issue with that?

**Comment by akkhan20** [comment]
id is null on all modules

**Comment by andreshg112** [comment]
Same thing here after updating.

**Comment by andreshg112** [comment]
@fherryfherry

**Comment by andreshg112** [comment]
Working now! Thank you so much, @fherryfherry.
This should be closed.
