### ISSUE TITLE
Why CRUDBOOSTER is used?

### ISSUE THREAD

**Issue by AbdulBazith** [crocodic-studio/crudbooster#1259]
Guys i am new to laravel. 
I have a  done a small application using laravel framework.
I followed J.A.Curtis video in you tube to develop the application

i normally done the application by 
designing the form.
created a  resource controller (index,create,store,edit,update,delete) and use these functions to perform my tasks.

Now i was assigned a new project which is a job portal website.

Someone suggested me to use Crud Booster to develop the job portal website.

Whats my doubt is weather Crud Booster is just only for admin panel purpose else the whole application can done using the crud booster.

i took the employer module as my work.
The designer team gave the form design for the employer module.

Now what should i do? normally in laravel if i press the submit button after filling the data  it redirects to store function in the controller the data is validated and stored. this is normal procedure.

now if i need to use crud booster means how can i use it? if i press the submit button it should save the data. for this how i can use the crud booster? so confusing about crud booster?

Kindly someone suggest please..

**Comment by fherryfherry** [comment]
I didn't really get your mean. But basically, If you are using crudbooster it means, all the CRUD Jobs are done by default. Just create a module from the table you are created before, and the Browse Data, Create Form, Edit Form, Detail Data, Delete data jobs are ready for use.
If you want to custom any function of that CRUD, you can override the create method, edit method, etc just like you using the Laravel as normally.

**Comment by AbdulBazith** [comment]
@fherryfherry Thank you so much for your response.

whats my doubt is i cant see any create or delete or edit method in the crudbosoter controller. 

If i create a normal resource controller then there will be methods such as index, store,edit, update, delete, create. so through a button click i can redirect to the desired method.

to test a sample i created a new laravel project. installed crudbboster and created a module (name =company_registration). created the table and done a form and added a data also. everything is fine.

but in the "AdminCompanyDetailsController" where the insert, delete, update methods are there ??

i can see 

public function cbInit()
public function actionButtonSelected($id_selected,$button_name)
public function hook_query_index(&$query)
.. etc

My designer sent me a form design with menu bar everything..

after filling the form if click the 'Add' button the data must be added to the DB. (Normally we write this function i create method in resource controller)

Here how can i redirect this to the crudbooster??

I think you understood my question??

iam so confused with normal format and crudbooster format.

i referred in google there are no sufficient reference for my doubt. 

i need the crudbooster proccess to my form design my button click etc??

Kindly help?? if possible share any related video or link

**Comment by fherryfherry** [comment]
In CRUDBooster you won't see CRUD Method, Views, Models, etc. CRUDBooster has own Main Controller in the Package System that has all the crud method needs. We as a developer only need to define the scaffold in the **generated controller** by CRUDBooster.

In the cbInit(), you can put the column scaffolding.
In the hook_query_index(), you can modify the index query as you wish.
In the hook_before_add(), you can inject the data before it's sent to "Adding Process Query
in the hook_after_add(), you can put some condition whenever "Adding process query" finished
in the hook_before_edit(), just like hook_before_add
in the hook_after_edit(), just like hook_after_add
etc...

https://www.youtube.com/channel/UCgOJR3khWEykIBBR8vAGtcA/videos
https://cloud.githubusercontent.com/assets/6733315/24070665/78aba9ee-0bf4-11e7-82dd-96dde90e8c67.png
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/index.md
