### ISSUE TITLE
Action button using URL from database

### ISSUE THREAD

**Issue by efisher01** [crocodic-studio/crudbooster#1273]
How can I get a custom Action button to pull a URL from my MySQL database. For example:

Someone is filling out the form, they put a file path (or URL) in the "East Install" field. When going to the table view on the webpage, there's a green button (next to data, edit, delete buttons) that says "East Install" and uses the URL/File Path provided in the database?

**Comment by efisher01** [comment]
Few questions, I'm new to Laravel so I'm learning on the fly. 

Would the 'SomeController' be the controller that Crudbooster creates? Also, where in that controller would I put the Public Function redirect? 

Lastly, when I add the code for the 'add more action button' ($this->addaction[]= [ etc.) in the 'url'=> what would I put as the 'URL'

**Comment by nyel-dev** [comment]
the SomeController is something that you will create using the console


`php artisan make:controller SomeController`


the url that you will be adding should be the route that you have created on the routes/web.php


so your URL would be something like this:

`$this->addaction[] = ['label'=>'Action Button','url'=>'localhost/whatever/[id]'];`


sorry if I can't explain it really well but you can ask anytime if you still have questions.

**Comment by efisher01** [comment]
Makes sense! I actually had to go the other way of creating my own custom view. Due to other requests and needs.
