### ISSUE TITLE
Module Generator

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#129]
Error:
ErrorException in UrlGenerator.php line 314:
Route [AdminCmsUsersControllerGetAdd] not defined. (View: C:\xampp\htdocs\crud\vendor\crocodicstudio\crudbooster\src\views\sidebar.blade.php) (View: C:\xampp\htdocs\crud\vendor\crocodicstudio\crudbooster\src\views\sidebar.blade.php) (View: C:\xampp\htdocs\crud\vendor\crocodicstudio\crudbooster\src\views\sidebar.blade.php)

when trying to go to the next step of the module generator.. please fix

#Is the crudbooster framework is updated? or it is deprecated..?

**Comment by rebootcode** [comment]
Please do not create new ticket for same issue, it is already referenced here :- https://github.com/crocodic-studio/crudbooster/issues/122
