### ISSUE TITLE
checkbox problem

### ISSUE THREAD

**Issue by Reshmank** [crocodic-studio/crudbooster#130]
if i create a checkbox field , it was working when one checkbox is checked ,but if i not checked will comes error 

ErrorException in CBController.php line 774:
implode(): Invalid arguments passed

what will do ? if there is any solution for this problm

**Comment by fherryfherry** [comment]
hi what is version of your CRUDBooster ?

**Comment by fherryfherry** [comment]
update to latest version

**Comment by Benoit75** [comment]
Hello, 
Thanks for your work. 
I've got the same issue on 5.4  with this message : QueryException in Connection.php line 770:
SQLSTATE[HY000]: General error: 1366 Incorrect integer value:

Any ideas ? 
Thanks
