### ISSUE TITLE
modal for export data

### ISSUE THREAD

**Issue by risdiana27** [crocodic-studio/crudbooster#1304]
@fherryfherry  can i change modal for export data, i want to add more input for my report

**Comment by fherryfherry** [comment]
If you want to customize export modal on a special module, you don't need to customize the CB Export Data modal instead of creating your own export modal and export method.
In the cbInit() method
```php
$this->script_js = "
function showCustomExport() {
$("#modal-custom").modal("show");
}
";

$this->post_index_html = "
<div class='modal' id='modal-custom'>
....
</div>
";
$this->index_button[] = ['label'=>'Export Custom','url'=>"javascript:showCustomExport()",'icon'=>'fa fa-download'];
```
Dont forget create your own export method process : 
```php
public function getExportCustom()
{
...
}
```
