### ISSUE TITLE
Sort ASC or DESC Select datatable options SOLUTION PLEASE

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1307]
Hi,
How can I sort the option values in select dropdowns ?
Thanks in advance, cheers

**Comment by marcq64** [comment]
Sad that this project and community seems to be "dead". Only viable alternative seems to be today voyager  (free) and Laravel Nova where you get support even if you are a newbie and for basic issues.

**Comment by perlbrain** [comment]
Hi, i'm still using this project but you are right. There are not a lot of reactions anymore. When you use select2 there is an option build in for searching. The option for sorting I have not found yet. Not the anser you needed...

**Comment by marcq64** [comment]
Please wake up call, do someone know how to sort the options of $columns[] datatable join ? If yes sharing would be appreciate. Thanks in advance, cheers, Marc

**Comment by perlbrain** [comment]
Hi Marc, i don't think there is a standard sort option. You would have to add this yourself in the helpers Crudbooster.php

**Comment by marcq64** [comment]
Thanks a lot perlbrain for your answer, but since I'm newbie it is saddly still a little bit to complicated for me to do it by myselft but if you could just elaborate would be great. Thanks in advance, Cheers

**Comment by pbeltrand** [comment]
maybe this can help.
in vendor/crocodicstudio/crudbooster/src/views/default/type_components/select2/component.blade.php

find 

$select_table = explode(',', $form['datatable'])[0];
$select_title = explode(',', $form['datatable'])[1];

and add

$select_order = explode(',', $form['datatable'])[2];
if ($select_order == "") $select_order = $select_title;

and replace

$result = $result->orderby($select_title, 'asc')->get();
with
$result = $result->orderby($select_order, 'asc')->get();


now you can pass a third argument in the controller.

$this->form[] = ['label'=>'Elemento','name'=>'id_elemento','type'=>'select2','validation'=>'integer|min:0','width'=>'col-sm-10','datatable'=>'app_tipo_elemento,nombre,id'];

in this example im passing id as third parameter so the select get sorted by id.

hope it help.

**Comment by marcq64** [comment]
Thanks a lot pbeltrand, unexpected here to get some help... I solved this issue with JS already, but it seems that your solution is more elegant and need less resources. So I will use it ! Thanks again, cheers, Marc

**Comment by andreshg112** [comment]
I created a pull request for this. https://github.com/crocodic-studio/crudbooster/pull/1421
