### ISSUE TITLE
Invisible column in Grid Data

### ISSUE THREAD

**Issue by vadimobruchnikov** [crocodic-studio/crudbooster#1319]
CRUDBUSTER v5.4.х

How to make an invisible column(e.g. id) in a table?
Id is required for links and commands.

**Comment by marcq64** [comment]
I don't know if it is what you are looking for, but if it is the case , please have a look at this example :

`$columns[] = ['label'=>'ID Rôle','name'=>'roleID','type'=>'hidden','value'=>CRUDBooster::myPrivilegeId()];`

the type of the column is 'hidden'.

**Comment by vadimobruchnikov** [comment]
Thanks for example. 
In this case, the column will not be created in the table, but it should be created and not displayed, so that it can be used as [id]

The same will happen when you create a column with the 'visible'=>FALSE attribute.

/vendor/crocodicstudio/crudbooster/src/views/default/table.blade.php  (row :59)
...
foreach($columns as $col) {
    if($col['visible']===FALSE) continue;
...

I haven't found a solution yet(.

**Comment by marcq64** [comment]
I'm not sure I understand you, but concerning my example, the roleID doesn't appear in the index table, but this id is available for use for example hook before, after submitting the form (dd($_REQUEST);) :

`array:47 [▼
  "_token" => "E7MM9WF4pmwfuMjhgdKIWIWT1uwKTnzdayobiGwX"
  "return_url" => ""
  "ref_mainpath" => "http://mage.local/public/admin/commandes"
  "ref_parameter" => ""
  "child-ordersdetailuserID" => "1"
  **"child-ordersdetailroleID" => "1"`**

So I guess if it is working for this roleID, it should also work for your id ?

**Comment by vadimobruchnikov** [comment]
It is not in a form. 
It is in Grid Data column.
for example: 
I have a Grid Data

id   name 
1    Name1
2    Name2 

But I want to show only [name] column in grid data

id(hide)   name 
1(hide)    Name1
2(hide)    Name2 

If I set field type 'type'=>'hidden'
I will have result grid

name 
Name1
Name2 

and I can't apply [id] in grid data.
 
Sorry, for my bad english.

**Comment by vadimobruchnikov** [comment]
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-add-more-action-button.md

I want hide field [id] for this example.

**Comment by marcq64** [comment]
Ah ok, I couldn't find a solution due to lack of doc here, but I could manage to solve this for several IDs fields I dont want to show in the table grid but for whom I need to store the value into my table after submitting the data and it works fine :

`#table-ordersdetail > tbody > tr > td.userID,
 #table-ordersdetail > tbody > tr > td.roleID,
 #table-ordersdetail > tbody > tr > td.statusorderID,
 #table-ordersdetail > tbody > tr > td.statuslaboID { display:none; }`

See in the table, values are populated 👍 

![datatable](https://user-images.githubusercontent.com/33374514/49358478-63704780-f705-11e8-9654-3aaf9534eb4c.png)

**Comment by marcq64** [comment]
or try this one :

https://github.com/crocodic-studio/crudbooster/issues/1168

**Comment by vadimobruchnikov** [comment]
https://github.com/crocodic-studio/crudbooster/pull/1323/commits/9cba4feba193ce8eea2b8f23e627a3fc0a7644e0

**Comment by marcq64** [comment]
Thanks !

**Comment by Cruzv35** [comment]
> I don't know if it is what you are looking for, but if it is the case , please have a look at this example :
> 
> `$columns[] = ['label'=>'ID Rôle','name'=>'roleID','type'=>'hidden','value'=>CRUDBooster::myPrivilegeId()];`
> 
> the type of the column is 'hidden'.

this will just hide the value from the form... but not the list

**Comment by marcqvn** [comment]
Thanks Guys. In the meantime, I moved to a creative tim dashboard. I had to develop all from the scratch, but at the end it is more reliable and less risky for my projects and needs... Design is great too. And I can use the last PHP, Laravel version and have an updated application. Honestly less headache... Good luck!
