### ISSUE TITLE
SOLVED AND SOLUTION - Update data with hook_after_add

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1320]
Hi,
In order to come forward and go deeper with crudbooster, I need a tutor in order to go through a few point concerning crudbooster where I'm weak. 

Is someone available for skype paid tutoring for 4 to 8 hours ?

Please contact me if interested !

Thanks in advance, cheers, Marc

**Comment by abenzakour** [comment]
Hello Marc, 

You can ask your questions here,  we will help you for free :)

**Comment by marcq64** [comment]
Bonjour abenzakour,

C'est sympa. Je suis bloqué sur deux trois choses et je perds un temps incroyable à tenter de les résoudre.

J'ai créé un formulaire master|detail qui fonctionne comme je le souhaite.  

Par contre, je souhaiterais, lors de l'envoi du formulaire, enregistrer dans ma table orders_detail, dans le champ "laboratory" le nom du laboratoire qui doit traiter le produit. 

Cette requête pourrait récupérer l'information souhaité :

`SELECT laboratories.laboratory FROM products INNER JOIN laboratories ON products.laboratoryID=laboratories.id`

J'ai défini  dans mon controller une colonne "productnameID" qui récupère le no d'option sélectionné dans la liste déroulante correspondante :

`$columns[] = ['label'=>'Produit','name'=>'productnameID','type'=>'select','validation'=>'required|integer|min:0','width'=>'col-sm-10','datatable'=>'product_names,product_name','parent_select'=>'producttypeID'];`

Est-il possible de générer un update du record créé lors de l'envoi du formulaire avec l'information souhaitée, c'est-a-dire le nom du laboratoire ? Avec la public function hook_after_add($id) ? Dans l'affirmative comment ?

Merci d'avance pour tout aide, car je coince depuis une journée sur ce problème et deux autres.

Cheers,

Marc
[controller.txt](https://github.com/crocodic-studio/crudbooster/files/2636845/controller.txt)

**Comment by abenzakour** [comment]
Bien sur que tu peux, 

tu mets un  dd($_REQUEST);   dans la fonction hook_after_add   est tu auras l'ensemble des variables de ton formulaire.  tu px les utiliser pour faire la requete convenable et recuperer le nom du leboratoire, puis mettre à jour la ligne  dans la table orders_detail via  DB::Table('orders_detail')->update...

**Comment by marcq64** [comment]
Merci pour ton retour, est-ce que cela te sembles correct ? :

`$news = DB::table('orders_detail')->where('id',$id)->first();

		// REQUESTED VALUE : "ordersdetail-productname" => array:1 [▼ 0 => "1" ] :
		
	    $productnameID = array( 
	    	'ordersdetail-productnameID' => $input['productnameID'];
	    );

		// QUERY : SELECT laboratories.laboratory FROM products INNER JOIN laboratories ON products.laboratoryID=laboratories.id :
					
		$laboratory = DB::table('products')
					->join('laboratories', 'products.laboratoryID', '=', 'laboratories.id')
					->select('laboratories.laboratory')
					->get();
		
	    $data['description'] = "Laboratoire";
	    DB::table("orders_detail")->update($laboratory);`

Par contre, je dois encore indiquer dans quel champ de ma table orders_detail je souhaite mettre a jour le champ. n'est-ce pas ? Désolé pour cette question basique, mais j'apprends...

**Comment by marcq64** [comment]
Serait-il possible d'avoir un exemple ? Cela simplifierait et accélérerait grandement l'apprentissage. Merci d'avance.

**Comment by marcq64** [comment]
ok je crois que j'approche du but, je n'arrive juste pas a récupérer ma variable "productnameID" de son array :

`// POPULATE
		DB::table('orders_detail')->where('id',$id)->first();

		$data = [];
		**/* REQUESTED VALUE :   "ordersdetail-productnameID" => array:1 [▼
    0 => "1" ] : */**

		**$productname = $request->input('orders.0.productnameID');**

		/* QUERY : SELECT laboratories.laboratory FROM products INNER JOIN laboratories ON products.laboratoryID=laboratories.id : */
		
		$laboratory = DB::table('products')
					->join('laboratories', 'products.laboratoryID', '=', 'laboratories.id')
					->select('laboratories.laboratory')
					->where('products.id', '=', $productnameID)
					->get();
		
	    /* $data['description'] = "Laboratoire"; */
	    DB::table("orders_detail")->update(['laboratory' => $laboratory]);

	    }`

Merci d'avance de m'expliquer comment je peux récupérer de l'array ma valeur. L'array retournée par dd est  

`"ordersdetail-productnameID" => array:1 [▼
    0 => "1" ]`

**Comment by marcq64** [comment]
Dernière tentative.  Je n'arrive pas à récupérer ma valeur, tu peux me donner un coup de main ou non ?

**Comment by abenzakour** [comment]
$productnameID = $_REQUEST['ordersdetail-productnameID'][0];

**Comment by marcq64** [comment]
Merci pour ton retour, j'ai juste encore un petit souci : 

La valeur retournée dans le champ de la table est : **[{"laboratory":"Boulanger"}]**
Alors que seule la valeur "Boulanger" devrait être retournée.

lorsque je dd la valeur retournée par la requête (voir plus bas) : 

`Collection {#3541 ▼
  #items: array:1 [▼
    0 => {#3539 ▼
      +"laboratory": "Boulanger"
    }
  ]
}`

On retrouve "laboratory": "Boulanger", alors que je souhaiterais uniquement retourner "Boulanger".

As-tu stp une idée de la manière dont je peux régler ca ?

Merci d'avance

**Requête**
`// POPULATE the laboratory FIELD
		DB::table('orders_detail')->where('id',$id)->first();
		/* dd($id); */

		/* REQUESTED VALUE IN ARRAY :   "ordersdetail-productname" => array:1 [▼ 0 => "1" ] : */

    	$productname = $_REQUEST['ordersdetail-productname'][0];
    	/*  dd($productname); */  

		/* QUERY : select laboratories.laboratory FROM products LEFT JOIN laboratories ON products.laboratoryID = laboratories.id WHERE products.id = productname : */
		
		$laboratory = DB::table('products')
					->join('laboratories', 'products.laboratoryID', '=', 'laboratories.id')
					->select('laboratories.laboratory')
					->where('products.id', '=', $productname)
					->get();

    	/*  dd($laboratory); */  
		
		/* ADD DESCRIPTION TO RETURNED VALUE : [{"laboratory":"Boulanger"}] */
	    /* $data['description'] = "Laboratoire"; */

		/* UPDATE THE laboratory FIELD WITH THE RETURNED VALUE */
	    DB::table('orders_detail')->where('orderID', '=', $id)
->update(['laboratory'=> $laboratory]);`

**Comment by marcq64** [comment]
Merci pour ton retour, j'ai juste encore un petit souci : 

La valeur retournée dans le champ de la table est : **[{"laboratory":"Boulanger"}]**
Alors que seule la valeur "Boulanger" devrait être retournée.

lorsque je dd la valeur retournée par la requête (voir plus bas) : 

`Collection {#3541 ▼
  #items: array:1 [▼
    0 => {#3539 ▼
      +"laboratory": "Boulanger"
    }
  ]
}`

On retrouve "laboratory": "Boulanger", alors que je souhaiterais uniquement retourner "Boulanger".

As-tu stp une idée de la manière dont je peux régler ca ?

Merci d'avance

**Requête**

// POPULATE the laboratory FIELD
		DB::table('orders_detail')->where('id',$id)->first();
		/* dd($id); */

		/* REQUESTED VALUE IN ARRAY :   "ordersdetail-productname" => array:1 [▼ 0 => "1" ] : */

    	$productname = $_REQUEST['ordersdetail-productname'][0];
    	/*  dd($productname); */

		/* QUERY : select laboratories.laboratory FROM products LEFT JOIN laboratories ON products.laboratoryID = laboratories.id WHERE products.id = productname : */
		
		$laboratory = DB::table('products')
					->join('laboratories', 'products.laboratoryID', '=', 'laboratories.id')
					->select('laboratories.laboratory')
					->where('products.id', '=', $productname)
					->get();

    	dd($laboratory);
		
		/* ADD DESCRIPTION TO RETURNED VALUE : [{"laboratory":"Boulanger"}] */
	    /* $data['description'] = "Laboratoire"; */

		/* UPDATE THE laboratory FIELD WITH THE RETURNED VALUE */
	    DB::table('orders_detail')->where('orderID', '=', $id)
->update(['laboratory'=> $laboratory]);

**Comment by marcq64** [comment]
**Solved in stackoverflow** : https://stackoverflow.com/questions/53594949/laravel-update-query-return-laboratoryboulanger-as-value-instead-o

**Comment by marcq64** [comment]
Solution :

$laboratory = DB::table('orders_detail')
		->join('laboratories','orders_detail.producttypeID', '=', 'laboratories.id')
		->select('orders_detail.producttypeID','laboratories.laboratory')
		->where('orderID', '=', $id)
		->get('laboratory','producttypeID');

foreach($laboratory as $labo){
DB::table('orders_detail')
   ->where('orders_detail.orderID', '=', $id)
   ->where('orders_detail.producttypeID',$labo->producttypeID)
   ->update(['laboratory'=> $labo->laboratory]);
}
