### ISSUE TITLE
UNSOLVED - Message de Notification apparait, mais erreur lors de l'ouverture du message "NotFoundHttpException"

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1321]
Bonjour,

J'ai créé un hook_after_add pour confirmer au client sa commande :

`
public function hook_after_add($id) {

    	$config['content'] = "Notification Message";
		$config['to'] = CRUDBooster::adminPath('admin/notifications/read/{id}');
		$config['cms_users>id'] = CRUDBooster::myId();
		CRUDBooster::sendNotification($config); `

Le message apparait bien dans la fonction notifications (cloche) : 

`http://mage.local/public/admin/notifications/read/5?m=0`

par contre lorsque j'ouvre le message suivant est affiché :

`
NotFoundHttpException
--
in RouteCollection.php line 179
at RouteCollection->match(object(Request))in Router.php line 546
at Router->findRoute(object(Request))in Router.php line 525
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 53
`
Je suppose qu'il s'agit d'un souci de route...

Merci d'avance pour toute suggestion me permettant de régler ce souci,

Cheers,

Marc

**Comment by abenzakour** [comment]
tu vérifies cette ligne 
$config['to'] = CRUDBooster::adminPath('admin/notifications/read/{id}');

normalement le lien ne doit pas contenir admin....  remplace le par : 

$config['to'] = CRUDBooster::adminPath('notifications/read/{id}');

**Comment by marcq64** [comment]
Thanks,

J'ai fais la modif est j'ai toujours une erreur 👍

**Comment by marcq64** [comment]
(1/1) UnexpectedValueException
The Response content must be a string or object implementing __toString(), "object" given.
