### ISSUE TITLE
Master-Child Form | Radio Button | Checkbox issues to address

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1325]
Hi,

I have created this simple radio "field" :

Problem with default value :

$columns[] = ['label'=>'X','name'=>'xID','type'=>'radio','dataenum'=>'Non;Oui','value'=>'Non'];
$columns[] = ['label'=>'X','name'=>'xID','type'=>'radio','dataenum'=>'1|Non;2|Oui','value'=>1];
doesn't work, default value (Non) is not set. 

And this checkbox "field" :
 $columns[] = ['label'=>'Décoration Chocolat et  fruits','name'=>'dessertdecorchocolateID','type'=>'checkbox','dataenum'=>'Non;Oui'];
Checkboxes are not displayed.

@ fherryfherry : would you be good and take five minutes of your precious time to address this or at minima to explain the people how to do it properly in child form ?

Thanks for your effort.

Marc

============================================
**Operating system**
Laravel Framework 5.4.36
**Web server**
Laragon (Apache httpd-2-4-29-win64-VC15, MySQL-5-7-19-win64)
**Browser**
opera, chrome, firefox
**CRUDBooster version**
v5.4.18

**Comment by hillgp** [comment]
coloque isso em: \vendor\crocodicstudio\crudbooster\src\views\default\type_components\child\component.blade.php
@elseif($col['type']=='radio')
                                                    <?php
                                                    if($col['dataenum']):
                                                    $dataenum = $col['dataenum'];
                                                    if (strpos($dataenum, ';') !== false) {
                                                        $dataenum = explode(";", $dataenum);
                                                    } else {
                                                        $dataenum = [$dataenum];
                                                    }
                                                    array_walk($dataenum, 'trim');
                                                    foreach($dataenum as $e=>$enum):
                                                    $enum = explode('|', $enum);
                                                    if (count($enum) == 2) {
                                                        $radio_value = $enum[0];
                                                        $radio_label = $enum[1];
                                                    } else {
                                                        $radio_value = $radio_label = $enum[0];
                                                    }
                                                    ?>
                                                    <label class="radio-inline">
                                                        <input type="radio" name="child-{{$col['name']}}"
                                                               class='{{ ($e==0 && $col['required'])?"required":""}} {{$name_column}}'
                                                               value="{{$radio_value}}"> {{$radio_label}}
                                                    </label>
                                                    <?php endforeach;?>
                                                    <?php endif;?>

**Comment by marcq64** [comment]
Thank you for taking the time ! Unfortunately it is already in my component.blade.php installed version.

**Comment by marcq64** [comment]
Do someone have the solution and willing to share it ? Would be appreciated.

**Comment by vadimobruchnikov** [comment]
Test, please.
https://github.com/vadimobruchnikov/crudbooster/commit/81446a7f7c349bfec304eef6159f322f2288232c

**Comment by marcq64** [comment]
Thanks vadimobruchnikov, I have implemented your changes, but unfortunately the default value is still not set for this two tests :

	$columns[] = ['label'=>'X1','name'=>'dessertdecorchocolateID','type'=>'radio','dataenum'=>'Non;Oui','value'=>'Non'];
	$columns[] = ['label'=>'X2','name'=>'dessertdecorflowerID','type'=>'radio','dataenum'=>'1|Non;2|Oui','value'=>1];

But anyway your support is much appreciate. Cheers, Marc

**Comment by vadimobruchnikov** [comment]
Did you set 'validation'=>'required' in your example?

**Comment by vadimobruchnikov** [comment]
new commit
https://github.com/crocodic-studio/crudbooster/pull/1323/commits/2af1a23a03d0ec0d2b95a843f45d05a24a0a1bbf

```
$this->form[] = ['label'=>'idX','name'=>'test_str','type'=>'radio','validation'=>'required','width'=>'col-sm-9','dataenum'=>'Non;Oui'];
$this->form[] = ['label'=>'idI','name'=>'test_int','type'=>'radio','validation'=>'required','width'=>'col-sm-9','dataenum'=>'1|Non;2|Oui'];
```
1 - field is a String type
2 - field is a Int type

Thanks for your message. I forgot check CRUDBooster::isCreate() mode.		

![default](https://user-images.githubusercontent.com/26638102/49690979-3a5b1700-fb4a-11e8-98ce-3dde3cef15cb.png)

**Comment by marcq64** [comment]
Thanks for your update and work vadimobruchnikov : 

It is working perfectly for form as tested with :

			# Chocolate
			$this->form[] = ['label'=>'Décoration Chocolat et fruits','name'=>'dessertdecorchocolateID','type'=>'radio','width'=>'col-sm-10','dataenum'=>'Non;Oui','validation'=>'required'];
			# Flowers
			$this->form[] = ['label'=>'Décoration petites fleurs','name'=>'dessertdecorflowerID','type'=>'radio','width'=>'col-sm-10','dataenum'=>'1|Non;2|Oui','validation'=>'required'];

default values are set. 

But it doesn't work at all in columns :

			# Chocolate
			$columns[] = ['label'=>'Décoration Chocolat et fruits','name'=>'dessertdecorchocolateID','type'=>'radio','width'=>'col-sm-10','dataenum'=>'Non;Oui','validation'=>'required'];
			# Flowers
			$columns[] = ['label'=>'Décoration petites fleurs','name'=>'dessertdecorflowerID','type'=>'radio','width'=>'col-sm-10','dataenum'=>'1|Non;2|Oui','validation'=>'required'];

As you can see in the screencapture : in the form and in the child
![radio](https://user-images.githubusercontent.com/33374514/49693314-b2086080-fba1-11e8-9414-005f99bd2946.png)

I can use JavaScript, which is working well to set the default value, so no hurry to tackle this.

Thanks again for your support, much appreciate, cheers, Marc

**Comment by marcq64** [comment]
Hi Vadimo,

If I understand you correctly, please find attached my controller and the tables you need to make it works. I don't thimk you need the js and css files to make it works.

Master table is : orders and Detail is : orders_detail.

 In the controller you will find the form and columns radio fields under :
# TEST RADIO TEST RADIO TEST RADIO TEST RADIO TEST RADIO TEST RADIO TEST RADIO TEST RADIO TEST RADIO

I hope it helps, Cheers, Marc

[TABLES.txt](https://github.com/crocodic-studio/crudbooster/files/2660379/TABLES.txt)
[Controller.txt](https://github.com/crocodic-studio/crudbooster/files/2660381/Controller.txt)

**Comment by marcq64** [comment]
SOLUTION :

`function` setRadioDefaultValues() {
	
	/* Decoration */
	$('input:radio[name=child-dessertdecorchocolateID]:nth(0)').attr('checked',true);
	$('input:radio[name=child-dessertdecorflowerID]:nth(0)').attr('checked',true);

};

window.onload = setRadioDefaultValues;`
