### ISSUE TITLE
Looking for a freelancer

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1333]
Hi,

I am up to finish my project, but I have some issues to tackle and to fix. 

I'm therefore looking for a freelancer ready to give me a hand.

Process :

-  I send you detailed specifications
- You give me a quote
- I accept and pay half of the quotation upfront
- You download the files and dump on my server

If interested please take contact with me, I will get back to you latest on the 15 December.

Cheers, Marc

**Comment by Nsobi** [comment]
Im Nsobi i developed active application using crudbooster,
in the following area;
Human resource management,
incident management, and 
vehicle database.
This is my contact
 skype_id: nsobhijason
email:nsobhilemo@gmail.com
mobileno:+255713491132

**Comment by elemes1** [comment]
Hi, 

In case you need a hand. you can reach me on elemes11@gmail.com
developed a couple of solution using crudbooster. 
Full Fledge Retail portal. 
Estate Management Portal 
Staff Hub and some cool apps. 

If your request isn't much I can offer a free one.

**Comment by marcq64** [comment]
Hi Samuel,

Thanks for your interest, I'll get back to you latest on the 15th December.

Cheers,

Marc
On 10-Dec-18 15:03:49, Samuel <notifications@github.com> wrote:
Hi,
In case you need a hand. you can reach me on elemes11@gmail.com [mailto:elemes11@gmail.com]
developed a couple of solution using crudbooster.
Full Fledge Retail portal.
Estate Management Portal
Staff Hub and some cool apps.
If your request isn't much I can offer a free one.

**Comment by rizkiheryandi** [comment]
You can contact us at https://soft.uatech.co.id or hello@uatech.co.id
