### ISSUE TITLE
CRUDBooster::isSuperadmin()

### ISSUE THREAD

**Issue by pandanaran** [crocodic-studio/crudbooster#134]
Coba set kolom hanya tampil jika superadmin dng cara berikut. tapi kolom dimaksud tetap tidak tampil

$this->col = array();
if (CRUDBooster::isSuperadmin())
{
	$this->col[] = ["label"=>"Users","name"=>"id_cms_users","join"=>"cms_users,name"];
}
Ada saran ??

**Comment by fherryfherry** [comment]
Anda sudah memastikan login menggunakan akun superadmin ?

**Comment by pandanaran** [comment]
Yup, sudah login sebagai superadmin tapi kolom tetep tidak tampil mas..

**Comment by fherryfherry** [comment]
update to latest version
