### ISSUE TITLE
error on edit module

### ISSUE THREAD

**Issue by samucati** [crocodic-studio/crudbooster#1345]
my first module, while writing the record is giving error: Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException

**Comment by DeveloperOnCall** [comment]
@samucati - Did you get this worked out, looks like a routes problem. If it's working now, please close the issue -- if not, let me know and maybe I can help you solve it.

D

**Comment by abeltpn** [comment]
Hello, I have this problem, what is the solution?
