### ISSUE TITLE
module edit fields

### ISSUE THREAD

**Issue by squidv3** [crocodic-studio/crudbooster#1347]
I installed crudbooster on my host host, but the version is different from what I have installing on my xammp. And I'm not able to edit the modules (the display fields) and edit and add fields. can someone tell me what has changed and how do i see the installed version of crudbooster
![captura de tela 2018-12-24 as 16 46 16](https://user-images.githubusercontent.com/14914680/50406009-d700f400-079b-11e9-82b1-fc213f5aea69.png). hostgator

**Comment by DeveloperOnCall** [comment]
I'm not sure I understand your problem here -- but to see the version use the artisan command

```bash
   php artisan crudbooster:version
```
