### ISSUE TITLE
page_title only showing "1"

### ISSUE THREAD

**Issue by felipe-balloni** [crocodic-studio/crudbooster#1354]
laravel 5.7.*
PHP 7.3.0
Crudboster 5.4.15

A new installation and I noticed that $page_title at create or edit form is only showing " 1" instead data configured at module.

![image](https://user-images.githubusercontent.com/19998735/50727222-267de300-10ff-11e9-8d29-78d274887a5a.png)

**Comment by wladiz2001** [comment]
I have the same problem ...

**Comment by felipe-balloni** [comment]
I Solved this changing line 18 at crudbooster/src/views/default/form.blade.php:

From: <strong><i class='{{CRUDBooster::getCurrentModule()->icon}}'></i> {!! $page_title or "Page Title" !!}</strong>
to: <strong><i class='{{CRUDBooster::getCurrentModule()->icon}}'></i> {!! $page_title !!}</strong>

It'll solve at add form and edit form.

To complet the solution at edit form, we need to change languages files, its missing the second parameter :name at edit_data_page_title and detail_data_page_title.'

'edit_data_page_title' => 'Edit :module :name',
'detail_data_page_title' => 'Detail :module :name',

don't forget to check at other langs.

I recommend override crudbooster functions getadd, getedit and getdetail at controller.

Tks.

**Comment by wladiz2001** [comment]
According to the [official upgrade guide](https://laravel.com/docs/5.7/upgrade): `The Blade "or" operator has been removed in favor of PHP's built-in ?? "null coalesce" operator, which has the same purpose and functionality.`
