### ISSUE TITLE
Translate Upload Field Button 'Choose File | Answer from Crudbooster expected please !

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1355]
Hi,
Would appeciate a reaction from the crudbooster team, please tell me how to translate the upload field type button 'Choose File'. Reaction expected please, since you didn't seem to exist anymore...

**Comment by DeveloperOnCall** [comment]
@marcq64 - They are still around, just busy getting ready for the much-anticipated v6 of CRUDBooster... 

I have never chosen to change the file button text. From my brief research on your behalf, I found a possible solution.

As this is not at all related to CRUDBooster (that button and it's text are generated by the browser and not the underlying html code (and certainly not the server-side code)

Try using [Bootstrap File Style](https://markusslima.github.io/bootstrap-filestyle/) I think this might suit your needs. If not, I'd recommend finding a way to do this in jQuery as there is nothing CRUDBooster can do (or you can do in CRUDBooster alone) to change that text.

I hope this answers your question.
D.

**Comment by marcq64** [comment]
@DeveloperOnCall, 

I appreciate your feedback, thank you. 

I need to translate the 'Choose file' inot french or other languages, since I'm working mainly for european based companies which have other languages then english. So translation is an important issue for me.

I'm already using Jquery to translate other Crudbooster buttons like :

`/* OVERRIDE BUTTONS
/* Change the 'Ajouter' button value into 'Ajouter au panier' */
$('#btn-add-table-ordersdetail').val('Ajouter au panier');
/* Change the 'Ajouter' button value into 'Commander' */
$('#form > div.box-footer > div > div > input:nth-child(2)').val('Commander');

$("#content_section > div > div > div.panel-heading > strong").html("");
$( "<div>Commander</div>" ).insertAfter( "#content_section > div > div > div.panel-heading > strong");

$("#panel-form-ordersdetail > div.panel-body > div.row > div > div > div.panel-heading").html("");
$( "#panel-form-ordersdetail > div.panel-body > div.row > div > div > div.panel-heading" ).append( "<div>Choisissez vos produits</div>" );

$("#panel-form-ordersdetail > div.panel-body > div.panel.panel-default > div.panel-heading").html("");
$( "#panel-form-ordersdetail > div.panel-body > div.panel.panel-default > div.panel-heading" ).append( "<div>Votre panier</div>" );`

So I tried of course to do it for this upload button, but it I couldn.t find a way to make it work

It is why I had to post this issue and ask the Crudbooster team for some explanation how to deal with it. Because I'm not omniscient, because I was stuck and I thought a community should be interested in helping each other and share knowledge.

I will have a look to the bootstrap-filestylex.

Thanks anyway for your feedback, cheers, Marc

**Comment by DeveloperOnCall** [comment]
@marcq64 You should also change your ```<html>``` tag in the admin_template.blade.php to represent the user's language or a set language..

```<html lang="fr" xml:lang="fr" xmlns="http://www.w3.org/1999/xhtml">```

**Comment by marcq64** [comment]
@DeveloperOnCall,

Thanks, will do so !

**Comment by DeveloperOnCall** [comment]
Hey @marcq64 let's close this one off as well, please.

**Comment by marcq64** [comment]
@DeveloperOnCall, many thanks here too, cheers, Marc
