### ISSUE TITLE
Help with master/detail type child, please.

### ISSUE THREAD

**Issue by felipe-balloni** [crocodic-studio/crudbooster#1356]
HI, 

I'm trying to create a master / detail form where the detail table is optional (the user can insert details ou not).

And I have the problem that does not fill any details / child the crud inserts null data in the details tables.

I think it needs to make some change in the code of the postAddSave function for it to check if the child has no data.

Anyone have any tips, please?

**Comment by DeveloperOnCall** [comment]
@felipe-balloni I would recommend you make use of the ```hook_before_add()``` method to check those values and remove them if null from the $postdata.

D

**Comment by felipe-balloni** [comment]
Tanks!
