### ISSUE TITLE
How to use only my own insert query in admin controller?

### ISSUE THREAD

**Issue by wiraxie** [crocodic-studio/crudbooster#1357]
I just made a module and menu about user data. In the controller, i made a laravel query to insert into my database table inside **hook_before_add** function. The problem is, after I hit the save button, the controller inserted 2 records. All I need to to is use my own laravel query to insert into my table because I need encrypt the password field with my own function(my company's standard password encryption) there. Can anyone help me, please?
Thank you in advance!
![image](https://user-images.githubusercontent.com/15441120/50759190-dafe3d00-1296-11e9-8509-1a90de991f3c.png)

**Comment by DeveloperOnCall** [comment]
@wiraxie I believe you should be able to override the ```postAddSave()``` method in your controller that would give you complete control over the insert row. 

If you look at ...
```/vendor/crocodicstudio/crudbooster/src/controllers/CBController.php```

It will give you a better understanding on how to override it within your own (or CB Generated) controller.

Hope that helps :)
D

**Comment by DeveloperOnCall** [comment]
@wiraxie -- if this is all sorted, would you mind closing the issue? Helps the crocodic developers save time (hopefully to put towards the much anticipated v6.0..)

D
