### ISSUE TITLE
After update v5.3.1.0

### ISSUE THREAD

**Issue by rskonieczka** [crocodic-studio/crudbooster#136]
After update to v5.3.1.0 in own modules.

BTW. Good job

> - in Controller.php line 82
> - at Controller->__call('constructor', array()) in AdminLtmTranslationsController.php line 161
> - at AdminLtmTranslationsController->constructor() in AdminLtmTranslationsController.php line 161
> - at AdminLtmTranslationsController->__construct()
> - at ReflectionClass->newInstanceArgs(array()) in Container.php line 794
> - at Container->build('App\Http\Controllers\AdminLtmTranslationsController', array()) in Container.php line 644
> - at Container->make('App\Http\Controllers\AdminLtmTranslationsController', array()) in Application.php line 709
> - at Application->make('App\Http\Controllers\AdminLtmTranslationsController') in Route.php line 203
> - at Route->getController() in Route.php line 316
> - at Route->controllerMiddleware() in Route.php line 278
> - at Route->gatherMiddleware() in Router.php line 666
> - at Router->gatherRouteMiddleware(object(Route)) in Router.php line 646
> - at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 629
> - at Router->dispatchToRoute(object(Request)) in Router.php line 607
> - at Router->dispatch(object(Request)) in Kernel.php line 268
> - at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
> - at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
> - at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
> - at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> - at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
> - at Pipeline->then(object(Closure)) in Kernel.php line 150
> - at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
> - at Kernel->handle(object(Request)) in index.php line 54

---------
`# composer info`

> - barryvdh/laravel-dompdf               v0.7.1   A DOMPDF Wrapper for Laravel
> - barryvdh/laravel-translation-manager  v0.2.7   Manage Laravel Translations
> - classpreloader/classpreloader         3.1.0    Helps class loading performance by generating a single PHP file containing all of the autoloaded files for a specific use case
> - crocodicstudio/crudbooster            v5.3.1.0 CRUDBooster Laravel CRUD Generator. One Control, Powerfull, Mobile API Optimization
> - dnoegel/php-xdg-base-dir              0.1      implementation of xdg base directory specification for php
> - doctrine/annotations                  v1.3.1   Docblock Annotations Parser
> - doctrine/cache                        v1.6.1   Caching library offering an object-oriented API for many cache backends
> - doctrine/collections                  v1.4.0   Collections Abstraction library
> - doctrine/common                       v2.7.2   Common Library for Doctrine projects
> - doctrine/dbal                         v2.5.10  Database Abstraction Layer
> - doctrine/inflector                    v1.1.0   Common String Manipulations with regard to casing and singular/plural rules.
> - doctrine/instantiator                 1.0.5    A small, lightweight utility to instantiate objects in PHP without invoking their constructors
> - doctrine/lexer                        v1.0.1   Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
> - dompdf/dompdf                         v0.7.0   DOMPDF is a CSS 2.1 compliant HTML to PDF converter
> - fzaninotto/faker                      v1.6.0   Faker is a PHP library that generates fake data for you.
> - guzzlehttp/psr7                       1.3.1    PSR-7 message implementation
> - hamcrest/hamcrest-php                 v1.2.2   This is the PHP port of Hamcrest Matchers
> - intervention/image                    2.3.10   Image handling and manipulation library with support for Laravel integration
> - intervention/imagecache               2.3.3    Caching extension for the Intervention Image Class
> - jakub-onderka/php-console-color       0.1      
> - jakub-onderka/php-console-highlighter v0.3.2   
> - jeremeamia/SuperClosure               2.3.0    Serialize Closure objects, including their context and binding
> - laravel/framework                     v5.3.30  The Laravel Framework.
> - league/flysystem                      1.0.33   Filesystem abstraction: Many filesystems, one API.
> - maatwebsite/excel                     2.1.10   An eloquent way of importing and exporting Excel and CSV in Laravel 4 with the power of PHPExcel
> - mockery/mockery                       0.9.7    Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other testing framework. Its core goal is to offer a test double framework...
> - monolog/monolog                       1.22.0   Sends your logs to files, sockets, inboxes, databases and various web services
> - mtdowling/cron-expression             v1.2.0   CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
> - myclabs/deep-copy                     1.6.0    Create deep copies (clones) of your objects
> - nesbot/carbon                         1.22.1   A simple API extension for DateTime.
> - nikic/php-parser                      v3.0.2   A PHP parser written in PHP
> - paragonie/random_compat               v2.0.4   PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
> - phenx/php-font-lib                    0.4      A library to read, parse, export and make subsets of different types of font files.
> - phenx/php-svg-lib                     0.1      A library to read, parse and export to PDF SVG files.
> - phpdocumentor/reflection-common       1.0      Common reflection classes used by phpdocumentor to reflect the code structure
> - phpdocumentor/reflection-docblock     3.1.1    With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
> - phpdocumentor/type-resolver           0.2.1    
> - phpoffice/phpexcel                    1.8.1    PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
> - phpspec/prophecy                      v1.6.2   Highly opinionated mocking framework for PHP 5.3+
> - phpunit/php-code-coverage             4.0.5    Library that provides collection, processing, and rendering functionality for PHP code coverage information.
> - phpunit/php-file-iterator             1.4.2    FilterIterator implementation that filters files based on a list of suffixes.
> - phpunit/php-text-template             1.2.1    Simple template engine.
> - phpunit/php-timer                     1.0.8    Utility class for timing
> - phpunit/php-token-stream              1.4.9    Wrapper around PHP's tokenizer extension.
> - phpunit/phpunit                       5.7.9    The PHP Unit Testing framework.
> - phpunit/phpunit-mock-objects          3.4.3    Mock Object library for PHPUnit
> - psr/http-message                      1.0.1    Common interface for HTTP messages
> - psr/log                               1.0.2    Common interface for logging libraries
> - psy/psysh                             v0.8.1   An interactive shell for modern PHP.
> - ramsey/uuid                           3.5.2    Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
> - sebastian/code-unit-reverse-lookup    1.0.0    Looks up which function or method a line of code belongs to
> - sebastian/comparator                  1.2.4    Provides the functionality to compare PHP values for equality
> - sebastian/diff                        1.4.1    Diff implementation
> - sebastian/environment                 2.0.0    Provides functionality to handle HHVM/PHP environments
> - sebastian/exporter                    2.0.0    Provides the functionality to export PHP variables for visualization
> - sebastian/global-state                1.1.1    Snapshotting of global state
> - sebastian/object-enumerator           2.0.0    Traverses array structures and object graphs to enumerate all referenced objects
> - sebastian/recursion-context           2.0.0    Provides functionality to recursively process PHP variables
> - sebastian/resource-operations         1.0.0    Provides a list of PHP built-in functions that operate on resources
> - sebastian/version                     2.0.1    Library that helps with managing the version number of Git-hosted PHP projects
> - swiftmailer/swiftmailer               v5.4.5   Swiftmailer, free feature-rich PHP mailer
> - symfony/console                       v3.1.10  Symfony Console Component
> - symfony/css-selector                  v3.1.10  Symfony CssSelector Component
> - symfony/debug                         v3.1.10  Symfony Debug Component
> - symfony/dom-crawler                   v3.1.10  Symfony DomCrawler Component
> - symfony/event-dispatcher              v3.2.2   Symfony EventDispatcher Component
> - symfony/finder                        v3.1.10  Symfony Finder Component
> - symfony/http-foundation               v3.1.10  Symfony HttpFoundation Component
> - symfony/http-kernel                   v3.1.10  Symfony HttpKernel Component
> - symfony/polyfill-mbstring             v1.3.0   Symfony polyfill for the Mbstring extension
> - symfony/polyfill-php56                v1.3.0   Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
> - symfony/polyfill-util                 v1.3.0   Symfony utilities for portability of PHP codes
> - symfony/process                       v3.1.10  Symfony Process Component
> - symfony/routing                       v3.1.10  Symfony Routing Component
> - symfony/translation                   v3.1.10  Symfony Translation Component
> - symfony/var-dumper                    v3.1.10  Symfony mechanism for exploring and dumping PHP variables
> - symfony/yaml                          v3.2.2   Symfony Yaml Component
> - tijsverkoyen/css-to-inline-styles     2.2.0    CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when you're sending emails.
> - unisharp/laravel-filemanager          1.6.3    A file upload/editor intended for use with Laravel 5 and CKEditor / TinyMCE
> - vlucas/phpdotenv                      v2.4.0   Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
> - webmozart/assert                      1.2.0    Assertions to validate method input/output with nice error messages.

-------------
`composer diagnose `
> 

- >Checking composer.json: OK
- > Checking platform settings: OK
- > Checking git settings: OK
- > Checking http connectivity to packagist: OK
- > Checking https connectivity to packagist: OK
- > Checking github.com oauth access: OK
- > Checking disk free space: OK
- > Checking pubkeys: 
- > Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
- > Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
- > OK
- > Checking composer version: OK

**Comment by fherryfherry** [comment]
Hi please follow upgrade guide
Pada tanggal 30 Jan 2017 20.28, "Rafał Skonieczka" <notifications@github.com>
menulis:

**Comment by rskonieczka** [comment]
@fherryfherry 
After remove `$this->constructor();`
> BadMethodCallException in Controller.php line 82:
> Method [cbInit] does not exist.

**Comment by fherryfherry** [comment]
Have you rename the construct to cbInit?
Pada tanggal 30 Jan 2017 20.38, "Rafał Skonieczka" <notifications@github.com>
menulis:

**Comment by rskonieczka** [comment]
@fherryfherry Could you give detailed instructions. TNX

**Comment by fherryfherry** [comment]
Open AdminLtmTranslationsController.php
1. at line function __construct() { rename to function cbInit() {
2. at that method also, at the bottom of method, there is $this->constructor(), remove that
