### ISSUE TITLE
SOLVED & SOLUTION | One Controller function for multiple queries and one route

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1361]
Following my previous question : https://github.com/crocodic-studio/crudbooster/issues/1360

I have created a custom controller to create dashboards for each of my defined Role|Privilege :

The Dashboards will contain Role|Privilege specific statistics.

In order to populate the Role|Privilege specific statistics, I have created a function with already 2 statistics for one of my role :

public function customer_statistics()
{

	$customer_untreated = DB::table('orders_detail')
			->distinct('orderID')
			->where('statusorderID', '=', 2)
			->where('orders_detail.userID','=',Session::get('admin_id'))
			->count('orderID');

	return view ('customer_dashboard')->with('customer_untreated',$customer_untreated);

	$customer_open = DB::table('orders_detail')
			->distinct('orderID')
			->where('statusorderID', '=', 3)
			->where('orders_detail.userID','=',Session::get('admin_id'))
			->count('orderID');

	return view ('customer_dashboard')->with('customer_open',$customer_open);

}

The route I have defined is : 

Route::get('/admin', 'DashboardsController@customer_statistics');

But it doesn't work, only the first small-box is populated with the query returned value :

![image](https://user-images.githubusercontent.com/33374514/50903089-530f6300-144f-11e9-857c-b973a2764156.png)

I guess I have a route issue. I'm stuck and I would need some help here. Thanks in advance, cheers, Marc

**Comment by marcq64** [comment]
Ok found the solution :

I change the return of my function in the controller :

		    public function customer_statistics()
		    {

		    	$customer_untreated = DB::table('orders_detail')
						->distinct('orderID')
						->where('statusorderID', '=', 2)
						->where('orders_detail.userID','=',Session::get('admin_id'))
						->count('orderID');

				// return view ('customer_dashboard')->with('customer_untreated',$customer_untreated);

		    	$customer_open = DB::table('orders_detail')
						->distinct('orderID')
						->where('statusorderID', '=', 3)
						->where('orders_detail.userID','=',Session::get('admin_id'))
						->count('orderID');

				// return view ('customer_dashboard')->with('customer_open',$customer_open);
				return view ('customer_dashboard',compact('customer_untreated', 'customer_open'));

		    }

Route is :

Route::get('/admin', 'DashboardsController@customer_statistics');

View :

{{ $customer_untreated }}
{{ $customer_open }}

Result :

![image](https://user-images.githubusercontent.com/33374514/50903875-776c3f00-1451-11e9-918c-b9c3f2f76014.png)


-----

We are a community, so please don't be a j... and share your solutions with the other people, because they might certainly encounter the same problem one day.

**Comment by DeveloperOnCall** [comment]
You are returning something before you are finished gathering content for the view. Try this..

```php
public function customer_statistics() {

         $data = array();

         $customer_untreated = DB::table('orders_detail')
		->distinct('orderID')
		->where('statusorderID', '=', 2)
		->where('orders_detail.userID','=',Session::get('admin_id'))
		->count('orderID');

         $data['customer_untreated'] = $customer_untreated;

        $customer_open = DB::table('orders_detail')
		->distinct('orderID')
		->where('statusorderID', '=', 3)
		->where('orders_detail.userID','=',Session::get('admin_id'))
		->count('orderID');

       $data['customer_open'] = $customer_open;

    return view('customer_dashboard', $data);
}
```

Now you access the data using $customer_untreated and $customer_untreated inside your view.

Hope that helps..
D

**Comment by DeveloperOnCall** [comment]
HAHA -- looks like ya didn't need help at all -- just time... :)

**Comment by marcq64** [comment]
@DeveloperOnCall

I managed to solve it, don't know which solution is more elegant, but it works ! Thanks anyway, most appreciate your support, cheers, Marc

**Comment by DeveloperOnCall** [comment]
To make life easier - laravel has some shortcuts.. you can streamline these lines..

```php
                 ->where('statusorderID', '=', 3)
		->where('orders_detail.userID','=',Session::get('admin_id'))
```

By removing the '=' like below..

```php
                 ->where('statusorderID', 3)
		->where('orders_detail.userID,Session::get('admin_id'))
```

When it is a '=' the query needs...

Might save ya a bit of time...

**Comment by marcq64** [comment]
@DeveloperOnCall,
I really start to enjoy the Laravel environment and Crudbooster, since I become more savy and can start to solve issues by myself. And thanks to people like you I can learn and improve my skills, it is why it is in my opinion important in a community like ours to share our knowledge. Thanks again, its late now in Saigon so I stop for today, cheers, Marc

**Comment by DeveloperOnCall** [comment]
@marcq64 catch me on Skype (oncalldeveloper) -- I'd like to talk.
