### ISSUE TITLE
Controller | Get $row id in query

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1365]
Hi,

I have created a crud to upload pictures. I have added a checkbox field in order to enable the user to set a category or several categories for the uploaded pictures.

I have created a relationship :
$this->form[] = ['label'=>'Catégorie','name'=>'category','type'=>'checkbox','validation'=>'required','width'=>'col-sm-10','datatable'=>'gallery_category,name','relationship_table'=>'image_categories'];

which save the checked value(s) into the following table :

**mage_categories**
id  |  gallery_images_id  |  gallery_category_id
26 |  2995	              |  4
27 |  2995	              |  5
28 |  2995	              |  6
29 |  2993	              |  7
30 |  2993	              |  10
31 |  2993	              |  4
32 |  2993	              |  5
33 |  2993	              |  6

I have created an other table which contains the gallery categories :

**gallery_category**

id  |  name
4  |  Fille
5  |  Garçon
6  |  Pour les petits
7  |  Adultes
8  |  Mariage
9  |  Evénements religieux
10|  Entreprise

I would like to populate the table Categorie column 

![image](https://user-images.githubusercontent.com/33374514/51082859-cbbd3a80-1741-11e9-9f17-067f14642820.png)

with the data from the relationship table and instead of displaying the value (4,5,6 etc.) displaying the selected categories from the gallery_category (Fille, Garçon, Pour les petits etc.).

In the detail view you can see the 3 category tags just above the image. I would like to have those three tags displayed into the category table column :

![image](https://user-images.githubusercontent.com/33374514/51096778-b3a4f400-17f1-11e9-86d4-0487c5228cbf.png)

I didn't know how to do it in a simple way (if there's one) and I couldn't find consistent explanation (documentation or forum questions) on how to deal with the relationship table related datas in order to display the tags (similar as in the detail view). So I thought I can create a query to get the values :

$this->col[] = ['label'=>"Catégorie","name"=>"(select GROUP_CONCAT(gallery_category.name) from gallery_images join image_categories on gallery_images.id=image_categories.gallery_images_id join gallery_category on image_categories.gallery_category_id=gallery_category.id where image_categories.gallery_images_id = gallery_images.id) as Catégorie"];

The query is returning the appropriate value in SQL but of course doesn't work in CRUDBooster since I need to populate the individual rows with their select categories.

So I thought I could just retrieve the row id.

I added this :

$row = CRUDBooster::first($this->table,$id);

And changed the where clause of my query with :

where image_categories.gallery_images_id =$row.

But it doesn't work too.

So now I'm stuck and I need the CRUDBooster team to help solve this trivial issue which "costs" me already over 3 hours of no success.

Would appreciate your help. Thanks, cheers, Marc

**Comment by DeveloperOnCall** [comment]
I think this is just a small error - but I could be wrong.

This gives you the full row..
```php
$row = CRUDBooster::first($this->table,$id);
```

This tells Laravel to look for a row where the 'id' = the full row.
```php
   where image_categories.gallery_images_id =$row.
```

Give it the 'id' from the row
```php
where image_categories.gallery_images_id =$row->id
```

Hope that helps.
D

**Comment by marcq64** [comment]
Hi,

Thanks for your reply !

I've already tried with $row->id, but I get the following error :

# START GET THE ROW ID
			$row = CRUDBooster::first($this->table,$id);
			# END GET THE ROW ID

			# START COLUMNS DO NOT REMOVE THIS LINE
			$this->col = [];
			$this->col[] = ['label'=>"Catégorie","name"=>"(select GROUP_CONCAT(gallery_category.name) from gallery_images join image_categories on gallery_images.id=image_categories.gallery_images_id join gallery_category on image_categories.gallery_category_id=gallery_category.id where image_categories.gallery_images_id = $row->id) as Catégorie"];
			$this->col[] = ["label"=>"Image","name"=>"upload_model","image"=>true,"width"=>"450px"];
			# END COLUMNS DO NOT REMOVE THIS LINE

Controller :

# START GET THE ROW ID
			$row = CRUDBooster::first($this->table,$id);
			# END GET THE ROW ID

			# START COLUMNS DO NOT REMOVE THIS LINE
			$this->col = [];
			$this->col[] = ['label'=>"Catégorie","name"=>"(select GROUP_CONCAT(gallery_category.name) from gallery_images join image_categories on gallery_images.id=image_categories.gallery_images_id join gallery_category on image_categories.gallery_category_id=gallery_category.id where image_categories.gallery_images_id = $row->id) as Catégorie"];
			$this->col[] = ["label"=>"Image","name"=>"upload_model","image"=>true,"width"=>"450px"];
			# END COLUMNS DO NOT REMOVE THIS LINE

I also tried with the hook_row_index instead of the query into the col[]  :

Changed : $this->col[] = ['label'=>"Catégorie","name"=>"category"];

public function hook_row_index($row,$column_index,&$column_value) {       
	
		if($column_index == 1) {

			/* START POPULATE the laboratory FIELD */
			/* dd($id); */

			/* REQUESTED VALUE */
	    	$row = DB::table($this->table)->where("id", $id)->first();

			/* QUERY */
			/* SQL : GET THE CATEGORY(-IES) */
			
			$categorytags = DB::table('gallery_images')
							->join('image_categories','gallery_images.id', '=', 'image_categories.gallery_images_id')
							->join('gallery_category','image_categories.gallery_category_id', '=', 'gallery_category.id')
							->select('gallery_category.name')
							->where('image_categories.gallery_images_id', '=', $row->id)
							->get();
	    	// dd($category_tags);
			
			$column_value = $categorytags;
	        
		}

No error message here

but the Category column is populated with a []

No clue what is wrong here...

**Comment by marcq64** [comment]
Anyone has an idea or had the same issue and could kindly point me in the right direction ?

**Comment by marcq64** [comment]
tried this also

           if($column_index == 1) {

				/* START POPULATE the laboratory FIELD */
				/* dd($id); */

				/* REQUESTED VALUE */
		    	$row = CRUDBooster::first($this->table,$id);
				/* dd($row); */

				/* QUERY */
				/* SQL : GET THE CATEGORY(-IES) */
				
				$categories = DB::table('gallery_images')
								->join('image_categories','gallery_images.id', '=', 'image_categories.gallery_images_id')
								->join('gallery_category','image_categories.gallery_category_id', '=', 'gallery_category.id')
								->select('gallery_category.name')
								->where('image_categories.gallery_images_id', '=', '$row->id')
								->get();
		    	// dd($category_tags);
				
				$column_value = $categories;
		        
			}

nothing returned, I really need here your expertise guys, my query is working fine but nothing is returned in the category column... only []

**Comment by marcq64** [comment]
I can't get the row id, need definitively help here...

**Comment by DeveloperOnCall** [comment]
@marcq64 Have you considered creating your own index view for this page?

What if we tried this

```php
public function hook_row_index($column_index,&$column_value) {

	if($column_index == 1 ) {

		$row_id = $column_value;
                 define("ROW_ID", $row_id);

	}
	
	if( $column_index == 2 && defined("ROW_ID") ) {

		$categories = DB::table('gallery_images')
		->join('image_categories','gallery_images.id', '=', 'image_categories.gallery_images_id')
		->join('gallery_category','image_categories.gallery_category_id', '=', 'gallery_category.id')
		->select('gallery_category.name')
		->where('image_categories.gallery_images_id', '=', ROW_ID)
		->get();
				
		// dd($categories);
		
		$column_value = $categories;

	}

}

```

As I said, I've never done anything similar - so this is a best-guess situation... lol
D

**Comment by marcq64** [comment]
Hey thanks ! Sadly still no value returned...

**Comment by marcq64** [comment]
strange... nothing happen...

[](https://www.screencast.com/t/oMw8Zog4)

**Comment by DeveloperOnCall** [comment]
Come onto Stack...

**Comment by DeveloperOnCall** [comment]
I believe this is working...

```php
if( $column_index == 2 && defined("ROW_ID") ) {

				$categories = DB::table('gallery_images')
				->join('image_categories','gallery_images.id', '=', 'image_categories.gallery_images_id')
				->join('gallery_category','image_categories.gallery_category_id', '=', 'gallery_category.id')
				->select('gallery_category.name')
				->where('image_categories.gallery_images_id', '=', ROW_ID)
				->get();
						
				//dd($categories);
                $vals = '';
                foreach($categories as $cati){
                    $vals .= $cati->name.',';
                }
				
				$column_value = $vals;

}
```

**Comment by marcq64** [comment]
@DeveloperOnCall

Like always you nailed it ! Appreciate your dedicated support D, thanks. 

I should have remembered that foreach was neccessary since I was returning an array... 

**SOLUTION :**

public function hook_row_index($column_index,&$column_value) {

			if($column_index == 1 ) {

				$row_id = $column_value;
				define('ROW_ID', $row_id);

			}
			
			if( $column_index == 2 && defined('ROW_ID') ) {

				$categories = DB::table('gallery_images')
								->join('image_categories','gallery_images.id', '=', 'image_categories.gallery_images_id')
								->join('gallery_category','image_categories.gallery_category_id', '=', 'gallery_category.id')
								->select('gallery_category.name')
								->where('image_categories.gallery_images_id', '=', ROW_ID)
								->get();
						
				// dd($categories);
                $returned_values = '';

                foreach($categories as $caties) {

                    $returned_values .= $caties->name.' | ';

                }
				
				$column_value = $returned_values;

			}

		}
