### ISSUE TITLE
SOLVED & SOLUTION | Date | Form Field | How reformat Date before storage into table | Hook Method

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1375]
Hi,

I'm using a datepicker where the date format is 'D. d MM yyyy' (displayed : Mer. 23 Janvier 2019).

Of course this value can't be saved into by table column.

So I would like to change the date format before this element value is saved into the table. Is there an hook method which enable to change | format etc. element values before being saved into the table ?

if it is the hook_before_add than it doesn't work with :

		   `# START POPULATE the delivery_date VALUE

			# QUERY
			# GET the delivery_date VALUE
	    	
	    	$deliverydate = $_REQUEST['delivery_date']; // Mer. 23 Janvier 2019

	    	$formatter = new \IntlDateFormatter('fr_FR', \IntlDateFormatter::NONE, \IntlDateFormatter::NONE);
			$formatter->setPattern('eee dd MMMM y');
			$deliverydate_conv_1 = $formatter->parse($deliverydate);
			$deliverydate_conv_2 = date('Y-m-d', $deliverydate_conv_1);

	    	// dd($deliverydate_conv_2);

			# UPDATE THE delivery_date VALUE WITH THE NEWLY FORMATED DATE VALUE

			DB::table('orders')
	                ->where('orderID', '=', $id)
	                ->update(array('delivery_date' => $deliverydate_conv_2));

		    # END POPULATE the delivery_date VALUE
`

Following error is displayed :

`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: 'Jeu. 31 Janvier 2019' for column 'delivery_date' at row 1 (SQL: insert into `orders` (`total`, `delivery_date`, `userID`, `roleID`, `created_at`) values (195, Jeu. 31 Janvier 2019, 5, 4, 2019-01-20 07:42:21))`

Crudbooster support needed here since handling date is a pain in the ... here.

Cheers,

Marc

**Comment by marcq64** [comment]
I added my own method into the controller :

**Controller**

	    public function setDateAttribute($input)
		{

	    $this->attributes['delivery_date'] = 
			Carbon::createFromFormat(config('app.delivery_date_format'), $input)->format('Y-m-d');
		
		}

**App**
    /*
    |--------------------------------------------------------------------------
    | Application Delivery_Date Formats
    |--------------------------------------------------------------------------
    |
    */

    'delivery_date_format' => 'D d MM yyyy',
    'delivery_date_format_js' => 'D d MM yyyy',

but also not working. 

So please need Crudbooster team here to give me an example on how to do it properly with Crudbooster.

Thanks in advance

**Comment by marcq64** [comment]
Hi,
Would appreciate some support here to point me in the right direction since it is not obvious. Thanks in advance, cheers, Marc

**Comment by marcq64** [comment]
**SOLUTION :**

	    public function hook_before_add(&$postdata) {

		    # START REFORMAT the delivery_date VALUE BEFORE STORAGE

			# GET the delivery_date VALUE
	    	
	    	$deliverydate = $postdata['delivery_date']; // Mer. 23 Janvier 2019

	    	$formatter = new \IntlDateFormatter('fr_FR', \IntlDateFormatter::NONE, \IntlDateFormatter::NONE);
			$formatter->setPattern('eee dd MMMM y');
			$formatter_parse = $formatter->parse($deliverydate);
			$deliverydate_formatted = date('Y-m-d', $formatter_parse);

			$postdata['delivery_date'] = $deliverydate_formatted; // 2019-01-23

			// dd($deliverydate_formatted);

		    # END REFORMAT the delivery_date VALUE BEFORE STORAGE

	    }

Special thanks to @DeveloperOnCall which helped to fix this issue

**Comment by josetiagobispo** [comment]
I would solve it in an easier way


[cvtxnyST.txt](https://github.com/crocodic-studio/crudbooster/files/2962264/cvtxnyST.txt)

**Comment by marcq64** [comment]
Thanks @josetiagobispo, in the meantime I solved it with one line with the welll known strtotime :

$postdata['delivery_date'] = date("Y-m-d",strtotime($postdata['delivery_date']));
