### ISSUE TITLE
Type Header

### ISSUE THREAD

**Issue by squidv3** [crocodic-studio/crudbooster#1377]
I tried to put a header through the control of modules but it only works if I put a value in the field "name" however at the time of inserting the data in the database it treats the header as a field of the database. is there any way around this?

![captura de tela 2019-01-22 as 16 53 09](https://user-images.githubusercontent.com/14914680/51561517-379c5300-1e66-11e9-836d-8ad957de6dfc.png)

**Comment by DeveloperOnCall** [comment]
>  put a header through the control of modules

I am not sure it is clear what you are trying to do here...

D

**Comment by squidv3** [comment]
> > put a header through the control of modules
> 
> I am not sure it is clear what you are trying to do here...
> 
> If you are trying to add a sort of 'section header' - that cannot be done in the module generator.
> 
> D

and how can I put a header outside the generated module (controllerxxx) without having to create a custom add

**Comment by squidv3** [comment]
![captura de tela 2019-01-25 as 18 59 07](https://user-images.githubusercontent.com/14914680/51775120-679c5e00-20d3-11e9-8701-76a666fcd5c6.png)

I need this information in my form

**Comment by caweb** [comment]
You have to put the header above the field where you want it to appear and put in "NAME" the name of the field in the table
Example:
$this->form[] = ["label"=>"Header Form","type"=>"header","name"=>"**field_name**"];
$this->form[] = ['label'=>'FirstName','name'=>'**field_name**','type'=>'text','validation'=>'max:50'];
