### ISSUE TITLE
select2 work like datamodal 

### ISSUE THREAD

**Issue by samidcode** [crocodic-studio/crudbooster#1380]
hello please help  i want select2 work like datamodal in child   because i want to place datamodal with select 2 
i want select2 fill all columns

			# START FORM DO NOT REMOVE THIS LINE
			$this->form = [];
			$this->form[] = ['label'=>'Numéro de commande','name'=>'num-_comm','type'=>'text','validation'=>'required|min:1|max:255','width'=>'col-sm-10'];

				$columns=[];
			$columns[] = ['label'=>'code de produit','name'=>'produit_id','type'=>'datamodal','datamodal_table'=>'produit','datamodal_where'=>'produit.qty > 0 ','datamodal_columns'=>'code,nom','datamodal_select_to'=>'nom:nom,prix_unit:prix_unit,code:code','datamodal_size'=>'large'];
			$columns[] = ['label'=>'Nom de produit','name'=>'nom','type'=>'text','required'=>true];
			$columns[] = ['label'=>'Prix unitaire','name'=>'prix_unit','type'=>'number','required'=>true];
			
			$columns[] = ['label'=>'Prix de vente','name'=>'price_vent','type'=>'number','required'=>true ] ;
			
			$this->form[] = ['label'=>'Orders Detail','name'=>'orders_detail','type'=>'child','columns'=>$columns,'table'=>'comm_info','foreign_key'=>'commande_id'];

			$this->form[] = ['label'=>'Type de paiement','name'=>'type','type'=>'select','validation'=>'required|min:1|max:255','width'=>'col-sm-10','dataenum'=>'Espèces ;Chèque'];
			$this->form[] = ['label'=>'Totale','name'=>'totale','type'=>'money','validation'=>'required|integer|min:0','width'=>'col-sm-10'];`

![2f2e64988b557adcbe9e37ebd7e15fde](https://user-images.githubusercontent.com/47065346/51872748-76447880-2352-11e9-9d87-31a2d2cccb6b.jpg)

**Comment by samidcode** [comment]
eny help please i can pay you if you want

**Comment by ontzuevanhussen** [comment]
I can help you

**Comment by samidcode** [comment]
thats my facebook if you wana contact me  fb.com/anas.samidi

**Comment by samidcode** [comment]
please what  you need to help me


‫في الأحد، 3 فبراير 2019 في 3:56 م تمت كتابة ما يلي بواسطة
‪ontzuevanhussen‬‏ <‪notifications@github.com‬‏>:‬
