### ISSUE TITLE
Get LoggedIn User

### ISSUE THREAD

**Issue by hassekf** [crocodic-studio/crudbooster#139]
How do i get the current logged in user INSIDE __construct in the controller?

Every helper i try to use inside the construct, comes back NULL.

**Comment by fherryfherry** [comment]
its laravel 5.3 problem, please upgrade to the latest cb version and then follow the upgrade guide 
http://crudbooster.com/doc/5.3/upgrade-guide

**Comment by hassekf** [comment]
Sorry but i'm using both laravel last version and CB version. That's probably not the issue.
