### ISSUE TITLE
FatalErrorException in AdminController.php line 750: Class 'App\Users' not found

### ISSUE THREAD

**Issue by harimayco** [crocodic-studio/crudbooster#14]
found this issue when doing relogin from unlock screen.
FatalErrorException in AdminController.php line 750: Class 'App\Users' not found
code line 750 :
`$users 		= Users::find($id); 	`
seems the Users.php file model has been deleted
7f1c06c3ee8725f935097bcbe1a530cdb6b52704

**Comment by fherryfherry** [comment]
please update
