### ISSUE TITLE
Get LoggedIn User

### ISSUE THREAD

**Issue by hassekf** [crocodic-studio/crudbooster#140]
How do i get the current logged in user INSIDE __construct in the controller?

Every helper i try to use inside the construct, comes back NULL.

ps: i'm using both laravel last version and CB version. That's probably not the issue.

Laravel Framework 5.4.6.

And it's a fresh install of them.

**Comment by fherryfherry** [comment]
have you try CRUDBooster::myId() ?

**Comment by hassekf** [comment]
Yes, like i said, every helper i try inside the construct, gives me NULL back when related to loggedin user data. 

myId and myPrivilegeId as well. I needed to check those, wanted to work on some conditions for the form.

**Comment by fherryfherry** [comment]
Sorry you said construct, but in the latest CB version not using construct anymore instead cbInit() ....

**Comment by hassekf** [comment]
That is strange. I installed CB from the command line less than 24h ago with the command:

composer require crocodicstudio/crudbooster=5.3.1.*

So what do i do to check CB version?

**Comment by tomatoe45** [comment]
BTW @hassekf .. did you receive any error like Application::share() when you try to create fresh laravel project 5.4.* and the CB?

**Comment by hassekf** [comment]
@tomatoe45 

Yes. ::share() is deprecated in 5.4, you need to replace in two locations:

`vendor/unisharp/laravel-filemanager/src/LaravelFilemanageServiceProvider.php
line 47`

Replace:
`$this->app['laravel-filemanager'] = $this->app->share(function ()`
by
`$this->app->singleton('laravel-filemanager', function ()`

---------------------------------------

And also in

`vendor/crocodicstudio/crudbooster/src/CRUBBoosterServiceProvider.php Line 74~`

Replace
`$this->app['crudbooster'] = $this->app->share(function ()`
by
`$this->app->singleton('crudbooster', function ()`

With that, you will be able to run:
php artisan vendor:publish
and
php artisan vendor:publish --provider="crocodicstudio\crudbooster\CRUDBoosterServiceProvider" --force

Without the artisan error on share() function undefined. 

@fherryfherry I'm not very used to github, can you make that fix and credit my help if possible?

:+1:

**Comment by fherryfherry** [comment]
noted @hassekf thank

**Comment by tomatoe45** [comment]
Yay it work.. Thanks @hassekf . and also when i'm trying migrate the database i have this error 

"Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `
users  ←[39;49m
←[37;41m  _email_unique`(`email`))"

I have added the code in boot() 

" Schema::defaultStringLength(191); "

and include the 

"use Illuminate\Support\Facades\Schema;"

and works fine now.. Thanks..
