### ISSUE TITLE
hook_before_delete & hook_after_delete are not trigger when using bulk delete

### ISSUE THREAD

**Issue by oppakub** [crocodic-studio/crudbooster#141]
Hi,

When I deleted all records using the bulk delete button, it seems that the functions hook_before_delete and hook_after_delete are not triggered.

I am on version 5.3.1.2

**Comment by tomatoe45** [comment]
@oppakub  on what form sir?

**Comment by oppakub** [comment]
on my customized form that was automatically generated by your framework

**Comment by tomatoe45** [comment]
@oppakub  this is not my framework btw. i am also a user of this wonderful framework.. is great isn't it?

**Comment by fherryfherry** [comment]
update to latest version
