### ISSUE TITLE
problems deploying

### ISSUE THREAD

**Issue by baradhili** [crocodic-studio/crudbooster#1410]
Hi,
noticed a few things that seem to be a bit weird..
1. if I deploy this to a server, the modules I've created disappear from my sidebar
2. I seem to need to run crudbooster install command to get things working at all even though I copied pretty much everything up (though excluded node_modules)

Any advice?
Thanks

**Comment by xant1986** [comment]
is your server environment same as your local? 
reference to this https://laravel.com/docs/5.0#server-requirements

**Comment by baradhili** [comment]
yes,
but what I noticed is that I need to update the seeders. the default seeders only build the menus and modules for the base.. So future people with this problem, crudbooster doesn't do everything for you :)..

**Comment by sdmalfian** [comment]
> yes, but what I noticed is that I need to update the seeders. the default seeders only build the menus and modules for the base.. So future people with this problem, crudbooster doesn't do everything for you :)..

Hello, how do you then exporting your modules to deployment?

**Comment by baradhili** [comment]
I gave up to be honest
