### ISSUE TITLE
Mask in form fields

### ISSUE THREAD

**Issue by mpiacentinis** [crocodic-studio/crudbooster#1411]
How do I create masks on forms, where should I change them? how should I proceed?
Ex. 99.999.999/9999-99
99.999-999

**Comment by hillgp** [comment]
https://pt.stackoverflow.com/questions/177760/como-se-faz-m%C3%A1scara-para-exibi%C3%A7%C3%A3o-de-fone-cnpj-cpf-etc-no-laravel

**Comment by felipe-balloni** [comment]
boa noite.

eu fiz várias modificações e alterei os componentes do crud, para que possa usar no controller direto. Segue exemplo.

```

[text.zip](https://github.com/crocodic-studio/crudbooster/files/2985929/text.zip)


 $this->form[] = ['label'=>'CPF/CPNJ','name'=>'federal_id','type'=>'text','validation'=>'max:25|unique:clients|formato_cpf_cnpj|cpf_cnpj','width'=>'col-sm-10',
                             'help'=>'CPF no formato 000.000.000-00 ou CPNJ no formato 00.000.000/0000-00.',
                             'mask'=>'\'mask\':[\'999.999.999-99\', \'99.999.999/9999-99\']'];
```
tem modificar o componente **text** do crud em dois arquivos da uma olhada neles... e tem que colocar os plugins no admin_template_plugins.blade.php 

`
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.5/jquery.inputmask.bundle.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/inputmask/inputmask.extensions.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.5/inputmask/inputmask.date.extensions.js"></script>`

**Comment by mpiacentinis** [comment]
Otimo, conseguiu, grato pela atenção.
