### ISSUE TITLE
Custom Home Page and Template

### ISSUE THREAD

**Issue by tiznull** [crocodic-studio/crudbooster#1413]
Is there a way to have your own login page and wrapper for the blade template? Meaning, how do you extend the design with your own blade template for the login page and admin area?

**Comment by Inxo** [comment]
Sure. Copy login.blade.php into /resources/views/vendor/crudbooster/login.blade.php and change

**Comment by tiznull** [comment]
You just made my day. Thank you!!!

**Comment by marcq64** [comment]
Please close your issue
