### ISSUE TITLE
Need help with callback_php

### ISSUE THREAD

**Issue by roriau** [crocodic-studio/crudbooster#1415]
Hello 
I have a expiration date field like this 2019-03-03 12:12:12

> $this->col[] = ["label"=>"Expiration date","name"=>"exp_date"];

 and i want to set callback_php to change this field to remaining days like this

> $startdate="now"; 
> $enddate="exp_date"; 
> 
> $diff=strtotime($enddate)-strtotime($startdate);  
> $temp=$diff/86400;
> $days=floor($temp); echo $days; $temp=24*($temp-$days);

anyway to make this happen ? help appreciated.
Sorry for my bad english.

![capture](https://user-images.githubusercontent.com/837064/53961079-c3222880-4122-11e9-898b-410e9907af28.PNG)

**Comment by elemes1** [comment]
Hi use Carbon to get this.
You can parse to date and then do diff for humans

**Comment by roriau** [comment]
> Hi use Carbon to get this.
> You can parse to date and then do diff for humans

hi elemes1 thanks for reply 
can you provide me info for how to use that library ?

**Comment by marcq64** [comment]
I don't really understand what you want but if you want to alter the format of you date then you can do it as followed :

'callback_php'=>'date("d/m/Y",strtotime($row->deliverydate))'

**Comment by xant1986** [comment]
try this,
`$this->col[] = ["label"=>"LTB (days)","name"=>"trouble_date","callback"=>function($row) { if($row->trouble_date) {
				$now = \Carbon::now();
				$t_date = \Carbon::parse($row->trouble_date);
				return $t_date->diffInDays($now);
			} }];`

**Comment by roriau** [comment]
what's the version of carbon and laravel i need to install ? 

`laravel/framework v5.4.36 requires nesbot/carbon ~1.20 -> satisfiable by nesbot/carbon[1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2] but these conflict with your requirements or minimum-stability.`

**Comment by roriau** [comment]
> $this->col[] = ["label"=>"LTB (days)","name"=>"trouble_date","callback"=>function($row) { if($row->trouble_date) { $now = \Carbon::now(); $t_date = \Carbon::parse($row->trouble_date); return $t_date->diffInDays($now); } }];

(1/1) FatalThrowableError
Class 'Carbon' not found
