### ISSUE TITLE
Image upload?

### ISSUE THREAD

**Issue by HeartlandTechie** [crocodic-studio/crudbooster#142]
Does the image upload work correctly for the site logo?   I have tried twice and it doesn't error, but it doesn't actually upload anything.  Thoughts?

**Comment by tomatoe45** [comment]
@HeartlandTechie Hi sir.. mine is working fine.. can i ask what is the error that you encounter maybe i can help with your concern.

**Comment by HeartlandTechie** [comment]
That's the issue, I check my apache error log and my laravel error log and neither one shows an error.   The file simply isn't there.  I gives me a file name from the database, but no file or directory has been created.  I've even went to chmod 777 on the public folder and chown to the www-user and still no file upload.   ???

**Comment by tomatoe45** [comment]
@HeartlandTechie  try to lookup from your project/storage/app/date.. you can see the image there that you upload..

**Comment by HeartlandTechie** [comment]
Yep, I see it there . . . so how does it show if it's listed from /public?   I'm currently using this in a subdirectory:  http://10.201.17.2/alum/public/index.php/admin/statistic_builder/builder/2

**Comment by izzu7** [comment]
i am having the issue where the images are being uploaded to storage/app/  but in the backend the url is related to public/uploads/

![issue](https://cloud.githubusercontent.com/assets/417882/22849300/0f89757e-f022-11e6-884b-9e77adb9ed32.png)

**Comment by fherryfherry** [comment]
you may try pretty URL mode instead index.php/*

**Comment by douglasjosenieves** [comment]
LISTO SOLUCIONADO ..! PARA TODOS DESPUES DE 2 DIAS SIN DORMIR 


LO HICE EN WINDOWS II2 Y LO MISMO EN XAMPP 

1) LA CARPETA PUBLIC/UPLOAD (NOOOO ES UNA CARPETA COMO TAL . ES ALGO COMO UN ACCESO DIRECTO A ) \storage\app . SI VEZ EL ICONO DE LA CARPETA ES RARO NO ES IGUAL QUE UNA CARPETA NORMAL .

TIENES QUE HACER COMO UN ESPEJO ENTRE LAS DOS CARPETAS PUBLIC/UPLOAD Y \storage\app

YO LO HICE EN CMD CONSOLA DE WINDOWS 
EL CODIGO DEL COMANDO ES: 
mklink /D "D:\Parallels\Plesk Panel\Vhosts\cohenyaguirre2.tk\httpdocs\public\uploads"
"D:\Parallels\Plesk Panel\Vhosts\cohenyaguirre2.tk\httpdocs\storage\app"

mklink crea un vínculo simbólico

SALUDOS Y ESPERO QUE LES SIRVA.

**Comment by shemul** [comment]
I have the same issue. Is there any solution for it ? @fherryfherry , @izzu7

**Comment by fherryfherry** [comment]
Update to the latest cb version
Pada tanggal 31 Mar 2017 19.50, "Shemul Hossain" <notifications@github.com>
menulis:

**Comment by shemul** [comment]
I'm having 5.3.2.* installed ..

**Comment by fherryfherry** [comment]
Have you check your composer shown nothing to update?

After update to latetst, please make sure delete the real dir uploads in
public dir if exist, because CB will create symlink instead real dir
Pada tanggal 31 Mar 2017 19.53, "Shemul Hossain" <notifications@github.com>
menulis:

**Comment by shemul** [comment]
thank you so much. It works ! 😆 
crudbooster's will rock soon in laravel community

**Comment by atiko7-tomas** [comment]
**Here's the magic:**

CB uses symlinks to mirror files to the public folder. There are two symlinks:

vendor/crocodicstudio/crudbooster -> public/vendor/crudbooster

storage/app -> public/uploads

So when deploying the app to a remote server thorugh an ftp or a simple copy-paste to a server, the symlinks are not copied, and the uploading of images brokes and the info inside both folders may be copied too, duplicating it.

**What to do?**

Delete the two linked folders inside the public one, and recreate the symlink.

**How?**

Remember symlinks would fail to create if the linked folder (the one inside the public folder) exists, even if its empty.

_This php snippet works if you run it in a file in the root folder._

```
echo("OS: " . PHP_OS . " </br>");
if (strtolower(substr(PHP_OS, 0, 3)) !== 'win') {
    $target = __DIR__ . '/storage/app';
    $link = __DIR__ . '/public/uploads';
    echo("symlink de: $target a: $link </br>");
    $resultado = symlink($target, $link);

    if ($resultado) {
        echo("symlink de uploads creado.<br/><br/>");
    } else {
        echo("symlink de uploads fallido.<br/><br/>");
    }
} else {
    $target = __DIR__ . '\\storage\\app';
    $link = __DIR__ . '\\public\\uploads';
    exec("mklink /J \"{$link}\" \"{$target}\"", $resultado, $codigo);
    echo("{$codigo}<br/><br/>");
}
```

**Why does this happen to me?**

When installing CB with command line, the symlinks are created but when copying the files to the server no symlink is copied or created.

**Where does this logic resides?**


[https://github.com/crocodic-studio/crudbooster/blob/b4446a0d95a6515345cfe7370f864c219957343a/src/commands/CrudboosterInstallationCommand.php#L66](url)

**Comment by 5lineofcode** [comment]
update your CBController like this.
we also have unique file name.

![image](https://user-images.githubusercontent.com/43805298/55874501-bdee4880-5bbc-11e9-9efa-17e7acee963e.png)
