### ISSUE TITLE
No Support and Unsolved | Ajax call to pass data to controller

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1420]
Hi,

**CONTEXT**

By editing a row, if the user change the values of 4 select elements, than the productprice changes in the "productprice" input according to the combination of the 4 selected values. 

I'm populating the input "productprice" with the new productprice with a javascript script which is triggered on change.

I need to pass the new productprice value to my controller since I need this value in order to update one of my table with it.

**PROBLEM**
It doesn't work. 

`VM2580:1 GET http://mywebapp.com/mes_commandes_non_traitees/edit 500 (Internal Server Error)`

Help would be appreciated here. Thanks, Marc

**AJAX CALL IN THE JAVASCRIPT FILE :**

`
...
  	var productprice_new = $('#productprice').val();
	console.log(productprice_new);

	$.ajax({
    url: '/mes_commandes_non_traitees/edit',
    type: 'get',
    data:  {'productprice_new' : productprice_new},
        success: function( data ) {
        	console.log('successful');
    	}
	})
`
console.log show the appropriate value | productprice
console.log show "successful"

**ROUTE :**

`Route::get('/mes_commandes_non_traitees/edit','get_productprice_new@get_productprice_new');`

**CONTROLLER CUSTOM METHOD :**

`public function get_productprice_new(Request $request) {
        
        $data = $request->all(); // This will get all the request data.

        dd($data); // This will dump and die
        
    }`

**Comment by fherryfherry** [comment]
What the name of your controller?
```
Route::get('/mes_commandes_non_traitees/edit','get_productprice_new@get_productprice_new');
```
I think you're wrong to put the controller name, it should be like bellow
```
Route::get('/something/edit','FooController@barMethod');
```

**Comment by marcq64** [comment]
@fherryfherry, thanks for your time.

I'm unable to pass my value:

If I understand the ajax function well, the url is a file where the value is stored right ?

If it is right, I have created a file into /app/Controllers/ajaxupdate.php and defined the "Ajax Url" as follows :

`
 url: '/app/Controllers/ajaxupdate.php',
`
Then I have correct the route as follows :

`
Route::get('/admin/mes_commandes_non_traitees/edit/ajaxupdate','AdminMesCommandesNonTraiteesController@getProductpriceNew');
`

I know something is obviously wrong since I get now this error :

`
GET http://www.webapp.com/app/Controllers/ajaxupdate.php?productprice_new=130.00 404 (Not Found)

I just can see that the price is added correctely to the URL (130.00) which is already good, but now I need to pass it to the controller method.

Need your expertise @fherryfherry. Thanks in advance for your time, Marc

JS FILE
`
....
	else if (d1 == 4 && d2 == 27 && d3 == '' && pl1 == 4 && pl2 == 4) { $('#productprice').val('79.00'); }
	else if (d1 == 4 && d2 == 27 && d3 == '' && pl1 == 4 && pl2 == 5) { $('#productprice').val('89.00'); }

  	var productprice_new = $('#productprice').val();
	console.log(productprice_new);

	$.ajax({
    url: '/app/Controllers/ajaxupdate.php',
    type: 'get',
    data:  {'productprice_new' : productprice_new},
        success: function( data ) {
        	console.log(data);
    	}
	})

})
`

Route :
`
Route::get('/admin/mes_commandes_non_traitees/edit/ajaxupdate','AdminMesCommandesNonTraiteesController@getProductpriceNew');
`

Controller Method :
`
	    public function getProductpriceNew(Request $request) {

        $data = $request->all(); // This will get all the request data.

        dd($data); // This will dump and die

    	}
`

**Comment by marcq64** [comment]
Tried all the day... without success, so please i f someone knows how to do, help would be appreciated.

Last test was :

js file :

```
  	var rowID = rowid;
  	var productprice_new = $('#productprice').val();
  	var orderID = $('#orderID').val();
	console.log(productprice_new,rowID,orderID);

	$.ajax({
	// url: '/assets/ajax/ajaxupdate.php',
	type: 'get',
    url: '/admin/mes_commandes_non_traitees/edit'+ '/' + rowID +  '/' + productprice_new + '/' + orderID + '/',
                success: function (data) {
                    console.log('worked!');
                },
                error: function (data) {
                    console.log('Error:', data);
                }
	})
```

Route :

`Route::get('/admin/mes_commandes_non_traitees/edit/{rowID}/{productprice_new}/{orderID}/','AdminMesCommandesNonTraiteesController@hook_after_edit');`

Controller :

```
	    public function hook_after_edit($id) {
	        
	        $productprice_new1 = $_GET['productprice_new'];
	        $rowID1 = $_GET['rowID'];
	        $orderID1 = $_GET['orderID'];

	        dd($productprice_new,$rowID,$orderID);

	    }
```
