### ISSUE TITLE
nesbot/carbon dependency conflicts with crocodicstudio/crudbooster=5.4.0

### ISSUE THREAD

**Issue by SEzekiel** [crocodic-studio/crudbooster#1426]
Hi there!!

I recently created a Laravel  5.8 project and attempted to install crudbooster using composer which seems to require nestbot/carbon

I'm getting the following output when attempting to install crocodicstudio/crudbooster=5.4.0
...
    - Can only install one of: nesbot/carbon[1.24.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.24.1, 2.16.0].
    - Can only install one of: nesbot/carbon[1.24.2, 2.16.0].
    - Can only install one of: nesbot/carbon[1.25.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.26.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.26.1, 2.16.0].
    - Can only install one of: nesbot/carbon[1.26.2, 2.16.0].
    - Can only install one of: nesbot/carbon[1.3.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.4.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.5.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.6.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.7.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.8.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.9.0, 2.16.0].
    - Installation request for nesbot/carbon (locked at 2.16.0) -> satisfiable by nesbot/carbon[2.16.0].

Installation failed, reverting ./composer.json to its original content.
It seems to me that laravel aready ships with nestbot/carbon, or am I wrong. Is there a way I can fix this or an alternative way to install crudbooster?

PHP Version 7.2.12

Thanks in advance

**Comment by dagalumin** [comment]
I solved all these composer errors installing Crudbooster over Laravel 5.7 (it seems the latest crudbooster is not dependency compatible with laravel 5.8) with this command: 
`composer create-project laravel/laravel <project_name> 5.7.*`
if you get also a mcrypt library error from composer, you should pass to PHP 7.1.* since from 7.2 mcrypt has been removed.

**Comment by SEzekiel** [comment]
Thanks @dagalumin for your advise and especially for the PHP 7.2 heads up. I generally love using the most updated versions of stuff that I use, but for now, I will go with your idea.

**Comment by dagalumin** [comment]
I agree with you, we all hope that mcrypt requirement will be dropped in new versions of CRUDbooster since deprecated from long time and now even removed from PHP.

**Comment by alokraj68** [comment]
@dagalumin Any idea when the new version of crudbooster is coming?
