### ISSUE TITLE
get error on fresh install

### ISSUE THREAD

**Issue by chimurf** [crocodic-studio/crudbooster#1429]
I have new update of laravel and create new project.
I followed the installation instruction already at https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/installation.md

at the step 1
Open the terminal, navigate to your project directory.
$ composer require crocodicstudio/crudbooster

![image](https://user-images.githubusercontent.com/46837549/54572925-7ab91380-4a1c-11e9-9ce2-815b062a346d.png)

what can i do?

**Comment by dagalumin** [comment]
please check https://github.com/crocodic-studio/crudbooster/issues/1426

**Comment by chimurf** [comment]
yeayy.
got it. 

thanks a lot.
