### ISSUE TITLE
Problem Import data with relationship

### ISSUE THREAD

**Issue by jdredondo** [crocodic-studio/crudbooster#143]
I have a table "Category" with columns: id, category. And a table "Product" with columns: id, category_id, name. I'm importing a file "xlsx" with columns:
category_id | name
1                  |  Product One
But no import the file .

i've generated the module twice and same problem.

**Comment by fherryfherry** [comment]
hi , make sure that primary field is "id" instead "category_id"

**Comment by jdredondo** [comment]
In the following image I show the step by step to create the modules and load the file, the data are not imported, am I doing something wrong?

[http://190.242.42.82/issue.jpg](url)

Thanks

**Comment by jdredondo** [comment]
I still have the same problem after the last update.

**Comment by fherryfherry** [comment]
update to latest version

**Comment by joxper** [comment]
Hi I still have the same problem when importing. Normal table no relationship, it shows "Import Successfully" but no data was imported

Table test:

-id
-name
-color
-date

XLS file with three rows, header and two rows of data.

I am using last version

**Comment by azarzaza** [comment]
import not working in latest version also!

**Comment by bsesic** [comment]
I had the problem that uploading an xlsx file with multiple sheets did not work, removing them however did it.
