### ISSUE TITLE
Add menu item - doesn't put it under the right privileges

### ISSUE THREAD

**Issue by HeartlandTechie** [crocodic-studio/crudbooster#144]
When I add a new user privilege and try to add a menu item to it (via the add item at the top of the page), it doesn't put it in the selected privilege.   How is that information transferred over?  I'm not seeing a hidden field for that?

**Comment by tomatoe45** [comment]
@HeartlandTechie .. hello sir.. after you add the new user privilege and add the menu to it.. to see the menu.. you need to logged on as the user privilege access that you created for you to see the menu that  you add..

**Comment by HeartlandTechie** [comment]
To replicate, go to a different user privilege in the drop down, it shows you the current menu items, and if you use the buttons at the top of the page, the new menu item is created at the root level of your structure.  I can add it successfully with the add link to the right in the middle of the page.  There are no mechanisms to copy menu items to another or to move them to another user.  I manually changed it in the database.

**Comment by fherryfherry** [comment]
@HeartlandTechie, unfortunately, there is no replicate feature at currently feature. And the issue about replicating menu is different with this board title. You may close this issue and create new request/issue for replicate menu

**Comment by HeartlandTechie** [comment]
Ok, the original issue still is, if you click on the add button at the top when you have selected a different user privilege, the addition should take into account where you are or not even give the button as an option.

**Comment by fherryfherry** [comment]
update to latest version
