### ISSUE TITLE
Error Form Edit

### ISSUE THREAD

**Issue by ada27** [crocodic-studio/crudbooster#1455]
Mohon bantuan nya mas @fherryfherry 

Saya punya form seperti di bawah ini yang memiliki relasi ke tabel lain, saya blok merah, dan saya disable form tersebut agar tidak bisa dilakukan editing oleh user yang berbeda role aksesnya
![Capture](https://user-images.githubusercontent.com/44355293/58523828-74070380-81f8-11e9-9a33-2d21551b13df.PNG)

namun ketika di lakukan save untuk form yang saya block merah, di database dari data awalnya ada ketika form itu di disabel dan dilakukan edit dan save, field di databasenya menjadi null

Mohon pencerahan nya

**Comment by fherryfherry** [comment]
Kalau mau di disable sebaiknya cukup di readonly bukan pakai disable.
.
Atau jikalau pakai disable di hook_after_edit nya sebaiknya di unset juga
biar tidak ikut tersave, karena dia isinya null.
e.g :
unset($data[`name`])

**Comment by ada27** [comment]
okey sudah bisa pake unset mas @fherryfherry  namun berjalan nya di hook berfore edit, seperti unset password_confirmation

Makasih banyak mas
