### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Ziaullah-Mommand** [crocodic-studio/crudbooster#146]
I am using crudbooster v5.3 I can't login when i submit the login form with usename and password I am getting the following error 
![screenshot 2017-02-09 10 26 53](https://cloud.githubusercontent.com/assets/10906405/22771208/f78a7aec-eeb2-11e6-8b05-799a9450edb3.png)

**Comment by Ginger45** [comment]
try clean cache 

type into your terminal

php artican cache:clear

**Comment by fherryfherry** [comment]
don't too long at the login page. Its laravel session time expired issue.
