### ISSUE TITLE
Join is not returning data in select

### ISSUE THREAD

**Issue by zapcriativo** [crocodic-studio/crudbooster#1471]
Hello,

I tried to create a crud with relationship, however the select that brings the data from the other table is returning null

I am doing the crud with with the **Instituicoes** table with the following fields fields inst_name and inst_type using select (This will write the ID of the relational table **instituicoes_tipo**).

![image](https://user-images.githubusercontent.com/7153803/60886870-68f8b780-a229-11e9-8e31-bdfa30106f65.png)

My code on Controller...

`
			# START COLUMNS DO NOT REMOVE THIS LINE
			$this->col = [];
			$this->col[] = ["label"=>"Inst Nome","name"=>"inst_nome"];
			$this->col[] = ["label"=>"Inst Tipo","name"=>"inst_tipo","join"=>"instituicoes_tipo,inst_tipo_nome"];
			# END COLUMNS DO NOT REMOVE THIS LINE

			# START FORM DO NOT REMOVE THIS LINE
			$this->form = [];
			$this->form[] = ['label'=>'Inst Nome','name'=>'inst_nome','type'=>'text','validation'=>'required|min:1|max:255','width'=>'col-sm-10'];
			$this->form[] = ['label'=>'Inst Tipo','name'=>'inst_tipo_nome','type'=>'select','validation'=>'required|integer|min:0','width'=>'col-sm-10','datatable'=>'instituicoes_tipo,inst_tipo_nome','parent_select'=>'id'];
			# END FORM DO NOT REMOVE THIS LINE`

Screen form

![image](https://user-images.githubusercontent.com/7153803/60887039-cd1b7b80-a229-11e9-96a5-adcd323954f2.png)

**Comment by squidv3** [comment]
ta errado tua clausula. tu ta dizendo que existe um 'parent_select'=>'id' porem no teu form não possui ele, apenas o Inst_nome acima dele que não serve como parent select

**Comment by zapcriativo** [comment]
@squidv3 obrigado pelo retorno...

Fiz a mudança, porém o crud ainda não preenche o select com os dados do join na outra tabela.

`			$this->form = [];
			$this->form[] = ['label'=>'Inst Nome','name'=>'inst_nome','type'=>'text','validation'=>'required|min:1|max:255','width'=>'col-sm-10'];
			$this->form[] = ['label'=>'Inst Tipo','name'=>'inst_tipo_nome','type'=>'select','validation'=>'required|integer|min:0','width'=>'col-sm-10','datatable'=>'instituicoes_tipo,inst_tipo_nome'];
`

@ squidv3 thanks for the feedback ...

I made the change, but crud still does not populate the select with the join data in the other table.

**Comment by zapcriativo** [comment]
It's work's 

Está funcionando 

Obrigado @squidv3

**Comment by zapcriativo** [comment]
@squidv3  na tabela relacional tenho o id que vou adicionar no campo da outra e o nome_tipo. 

Quero que no select fiquei no nome_tipo no label e o id como o valor que vai ser salvo no banco, como faço essa referencia?

**Comment by squidv3** [comment]
na propriedade do select vai em datatable e coloca assim "nomedatabela,nomedocampo

Ai ele vai te mostrar o que tu quer. isso se for para cadastro e edição

**Comment by zapcriativo** [comment]
Legal, mostrou certo o select.. mas agora tenho outro problema

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'inst_tipo_nome' in 'field list' (SQL: insert into `instituicoes` (`inst_nome`, `inst_tipo_nome`) values (Mena Camargo, 1))


O campo que quero gravar é o numero no campo ID da tabela auxiliar , porém está tentando gravar no inst_tipo_nome

**Comment by squidv3** [comment]
96 999728914 manda msg whatsapp

**Comment by zapcriativo** [comment]
Deu boa!!!! Valeu amigo.. 

Abraços

**Comment by zapcriativo** [comment]
@squidv3  você chegou a trabalhar com as api's do framework?
