### ISSUE TITLE
Issue with backend image paths

### ISSUE THREAD

**Issue by izzu7** [crocodic-studio/crudbooster#148]
i am having the same issue where the images are being uploaded to storage/app/  but in the backend the url is related to public/uploads/  and so the image is broken .

![issue](https://cloud.githubusercontent.com/assets/417882/22849300/0f89757e-f022-11e6-884b-9e77adb9ed32.png)

**Comment by fherryfherry** [comment]
Your php_info extension is missing
Pada tanggal 11 Feb 2017 07.53, "israel james" <notifications@github.com>
menulis:

**Comment by izzu7** [comment]
![fileinfo](https://cloud.githubusercontent.com/assets/417882/22855785/97ead0f0-f0ab-11e6-9523-29f96fd56f10.png)

if you are talking about this i have it on from before , i have read about you saying something related to routes ,how and where to fix it, do help me thanks

**Comment by izzu7** [comment]
sorry the issue was i was accessing the site using the domain.dev host set on my windows hosts file like isuzu.dev/public/index.php/admin 

but when i am using localhost/isuzu/public/admin everything works

**Comment by emgg2222** [comment]
Hi there, 
I have 5.5 version, I have the same problem.
Where can I fix it in this version?
Thanks in advance
