### ISSUE TITLE
How to Rename the export button.

### ISSUE THREAD

**Issue by armandob1223** [crocodic-studio/crudbooster#1481]
Please, if anyone knows how to rename the export data button, I would appreciate it if you informed me.
Greetings.

![export](https://user-images.githubusercontent.com/42210405/62478187-78abe300-b778-11e9-88d7-d36ab11ac426.png)

**Comment by maps75** [comment]
Open the file "..\vendor\crocodicstudio\crudbooster\src\localization\es\crudbooster.php" and change the value for the key "button_export".

**Comment by armandob1223** [comment]
Thank you so much
