### ISSUE TITLE
Class 'crocodicstudio\crudbooster\middlewares\DB' not found

### ISSUE THREAD

**Issue by dexteros** [crocodic-studio/crudbooster#1488]
At the moment of logging in I am having the following error:

Class 'crocodicstudio\crudbooster\middlewares\DB' not found

![Screenshot from 2019-08-23 17-53-11](https://user-images.githubusercontent.com/5299362/63627820-00924980-c5cf-11e9-8ae2-50a55280c2f9.png)

I observe the call on line 32 to **DB :: table ('cms_menus')**
Please your help to solve the error. PHP 5.6, Crudbooster 5.4

![Screenshot from 2019-08-23 17-58-03](https://user-images.githubusercontent.com/5299362/63627961-aa71d600-c5cf-11e9-931c-1382443afde3.png)

**Comment by fherryfherry** [comment]
Oops. Try add "use DB;" above of class name

**Comment by renzocastillo** [comment]
@dexteros please add "use DB" at the top of your class at crudbooster/Middleware/cb_backend.php
