### ISSUE TITLE
Error Creating Module

### ISSUE THREAD

**Issue by furqon** [crocodic-studio/crudbooster#150]
error when creating new module, id not found.
<img width="843" alt="screen shot 2017-02-12 at 11 42 11 pm" src="https://cloud.githubusercontent.com/assets/446747/22864077/ff8d6f66-f17c-11e6-980d-6f393f47de4f.png">

what I am doing currently is adding default id in ModulsController.php

```
$id = ($id == '') ? 0 : $id;
$row = CRUDBooster::first($this->table,['id'=>$id]);
```

env:
crudbooster: 5.3.1.2
laravel: 5.3.*
db: pgsql 9.5.4

**Comment by fherryfherry** [comment]
update to latest version
