### ISSUE TITLE
SOLUTION : Updated Laravel to 5.5.48 / Crudbooster to 5.4.22 | foreign key missing in child table by new entries

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1504]
**PHP 7.2.19 AND 7.1.0 BOTH TESTED
LARAVEL 5.5.48
CRUDBOOSTER 5.4.22**

-----------------------------------------------------------------------------------------------------------

Hi,

Perhaps one of you guys had the same issue :

**PROBLEM**
I needed to update my Laravel Framework to another version in order to be able to use another third party package.

I have updated Laravel to version 5.5.48 and Crudbooster to version 5.4.22 (composer update).

Everything seems to work fine, but...

By creating a new entry with a  Child Form (Master - Detail)

Master : order_new table
Detail : order_details_new table

which was working fine the last 18 months

the id of the Master table (foreign key) isn't longer included|saved into the Detail table "orderID" field.

If someone have a quick solution, I would appreciate.

Cheers

**Comment by rizkytester** [comment]
up

**Comment by marcq64** [comment]
SOLUTION :

https://github.com/crocodic-studio/crudbooster/pull/1500

Thanks a lot ...
