### ISSUE TITLE
Master Detail Form

### ISSUE THREAD

**Issue by poerwiyanto** [crocodic-studio/crudbooster#151]
Is it possible to create a master detail form using CRUDBooster (e. g. invoice and its details)? Thanks.

**Comment by fherryfherry** [comment]
yes you can
you may refer : 
http://crudbooster.com/doc/5.3/relationship-module
or http://crudbooster.com/doc/5.3/form-scaffolding#child

**Comment by poerwiyanto** [comment]
Can I make the master detail in one form using <div> and DOM? If I can, where should I put the detail form?

**Comment by fherryfherry** [comment]
you may try form scaffolding child

**Comment by poerwiyanto** [comment]
I think I got the ideas. Thanks.
