### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by kanishka90** [crocodic-studio/crudbooster#1511]
[UnexpectedValueException]                                                          
  Could not parse version constraint 6.0-beta.*: Invalid version string "6.0-beta.*"

**Comment by gbesoain** [comment]
Just use "6.0-beta.1" it worked in my laravel 6 install

**Comment by kanishka90** [comment]
> Just use "6.0-beta.1" it worked in my laravel 6 install

Thank's It works.
