### ISSUE TITLE
V6 - Developer Area

### ISSUE THREAD

**Issue by JulyanoF** [crocodic-studio/crudbooster#1512]
Following [this guide](https://crudbooster.com/docs/developer), I tried to access my developer area after execute `php artisan crudbooster:developer` and it retrieves "404 Not Found". Is there some extra requisites to access developer area?

**Comment by fherryfherry** [comment]
Make sure your project folder is included

**Comment by Nsobi** [comment]
How is there,than you for this amazing tool mr  fherryfherry 
What do you mean  "Make sure your project folder is included",im still getting the same error "404 Not Found"

**Comment by fherryfherry** [comment]
Screenshot terminal response

**Comment by JulyanoF** [comment]
@fherryfherry here is the screenshot you just requested:

![image](https://user-images.githubusercontent.com/17284704/66719559-de939700-edc7-11e9-89fa-7823eea19ec0.png)

**Comment by fherryfherry** [comment]
> @fherryfherry here is the screenshot you just requested (my project root folder is /var/www/html/contas):
> 
> ![image](https://user-images.githubusercontent.com/17284704/66719559-de939700-edc7-11e9-89fa-7823eea19ec0.png)

It looks like you don't have active htacces mod_rewrite https://hostadvice.com/how-to/how-to-enable-apache-mod_rewrite-on-an-ubuntu-18-04-vps-or-dedicated-server/ @JulyanoF

**Comment by JulyanoF** [comment]
> > @fherryfherry here is the screenshot you just requested (my project root folder is /var/www/html/contas):
> > ![image](https://user-images.githubusercontent.com/17284704/66719559-de939700-edc7-11e9-89fa-7823eea19ec0.png)
> 
> It looks like you don't have active htacces mod_rewrite https://hostadvice.com/how-to/how-to-enable-apache-mod_rewrite-on-an-ubuntu-18-04-vps-or-dedicated-server/ @JulyanoF

I guess the problem is not it. I can access https://localhost/contas/public and https://localhost/contas/public/admin normally. There are two other test projects running with CrudBooster v5 and doesn't have any problem.
And mod_rewrite was already activated

**Comment by xant1986** [comment]
Try access https://localhost/contas/public/developer/...
