### ISSUE TITLE
Updated Laravel to 5.7.28 / Crudbooster to 5.4.0.16 | foreign key missing in child table by new entries

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1517]
**PHP 7.2 AND 7.1 BOTH TESTED
LARAVEL 5.7.28
CRUDBOOSTER 5.4.0.16**

Hi,

Made a fresh install today of : 

Laravel 5.7.28
Crudbooster + update

**PROBLEM**

Everything seems to work fine, but...

By creating a new entry with a Child Form (Master - Detail)

Master : order_new table
Detail : order_details_new table

SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count

SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 2 (21S01)

SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 2 (21S01)

Same problem I had a few days before with :

PHP 7.2 AND 7.1 BOTH TESTED
LARAVEL 5.5.48
CRUDBOOSTER 5.4.22
https://github.com/crocodic-studio/crudbooster/issues/1504

Checked that 

https://github.com/crocodic-studio/crudbooster/commit/f48f269d83ec042300a5526e6f64fdfe44d056c9

and version is ok.

If someone have a quick solution here too, so I can wait for a stable version 6, I would appreciate.

Cheers

**Comment by tiznull** [comment]
Please use tiznull:patch-3 to fix this. Pull request submitted.
[https://github.com/tiznull/crudbooster/tree/patch-3](tiznull:patch-3)

**Comment by marcq64** [comment]
@tiznull After a file mismatch, it is working ! Thank you a lot, cheers, Marc

**Comment by tiznull** [comment]
Very cool! Thank you.

**Comment by allanbatingal** [comment]
marcq64 can your help me with this error 

Insert value list does not match column list: 1136 Column count doesn't match value count at row 2

**Comment by marcq64** [comment]
@allanbatingal

If I remember well we have made a change here :

vendor/crocodicstudio/crudbooster/src/controllers
into the CB controller 

Find my file attached.

My developer told me to check line number 1228 and 1237

[CBController.txt](https://github.com/crocodic-studio/crudbooster/files/3840040/CBController.txt)

Hope it helps, please keep me posteed.

PS : Do you now how I could custom the filter ?

**Comment by Gopal-Bandyopadhyay** [comment]
May be Multiple DataModel Is used under Child Form.
Use only one DataModel to add data under Child Form

**Comment by Gopal-Bandyopadhyay** [comment]
Previous CBController 
if(!empty($column_data)){
                        **$column_data[$fk] = $id;**
                        $child_array[] = $column_data;
                    }
change Line no 1229, $id to $lastInsertId
After Change CB controller in Child Type
 if(!empty($column_data)){
                        **$column_data[$fk] = $lastInsertId;**
                        $child_array[] = $column_data;
                    }

Problem Solved
