### ISSUE TITLE
Portability from Version 5.4.0 to Version 6 beta

### ISSUE THREAD

**Issue by marcq64** [crocodic-studio/crudbooster#1519]
Hi,

Thank you for this new version !

Could please give some details about the portability from Version 5.4.0 App to Version 6 beta ?

**Comment by fherryfherry** [comment]
The big major change is code style.
Then : 
- Developer area
- Plugin
- Theme 
- Security
- Register, Forgot 
- Using default laravel auth (users table)

**Comment by marcq64** [comment]
Thank you for your feedback
