### ISSUE TITLE
Empty a Input

### ISSUE THREAD

**Issue by fabianscholz** [crocodic-studio/crudbooster#153]
Hi, i try to clear a input field in a module. 
I empty all text in the input field but if i try to save, no changes.
If i overwrite the input, it's okay, but if i save empty, the value before was saved.
The input is a simplte text field, it's not required and no other validation.

Any tip?
Fabian

**Comment by fherryfherry** [comment]
![image](https://cloud.githubusercontent.com/assets/6733315/22971432/3994bd90-f3a8-11e6-9c60-d2ea78046d37.png)
it seems a bug, you should remove this code @ CBController

**Comment by fherryfherry** [comment]
update to latest version
