### ISSUE TITLE
CRUDBOOSTER v6 Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

### ISSUE THREAD

**Issue by rizkytester** [crocodic-studio/crudbooster#1531]
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

![image](https://user-images.githubusercontent.com/14036233/67950577-6da00c00-fc1c-11e9-8ae9-a2622d37ed2e.png)

**Comment by fherryfherry** [comment]
It's general issue for laravel. There is solution out there bro to fix this migration issue. Try search at the google first

Fyi as far as I know this because mysql version compatible

**Comment by rizkytester** [comment]
yes, I change my xampp to version xampp 7.3.11 and its working fine om
hehehehehe
semoga ilmu anda berkah abangda dan menjadi amal soleh
