### ISSUE TITLE
Extend privileges

### ISSUE THREAD

**Issue by poerwiyanto** [crocodic-studio/crudbooster#155]
Hi, is it possible to extend privileges? For example, I want to add "approve" action. How can I define access control for each privilege/role? Thanks.

**Comment by fherryfherry** [comment]
Sorry, i don't understand, may you explain more?

**Comment by poerwiyanto** [comment]
I want to add a new action/button called "approve", which can only be seen and used by a supervisor to approve a purchase order. Can I extend the privileges to do so?

**Comment by fherryfherry** [comment]
Yes you can. You can do by put the if condition between the addaction
array. Then to determine what the privilege id is used you can use
CRUDBooster::myPrivilegeId(). Just give condition if privilege id is equal
with the supervisor privilege id
Pada tanggal 17 Feb 2017 18.50, "poerwiyanto" <notifications@github.com>
menulis:
