### ISSUE TITLE
Using the model

### ISSUE THREAD

**Issue by avifatal** [crocodic-studio/crudbooster#157]
Hi,
I want to build a multi tenant app, every user may see his data only.
This means that I need row level security. usually I do it with model scoping.
So I want to access the model, is it possible?
Thanks!

**Comment by fherryfherry** [comment]
first, you can build the module without GUI. For the first time, you just need to create the file by add from module generator. After that, you can learn at the documentation about form scaffolding & column scaffolding.

Basically, CB does not create **Model** for each table. So you can create your own table model.

Then about "Every user may see his data only", you can use the hook_query_index . Which it can be used to modify the query module.

![image](https://cloud.githubusercontent.com/assets/6733315/23092313/697c6d24-f5fa-11e6-8d89-1ae53f1b0401.png)

**Comment by avifatal** [comment]
Thanks.
What's the point of using Model if crudbooster isnt using it.
Am i right?

**Comment by fherryfherry** [comment]
Yes you are right

**Comment by ismaeljoseph** [comment]
I wanted to integrate Chatter, Chatter configuration use App\User Model. From your early conversation can i conclude that Chatter is not compatible with it?
Thanks for answering.
