### ISSUE TITLE
Just blank page after login (Super Admin)

### ISSUE THREAD

**Issue by soraaa** [crocodic-studio/crudbooster#1575]
After creating module and statistic then assign the menu to specific role, I try to re-login to admin dashboard but it just show blank page, no error message. But standard user is able to login to dashboard normally.

**_I'm using latest stable CB (5.4.22) on laravel 5.7_**

**Comment by soraaa** [comment]
Solved by putting statistic on dashboard

**Comment by zerubbabel** [comment]
how did you solved this problem??

**Comment by ranggasan** [comment]
> how did you solved this problem??

just add statistic to your admin dashboard
