### ISSUE TITLE
form + child table grid

### ISSUE THREAD

**Issue by crottolo** [crocodic-studio/crudbooster#1578]
Hi, i want add a from the child table with join with the id number.
example below:
![Schermata 2020-03-19 alle 13 32 37](https://user-images.githubusercontent.com/16843729/77068028-31602300-69e6-11ea-9c3d-3d051af8198a.png)

can help me?
i'm use crudbooster 5.4 fresh install

**Comment by Anfal63** [comment]
check my question,
I have not problem with only one child form
https://github.com/crocodic-studio/crudbooster/issues/1603
