### ISSUE TITLE
Uninstall Developer Panel

### ISSUE THREAD

**Issue by pietrocinaglia** [crocodic-studio/crudbooster#1582]
Hi, I write here to ask if exist e quick method to uninstall (remove totally) the developer panel before production step. I think this step is useful to reduce vulnerabilities in production. 
Thanks for attention.

**Comment by fherryfherry** [comment]
Modify the cb 6 route at the
vendor/crocodicstudio/crudbooster/src/routes.php

Remove the developer path route at there

Pada tanggal Sab, 11 Apr 2020 20:51, Pietro Cinaglia <
notifications@github.com> menulis:

**Comment by pietrocinaglia** [comment]
Thanks! So... it is not possible remove all related files by using a simple command.
Anyway, thanks a lot for your solution.
