### ISSUE TITLE
showing a grid bellow the form

### ISSUE THREAD

**Issue by avifatal** [crocodic-studio/crudbooster#159]
Hi,
My database has offices table, each user belongs to an office.
I added a field to cms_user.
```
Schema::table('cms_users', function (Blueprint $table) {
        $table->integer('office_id')->nullable()->unsigned();
        $table->foreign('office_id')->references('id')->on('offices');
});
```
when editing the office (when viewing the form), I want to show all the users related to this office.

in my AdminCmsUsersController I have this:
```
$this->col[] = ["label"=>"Office Id","name"=>"office_id","join"=>"offices,name"];
```

this is what I have in my AdminOfficesController
```
  $this->sub_module[] = ['label'=>'Users','path'=>'users','parent_columns'=>'id,email','button_color'=>'primary','button_icon'=>'fa fa-bars','foreign_key' => 'office_id'];
```
these are the problems.

1.  inside the office edit form I dont see the related users.
2.  I got a new button in the office grid 'Users', when clicking on it I get the error: There is no FK for that table

Thanks

**Comment by fherryfherry** [comment]
To use form / grid inside form you need to use child type instead of sub_module
sub_module used for graded module view
