### ISSUE TITLE
How to update to new version?

### ISSUE THREAD

**Issue by isnanu** [crocodic-studio/crudbooster#16]
Hay, i have a questin before use crudbooster . If i have create web with crudbooster and , i want update my old crudbooster version to new version. It's possible to update crudbooster without losing my old file and get new version update? and what should i do if after update i get some error or some bug? im newbee in web programming and want to learn Laravel with crudbooster. And maybe you can also share more tutorial how to create page for 'register' and some 'home' view in other language like 'Bahasa'. Thanks :)

**Comment by fherryfherry** [comment]
Basically just replace with latest crudbooster . Then re-migration "php artisan migrate" . In the future, we will post a tutorial, but we do not have much time to post a tutorial at this time. But we hard work to post tutorials as soon as possible.
