### ISSUE TITLE
Unable create List API

### ISSUE THREAD

**Issue by aldiskatel** [crocodic-studio/crudbooster#1602]
Hello I have created a table call it the "players" table. In the table there are 3 records
player A, player B, player C

I want to list all users in api using listings (without id parameter or anything). but after I made it and I tested it on Postman it gave an error:
`count (): Parameter must be an array or an object that implements Countable`
<img width="1168" alt="Screen Shot 2020-09-07 at 15 48 17" src="https://user-images.githubusercontent.com/20250991/92361800-90932a80-f121-11ea-8222-a1cfbe9a0f55.png">

Am I forgetting something?

**Comment by fherryfherry** [comment]
Versi Php nya terlalu tinggi mas

**Comment by aldiskatel** [comment]
terimakasih banyak mas @fherryfherry atas responsenya.

**Comment by fherryfherry** [comment]
Join ke tele aja mas

**Comment by aldiskatel** [comment]
telenya apa mas @fherryfherry
