### ISSUE TITLE
Cant install require command 

### ISSUE THREAD

**Issue by SandyUgale** [crocodic-studio/crudbooster#161]
I have been trying to us following command:

$ composer require crocodicstudio/crudbooster=5.3.1.*

But getting across following error message of DOS

  Problem 1
    - The requested package laravel/framework (locked at v5.4.12, required as 5.
3.*) is satisfiable by laravel/framework[v5.4.12] but these conflict with your r
equirements or minimum-stability.
  Problem 2
    - The requested package symfony/css-selector (locked at v3.2.4, required as
3.1.*) is satisfiable by symfony/css-selector[v3.2.4] but these conflict with yo
ur requirements or minimum-stability.
  Problem 3
    - The requested package phpunit/phpunit (locked at 5.7.13, required as ~4.0)
 is satisfiable by phpunit/phpunit[5.7.13] but these conflict with your requirem
ents or minimum-stability.
  Problem 4
    - intervention/image 2.3.9 requires ext-fileinfo * -> the requested PHP exte
nsion fileinfo is missing from your system

**Comment by fherryfherry** [comment]
Its seems your environment is not meet

**Comment by tomatoe45** [comment]
post your php environment version--
