### ISSUE TITLE
Class 'Str' not found in menu managment

### ISSUE THREAD

**Issue by rizkytester** [crocodic-studio/crudbooster#1619]
Laravel 5.5
crudbooster 5.5.3
get error when I make sub menu sidebar

Class 'Str' not found (View: F:\GAME DATA\xampp72\htdocs\auj\vendor\crocodicstudio\crudbooster\src\views\sidebar.blade.php) (View: F:\GAME DATA\xampp72\htdocs\auj\vendor\crocodicstudio\crudbooster\src\views\sidebar.blade.php) (View: F:\GAME DATA\xampp72\htdocs\auj\vendor\crocodicstudio\crudbooster\src\views\sidebar.blade.php)

![gambar](https://user-images.githubusercontent.com/14036233/99355535-0adaea80-28db-11eb-8131-9431cec3d52f.png)

**Comment by fherryfherry** [comment]
What laravel version?

**Comment by rizkytester** [comment]
pakai Laravel 5.5.50 bg

**Comment by rizkytester** [comment]
sudah pakai ini tapi gak bisa juga

function ends_with($text, $key) {
       return \Illuminate\Support\Str::endsWith($text, $key);
}

**Comment by fherryfherry** [comment]
Coba pakai laravel 6

**Comment by rizkytester** [comment]
oke bg
makasih banyak bg

https://codecanyon.net/item/goodang-warehouse-inventory-management-android-apps-and-website/26701674
ini gak tau siapa yang buat bang, cuma saya liat live preview nya bagus juga

**Comment by fherryfherry** [comment]
Produk Goodang dari salah satu tim kami mas masih dalam circle

**Comment by rizkytester** [comment]
ohh
pantes bagus mas

sbelumnya makasih banyak ya mas

**Comment by fherryfherry** [comment]
Sipp mas terima kasih
