### ISSUE TITLE
Menu Management Error After Add Submenu

### ISSUE THREAD

**Issue by idhammubarok** [crocodic-studio/crudbooster#1627]
Hallo, saya menemukan kesalaha ketika membuat sub menu, apakah ada solusi atas masalah ini :

![bugcb](https://user-images.githubusercontent.com/27127955/100333543-4aa18080-3005-11eb-882d-5d327f75498b.png)

**Comment by fherryfherry** [comment]
Coba install laravel 6 dan CB 5.5

**Comment by idhammubarok** [comment]
thanks pak @fherryfherry solved
