### ISSUE TITLE
 Target class [Database\Seeders\CBSeeder] does not exist.

### ISSUE THREAD

**Issue by mreading2020** [crocodic-studio/crudbooster#1637]
Fresh install, See below output, any ideas would be much appreciated. 

C:\laragon\www\cma
λ php artisan crudbooster:install

#     __________  __  ______  ____                   __
#    / ____/ __ \/ / / / __ \/ __ )____  ____  _____/ /____  _____
#   / /   / /_/ / / / / / / / __  / __ \/ __ \/ ___/ __/ _ \/ ___/
#  / /___/ _, _/ /_/ / /_/ / /_/ / /_/ / /_/ (__  ) /_/  __/ /
#  \____/_/ |_|\____/_____/_____/\____/\____/____/\__/\___/_/
#

--------- :===: Thanks for choosing CRUDBooster :==: ---------------
====================================================================
System Requirements Checking:
Laravel Version (>= 5.5): [Good]
PHP Version (>= 7.2.*): [Good]
Mbstring extension: [Good]
OpenSSL extension: [Good]
PDO extension: [Good]
Tokenizer extension: [Good]
XML extension: [Good]
GD extension: [Good]
PHP Fileinfo extension: [Good]
public dir is writable: [Good]
--
Installing:

 Do you have setting the database configuration at .env ? (yes/no) [no]:
 > yes

Publishing crudbooster assets...
Copied Directory [\vendor\crocodicstudio\crudbooster\src\assets] To [\public\vendor\crudbooster]
Publishing complete.
Dumping the autoloaded files and reloading all new files...
Migrating database...
Nothing to migrate.

   Illuminate\Contracts\Container\BindingResolutionException

  Target class [Database\Seeders\CBSeeder] does not exist.

  at C:\laragon\www\cma\vendor\laravel\framework\src\Illuminate\Container\Container.php:832
    828â–•
    829â–•         try {
    830â–•             $reflector = new ReflectionClass($concrete);
    831â–•         } catch (ReflectionException $e) {
  âžœ 832â–•             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    833â–•         }
    834â–•
    835â–•         // If the type is not instantiable, the developer is attempting to resolve
    836â–•         // an abstract type such as an Interface or Abstract Class and there is

  1   C:\laragon\www\cma\vendor\laravel\framework\src\Illuminate\Container\Container.php:830
      ReflectionException::("Class Database\Seeders\CBSeeder does not exist")

  2   C:\laragon\www\cma\vendor\laravel\framework\src\Illuminate\Container\Container.php:830
      ReflectionClass::__construct("Database\Seeders\CBSeeder")

**Comment by Stupa163** [comment]
+1 have the same issue on a fresh install

**Comment by fherryfherry** [comment]
I will check it out

**Comment by vencendor** [comment]
Same problem, i try to install it on new ubuntu server without any changes: 

    composer create-project laravel/laravel example-app
    cd example-app
    composer require crocodicstudio/crudbooster
after edit .env : 
    php artisan crudbooster:install

error: 
    Target class [Database\Seeders\CBSeeder] does not exist.

**Comment by JRB-y** [comment]
Same here, on a fresh installation.
Any update ?

**Comment by johanpret** [comment]
Yep, same issue on fresh installation.
Also tried "composer dump-autoload", then again "php artisan crudbooster:install", but still has same issue.
No update yet? Please if possible, this has been reported 5 Jan. So if possible, please kindly help.

**Comment by fherryfherry** [comment]
Please update latest version

**Comment by arianjewel** [comment]
go to vendor\crocodicstudio\crudbooster\src\database\seeds\CBSeeder.php.
then comment or remove line `namespace Database\Seeders;` 
then run `composer dump-autoload`.
then run `php artisan crudbooster:install`

Hope, This will work.
