### ISSUE TITLE
Not able to install on laravel 8

### ISSUE THREAD

**Issue by sanjaylama** [crocodic-studio/crudbooster#1643]
I am trying to install it on laravel 8 but get this error

 Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /Applications/MAMP/htdocs/crudbooster/vendor/crocodicstudio/crudbooster/src/commands/CrudboosterInstallationCommand.php on line 52

  at vendor/symfony/process/Process.php:141
    137▕      * @param int|float|null $timeout The timeout in seconds or null to disable
    138▕      *
    139▕      * @throws LogicException When proc_open is not installed
    140▕      */
  ➜ 141▕     public function __

when I run
php artisan crudbooster:install

It is not compatible at all?

**Comment by Stupa163** [comment]
Probably fixed by #1644

**Comment by sanjaylama** [comment]
No still is not working on laravel 8. 
Firstly when i do 
composer require crocodicstudio/crudbooster
 And the files in the github is not fully downloaded, ie, CBSeeder.php is not downloaded at all.
I manually downloaded and put in seeder folder and ran
php artisan crudbooster:install
after .evn settings.
It says
 Cannot declare class CBSeeder, because the name is already in use
If I removed CBSeeder.php
it says CBSeeder not found (what a joke)

Finally was able to make seeders work manually.
But not after login it shows 404 admin not found after I put the username and password
Goes nowhere.

Seems like you need to test for for laravel8

**Comment by fherryfherry** [comment]
Please install the latest version
