### ISSUE TITLE
What a buggy thing

### ISSUE THREAD

**Issue by sanjaylama** [crocodic-studio/crudbooster#1645]
I ran composer require crocodicstudio/crudbooster=5.5.* it says no such packages..then I tried
composer require crocodicstudio/crudbooster
it worked but does not import all files
for example it was not able to get seeder file. 
I manually downloaded the seeder file cbseeder inside seeder and ran 
php artisan db:seed
does not run CBSeeder at all

and even this
php artisan db:seed --class=CBSeeder

It says 
Target class [App\Database\Seeders\CBSeeder] does not exist
but file/class is there

I even tried 
composer dump-autoload
and re-ran fresh migrate with seeder, database-tables are created but no seeding

**Comment by JRB-y** [comment]
Can we have your work around ?

**Comment by pmietlicki** [comment]
Uncomment this inside CBSeeder.php :
namespace Database\Seeders; //Fix: Target class [CBSeeder] does not exist.
