### ISSUE TITLE
Error while Update - php artisan crudbooster:update

### ISSUE THREAD

**Issue by aagastya-sid** [crocodic-studio/crudbooster#1647]
Once installed on local works but transferred to server and there issue about image upload error and when tried to update this is the issue I am facing

PHP 7.3 | Laravel 6

![cPanel-Terminal](https://user-images.githubusercontent.com/10804578/106199840-033d9900-61dc-11eb-9306-24d53f7bd11f.png)

**Comment by arrazka** [comment]
how you solve the problem.. ?
