### ISSUE TITLE
Error Modul Generator With Sql Server

### ISSUE THREAD

**Issue by idhammubarok** [crocodic-studio/crudbooster#1658]
Mohon bantuan Mr. @fherryfherry , 

saya menggunakan CB v5.5 dan Sql Server, menemukan kesalahan ketika menggenerate modul

![Screen Shot 2021-03-01 at 13 42 30](https://user-images.githubusercontent.com/27127955/109461511-d4de0280-7a94-11eb-9ce5-470ea7765563.png)

**Comment by fherryfherry** [comment]
Update versi terbaru mas
