### ISSUE TITLE
Call to undefined method Maatwebsite\Excel\Excel::load() Import Excel Error in CB 

### ISSUE THREAD

**Issue by idhammubarok** [crocodic-studio/crudbooster#1669]
Dear Mr @fherryfherry 

When I import data from excel, I find an error Excel :: load, after I searched it turned out that Maatwebsite v.3 is not supported for this, I tried to downgrade to v.2 but crocodic locked it ..

is there a solution for this in CB

thank you for every answer given, this will really help me.

**Comment by ahmedgfathy** [comment]
still this problem exist till no, i wish one of the team of the crudbooster solve it

**Comment by idhammubarok** [comment]
Done, I upgraded the latest version of the Maatwebsite library and made my own helper.

**Comment by michaellearntorock2022** [comment]
> Done, I upgraded the latest version of the Maatwebsite library and made my own helper.

can you share the code plz?
