### ISSUE TITLE
Filter by date, betwen doesn't work

### ISSUE THREAD

**Issue by bhayron** [crocodic-studio/crudbooster#1683]
## When I filter by date, it doesn't work
![image](https://user-images.githubusercontent.com/4968294/123091418-b1521580-d3ff-11eb-8876-a9c42f7f36d3.png)

![image](https://user-images.githubusercontent.com/4968294/123091493-c9c23000-d3ff-11eb-84bc-17d842ae0c46.png)

laravel 5.5
crudbooster 5.5

**Comment by bhayron** [comment]
##I tested it with all versions but it didn't work


![image](https://user-images.githubusercontent.com/4968294/123114661-dc476400-d415-11eb-8ce1-84171ddd3404.png)


laravel 8.40
crudbooster 5.6

**Comment by renzocastillo** [comment]
@bhayron could you please share the generated query string after submit?

**Comment by bhayron** [comment]
http://localhost/estoque/public/admin/solicitacao37?filter_column%5Bsolicitacao.id%5D%5Btype%5D=&filter_column%5Bsolicitacao.id%5D%5Bsorting%5D=&filter_column%5Bpaciente.nome%5D%5Btype%5D=&filter_column%5Bpaciente.nome%5D%5Bsorting%5D=&filter_column%5Bpaciente1.numero%5D%5Btype%5D=&filter_column%5Bpaciente1.numero%5D%5Bsorting%5D=&filter_column%5Bsolicitacao.data%5D%5Btype%5D=between&filter_column%5Bsolicitacao.data%5D%5Bvalue%5D=&filter_column%5Bsolicitacao.data%5D%5Bvalue%5D%5B%5D=06%2F15%2F2021&filter_column%5Bsolicitacao.data%5D%5Bvalue%5D%5B%5D=06%2F23%2F2021&filter_column%5Bsolicitacao.data%5D%5Bsorting%5D=&filter_column%5Bsetor.nome%5D%5Btype%5D=&filter_column%5Bsetor.nome%5D%5Bsorting%5D=&filter_column%5Bcms_users.name%5D%5Btype%5D=&filter_column%5Bcms_users.name%5D%5Bsorting%5D=&filter_column%5Bsolicitacao.status%5D%5Btype%5D=&filter_column%5Bsolicitacao.status%5D%5Bsorting%5D=&lasturl=http%3A%2F%2Flocalhost%2Festoque%2Fpublic%2Fadmin%2Fsolicitacao37

**Comment by renzocastillo** [comment]
Could you please share solicitao data values for each row?

**Comment by bhayron** [comment]
Yes
![image](https://user-images.githubusercontent.com/4968294/123581752-ed47fa80-d7b2-11eb-8f89-86e44e9fcdd2.png)

**Comment by renzocastillo** [comment]
You have formatted your date, right? But your are saving maybe mysql timestring YY-MM-DD. Can you try to change the query string value to that date format and try again please?

**Comment by bhayron** [comment]
Yes, I've tried it that way too.
![image](https://user-images.githubusercontent.com/4968294/123582275-ebcb0200-d7b3-11eb-804f-5e33fd5619e4.png)

![image](https://user-images.githubusercontent.com/4968294/123582364-0bfac100-d7b4-11eb-960f-4489e7126bd2.png)

![image](https://user-images.githubusercontent.com/4968294/123582386-15842900-d7b4-11eb-853e-7c753c49b30c.png)

unsuccessfully

**Comment by renzocastillo** [comment]
Please take a look at the adjustments at cbcontroller. It may help you solve this issue. I made a PR for a similar feature over here

https://github.com/crocodic-studio/crudbooster/pull/1692

**Comment by bhayron** [comment]
OK thank you. I will try to apply the modifications.

**Comment by renzocastillo** [comment]
@bhayron  please test this PR https://github.com/crocodic-studio/crudbooster/pull/1694, It needed carbon object to $value

**Comment by bhayron** [comment]
Solved, 
Thank you very much!!!!

**Comment by muhammedaksam** [comment]
That vendor\crocodicstudio\crudbooster\src\controllers\CBController.php change at #1694 fixed my issue too. Thanks.
