### ISSUE TITLE
Update user privilege 

### ISSUE THREAD

**Issue by jankod** [crocodic-studio/crudbooster#169]
Update user privilege not work. I use versions v5.3.1.7 on windows php 7.1.

**Comment by fherryfherry** [comment]
Hi for update , you need to follow the update guide 
![image](https://cloud.githubusercontent.com/assets/6733315/23289247/0c314b5a-fa7b-11e6-8f77-2614ba7fc1f8.png)
https://github.com/crocodic-studio/crudbooster/releases/tag/v5.3.1.7
