### ISSUE TITLE
CRUDBooster Sort & Filter Not working to start date and End date

### ISSUE THREAD

**Issue by idhammubarok** [crocodic-studio/crudbooster#1697]
i found an error when using date with type between in sort and filter in crudbooster, after i debug i see the date format is still intact, i tried to make a standard date format and it worked,

original example:

if ($type == 'between') {
     if ($key && $value) {

         $result->whereBetween($key, $value);
     }
 } else {
     continue;
 }

I change:

if ($type == 'between') {
     if ($key && $value) {

         $value = [
             date('Y-m-d',strtotime($value[0])),
             date('Y-m-d',strtotime($value[1])),
         ];

         $result->whereBetween($key, $value);
     }
 } else {
     continue;
 }

may be useful

**Comment by arrazka** [comment]
not working for me...
