### ISSUE TITLE
how to make fake data ?

### ISSUE THREAD

**Issue by magussiro** [crocodic-studio/crudbooster#17]
laravel is include Faker,but i can' find it in composer.json

**Comment by harimayco** [comment]
laravel 5.0 doesn't include faker.
but you can install it with composer.
`composer require fzaninotto/faker --dev`

**Comment by magussiro** [comment]
oops...still didn't work,probably dependency conflict , I'm not sure how to fix it.

###########################################
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support v5.2.25 requires illuminate/contracts 5.3.* -> satisfia                                                                                                                                                             ble by illuminate/contracts[5.3.x-dev] but these conflict with your requirements                                                                                                                                                              or minimum-stability.
    - Conclusion: remove laravel/framework v5.0.35
    - Conclusion: don't install laravel/framework v5.0.35
    - barryvdh/laravel-debugbar v2.2.0 requires illuminate/support 5.1.*|5.2.* -                                                                                                                                                             > satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v                                                                                                                                                             5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.                                                                                                                                                             2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5                                                                                                                                                             .2.37, v5.2.43, v5.2.6, v5.2.7].
    - barryvdh/laravel-debugbar v2.2.1 requires illuminate/support 5.1.*|5.2.* -                                                                                                                                                             > satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v                                                                                                                                                             5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.                                                                                                                                                             2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5                                                                                                                                                             .2.37, v5.2.43, v5.2.6, v5.2.7].
    - barryvdh/laravel-debugbar v2.2.2 requires illuminate/support 5.1.*|5.2.* -                                                                                                                                                             > satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v                                                                                                                                                             5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.                                                                                                                                                             2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5                                                                                                                                                             .2.37, v5.2.43, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5                                                                                                                                                             .0.35
    - don't install illuminate/support v5.1.13|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.16|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5                                                                                                                                                             .0.35
    - don't install illuminate/support v5.1.20|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.22|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.25|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.28|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.30|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.31|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.41|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5                                                                                                                                                             .0.35
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5                                                                                                                                                             .0.35
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5                                                                                                                                                             .0.35
    - don't install illuminate/support v5.2.19|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.21|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.24|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.26|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.27|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.28|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.31|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.32|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.37|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.43|don't install laravel/framework v                                                                                                                                                             5.0.35
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5                                                                                                                                                             .0.35
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5                                                                                                                                                             .0.35
    - Installation request for laravel/framework (locked at v5.0.35, required as                                                                                                                                                              5.0.*) -> satisfiable by laravel/framework[v5.0.35].
    - Installation request for barryvdh/laravel-debugbar ^2.2 -> satisfiable by                                                                                                                                                              barryvdh/laravel-debugbar[v2.2.0, v2.2.1, v2.2.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by harimayco** [comment]
_"please read the package requirements or description before installing some package"_

seems you are trying to install laravel-debugbar [**v2.2.0**](https://packagist.org/packages/barryvdh/laravel-debugbar#v2.2.0) `illuminate/support: 5.1.*|5.2.*`
as you can see this version is not compatible with **laravel 5.0.35**
to solve this you can install laravel-debugbar [**v2.1.3**](https://packagist.org/packages/barryvdh/laravel-debugbar#v2.1.3) `illuminate/support: ~5.0.17|5.1.*|5.2.*`

you can run : 
`composer require "barryvdh/laravel-debugbar:~2.1.3" --dev`
or edit composer.json file : 
```
"require-dev": {
...
"barryvdh/laravel-debugbar": "~2.1.3",
...
}
```
the run `composer update`

good luck

**Comment by magussiro** [comment]
I'll try it, thanks a lot, or I try lower version Faker,
