### ISSUE TITLE
Package crocodicstudio/crudbooster at version 5.6.* has a PHP requirement incompatible with your PHP version (8.0.8)

### ISSUE THREAD

**Issue by gpalsingh30** [crocodic-studio/crudbooster#1701]
Package crocodicstudio/crudbooster at version 5.6.* has a PHP requirement incompatible with your PHP version (8.0.8)

**Comment by gpalsingh30** [comment]
Whilst installation I am getting this error.... I am on Laravel 8.0, PHP 8.0.8 (cli) (built: Jul  1 2021 15:26:46) ( NTS )

**Comment by meeftah** [comment]
maybe because crudbooster require php 7.4 and up but not 8...try to downgrade your php version or switch to 7.4 for the time being...

**Comment by gpalsingh30** [comment]
The issue sorted after I downgraded to PHP 7.4.
