### ISSUE TITLE
Privilege Role

### ISSUE THREAD

**Issue by Mahdi-Ba** [crocodic-studio/crudbooster#171]
i define one role the name is e.x programmer then give role to one item of menu full crud but when create  user an give that role then login just see empty dashboard !!!
whats happen ? that is my mistake or app dont work carefully?
when i give super admin role working true !!
please help me thanks

**Comment by Mahdi-Ba** [comment]
id_cms_privileges	this column in cms_users dont get value i think this is bug

**Comment by fherryfherry** [comment]
Hi, in addition to give role, you need to create a menu for the user at menu management

**Comment by Mahdi-Ba** [comment]
oh yes sorry :+1: .Thank u so much really powerfull # #
