### ISSUE TITLE
Primary Key in postgresql

### ISSUE THREAD

**Issue by furqon** [crocodic-studio/crudbooster#172]
om Fery,

Found out that the way getting primary key column in postgresql is different with mysql. In CRUDBooster helper, findPrimaryKey. There is no COLUMN_KEY field in pgsql.
Here is not a pretty solution specific for pgsql

`
public static function findPrimaryKey($table) {
	$table = CRUDBooster::parseSqlTable($table);	
	// -- mysql
	// $keys = DB::select('SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = :database AND TABLE_NAME = :table AND COLUMN_KEY = \'PRI\'', ['database'=>$table['database'], 'table'=>$table['table']]);

	$keys = DB::select('select tc.table_schema, tc.table_name, kc.column_name from information_schema.table_constraints tc, information_schema.key_column_usage kc where tc.constraint_type = \'PRIMARY KEY\' and kc.table_name = tc.table_name and kc.table_schema = tc.table_schema and kc.constraint_name = tc.constraint_name and tc.table_name = :table', ['table'=>$table['table']]);

	return $keys[0]->column_name;
}
`

**Comment by fherryfherry** [comment]
hi @furqon , if you found this is a solution for postgre, you could push it to the github

**Comment by cratosloks** [comment]
I'm having the same problem

**Comment by dsantonio** [comment]
Hi, in vendor/crocodicstudio/crudbooster/src/helpers/CRUDBooster.php change the function findPrimaryKey to:

`		public static function findPrimaryKey($table) {
			if(!$table) return 'id';
			
			if(self::getCache('table_'.$table,'primary_key')) {
				return self::getCache('table_'.$table,'primary_key');
			}			
			$table = CRUDBooster::parseSqlTable($table);

			if(!$table['table']) throw new \Exception("parseSqlTable can't determine the table");							
                        
                        $query = "";
                        if(config('database.default')=='pgsql'){
                            $query = "select * from information_schema.key_column_usage WHERE TABLE_NAME = '$table[table]'";
                        } else {
                            $query = "select * from information_schema.COLUMNS where TABLE_SCHEMA = '$table[database]' and TABLE_NAME = '$table[table]' and COLUMN_KEY = 'PRI'";
                        }
                        $keys = DB::select($query);
                        $primary_key = $keys[0]->COLUMN_NAME;
                        if($primary_key === null) $primary_key = $keys[0]->column_name;
                        
                        if($primary_key) {				
				self::putCache('table_'.$table,'primary_key',$primary_key);
				return $primary_key;
			}else{
				return 'id';
			}			
		}`

Also, change in: vendor/crocodicstudio/crudbooster/src/controllers/MenusController.php 
`"is_protected = false"`

**Comment by marcosa460** [comment]
Thank you so much @dsantonio , you solved my problem. it worked for me.

**Comment by furqon** [comment]
I think this thread can be closed
