### ISSUE TITLE
Button approve only for superadmin

### ISSUE THREAD

**Issue by MNH-16** [crocodic-studio/crudbooster#1728]
I want to add a new action/button called "approve" and "reject", which can only be seen and used by a superadmin to approve or reject request

our script
	        $this->addaction = array();
	        if(CRUDBooster::myPrivilegeId(1)) {  
	        $this->addaction[] = ['label'=>'Approve','url'=>CRUDBooster::mainpath('set-status/Approve/[id]'),'icon'=>'fa fa-check','color'=>'success','showIf'=>"[status_permintaan] == 'Pending'",'confirmation' => true,];
	        $this->addaction[] = ['label'=>'Reject','url'=>CRUDBooster::mainpath('set-status/Reject/[id]'),'icon'=>'fa fa-remove','color'=>'danger','showIf'=>"[status_permintaan] == 'Pending'",'confirmation' => true];
	        }

but still show in user, how to fix it?

**Comment by dedyksuntoro** [comment]
`if(CRUDBooster::myPrivilegeId() == 1)` or use `CRUDBooster::isSuperadmin()`

**Comment by MNH-16** [comment]
> `if(CRUDBooster::myPrivilegeId() == 1)` or use `CRUDBooster::isSuperadmin()`

its work, thankyou @dedyksuntoro
