### ISSUE TITLE
Question , How can I translate this control into Spanish?

### ISSUE THREAD

**Issue by mariolugo2** [crocodic-studio/crudbooster#1746]
days and months

![image](https://user-images.githubusercontent.com/18292605/153775142-a673537f-7023-42f0-9982-21381e022c93.png)

**Comment by josbeni** [comment]
Hola Mario. 
Hay  que hacer algunas modificaciones. 

Para corregir datePicker
en laravelapp/vendor/crocodicstudio/crudbooster/src/views/default/type_components/date/asset.blade.php

  <script type="text/javascript">
        var lang = '{{App::getLocale()}}';
        $(function () {
            $('.input_date').datepicker({
                // format: 'yyyy-mm-dd',
                format: 'dd-mm-yyyy',
                @if (in_array(App::getLocale(), ['ar', 'fa']))
                rtl: true,
                @endif
                language: lang
            });

            $('.open-datetimepicker').click(function () {
                $(this).next('.input_date').datepicker('show');
            });

        });

    </script>
    
    
    Para corregir DateTimePicker
    En laravelapp/vendor/crocodicstudio/crudbooster/src/views/default/type_components/datetime/asset.blade.php
      <script type="text/javascript">
        var lang = '{{App::getLocale()}}';
        moment.locale(lang);
        $(function() {
            $('.input_datetime').daterangepicker({
                singleDatePicker: true,
                timePicker: true,
                timePickerIncrement: 1,
                timePicker24Hour: true,
                autoApply: false,
                showDropdowns: true,
                locale: {
                    // format: "YYYY-MM-DD HH:mm:ss",
                    format: "DD-MM-YYYY HH:mm:ss",

                },

            });
        });
    </script>


En el Controller, en este  caso AdminPostsController
class AdminPostsController extends \crocodicstudio\crudbooster\controllers\CBController


Mostrar fecha y hora
			$this->col[] = ["label"=>"FECHA","name"=>"date","callback_php"=>'date("d/m/Y",strtotime($row->date))'];
			$this->col[] = ["label"=>"FECHA y HORA","name"=>"date_time","callback_php"=>'date("d/m/Y H-i-s",strtotime($row->date_time))'];

Ingresar fecha y hora 
			$this->form[] = ['label'=>'FECHA','name'=>'date','type'=>'date','validation'=>'required|date','width'=>'col-sm-10','help'=>'Ingrese una fecha coherente..!','placeholder'=>'Fecha de edición',"callback_php"=>'($row->date!=null?date("d-m-Y",strtotime($row->date)):"")'];
			$this->form[] = ['label'=>'FECHA y HORA','name'=>'date_time','type'=>'datetime','validation'=>'required','width'=>'col-sm-9'];


Convertir en fecha antes de agregar nuevo
	    public function hook_before_add(&$postdata) {        
			//Your code here

		if(!empty($postdata['date']))
			$postdata['date'] = date("Y-m-d",strtotime($postdata['date']));

		if(!empty($postdata['date_time']))
			$postdata['date_time'] = date("Y-m-d H-i-s",strtotime($postdata['date_time']));
	}

Convertir en fecha antes de actualizar edición
	    public function hook_before_edit(&$postdata,$id) {        
	        //Your code here

			if(!empty($postdata['date']))
				$postdata['date'] = date("Y-m-d",strtotime($postdata['date']));
	    
	
			if(!empty($postdata['date_time']))
				$postdata['date_time'] = date("Y-m-d H-i-s",strtotime($postdata['date_time']));
		}

![DeepinScreenshot_Seleccionar área_20220213220607](https://user-images.githubusercontent.com/1318757/153784630-d0d726f9-972f-463b-b251-afbc2b4bbabc.png)
Espero te sirva. 
Saludos Josbeni.

**Comment by mariolugo2** [comment]
> Hola Mario. Hay que hacer algunas modificaciones.
> 
> Para corregir datePicker en laravelapp/vendor/crocodicstudio/crudbooster/src/views/default/type_components/date/asset.blade.php
> 
> <script type="text/javascript"> var lang = '{{App::getLocale()}}'; $(function () { $('.input_date').datepicker({ // format: 'yyyy-mm-dd', format: 'dd-mm-yyyy', @if (in_array(App::getLocale(), ['ar', 'fa'])) rtl: true, @endif language: lang }); $('.open-datetimepicker').click(function () { $(this).next('.input_date').datepicker('show'); }); }); </script>
> ```
> Para corregir DateTimePicker
> En laravelapp/vendor/crocodicstudio/crudbooster/src/views/default/type_components/datetime/asset.blade.php
>   <script type="text/javascript">
>     var lang = '{{App::getLocale()}}';
>     moment.locale(lang);
>     $(function() {
>         $('.input_datetime').daterangepicker({
>             singleDatePicker: true,
>             timePicker: true,
>             timePickerIncrement: 1,
>             timePicker24Hour: true,
>             autoApply: false,
>             showDropdowns: true,
>             locale: {
>                 // format: "YYYY-MM-DD HH:mm:ss",
>                 format: "DD-MM-YYYY HH:mm:ss",
> 
>             },
> 
>         });
>     });
> </script>
> ```
> 
> En el Controller, en este caso AdminPostsController class AdminPostsController extends \crocodicstudio\crudbooster\controllers\CBController
> 
> Mostrar fecha y hora $this->col[] = ["label"=>"FECHA","name"=>"date","callback_php"=>'date("d/m/Y",strtotime($row->date))']; $this->col[] = ["label"=>"FECHA y HORA","name"=>"date_time","callback_php"=>'date("d/m/Y H-i-s",strtotime($row->date_time))'];
> 
> Ingresar fecha y hora $this->form[] = ['label'=>'FECHA','name'=>'date','type'=>'date','validation'=>'required|date','width'=>'col-sm-10','help'=>'Ingrese una fecha coherente..!','placeholder'=>'Fecha de edición',"callback_php"=>'($row->date!=null?date("d-m-Y",strtotime($row->date)):"")']; $this->form[] = ['label'=>'FECHA y HORA','name'=>'date_time','type'=>'datetime','validation'=>'required','width'=>'col-sm-9'];
> 
> Convertir en fecha antes de agregar nuevo public function hook_before_add(&$postdata) { //Your code here
> 
> ```
> 	if(!empty($postdata['date']))
> 		$postdata['date'] = date("Y-m-d",strtotime($postdata['date']));
> 
> 	if(!empty($postdata['date_time']))
> 		$postdata['date_time'] = date("Y-m-d H-i-s",strtotime($postdata['date_time']));
> }
> ```
> 
> Convertir en fecha antes de actualizar edición public function hook_before_edit(&$postdata,$id) { //Your code here
> 
> ```
> 		if(!empty($postdata['date']))
> 			$postdata['date'] = date("Y-m-d",strtotime($postdata['date']));
>     
> 
> 		if(!empty($postdata['date_time']))
> 			$postdata['date_time'] = date("Y-m-d H-i-s",strtotime($postdata['date_time']));
> 	}
> ```
> 
> ![DeepinScreenshot_Seleccionar área_20220213220607](https://user-images.githubusercontent.com/1318757/153784630-d0d726f9-972f-463b-b251-afbc2b4bbabc.png) Espero te sirva. Saludos Josbeni.

Gracias por tu respuesta  , realizare los ajustes y regreso para actualizar el post.
