### ISSUE TITLE
API Generator : Where clause issue

### ISSUE THREAD

**Issue by zamaludin** [crocodic-studio/crudbooster#178]
saya coba tambahkan where clause issue
contoh

`uid = '[uid]'`

tapi hasilnya tetap tidak berpengaruh

![image](https://cloud.githubusercontent.com/assets/13063378/23354443/d09ae1ec-fd03-11e6-8f20-2a9cce36d91f.png)

saya cek hasilnya menunjukan kalau value dari parameter tidak di ambil dan membandingkan dengan nilai string '[uid]' bukan value dari [uid]

**Comment by fherryfherry** [comment]
coba di screenshot form generatornya juga

**Comment by furqon** [comment]
sepertinya ini mirip dengan issue #170 
solusi sementara di saya di baris 54 ApiController.php
`$table                    = str_replace(env('DB_SCHEMA').'.', '', $row_api->tabel);`

kurang cantik, tapi sementara work. nunggu release update nya :D

**Comment by zamaludin** [comment]
@fherryfherry  
![image](https://cloud.githubusercontent.com/assets/13063378/23359095/3e932610-fd17-11e6-914c-83d8d639d5a3.png)
![image](https://cloud.githubusercontent.com/assets/13063378/23359145/6f7097f4-fd17-11e6-9bd5-516ceaa9e11c.png)


@furqon siap saya coba dulu. makasi suhu

**Comment by fherryfherry** [comment]
please update terbaru
