### ISSUE TITLE
Api Genereator : Password Problem

### ISSUE THREAD

**Issue by FaizalAmiruddinR2** [crocodic-studio/crudbooster#185]
I've a problem when make API for register and login. I just make an API wtih action type Create/Add for register, and Detail / Read for login.
When I try to login I found that the password not converted to hash and also for login it returned that the password is wrong.

Laravel 5.3.0
CRUDBooster 5.3.1.*
![screencapture-localhost-flance-public-admin-api_generator-edit-api-2-1488422487933](https://cloud.githubusercontent.com/assets/6519497/23490821/38ba09e4-ff2d-11e6-8fb3-9eeb16f6b9f1.png)
![screencapture-localhost-flance-public-admin-api_generator-edit-api-1-1488422377292 1](https://cloud.githubusercontent.com/assets/6519497/23490822/38d67a98-ff2d-11e6-9ec6-bd61efdf0bcb.png)
![screenshot from 2017-03-02 09-43-27](https://cloud.githubusercontent.com/assets/6519497/23490954/13c5b344-ff2e-11e6-822e-62a0c1c12bb6.png)
![screenshot from 2017-03-02 09-46-40](https://cloud.githubusercontent.com/assets/6519497/23490953/13c3eeec-ff2e-11e6-84f7-bbc98e2e2f0e.png)
![screenshot from 2017-03-02 09-53-02](https://cloud.githubusercontent.com/assets/6519497/23490955/13c76dc4-ff2e-11e6-8516-aadb6193c5df.png)

**Comment by fherryfherry** [comment]
Hi for temporary solving, you can make hash in hook before manually
Pada tanggal 2 Mar 2017 09.55, "Faizal Amiruddin" <notifications@github.com>
menulis:

**Comment by FaizalAmiruddinR2** [comment]
Still wrong password

**Comment by waffi** [comment]
update your crudbooster
https://github.com/crocodic-studio/crudbooster/issues/664

**Comment by azarzaza** [comment]
still the issue is not cleared

**Comment by thaotx** [comment]
i got same problem, when create user with api, password is wrong, but after change password in admin panel, try login again then it's successfull

**Comment by aagastya-sid** [comment]
This problem is still not solved
