### ISSUE TITLE
Many to many problem

### ISSUE THREAD

**Issue by amineqas** [crocodic-studio/crudbooster#187]
hello,
would you mind create a video in your youtube channel contain the steps to generate a module of many to many ??

**Comment by fherryfherry** [comment]
Hi, yes, thanks for your suggestion

**Comment by amineqas** [comment]
is there any opportunity to make that video or give me an instruction to create it because i need it now  ?

**Comment by fherryfherry** [comment]
In CB you can use [child type](http://crudbooster.com/doc/5.3/form-scaffolding#child) 

If that not meet, you might want to create your own form by following this tutorial 
https://www.youtube.com/watch?v=67C47y04Kjk

**Comment by amineqas** [comment]
when i create sub module like this one : 
$this->sub_module[] = ['label'=>'commande client','path'=>'cmdflights','foreign_key'=>'cmdflight_id','button_color'=>'primary','button_icon'=>'fa fa-bars'];

it gave me this error :( 
<img width="698" alt="screen shot 2017-03-06 at 6 01 07 pm" src="https://cloud.githubusercontent.com/assets/23016494/23622544/01075dae-0297-11e7-8ee9-ad0f0162af96.png">

**Comment by fherryfherry** [comment]
please update sir
