### ISSUE TITLE
Route [NotificationsControllerGetLatestJson] not defined.

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#189]
Hi, after i refresh  the migration iv'e got this error 

> Route [NotificationsControllerGetLatestJson] not defined. (View: C:\Users\Tomatoe\Desktop\Projects\fin\vendor\crocodicstudio\crudbooster\src\views\admin_template_plugins.blade.php) (View: C:\Users\Tomatoe\Desktop\Projects\fin\vendor\crocodicstudio\crudbooster\src\views\admin_template_plugins.blade.php) (View: C:\Users\Tomatoe\Desktop\Projects\fin\vendor\crocodicstudio\crudbooster\src\views\admin_template_plugins.blade.php)

>http://imgur.com/YPTVdn9

and also i try to create a module for the users table not the cms_table i also receive the error
> InvalidArgumentException in DatabaseManager.php line 239: Database [fnl] not configured..

>http://imgur.com/7IlQYrB

and last thing when i try to upload an avatar from the module i create then the type is "filemanager".. the error says it was Internal Server Error.. 

any ideas? Thanks in Advance Ferry..

**Comment by fherryfherry** [comment]
NotificationsControllerGetLatestJSON is not defined it means a module that named notification is not inserted when migration

Database not configured, this issue still in investigation, some people facing the same issue

internal server error, Usually its happen if conflict with the permission at your folder, public/*
or there is missing PHP extension

**Comment by tomatoe45** [comment]
why is that when i try to publish the vendor of crud the migration of the laravel has been deleted the users table and the password_reset table..  i was wondering since my setup and setting lost during the migration:refresh and i cannot use the module for the users.. will wait for the release.. 

Thanks.. ferry..

**Comment by fherryfherry** [comment]
hi @tomatoe45 you have run an uncomplete command, if you want re-migrate, please run: 

`php artisan migrate:refresh --seed`

**Comment by tomatoe45** [comment]
Thanks fherry..

**Comment by hengsoheak** [comment]
After  ` php artisan migrate:refresh --seed` all table were created but they are all empty.

**Comment by chandnitin** [comment]
not work

**Comment by chandnitin** [comment]
php artisan migrate:refresh --seed 
not work

**Comment by chandnitin** [comment]
ErrorException in UrlGenerator.php line 314:
Route [NotificationsControllerGetLatestJson] not defined. (View: C:\wamp\www\addonpanel\addon\vendor\crocodicstudio\crudbooster\src\views\admin_template_plugins.blade.php) (View: C:\wamp\www\addonpanel\addon\vendor\crocodicstudio\crudbooster\src\views\admin_template_plugins.blade.php) (View: C:\wamp\www\addonpanel\addon\vendor\crocodicstudio\crudbooster\src\views\admin_template_plugins.blade.php)
