### ISSUE TITLE
Suggestion: Field with Inline Search

### ISSUE THREAD

**Issue by franciscoluiz** [crocodic-studio/crudbooster#191]
I would like to suggest a new field, a text field with inline search... like tags...

Just as it already exists in other crud-generators. This would enrich the CB.

![Image](https://cloud.githubusercontent.com/assets/506510/23552844/9c7df42a-fffc-11e6-816d-9417b700dae7.png)

**Comment by fherryfherry** [comment]
By the way, this already exists in the latest CB version
select2 type, with relationship_table attribute
