### ISSUE TITLE
aviable for laravel 5.4

### ISSUE THREAD

**Issue by renamate** [crocodic-studio/crudbooster#192]
Hello i'm new for crudbootster and i dont know if is posible install it on laravel 5.4

Thank for this project.

**Comment by tomatoe45** [comment]
Please refer to this .

>http://crudbooster.com/doc/5.3/installation


this might help you with your needs.. Thanks.

**Comment by renamate** [comment]
I already read the whole manual and does not make any reference to laravel 5.4 so check here, it's compatible?

**Comment by tomatoe45** [comment]
good to here that you read the manual. for your satisfaction you can create the project with 5.4. as far as i can read the manual the laravel 5.3.* is highlighted .. so the system can run properly.. please also consider checking the closed issue i might help you a lot.. iv'e also referred the manual to avoid program issue..

**Comment by tomatoe45** [comment]
in laravel 5.4 you will encounter the error with ::share() it is because it was deprecated. that is why laravel 5.3 is recommended for the crudbooster..
