### ISSUE TITLE
Error on Privilege

### ISSUE THREAD

**Issue by thangasamy003** [crocodic-studio/crudbooster#193]
I have created the Privilege. After i have created the user with the privilege, but the privilege is not set for the user. I'm new to laravel please help me to fix this problem.

**Comment by tomatoe45** [comment]
Hi, for the record just update your crudbooster 

Please refer to this as update guide.. 

[#168](https://github.com/crocodic-studio/crudbooster/issues/168)

Thanks.

**Comment by technoartista** [comment]
Same error for me , after giving permission, the module is not displayed for the user when logged in . Do I have to update and codes after composer update command?

**Comment by tomatoe45** [comment]
iv'e encounter that error  before.. i was not able to assign the privilege to the specific user.. but after updating my crudbooster that bug was fix.. just follow the update guide and the error was solved..

**Comment by fherryfherry** [comment]
You might watch this video https://www.youtube.com/watch?v=089UoN4Bm2Q @thangasamy003 @technoartista
