### ISSUE TITLE
Menu Privilege

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [crocodic-studio/crudbooster#195]
Menus do not appear when the user does not have super admin privilege.

After commenting on this line: // -> where ('id_cms_privileges', self :: myPrivilegeId ())

The problem was solved. Is there somewhere how to set the privilege of the menu?

                public static function sidebarMenu() {
                        $menu_active = DB::table('cms_menus')
//                      ->where('id_cms_privileges',self::myPrivilegeId())
                        ->where('parent_id',0)
                        ->where('is_active',1)
                        ->where('is_dashboard',0)
                        ->orderby('sorting','asc')
                        ->select('cms_menus.*')
                        ->get();

**Comment by fherryfherry** [comment]
You must add menu each privilege at menu management

**Comment by andersondeoliveiramachado** [comment]
Thanks.
Okay, I had not seen the privilege selection option at the top of the menu management page.
