### ISSUE TITLE
Child Type Error

### ISSUE THREAD

**Issue by marcosmaia** [crocodic-studio/crudbooster#196]
When adding a child from that error can anyone help me?

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'osweb657_crud.products_id' in 'where clause' (SQL: select `osweb657_crud`.`clientes`.`id`, `osweb657_crud`.`clientes`.`nome` from `osweb657_crud`.`clientes` where `osweb657_crud`.`products_id` = 1) (View: /home/osweb657/crudbooster/vendor/crocodicstudio/crudbooster/src/views/default/type_components/child/component.blade.php) (View: /home/osweb657/crudbooster/vendor/crocodicstudio/crudbooster/src/views/default/type_components/child/component.blade.php) (View: /home/osweb657/crudbooster/vendor/crocodicstudio/crudbooster/src/views/default/type_components/child/component.blade.php)

**Comment by fherryfherry** [comment]
It's looks like a bug for the child type sir, just wait for new release

**Comment by fherryfherry** [comment]
#205
