### ISSUE TITLE
Child error

### ISSUE THREAD

**Issue by marcosmaia** [crocodic-studio/crudbooster#198]
When adding a child from that error can anyone help me?

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ok.products_id' in 'where clause' (SQL: select `ok`.`stock`.`id`, `ok`.`stock`.`description`, `ok`.`stock`.`stock_in`, `ok`.`stock`.`stock_out` from `ok`.`stock` where `ok`.`products_id` = 1) (View: F:\WampDeveloper\Websites\crud.com\webroot\ok\vendor\crocodicstudio\crudbooster\src\views\default\type_components\child\component.blade.php) (View: F:\WampDeveloper\Websites\crud.com\webroot\ok\vendor\crocodicstudio\crudbooster\src\views\default\type_components\child\component.blade.php) (View: F:\WampDeveloper\Websites\crud.com\webroot\ok\vendor\crocodicstudio\crudbooster\src\views\default\type_components\child\component.blade.php)

**code Controllers main:**
http://legalemb.com.br/AdminOkProductsController.txt

**code Controllers child:**
http://legalemb.com.br/AdminOkStock1Controller.txt

**Comment by marcosmaia** [comment]
**code Controllers main:**
http://legalemb.com.br/AdminOkProductsController.txt

**code Controllers child:**
http://legalemb.com.br/AdminOkStock1Controller.txt

**Comment by fherryfherry** [comment]
#196
