### ISSUE TITLE
Child foreign key insert

### ISSUE THREAD

**Issue by wke102** [crocodic-studio/crudbooster#202]
I made a view with a foreign key to a table.

Eg: 
Product Table
id (pk)

Product Language Table
id_product (fk to Product Table)

Product language is a child inside Product table for the form, but when i save it says Unknown column product_id, is there any way I can link the foreign key so that when it insert i  will be linked.

**Comment by marcosmaia** [comment]
I'm also having the same problem and no one to help. But it looks like the problem and in the system it is changing the '.' By '_' because he actually seeks the product.id and not product_id

If you can, let me know, please.

**Comment by fherryfherry** [comment]
Please screenshot the error @wke102

**Comment by wke102** [comment]
![screen shot 2017-03-06 at 10 54 12 pm](https://cloud.githubusercontent.com/assets/2782879/23615010/f8009080-02bf-11e7-907d-7f6321d94a48.png)
![screen shot 2017-03-06 at 10 54 37 pm](https://cloud.githubusercontent.com/assets/2782879/23615011/f8022c9c-02bf-11e7-9941-3717c46aaf57.png)
![screen shot 2017-03-06 at 10 54 45 pm](https://cloud.githubusercontent.com/assets/2782879/23615012/f8069048-02bf-11e7-9599-75bcc8c2893f.png)

xe_post_category (id)
xe_post_category_language (id, id_post_category (fk))

Error Message:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mugbient.xe_post_category_id' in 'field list' (SQL: insert into `mugbient`.`xe_post_category_language` (`created_by`, `description`, `friendly_url`, `id`, `id_post_category`, `mugbient`.`xe_post_category_id`, `name`, `status`, `updated_by`) values (1, 1, 1, 1, 1, 8, 1, A, 1))

**There is also some issues with the child element which doesn't show anything after insert.
