### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Ziaullah-Mommand** [crocodic-studio/crudbooster#203]
When I am login into admin page I am getting this error.
![screen shot 2017-03-06 at 8 32 25 pm](https://cloud.githubusercontent.com/assets/10906405/23617856/1177d1c2-02ac-11e7-88ee-149a50fc6219.png)

**Comment by tomatoe45** [comment]
Hi sir please refer to this

 [https://github.com/crocodic-studio/crudbooster/issues/189](#189)


They are now updating that bug. please stay tuned for updates.. Thanks

**Comment by tomatoe45** [comment]
Please refer to this.. it might help you with NotificationControllerGetLatestJSON

[#189](https://github.com/crocodic-studio/crudbooster/issues/189)
