### ISSUE TITLE
Error (Header and Custom Field Set As Input Column)

### ISSUE THREAD

**Issue by esdayehezkiel** [crocodic-studio/crudbooster#206]
Hy, i just set a header and custom field type from your Form Scaffolding but it set as an input to database column. I dont want to make them as an input because i dont have database column for it. It's worked before i update my crudbooster version. Thank you.

**Comment by fherryfherry** [comment]
you can unset the postdata array at hook_before_add / hook_before_edit

**Comment by esdayehezkiel** [comment]
Got it, thanks!
