### ISSUE TITLE
problem column not found 1054 on table index

### ISSUE THREAD

**Issue by pablo-dave** [crocodic-studio/crudbooster#207]
![bug1](https://cloud.githubusercontent.com/assets/24419145/23693098/ae337c56-03a0-11e7-8588-bf321a384709.png)

When I use more of one column relationship, I get this error because it add "1" to the name of the table, This did not happen in crudbooster 5.3.0. *, I have now version 5.3.1.*

Thanks for help.

**Comment by fherryfherry** [comment]
you don't need to add the database name in join column

**Comment by pablo-dave** [comment]
So, how i can display the column joined to the table? thanks

**Comment by fherryfherry** [comment]
To learn more advanced code, you might open its controller,

The code should be an example : 
$this->col[] = ['label'=>'Product','name'=>'products_id','join'=>'products,name'];

**Comment by pablo-dave** [comment]
Thanks, corrected when updating
