### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#208]
fherry, is the NotificationsControllerGetLatestJSON error is already fix and also the migration?

i just wanna ask if when is the next update will be release?

Thanks. God Bless.

**Comment by fherryfherry** [comment]
Hi, not yet, still in progress
I can't make a confirm, but maybe this week, or next week
because I also fix a lot of other issues

**Comment by tomatoe45** [comment]
oh okey fherry thank you. because i cannot get into my app after i run the refresh migration. will wait for the updates Thanks fherry..
