### ISSUE TITLE
Error on script calendar

### ISSUE THREAD

**Issue by pablo-dave** [crocodic-studio/crudbooster#215]
![calendar](https://cloud.githubusercontent.com/assets/24419145/23736162/5245fc62-0458-11e7-80fa-3b4ed0119d58.png)

Calendar duplicate when get focus

**Comment by fherryfherry** [comment]
please make sure the name is not same, between ento and any other

**Comment by pablo-dave** [comment]
![calendar2](https://cloud.githubusercontent.com/assets/24419145/23820678/38ca0112-05ec-11e7-8af9-1a1ae588c432.png)

No, the name is diferent!
