### ISSUE TITLE
How to add new custom column in table ? 

### ISSUE THREAD

**Issue by shemul** [crocodic-studio/crudbooster#218]
I just want to add a new static column to the table view which won't affect any data model or anything.. How can I do that ?

**Comment by shemul** [comment]
Columns Scaffolding it is 😄

**Comment by shemul** [comment]
I can do that by "column Scaffolding" but the array required data filed. but i don't need any data filed for this.. 

`$this->col[] = ["label"=>"Static column","name"=>"ANYTHING"];`

**Comment by crauliuc** [comment]
Figured this out? Is there a way to add a class name to a column?
