### ISSUE TITLE
Hook Method Not Working

### ISSUE THREAD

**Issue by magussiro** [crocodic-studio/crudbooster#22]
I'm use  hook_before_index to get specific data,but not working

ControllerMaster/Controller.php
	public function hook_before_index(&$result) {
        //if (Session::get('admin_privileges_name') == 'customer')
            $result->where('id_cms_users',Session::get('admin_id'));

    }

**Comment by fherryfherry** [comment]
Never edit from that file "controller.php", you should edit from your own "module" controller

**Comment by magussiro** [comment]
Thanks,it's my fault, I edit the wrong place
