### ISSUE TITLE
 child been fixed?

### ISSUE THREAD

**Issue by marcosmaia** [crocodic-studio/crudbooster#220]
Does anyone know how to bug me if the bug makes child been fixed

**Comment by tomatoe45** [comment]
@marcosmaia they are currently processing the bug.. please stay tune for the updates.. Thanks

**Comment by fherryfherry** [comment]
don't create a duplicate issue just for bumping, sir, please comment at your own thread

**Comment by tomatoe45** [comment]
opps. my bad.. sorry.

**Comment by fherryfherry** [comment]
I mean for TS @tomatoe45 :D, lol
