### ISSUE TITLE
[HELP] Need to know the page source in viewing page

### ISSUE THREAD

**Issue by sweggggg** [crocodic-studio/crudbooster#222]
I need to reconfigure the codes in the viewing page so that i can do some customization in the page 

![capture](https://cloud.githubusercontent.com/assets/26056229/23786187/935db10a-05a6-11e7-9252-d9deae2e17ac.PNG)

**Comment by fherryfherry** [comment]
You might override the detail method, named "getDetail($id)"

**Comment by sweggggg** [comment]
which files?

**Comment by fherryfherry** [comment]
in its controller

**Comment by sweggggg** [comment]
no such lines exist in the controller file

**Comment by fherryfherry** [comment]
You need to add the `getDetail($id)` manually

**Comment by sweggggg** [comment]
actually i wanted to make it like the image below. 

i wanted to make the page have a checkbox built in

![935db10a-05a6-11e7-9252-d9deae2e17ac](https://cloud.githubusercontent.com/assets/26056229/23841136/103e551c-07e6-11e7-9501-e9e56f315adf.PNG)

**Comment by fherryfherry** [comment]
I think you need to make a custom whole of detail view

**Comment by sweggggg** [comment]
can you provide me with the specific file name and its directory?

**Comment by technoartista** [comment]
@fherryfherry  can you tell me how to design a custom page inside crudbooster ? do you have any documentation for that or youtube videos ... if so please share the link .
