### ISSUE TITLE
apakah statistic controllernya digenerate juga?

### ISSUE THREAD

**Issue by zamaludin** [crocodic-studio/crudbooster#223]
saya mau membuat tampilan custom dengan menyertakan statistik.. 
tetapi ternyata controllernya tidak di generate..

dan apakah ada cara lain untuk melakukan itu? (custom view)

**Comment by fherryfherry** [comment]
Anda tidak bisa custom statistic yang sudah digenerate. 
Jika anda perlu membuat statisstic sendiri, anda bisa membuat suatu method sendiri yang berisi view anda sendiri, kemudian tinggal tambahkan / set sebagai dashboard di menu management
