### ISSUE TITLE
API Generator - Using Action Type DETAIL/READ cannot return corresponding id records

### ISSUE THREAD

**Issue by eric8words** [crocodic-studio/crudbooster#224]
I defined the API as of below. However, I cannot retrieve the record using API call like this

"http://localhost:8888/api/getrec/3"
![api](https://cloud.githubusercontent.com/assets/6895217/23817399/c278bbe2-062d-11e7-8ed8-a318634b8320.png)

**Comment by fherryfherry** [comment]
http://localhost:8888/api/getrec?id=

**Comment by eric8words** [comment]
Still cannot. Below is the response. Thanks
![screen shot 2017-03-11 at 10 41 42 am](https://cloud.githubusercontent.com/assets/6895217/23819860/8d2512b4-0647-11e7-91f2-84130aa429c7.png)

**Comment by fherryfherry** [comment]
Still in investigation
