### ISSUE TITLE
Let's help the project??

### ISSUE THREAD

**Issue by marcosmaia** [crocodic-studio/crudbooster#225]
@fherryfherry did a great job, help the project donating any amount, donating, help you too, today a big project of this only received 10 Unfortunate this

**Comment by fherryfherry** [comment]
Never mind sir @marcosmaia, I'm working in a company that always using the CRUDBooster, so this tool just for help us in our company

**Comment by franciscoluiz** [comment]
marcos maia, de onde tu é? temos um grupo no telegram para os brazucas que usam crudbooster.

**Comment by marcosmaia** [comment]
@franciscoluiz minas brasil passa o convite pra mim

**Comment by franciscoluiz** [comment]
https://t.me/joinchat/AAAAAEHqibW6y8INT_pZPQ

**Comment by franciscoluiz** [comment]
conseguiu?

**Comment by wa7eedem** [comment]
we always can help the project with PR's :) .
also I wish you use [slack](https://slack.com/) to meet .

thank you all .
