### ISSUE TITLE
Error, select2 does not display items, only after inserting some text

### ISSUE THREAD

**Issue by pablo-dave** [crocodic-studio/crudbooster#226]
![select](https://cloud.githubusercontent.com/assets/24419145/23820901/5e9590dc-05f1-11e7-821f-9b9cb118feb1.png)

**Comment by fherryfherry** [comment]
I don't understand, have you click the dropdown items ?

**Comment by pablo-dave** [comment]
yo quiero que muestre los elementos de la base de datos de esta manera:
![select2](https://cloud.githubusercontent.com/assets/24419145/23824272/686b2af4-0641-11e7-8a72-284121f1aa52.png)

no me muestra los items:
![select](https://cloud.githubusercontent.com/assets/24419145/23824313/103ad180-0642-11e7-82e5-5b8f0ac7d6f0.png)

**Comment by fherryfherry** [comment]
As "placeholder" said, you need to enter 1 or more characters to show the values

**Comment by pablo-dave** [comment]
Yes, i solved it choosing type= select and initialize from load_js in controller: $("#x").select2();
