### ISSUE TITLE
There is no FK for that table

### ISSUE THREAD

**Issue by DeveloperOnCall** [crocodic-studio/crudbooster#227]
I have two tables -
'Galleries' (ang_galleries) stores image gallery names
'Images' (ang_images) stores images with a relationship to which gallery (id_ang_galleries)

When adding the sub_module - I get the error 'There is no FK for that table. I am confused because the FK is there as you can see in the attached dump.

Any help would be most appreciated. Thank you.

[gallery_tables.txt](https://github.com/crocodic-studio/crudbooster/files/835553/gallery_tables.txt)

**Comment by fherryfherry** [comment]
it mean fk for the attribute at your scaffolding

**Comment by DeveloperOnCall** [comment]
I'm sorry, I don't quite understand what you mean here. The form fields are related (table and form) to the columns as normal.

**Comment by shemul** [comment]
I'm also confused how the sub module works , it will be great if someone add new videos to crudbooster YouTube or explain briefly so that I can make video for crudbooster.

**Comment by fherryfherry** [comment]
please update to the latest version
