### ISSUE TITLE
QUICK QUESTION

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#228]
fherry why is that in the CRUDBoosterService.php

this line exists
>     if(file_exists(base_path('database/migrations/2014_10_12_000000_create_users_table.php'))) {        
            @unlink(base_path('database/migrations/2014_10_12_000000_create_users_table.php'));
        }  } > if(file_exists(base_path('database/migrations/2014_10_12_100000_create_password_resets_table.php'))) {            
            > @unlink(base_path('database/migrations/2014_10_12_100000_create_password_resets_table.php'));
        }
 well my users and password_resets migration has been remove.. i need those tables.. why is that in this version those migration are removed?

**Comment by fherryfherry** [comment]
Cb not use that migartion file, it makes ambigou
Pada tanggal 11 Mar 2017 14.13, "tomatoe45" <notifications@github.com>
menulis:

**Comment by tomatoe45** [comment]
so i need to create my own migration for users and password resets?

**Comment by fherryfherry** [comment]
Yes you may create your own self
Pada tanggal 11 Mar 2017 14.28, "tomatoe45" <notifications@github.com>
menulis:

**Comment by tomatoe45** [comment]
ah okay fherry.. Thank you.. it is the same process for seeding the default user?

**Comment by tomatoe45** [comment]
fherry, after migrating i have  this error.. 

> RuntimeException in Encrypter.php line 43:
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

i already run the key:generate..

**Comment by tomatoe45** [comment]
Opps. my bad. it fix now.. thanks fherry
