### ISSUE TITLE
Login not workig

### ISSUE THREAD

**Issue by xparthx** [crocodic-studio/crudbooster#229]
Hello,

I followed all the steps as written here:

http://crudbooster.com/doc/5.3/installation

The issue is when I'm trying to log in with below credentials, it is not working

username : admin@crudbooster.com
password : 123456

And it is because "cms_users" is table empty, I have tried php artisan migrate --seed too, but still same issue.

How can I insert that default admin user into that table?

Thanks

**Comment by fherryfherry** [comment]
it should work, but you may try to check the DatabaseSeeder.php file at 
`database/seeds`

![image](https://cloud.githubusercontent.com/assets/6733315/23829038/60b385e6-0717-11e7-92e2-c37afd95eea1.png)

**Comment by fherryfherry** [comment]
Please update to the latest version sir

**Comment by xparthx** [comment]
@fherryfherry Do you mean Laravel 5.4 or the latest version of the crudbooster?

If Laravel 5.4, then I have already tried, it is not compatible right now with it. https://github.com/crocodic-studio/crudbooster/issues/192

And I'm already using the latest version of the crudbooster. i.e version 5.3.2.*

By the way, I have check that seeder file, it is empty:

```
<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
    }
}
``


Thanks

**Comment by fherryfherry** [comment]
I mean, the CB sir,
Please re-install, I just update the CB last minutes

**Comment by xparthx** [comment]
@fherryfherry,

Ok let me give it a shot then

By the way I appriciate your quick response.

Thanks

**Comment by xparthx** [comment]
Worked with the latest CB version.

Would be good if you can make it compatible with the Laravel 5.4 soon

Thanks

**Comment by xparthx** [comment]
Hello @fherryfherry,

Now it is giving 404 for the assets (css & image):

GET http://localhost/crudbooster/public/vendor/crudbooster/assets/css/main.css 
login:12 GET http://localhost/crudbooster/public/vendor/crudbooster/assets/adminlte/bootstrap/css/bootstrap.min.css 
login:16 GET http://localhost/crudbooster/public/vendor/crudbooster/assets/adminlte/dist/css/AdminLTE.min.css 404 (Not Found)
login:95 GET http://localhost/crudbooster/public/vendor/crudbooster/assets/adminlte/plugins/jQuery/jQuery-2.1.4.min.js 
login:55 GET http://localhost/crudbooster/public/vendor/crudbooster/assets/logo_crudbooster.png 404 (Not Found)
login:95 GET http://localhost/crudbooster/public/vendor/crudbooster/assets/bg_blur3.jpg 404 (Not Found)
login:97 GET http://localhost/crudbooster/public/vendor/crudbooster/assets/adminlte/bootstrap/js/bootstrap.min.js 404 (Not Found)
logo_crudbooster.png:1 GET http://localhost/crudbooster/public/vendor/crudbooster/assets/logo_crudbooster.png 404 (Not Found)

Thanks

**Comment by mgcox2** [comment]
Anyone find a solution? I just installed CRUDBooster to check it out for a project, but I'm having the same issue with all the assets not found as @xparthx. Laravel 5.3 and CB 5.4.0.1.

**Comment by ChiaoFan** [comment]
same issue!!! please give me a solution...

**Comment by teguhsuwanda** [comment]
Just copy everything inside CBSeeder class to DatabaseSeeder class. It may be stupid, but it works for me. :D

**Comment by vivdub** [comment]
Try this:
sudo a2enmod rewrite
sudo service apache2 restart
 Also make sure AllowOverride is set to All in apache conf. /etc/apache2/apache2.conf

**Comment by waqasraza123** [comment]
@teguhsuwanda  your solution worked for me. I copied everything from CBSeeder  to DatabaseSeeder  and then php artisan db:seed

**Comment by tiznull** [comment]
I had this exact issue when I migrated from local to live. I just moved into the Laravel directory and updated CrudBooster and it worked for me. I will report back if there was any fallout.

`#> cd /var/www/project/master/laravel`
`#> php artisan crudbooster:update`

**Comment by lulosys** [comment]
admin@crudbooster.com 123456 entre con este usuario y agregue el super admin manual mente atravez de los modulos que ofrece crudbooster.
