### ISSUE TITLE
Error on table master - detail 

### ISSUE THREAD

**Issue by pablo-dave** [crocodic-studio/crudbooster#230]
![err](https://cloud.githubusercontent.com/assets/24419145/23826545/3d9b5706-066c-11e7-8b47-163066879d91.png)
![err2](https://cloud.githubusercontent.com/assets/24419145/23826547/41b3a1a4-066c-11e7-8764-270ae282d5b2.png)

**Comment by fherryfherry** [comment]
need to update to the latest version
