### ISSUE TITLE
symlink(): No such file or directory

### ISSUE THREAD

**Issue by Alexintosh** [crocodic-studio/crudbooster#233]
Hello, 

I started with a fresh installation of laravel 5.3 and followed the [installation guide](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/installation.md) using the Homestead vagrant machine.

When running `$ php artisan crudbooster:install` I get the error:

`
  [ErrorException]
  symlink(): No such file or directory
`

How do I fix it?

**Comment by GeekuTech** [comment]
Facing same issue.....
<img width="495" alt="image 2017-03-13 at 2 52 38 pm" src="https://cloud.githubusercontent.com/assets/20791972/23849280/d274bf16-07fc-11e7-8cbb-ed651f23ffbd.png">

**Comment by fherryfherry** [comment]
Have you install the latest version of cb?
Pada tanggal 13 Mar 2017 16.53, "Rana Ali" <notifications@github.com>
menulis:

**Comment by GeekuTech** [comment]
yes ....

I followed these steps 

1. composer create-project --prefer-dist laravel/laravel blog "5.3.*"
2. composer require crocodicstudio/crudbooster
3. then added crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class, to providers array  in the config/app.php file

**Comment by branigan** [comment]
You have to create folder "vendor" inside "public" to fix this error.

**Comment by GeekuTech** [comment]
Thanks ..... Its working

**Comment by Alexintosh** [comment]
It worked for me as well.

After that I was running into the following error: "The only supported ciphers are AES-128-CBC and AES-256-CBC "

FFR in order to solve it, run this command
`php artisan key:generate`

**Comment by ventouris** [comment]
I have the same issue. I cannot make it work whatever I do.. v5.4.0.10

**Comment by amirmasoud** [comment]
Check that symlink does not exist, if it does, it would throw same exception.
