### ISSUE TITLE
CIPHERS KEY

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#234]
fherry after i install the latest CB.. when i try to run the host the ciphers don't match

RuntimeException in Encrypter.php line 43:
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

Thanks..

**Comment by tomatoe45** [comment]
for this reason i need to restart my server..

**Comment by tomatoe45** [comment]
![app_settings](https://cloud.githubusercontent.com/assets/17925294/23838738/c29cc3e6-07d3-11e7-9bbf-446e9a439140.png)


i've also notice that the form is duplicated..

**Comment by fherryfherry** [comment]
Then, after restarting your machine, your chippers problem solved ?

**Comment by fherryfherry** [comment]
Try to reinstall about duplicate

**Comment by tomatoe45** [comment]
yeah i think so.. it needs to be restart before it solve.. it works find now.. for the duplicate i will try to reinstall..

**Comment by tomatoe45** [comment]
it works fine now fherry.. Thanks.. i'm going to close this issue now..
