### ISSUE TITLE
Error Updating User Privilege

### ISSUE THREAD

**Issue by esdayehezkiel** [crocodic-studio/crudbooster#235]
Hello, i'm trying to updating user privilege but it doesn't work. Please follow up this issue, Thank You.

**Comment by fherryfherry** [comment]
@esdayehezkiel screenshot please ?

**Comment by esdayehezkiel** [comment]
![user error2](https://cloud.githubusercontent.com/assets/26267141/23848251/e56d7746-0808-11e7-8a08-76389dd38c60.PNG)
![user error](https://cloud.githubusercontent.com/assets/26267141/23848252/e56e1a5c-0808-11e7-93a3-cac89ee45402.PNG)


The other privilege shown because i give the id_cms_privileges directly to cms_user database. If I set or change it in crudbooster is doesn't work.

**Comment by fherryfherry** [comment]
I think you have to update the latest crudbooster

**Comment by esdayehezkiel** [comment]
i'm using 5.2.7 but still didn't work.

**Comment by fherryfherry** [comment]
I don't get any problem with it, could you provide screenshots step by step

**Comment by esdayehezkiel** [comment]
Here the gif for the step by step.

![crudbooster](https://cloud.githubusercontent.com/assets/26267141/24029334/e1fea39e-0b07-11e7-852d-cea1e89b7038.gif)

**Comment by fherryfherry** [comment]
Hi, it seems you did the update instead of fresh install ? Am I Right ? 
If so, you have to replace `AdminCmsUsersController.php` in `app/Http/Controller` with newest. 

You can find newest controller in `/Vendor/crocodicstudio/crudbooster/src/userfiles/controllers/AdminCmsUsersController.php`

**Comment by esdayehezkiel** [comment]
Hi, yes i update my crudbooster since version 5.2.
Ok thanks @fherryfherry , thats fix the issue.
