### ISSUE TITLE
Error on installation: Class '' not found

### ISSUE THREAD

**Issue by 4502040** [crocodic-studio/crudbooster#236]
Migrating database...
PHP Fatal error:  Class '' not found in /var/www/crud/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 410

**Comment by fherryfherry** [comment]
Environment ?
PHP : ...
OS : ...
Laravel Version : ...
Database : ....
CRUDBooster Version : ....

**Comment by tomatoe45** [comment]
@4502040  hi sir , please refer this link for the program requirements to avoid system malfunction 

[Crudbooster Requirements](http://crudbooster.com/doc/5.3/installation)

Thanks

**Comment by fherryfherry** [comment]
update to the latest version please
