### ISSUE TITLE
Add new module, select table empty

### ISSUE THREAD

**Issue by jesus2828** [crocodic-studio/crudbooster#237]
Add new module, select table empty. I have version 5.3.2.7

**Comment by fherryfherry** [comment]
Environment ?
PHP : ...
OS : ...
Laravel Version : ...
Database : ....
CRUDBooster Version : ....

**Comment by tomatoe45** [comment]
@jesus2828 hi sir , please refer this link for the program requirements to avoid system malfunction 

[Crudbooster Requirements](http://crudbooster.com/doc/5.3/installation)

Thanks

**Comment by jesus2828** [comment]
PHP 5.6.30-7
Mcrypt PHP Extension
OpenSSL PHP Extension
Mbstring PHP Extension
Tokenizer PHP Extension
FileInfo PHP Extension
ubuntu 14.04
Laravel 5.3.30
mysql 5.5.54
crudbooster 5.3.2.7

**Comment by tomatoe45** [comment]
can you elaborate your problem that you encouter? or show screenshot so that many can help you..

**Comment by fherryfherry** [comment]
@tomatoe45 guys, I got it the problem, I'm working on it

**Comment by fherryfherry** [comment]
@jesus2828 hi try to run `php artisan config:clear`

**Comment by tomatoe45** [comment]
wow your so great,. thanks.. fherry

**Comment by jesus2828** [comment]
You are magicians, now I see the tables. Thanks
