### ISSUE TITLE
HELP !!! HOW TO MAKE AJAX FILTER CATEGORY AND SUB-CATEGORY ON CRUDBOOSTER 5.2

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#243]
HI... i need help to make filter ajax on crud laravel 5.2, i don't know what the right answer script and where to put it.

so, when i click one dropdown list like (GANJIL / GENAP), so, the next dropdown will automaticly change as i choose in GANJIL / GENAP.....

**Comment by fherryfherry** [comment]
please provider screenshots, so we can help you easily

**Comment by fherryfherry** [comment]
you need use sub_select, and make sure the select of first input also datatable
