### ISSUE TITLE
Symlink() error

### ISSUE THREAD

**Issue by mohdnazrul** [crocodic-studio/crudbooster#244]
After install require crocodicstudio/crudbooster=5.3.2.* and add crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class inside config. When do the hp artisan crudbooster:install get error message symlink() error.

**Comment by fherryfherry** [comment]
please make sure you have a vendor folder inside of public folder. Or you may create it. Then try crudbooster install again

**Comment by jesus2828** [comment]
Try install require crocodicstudio/crudbooster=5.3.2.7

**Comment by connormcwood** [comment]
Rename Uploads directory within Public and it should recreate it and it will no longer be linked to your previous install.
