### ISSUE TITLE
Problem double date in edit

### ISSUE THREAD

**Issue by hunterbit** [crocodic-studio/crudbooster#245]
Hello to all,
I have problems with the date fields.
In my edit page I have two dates. the first date opens with no problem but when I click on the second date does not open the schedule and if I open the inspector I see that there are right on the second calendar errors.

What's the problem?

![problem-date](https://cloud.githubusercontent.com/assets/3189486/23948094/ca477078-0981-11e7-8057-5b8bd940d44f.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3189486/23948093/ca43e50c-0981-11e7-8e15-e3162f5574c1.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/3189486/23948092/ca43d472-0981-11e7-83e6-99d48aa5b2ba.png)

**Comment by fherryfherry** [comment]
I'm on it

**Comment by hunterbit** [comment]
Problem now is half ok but when I click on calendar icon I view two calendar

![screenshot_5](https://cloud.githubusercontent.com/assets/3189486/23974628/84b20f36-09dc-11e7-8d7f-c53e01a6a431.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/3189486/23974629/84b3293e-09dc-11e7-824e-305c2e52aee0.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/3189486/23974630/84cda6f6-09dc-11e7-9d84-57f6f11e53db.png)

**Comment by hunterbit** [comment]
Also I wanted to ask if there's a method to set the date to null or otherwise empty because the calendar does not give me this opportunity.

Thank you.
