### ISSUE TITLE
how to install on vps server

### ISSUE THREAD

**Issue by suryacaprice** [crocodic-studio/crudbooster#246]
due to few mandatory requirements i ran into problems while hosting the application in vps ... do you have any documentation for the LAMP install guide that is necessary for the crudbooster to work in ubuntu 14.04 vps server with all the requirement listed below and how to install them .. might be very helpful for the newbies like me trying to host the crudbooster based application 

PHP >= 5.6.x
Mcrypt PHP Extension
OpenSSL PHP Extension
Mbstring PHP Extension
Tokenizer PHP Extension
FileInfo PHP Extension
Laravel Version 5.3.x

please provide step by step installation guide to have a fresh start on VPS ... including LAMP installation and php plugin enabling.

**Comment by wa7eedem** [comment]
crudbooster is just a laravle package and there is no special requirement  different from any laravle application .
follow these steps to install full php stack , then you will be able to proceed with laravel installation , then add the crudbooster package .

https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04

I hope this will help you .
