### ISSUE TITLE
Adding a new module... Migration Files

### ISSUE THREAD

**Issue by carloquilala** [crocodic-studio/crudbooster#247]
Do I need to create a new table first before creating a new module that has no relation with existing tables in my database? Or are there any possible way to auto generate new migration files upon creation of new module

**Comment by tomatoe45** [comment]
i think you need to create the table first in order for you to create a module.. since you can't create a module without table correct?

**Comment by fherryfherry** [comment]
@carloquilala CB has no migration creator. So you need to create it by yourself. If you want to add a menu without crud generator you can do by creating a controller yourself, then don't forget to extend the class to CRUDBooster class. At the menu management, you can add any kind of URL also any modules.

**Comment by pvgennip** [comment]
@fherryfherry I installed CB with success locally, the only thing that is not working (a blank page) is page 2 of the add new module wizard. Should this work with any table? What should be filled in the input fields? 

Your demo also has problems in page 3: https://crudbooster.com/demoo/public/admin/module_generator/step3 (Whoops, something went wrong)
