### ISSUE TITLE
SQL QUERY VIEW

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#248]
fherrey.. in previous version of this tool 5.3.1 we are able to see the view.. after update to 5.3.2 we are not able to see the view. is there any conflict with the view?

**Comment by fherryfherry** [comment]
Sorry, i don't understand what is the view that you mean? please screenshot

**Comment by tomatoe45** [comment]
Here..

![qry](https://cloud.githubusercontent.com/assets/17925294/23990406/e6b2be3a-0a70-11e7-9eb4-be7fe64df355.png)


we can't use out view query from database after update.. 

and also

>ErrorException in Style.php line 1326:
A non-numeric value encountered

when trying to export the data using pdf.. i think it was raise already...  i thnk.

**Comment by tomatoe45** [comment]
That "qryinvoice", is a "view" from out db..

**Comment by tomatoe45** [comment]
that export pdf is raise already by @sndpl with this ref [#238](https://github.com/crocodic-studio/crudbooster/issues/238)

**Comment by fherryfherry** [comment]
Hi about the list of tables. You may try set it by creating any module, then open the controller, set the table with your view, also modify the name of controller

**Comment by tomatoe45** [comment]
oh i see.. okay fherry let me try that .. thanks..
