### ISSUE TITLE
It would be possible to see the source code of your "try demo"?

### ISSUE THREAD

**Issue by jesus2828** [crocodic-studio/crudbooster#249]
It would be possible to see the source code of your "try demo"

**Comment by marcosmaia** [comment]
Also wanted so could see some examples ready

**Comment by franciscoluiz** [comment]
+1

I would also like to see the examples.

Could be somewhere else, like
Https://github.com/crocodic-studio/crudbooster-demo/

Then we could follow the evolution of the CB in the demonstration example.

**Comment by tomatoe45** [comment]
well as you can see.. it was demo.. it depends if you have the code for the demo..  and also for the example..  you can also refer to the documentation or check the process from the demo.. check from the statistic builder of from the module..

**Comment by fherryfherry** [comment]
@jesus2828 @marcosmaia @franciscoluiz thanks for your suggestion, I will try to give more sources that can help you more.

Also, don't forget to stay tuned at YT Channel https://www.youtube.com/channel/UCgOJR3khWEykIBBR8vAGtcA

**Comment by marcosmaia** [comment]
Unfortunately a simple documentation. More for a summary

**Comment by technoartista** [comment]
i need the example codes too ... cant find few elements found in demo at documentation
