### ISSUE TITLE
in vps server application not working

### ISSUE THREAD

**Issue by technoartista** [crocodic-studio/crudbooster#250]
when i test it in local everything is working fine ... i moved it to production in ubuntu 14.04 vps then when i open the page this show up ... app not opening
app url : http://vote.artista.tech/

please help

<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/../bootstrap/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);

**Comment by fherryfherry** [comment]
Hi, it is general issue, doesn't CRUDBooster issue,
you need to install LAMP correctly

[Install Lamp On lInux](
https://www.google.com/search?newwindow=1&rlz=1C1CHBF_enID709ID710&espv=2&q=install+lamp+linux&oq=install+lamp+linux&gs_l=serp.3..0l2j0i20k1j0i22i30k1l7.31078.32222.0.32695.7.7.0.0.0.0.368.567.0j1j0j1.2.0....0...1c.1.64.serp..5.2.564.IcviJ73UZy4)

**Comment by technoartista** [comment]
@fherryfherry thank you got it
