### ISSUE TITLE
Active/Unactive

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#251]
Hi there fherry.. how can we create this like from demo..

![active](https://cloud.githubusercontent.com/assets/17925294/24032187/9e3ae2f2-0b21-11e7-8cac-0858dae30cb5.png)

Thanks..

**Comment by fherryfherry** [comment]
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-add-more-action-button.md

**Comment by tomatoe45** [comment]
yes i'm already on it.. thank you fherry..

**Comment by tomatoe45** [comment]
fherry... for this code

> $this->addaction[] = array();

are we going to replace that with this?

>$this->addaction[] = ['label'=>'Set Active','url'=>CRUDBooster::mainpath('set-status/active/[id]'),'icon'=>'fa fa-check','color'=>'success','showIf'=>"[status] == 'pending'"];
>$this->addaction[] = ['label'=>'Set Pending','url'=>CRUDBooster::mainpath('set-status/pending/[id]'),'icon'=>'fa fa-ban','color'=>'warning','showIf'=>"[status] == 'active'"];

?

**Comment by tomatoe45** [comment]
it worked now thanks fherry
