### ISSUE TITLE
Class 'App\Http\Controllers' not found - Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by Clissoff** [crocodic-studio/crudbooster#253]
FatalErrorException in 0a8da276a78d2d56af0e855d5c3d2bbdc1c9772a.php line 3:
Class 'App\Http\Controllers\' not found 

![image](https://cloud.githubusercontent.com/assets/26506197/24073229/db12adda-0c26-11e7-837c-7ed7c5d5d796.png)

**Comment by fherryfherry** [comment]
how the chronology?

**Comment by Clissoff** [comment]
![image](https://cloud.githubusercontent.com/assets/26506197/24074735/f8d8ac38-0c40-11e7-897e-38dbec163116.png)

![image](https://cloud.githubusercontent.com/assets/26506197/24074740/141be802-0c41-11e7-9823-96d52c39b698.png)

**Comment by Clissoff** [comment]
php 5.6.30 laravel 5.3.30

**Comment by Clissoff** [comment]
https://www.youtube.com/watch?v=xPmkAQyVVtI  << I do as he teaches

**Comment by fherryfherry** [comment]
its seems you using `sub_module` also ?

**Comment by Clissoff** [comment]
how??

**Comment by fherryfherry** [comment]
In the future you should post issue with more detail information, like CB
version,  the cronolgy of issue,etc.. More detail information is better
Pada tanggal 25 Mar 2017 23.54, "Clissoff" <notifications@github.com>
menulis:
