### ISSUE TITLE
Table insert/update problem

### ISSUE THREAD

**Issue by salihkiraz** [crocodic-studio/crudbooster#255]
![image](https://cloud.githubusercontent.com/assets/7440402/24081853/be41eb34-0ccc-11e7-8dc3-2656c7bf713d.png)

![image](https://cloud.githubusercontent.com/assets/7440402/24081884/19fc3272-0ccd-11e7-80b4-f466a5d2526f.png)

![image](https://cloud.githubusercontent.com/assets/7440402/24081890/242df762-0ccd-11e7-9092-8b42ac3a3c5e.png)

my solution:

$this->arr=array_filter($this->arr);

```

public function postAddSave() {
....
...
...
...
...
$this->arr=array_filter($this->arr);
DB::table($this->table)->insert($this->arr);
}
```

**Comment by salihkiraz** [comment]
ok.thank you

**Comment by fherryfherry** [comment]
I forget to answer that your fields should be null allowed

**Comment by salihkiraz** [comment]
not null allowed. I did test.
