### ISSUE TITLE
Prevent an item from being sent

### ISSUE THREAD

**Issue by gfrodriguez** [crocodic-studio/crudbooster#260]
I have the following model entity relationship

![mysqlworkbench_2017-03-20_11-27-24](https://cloud.githubusercontent.com/assets/12382314/24110053/767edf84-0d60-11e7-9e3e-c14e4dcd8f49.png)

I need a form with select nested or select dependent, so that it is easy to choose an articulo in the form venta

I have the following controller:

```
$this->form[] = ['label'=>'Cantidad','name'=>'cantidad','type'=>'number','validation'=>'required|min:1|max:255','width'=>'col-sm-10'];
$this->form[] = ['label'=>'Laboratorio','type'=>'select','name'=>'laboratorio_id','width'=>'col-sm-10','datatable'=>'laboratorio,laboratorio'];
$this->form[] = ['label'=>'Presentacion','type'=>'select','name'=>'presentacion_id','datatable'=>'articulo,presentacion_id','width'=>'col-sm-10','parent_select'=>'laboratorio_id'];
$this->form[] = ['label'=>'Artículo','name'=>'articulo_id','type'=>'select','validation'=>'required','width'=>'col-sm-10','datatable'=>'articulo,nombre','parent_select'=>'presentacion_id'];
```
I need not be sent laboratorio_id or presentacion_id.

Somebody help me?

**Comment by esdayehezkiel** [comment]
Unset the laboratorio_id and precentacion_id before add and before edit.
Put this code in hook_before_edit and hook_before_add:

unset($postdata['laboratorio_id']);
unset($postdata['precentacion_id']);

I hope i understand what you need, and my answer can solve your problem.

**Comment by gfrodriguez** [comment]
Thanks you very much!!!
