### ISSUE TITLE
Enable / Add user registration and own user data

### ISSUE THREAD

**Issue by joransrb** [crocodic-studio/crudbooster#261]
Hi,

Im new to Laravel  and CRUDBooster, and got a question.

Can i add or is there a place to enable so that users can register for an account ?
And how do i make it so that when a user enters data in one of the modules, that data belongs only to that users and is not viewable by others.

Sorry if im asking at the wrong place, and if this is not related to crudbooster.

But if anyone could point me in the right direction for adding these features, that would be great.

**Comment by technoartista** [comment]
I have the same doubts too .. I am new to laravel aswell .

**Comment by fherryfherry** [comment]
Hi,
First, unfortunately, CB doesn't provide us a registration form at this time. So you need to create it by yourself. But we still in consider it to include in the future version.
The second question, by the way, it might be confused for you if I write down here. Today, I'm going to publish a new video about this thing. So, please subscribe and enable the notification our youtube channel https://www.youtube.com/channel/UCgOJR3khWEykIBBR8vAGtcA

**Comment by joransrb** [comment]
@fherryfherry ok, thanks for your reply, ill try to write the registration, always up for a challenge. i have already subscribed to the youtube channel, so looking forward to future videos.

**Comment by royhudayana** [comment]
@joransrb have you write your own registeration feature on your CB?
