### ISSUE TITLE
DataModal does not work properly

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#262]
Hi there fherry.. 

i already on the process of child form.. however when i click the item from the datamodal it doesn't appear on the textfield in form

I have this code 
>$columns = [];
			$columns[] = ['label'=>'Product Name','name'=>'product_id','type'=>'datamodal','datamodal_table'=>'products','datamodal_columns'=>'name,product_price','datamodal_select_to'=>'price:product_price', 'required'=>true];
			$columns[] = ['label'=>'Product Price','name'=>'product_price','type'=>'number','readonly'=>true];
			$columns[] = ['label'=>'Quantity','name'=>'quantity','type'=>'number','required'=>true];
			$columns[] = ['label'=>'Sub Total','name'=>'sub_total','type'=>'number','required'=>true,'readonly'=>true,'formula'=>"[product_price] * [quantity]"];
			$this->form[] = ['label'=>'Order Detail','name'=>'order_details','type'=>'child','columns'=>$columns,'table'=>'order_details','foreign_key'=>'order_id'];

I already check this video; https://www.youtube.com/watch?v=xPmkAQyVVtI&t=916s
and this : https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-make-a-child-form.md

but still the same.. any help?

**Comment by fherryfherry** [comment]
Hi, while you click on that item of  datamodal, try to see the console.log, see if any javascript error ?

**Comment by tomatoe45** [comment]
try to check on that.

**Comment by tomatoe45** [comment]
here it shows all my data..
![product name](https://cloud.githubusercontent.com/assets/17925294/24133474/279fa168-0e38-11e7-81a0-4dbd69da7372.png)

.. in this section it doesn't appear in the proname, price. and total

![order_detail](https://cloud.githubusercontent.com/assets/17925294/24133475/2ace6e00-0e38-11e7-8793-6764a397428d.png)

**Comment by fherryfherry** [comment]
Please be careful that your foreign key is not same with the documentation

`id_[tableName]` or `[tableName]_id`

**Comment by tomatoe45** [comment]
![demo](https://cloud.githubusercontent.com/assets/17925294/24149064/7a0ed6f6-0dfe-11e7-88d1-b1d2fdce8e8e.png)

 Same as in the demo.. the product name doesn't appear in the box after click the item from the child form..

**Comment by fherryfherry** [comment]
You've tried from the[ store ](http://crudbooster.com/store/simple-stock-manager)?

**Comment by tomatoe45** [comment]
Yes, it is from store,, the demo.. iv'e just downloaded it to try.. 


![untitled](https://cloud.githubusercontent.com/assets/17925294/24149763/dee53ef6-0e00-11e7-817f-f1c58c12c554.png)


still figuring out what happen. since it was working on the vid..

**Comment by fherryfherry** [comment]
It was very strange because mind is not problem

**Comment by tomatoe45** [comment]
yeah it was.. even though the demo it doesn't appear.,

**Comment by tomatoe45** [comment]
![order](https://cloud.githubusercontent.com/assets/17925294/24176180/6820b69e-0ed5-11e7-8b22-8198de9ad0ff.png)


Here iv'e tried that this morning it still the same.

**Comment by fherryfherry** [comment]
try to download this [v1.1]](https://github.com/crocodic-studio/simple-stock-manager/archive/v1.1.zip)

**Comment by tomatoe45** [comment]
Thank fherry.. and also iv'e notice that when i create a new menu (not from the store) it doesn't appear, when i check the database i was created however it was (null) from parent_id column.. it need to change manually to 0.

**Comment by fherryfherry** [comment]
hmm ok, its seems bug from array_filter

**Comment by tomatoe45** [comment]
![1 1](https://cloud.githubusercontent.com/assets/17925294/24181184/59b482a6-0ef4-11e7-9908-0f1e755bac12.png)
.. here it still the same.. the product name doesn't want to appear..

**Comment by fherryfherry** [comment]
![image](https://cloud.githubusercontent.com/assets/6733315/24181247/6b41039e-0eec-11e7-9528-05c14dd3f2ac.png)
try to inspect in the select button at data modal

**Comment by tomatoe45** [comment]
![modal](https://cloud.githubusercontent.com/assets/17925294/24181341/5f91f63a-0ef5-11e7-9f81-03d4b50cc4a9.png)


the label is null.. i think thats the cause.

**Comment by fherryfherry** [comment]
I'm on it

**Comment by tomatoe45** [comment]
Thanks fherry.

**Comment by fherryfherry** [comment]
hi try to replace browser.blade.php file with this one : 
[browser.blade.php.zip](https://github.com/crocodic-studio/crudbooster/files/860325/browser.blade.php.zip)

`/vendor/crocodicstudio/crudbooster/src/views/default/type_components/datamodal/browser.blade.php`

**Comment by tomatoe45** [comment]
roger that.. let me check

**Comment by tomatoe45** [comment]
hi fherry.. it works now. from the store.. it shows the data.. now i will try in on my project..  Thanks..

**Comment by tomatoe45** [comment]
hi fherry. can you add the features that is the order has been made, the stocks will automatically subtract.

**Comment by fherryfherry** [comment]
You can use MySQL trigger to subtract the product stock
or you can use the hook_after_add in the orders module, and put some query

**Comment by tomatoe45** [comment]
ah okey.. Thanks fherry..

**Comment by tomatoe45** [comment]
hi @fherryfherry .. the project from the store. are you using the laravel 5.4?
