### ISSUE TITLE
Primary Key "id"

### ISSUE THREAD

**Issue by franciscoluiz** [crocodic-studio/crudbooster#264]
Not all use the name "id" ... in my region, for example, it is common to use "cod" or "cd"

The configuration of the primary key could be defined by the user in the .env configuration file.

Something like that:

DB_DATABASE=**your_db_name**
DB_USERNAME=**your_db_user**
DB_PASSWORD=**password**
...
PRIMARY_KEY_NAME=**id**
PRIMARY_KEY_DELIMITER=**_**
PRIMARY_KEY_POS=**start** (or **end**)

**Comment by fherryfherry** [comment]
Hi, it sounds good, but need much of effort to do that. We need to fix the whole. 😃

**Comment by erickhavel** [comment]
Yes, I find this a rather strange assumption to hardcode the naming convention like this.

I also have different primary key names for each table, table1 has table1_id, othertable has othertable_id etc... Guess I'll have to look for another app.
