### ISSUE TITLE
Only CMS_Users show when creating Module via Module Generator 

### ISSUE THREAD

**Issue by connormcwood** [crocodic-studio/crudbooster#266]
Updating Composer and now I cannot use the Module Generator to create Modules from existing tables because it only displays the CMS_Users table. Prior to update each table was listed: Crudbooster.CMS_* however Crudbooster. has been dropped and only CMS_Users is displayed. 

Preexisting Modules which were created before composer was updated do however still display their contents and also allow new entries to be added.

Edit: Reverted to 5.3.2.12. List is working again. (Anything above breaks) Hope this helps.

However reverting back to .12 causes this issue:

> Call to undefined method crocodicstudio\crudbooster\helpers\CRUDBooster::getSortingFilter() (View: /Users/designstation20/Sites/CrudBooster/vendor/crocodicstudio/crudbooster/src/views/default/table.blade.php) (View: /Users/designstation20/Sites/CrudBooster/vendor/crocodicstudio/crudbooster/src/views/default/table.blade.php)

To already existing modules.

**Comment by tomatoe45** [comment]
have you tried to update the CB to latest version?

**Comment by connormcwood** [comment]
As mentioned in the post this error occurred when updating to most up to date CB version. Composer did however update many other components. I retrieved a previous copy so all is well.

**Comment by fherryfherry** [comment]
Hi try to update, and don't forget to run this command : 
`$ php artisan crudbooster:update`

and make sure you do also this command : 
`$ php artisan config:cache`

**Comment by mytrix-technology** [comment]
hi, I have a problem too. There's only table cms_users when creating a new module. I create a new table cms_pages but this is can't up on combobox.
I had try update crudbooster with follow the documentation and still only table cms_users in combobox.
This is a picture: 
![form step 1 module generator](https://cloud.githubusercontent.com/assets/9384806/24231598/2eac3d32-0fb8-11e7-8532-80db6819f427.png)
![new table database](https://cloud.githubusercontent.com/assets/9384806/24231609/3f458400-0fb8-11e7-861f-15f48a4996f3.png).

Can you help me and solve this issued??

**Comment by tomatoe45** [comment]
hi @connormcwood can we see the screen shots of your table name? your table name should not start with "cms_" iv'e tried that.. that is why, your table is not showed up when try to create a module.

**Comment by mytrix-technology** [comment]
oohh OK. it's correct. After I look at the script there is has a script with "cms_" and choose a new table.
Thanks for solution

**Comment by connormcwood** [comment]
@tomatoe45 Issue might be because laravel 5.4.15 has been used. Application works as I reverted back however safest Crudbooster version to use is 5.3.2.11. Cannot give you a screenshot because that save is outdated and the database has changed. I created tables using CMS_ prefix as I was following the data schema already set out, on my current version modules and table loading works.

**Comment by tomatoe45** [comment]
hi @connormcwood  iv'e also tried to use the laravel 5.4.* it doesn't show either if  your table name starts with "cms_" i think it is compatible now with the latest version of laravel as of the requirements of the crudbooster..

**Comment by connormcwood** [comment]
I've added a test table which shows. CMS_users and test table both show however others do not. Should I rename each table and remove CMS_?

**Comment by fherryfherry** [comment]
Avoid to use prefix cms_
Pada tanggal 29 Mar 2017 22.44, "Connor Mcgarty-Wood" <
notifications@github.com> menulis:
