### ISSUE TITLE
Join in form

### ISSUE THREAD

**Issue by gfrodriguez** [crocodic-studio/crudbooster#268]
I need to show name and not id in a form with a select dependent, does anyone know how to do a join in a form as in can it be on the grid?

![mysqlworkbench_2017-03-23_00-26-16](https://cloud.githubusercontent.com/assets/12382314/24233307/5933fda0-0f5f-11e7-893a-e87b1b43fcb6.png)

`$this->form[] = ['label'=>'Laboratorio','name'=>'laboratorio_id','type'=>'select','width'=>'col-sm-10','datatable'=>'laboratorio,nombre'];`
`$this->form[] = ['label'=>'Presentacion','name'=>'presentacion_id','type'=>'select','width'=>'col-sm-10','datatable'=>'articulo,presentacion_id','parent_select'=>'laboratorio_id'];`

![firefox_2017-03-23_00-22-41](https://cloud.githubusercontent.com/assets/12382314/24233225/de4a36a4-0f5e-11e7-9baf-69e40f69a7b7.png)

I need to show nombre in select presentacion and not the id

**Comment by tomatoe45** [comment]
try this.
![capture](https://cloud.githubusercontent.com/assets/17925294/24234869/850148e0-0fd5-11e7-9406-bcb06489d659.PNG)

in module generator>module_name>step_3_form_display>Presentacion_column>option>datatable>name_of_table,column_name (no space)

**Comment by tomatoe45** [comment]
or

>"join"=>"presentacion,nombre",

try..

**Comment by gfrodriguez** [comment]
No, I had already tried. The problem is that I need the articulo to be chosen with a select dependent of  laboratorio and presentacion

`$this->form[] = ['label'=>'Laboratorio','name'=>'laboratorio_id','type'=>'select','width'=>'col-sm-10','datatable'=>'laboratorio,nombre'];`

`$this->form[] = ['label'=>'Presentacion','name'=>'presentacion_id','type'=>'select','width'=>'col-sm-10','datatable'=>'articulo,presentacion_id','parent_select'=>'laboratorio_id'];`

`$this->form[] = ['label'=>'Artículo','name'=>'articulo_id','type'=>'select','validation'=>'required','width'=>'col-sm-10','datatable'=>'articulo,nombre','parent_select'=>'presentacion_id'];`

Thank you!
