### ISSUE TITLE
TABLE NOT SHOWING IN MODULE

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#269]
For those who have table problems:

Don't create a table name start with "cms_" it doesn't show. Iv'e tried it. Use different names other that "cms_". Thanks.

**Comment by franciscoluiz** [comment]
This could also would be set in the settings, as the id... (#264) no?

**Comment by tomatoe45** [comment]
that would be a good idea but i think that's issue in on the laravel since we create the migration in laravel itself.

**Comment by chayankiit** [comment]
![screenshot from 2017-11-15 03 22 54](https://user-images.githubusercontent.com/14080295/32806962-562f433e-c9b4-11e7-9e3a-d39a852d5826.png)


My custom table not show in pgsql database

**Comment by jair921** [comment]
Hi,

For pgsql add to .env DB_SCHEMA (set your schema)

![captura de pantalla de 2018-06-20 11-25-46](https://user-images.githubusercontent.com/7844423/41671639-5a223ba8-747d-11e8-8c6c-d4dcc2b9ef4f.png)

In config/database.php edit schema for get of .env

![captura de pantalla de 2018-06-20 11-26-10](https://user-images.githubusercontent.com/7844423/41671682-749c4a0a-747d-11e8-9b60-4117c45e6b49.png)

In config/crudbooster.php edit MAIN_DB_DATABASE

![captura de pantalla de 2018-06-20 11-26-26](https://user-images.githubusercontent.com/7844423/41671739-998bf9dc-747d-11e8-9a28-bdbdc01528f1.png)

![captura de pantalla de 2018-06-20 11-32-43](https://user-images.githubusercontent.com/7844423/41671795-c6f27cfc-747d-11e8-8dfd-17877f65f2f7.png)

**Comment by punk73** [comment]
> Hi,
> 
> For pgsql add to .env DB_SCHEMA (set your schema)
> 
> ![captura de pantalla de 2018-06-20 11-25-46](https://user-images.githubusercontent.com/7844423/41671639-5a223ba8-747d-11e8-8c6c-d4dcc2b9ef4f.png)
> 
> In config/database.php edit schema for get of .env
> 
> ![captura de pantalla de 2018-06-20 11-26-10](https://user-images.githubusercontent.com/7844423/41671682-749c4a0a-747d-11e8-9b60-4117c45e6b49.png)
> 
> In config/crudbooster.php edit MAIN_DB_DATABASE
> 
> ![captura de pantalla de 2018-06-20 11-26-26](https://user-images.githubusercontent.com/7844423/41671739-998bf9dc-747d-11e8-9a28-bdbdc01528f1.png)
> 
> ![captura de pantalla de 2018-06-20 11-32-43](https://user-images.githubusercontent.com/7844423/41671795-c6f27cfc-747d-11e8-8dfd-17877f65f2f7.png)

for those experience the same problem with sql server. it works for sql server too. just follow the step

**Comment by antoniobaptista** [comment]
I need to work with 2 databases, both MySQL, but I can not see the tables of the second database, I tried everything and there is no more information about it. Please help!

**Comment by tiznull** [comment]
This issue is still happening. I am seeing it now. Hoping to find a fix for everyone. Please let me know how you corrected it.

**Comment by Devamit2016** [comment]
what about column not showing and table fields?

**Comment by homsrieng** [comment]
For step 2 still have problem with column select null, @chayankiit do you have any solution ?
![Screen Shot 2022-02-18 at 3 25 20 PM](https://user-images.githubusercontent.com/12929292/154645684-e0b6489c-3062-42c5-85d6-48e8fabe1400.png)

**Comment by Fredy452** [comment]
I have the same problem I already have my application deployed on heroku using the pqsql database
![image](https://user-images.githubusercontent.com/38510500/176943130-37b1d203-6b7a-45f3-87ef-19a860f265f0.png)
