### ISSUE TITLE
Image display problem

### ISSUE THREAD

**Issue by pappu2017** [crocodic-studio/crudbooster#272]
Your CRUDBooster Sample project cannot showing images. What is the reason?

**Comment by fherryfherry** [comment]
try to remove uploads directory in public directory, then refresh

**Comment by pappu2017** [comment]
Problem solved. Thank you Ferry.

**Comment by aseptilena** [comment]
When I remove uploads directory in public directory, I could not get it works.

**Comment by aseptilena** [comment]
![image](https://user-images.githubusercontent.com/6253788/26976819-b3f6b114-4d4f-11e7-96e9-15c03c2aebb6.png)
I am using newest version for 5.3

**Comment by fherryfherry** [comment]
@aseptilena please use latest 5.4 instead 5.3, and make sure you have 'uploads' symlink directory in /public
if not, please run this following  command : 
`php artisan crudbooster:update`

Remember that actually, CB doesn't use real uploads directory in public dir, instead of saving in storage/..
it's way we need to put symlink uploads directory

**Comment by aseptilena** [comment]
Is the 5.4 compatible with laravel 5.3?

**Comment by aseptilena** [comment]
![image](https://user-images.githubusercontent.com/6253788/26977941-cf57d9fc-4d53-11e7-93b8-eb507f133874.png)
Here are the current condition of the access to the uploaded file.

**Comment by aseptilena** [comment]
-rw-r--rw- 1 www-data www-data 131K Jun  9 20:29 smik-story-5-let-s-go-home-01-by-muslimultimedia.jpg
The file exists.

**Comment by aseptilena** [comment]
![image](https://user-images.githubusercontent.com/6253788/27026207-2966c11c-4f87-11e7-980b-e06c58ed3664.png)

**Comment by abenzakour** [comment]
Good Job; 
Can you help me to make the same thing ? 

` 
rm -rf public/uploads
ln -s storage public/uploads
chown -R penmaru:www-data public/uploads
chmod -R og+rwx public/uploads

`

is that right ?

**Comment by aseptilena** [comment]
Yes, that's right

**Comment by mohammedabdallah** [comment]
@aseptilena  am followed ur instructions and worked fine in my local machine windows environment 
but the problem still exists on the server also  the image don't uploaded

**Comment by mohammedabdallah** [comment]
@fherryfherry  when i delete my upload in public directory gave me symlink permission denied and halt the server 
am using 5.3 version and laravel 5.4 ,server is linux

**Comment by 5lineofcode** [comment]
update your CBController like this.
we also have unique file name.

![image](https://user-images.githubusercontent.com/43805298/55874501-bdee4880-5bbc-11e9-9efa-17e7acee963e.png)

**Comment by idhammubarok** [comment]
@aseptilena  My problem is the same as yours, can I manage it with the GUI?

**Comment by aseptilena** [comment]
I think, it's impossible with GUI, because the problem is on the backend.
