### ISSUE TITLE
checkbox display category

### ISSUE THREAD

**Issue by pappu2017** [crocodic-studio/crudbooster#273]
while adding a product how to show categories in check box for multiple product category selection? can you show me with an example?

**Comment by fherryfherry** [comment]
you need to at `relationship_table` in the form of checkbox

`$this->form[] = ['label'=>'Categories','type'=>'checkbox','datatable'=>'categories,name','name'=>'categories','relationship_table'=>'products_category'];`

**Comment by pappu2017** [comment]
category table
products table
products_category table
relationship table
The above mentioned table structure is correct?
