### ISSUE TITLE
Error on making a Custom Form

### ISSUE THREAD

**Issue by pablo-dave** [crocodic-studio/crudbooster#274]
![custom](https://cloud.githubusercontent.com/assets/24419145/24306645/40218996-108f-11e7-827d-a6e51427266b.jpg)

**Comment by fherryfherry** [comment]
Try to update to the latest version
Pada tanggal 25 Mar 2017 00.42, "pablo-dave" <notifications@github.com>
menulis:

**Comment by pablo-dave** [comment]
thanks fherryfherry, i solved this adding the function cbView in CBController:

public function cbView($template,$data) {
			$this->cbLoader();
			echo view($template,$data);
	}
