### ISSUE TITLE
Issue Adding Child Controller

### ISSUE THREAD

**Issue by mthompson90** [crocodic-studio/crudbooster#275]
I am trying to add a child the same way as the demo. In the demo site, when the type is set to child there is an option to add the child controller.   However, I am getting a different option when I choose child from the parent form settings. (I updated CRUDbooster this morning, no change) 

**Demo Site:** 
<img width="704" alt="screen shot 2017-03-25 at 11 01 53 am" src="https://cloud.githubusercontent.com/assets/26654923/24324822/9c7f199a-114a-11e7-9fbd-a8c511599376.png">

**My Site:**
<img width="641" alt="screen shot 2017-03-25 at 11 01 10 am" src="https://cloud.githubusercontent.com/assets/26654923/24324839/d925662e-114a-11e7-91bd-bf2506ce0067.png">

I would like the child form to function the same was as in the **demo**: 
<img width="968" alt="screen shot 2017-03-25 at 11 05 03 am" src="https://cloud.githubusercontent.com/assets/26654923/24324854/27633064-114b-11e7-896f-40ce7fe7a8f0.png">

So far, this is the only way I could get it to work on **my site**: 
<img width="1000" alt="screen shot 2017-03-25 at 11 05 23 am" src="https://cloud.githubusercontent.com/assets/26654923/24324858/3613a684-114b-11e7-8413-b67fc7e19340.png">
 
Thank you in advance for your help! 
Mike Thompson

**Comment by fherryfherry** [comment]
Child type like the demo is no longer available has been replaced with new
one
Pada tanggal 26 Mar 2017 01.09, "mthompson90" <notifications@github.com>
menulis:
