### ISSUE TITLE
Issue with child type while use column type as 'select'

### ISSUE THREAD

**Issue by technoartista** [crocodic-studio/crudbooster#276]
Hi,

If i use 'select' type in child form. i am getting sql error. 

Check my codeset for child form,
`

			$this->form = [];
			$this->form[] = ['label'=>'Customer','name'=>'customers_id','type'=>'select2','validation'=>'required|integer|min:0','width'=>'col-sm-10','datatable'=>'customers,name','datatable_format'=>'name,\' - \',phone'];
			$this->form[] = ['label'=>'Order Number','name'=>'order_number','type'=>'text','validation'=>'required|min:1|max:255','width'=>'col-sm-10','readonly'=>'1'];

			$columns = [];
			$columns[] = [
				'label'=>'Product',
				'name'=>'products_id',
				'type'=>'datamodal',
				'datamodal_table'=>'products',
				'datamodal_columns'=>'name,sku,brands_id,categories_id,sell_price,stock',
				'datamodal_select_to'=>'name:products_name,sell_price:products_price,sku:products_sku,brands_id:brands_id,categories_id:categories_id',
				'datamodal_size'=>'large',
				'required'=>true
			];
			
			$columns[] = ['label'=>'Product SKU','name'=>'products_sku','type'=>'text','readonly'=>true,'required'=>true];

			$columns[] = ['label'=>'Product Brand','name'=>'brands_id','type'=>'select','readonly'=>false,'required'=>true,"datatable"=>"brands,name"];
			$columns[] = ['label'=>'Product Category','name'=>'categories_id','type'=>'text','readonly'=>true,'required'=>true];

			$columns[] = ['label'=>'Product Price','name'=>'products_price','type'=>'number','readonly'=>true,'required'=>true];
			$columns[] = ['label'=>'Quantity','name'=>'quantity','type'=>'number','required'=>true];
			$columns[] = ['label'=>'Sub Total','name'=>'sub_total','type'=>'number','formula'=>'[products_price] * [quantity]','readonly'=>true,'required'=>true];
			$this->form[] = ['label'=>'Order Detail','name'=>'order_detail','type'=>'child','columns'=>$columns,'width'=>'col-sm-10','table'=>'orders_detail','foreign_key'=>'orders_id'];

			// $this->form[] = ['label'=>'Order Detail','name'=>'order_detail','type'=>'child','width'=>'col-sm-10','table'=>'orders_detail','foreign_key'=>'orders_id'];
			
			$this->form[] = ['label'=>'Total','name'=>'total','type'=>'number','validation'=>'required|integer|min:0','width'=>'col-sm-10','readonly'=>'true'];
			$this->form[] = ['label'=>'Tax','name'=>'tax','type'=>'number','validation'=>'required|integer|min:0','width'=>'col-sm-10'];
			$this->form[] = ['label'=>'Discount','name'=>'discount','type'=>'number','validation'=>'required|integer|min:0','width'=>'col-sm-10'];
			$this->form[] = ['label'=>'Grand Total','name'=>'grand_total','type'=>'number','validation'=>'required|integer|min:0','width'=>'col-sm-10','readonly'=>'1'];
			# END FORM DO NOT REMOVE THIS LINE`

![image](https://cloud.githubusercontent.com/assets/19356598/24325027/08a1d3da-11b7-11e7-8011-78f9df801b0c.png)

My requirement:
1. Need to show Brand Name & Category Name with Product Name in select product popup modal.

![image](https://cloud.githubusercontent.com/assets/19356598/24325113/940d3a58-11b8-11e7-8a35-e87d8fdea460.png)

![image](https://cloud.githubusercontent.com/assets/19356598/24325154/08633d62-11b9-11e7-99c7-ccbb09bdb34a.png)

Note: i have study entire document and "component.blade.php". there is an option to use column type as 'select'

Please help to resolve this asap.

**Comment by princeprasanth** [comment]
Hey, 

I too face some kind of same issue in child type. Couldn't able to debug that issue, 

Let me know any solution for this issue.

**Comment by suryacaprice** [comment]
@franciscoluiz @fherryfherry can you please fix this

**Comment by fherryfherry** [comment]
Unfortunately join in datamodal popup does not support yet
Pada tanggal 31 Mar 2017 16.48, "suryacaprice" <notifications@github.com>
menulis:
