### ISSUE TITLE
How To Translating CB Into Bahasa

### ISSUE THREAD

**Issue by arif-awaludin** [crocodic-studio/crudbooster#278]
Salam
Mas Ferry, actually i don't know the name exacly for "Form Info" which i mean.
But when we use select/select2 in our form its usually appear "***Please select a "blablabla". But unfortunately the App i crete using CB is based on Bahasa. So that, May i change / translate "***Pease  select a"?

best regards

**Comment by fherryfherry** [comment]
What you mean is how to change the whole of language in Bahasa?
If so, you can following these steps :
1. copy `en`  directory in `/resources/lang/en` to `id` directory, so it would be: 
`/resources/lang/id`
2. Open `crudbooster.php` file in it, translate all of the variables into Bahasa
3. Then, set the default locale in `/config/app.php` to "id"

**Comment by arif-awaludin** [comment]
Waw
thanks so much :)

**Comment by arif-awaludin** [comment]
Kang Ferry, i have to tried to change default locale in _/config/app.php_ to "ar" and save it. But the language is still in English. Do i miss some step?

**Comment by fherryfherry** [comment]
as default, the config laravel in CB has been cached, you need to clear the config cache, by running these command : 
`php artisan config:cache`
or
`php artisan config:clear`

**Comment by arif-awaludin** [comment]
awsome  
🥇🥇🥇🥇🥇
