### ISSUE TITLE
Hi, I am Trying to use the API that generates from API Generator but, when i test it show me not found the url

### ISSUE THREAD

**Issue by Ziaullah-Mommand** [crocodic-studio/crudbooster#28]
So how to use the API

**Comment by fherryfherry** [comment]
Basicly the api generator will use POST method , so use POST method when you test the API

**Comment by Ziaullah-Mommand** [comment]
When i use post method I get the TokenMismatchException

**Comment by Ziaullah-Mommand** [comment]
Please anyone help me

**Comment by Ziaullah-Mommand** [comment]
http://crudbooster.com/demo/public/api/list_customer. I also checked this I got the same result.

**Comment by fherryfherry** [comment]
what version crudbooster that you are using now ?

**Comment by mommand** [comment]
The latest version

**Comment by fherryfherry** [comment]
update the latest version 5.2.7

**Comment by mommand** [comment]
How to update I don't know

**Comment by fherryfherry** [comment]
I think you should try start by reinstalling again 
Please follow getting started page , or : 

https://github.com/crocodic-studio/crudbooster

in future, if you want to update, just re compose require again. 
"composer require crocoicstudio/crudbooster"

**Comment by mommand** [comment]
I am new with the crudbooster, I think you are expert

**Comment by fherryfherry** [comment]
No problem sir, just follow the instruction of install
