### ISSUE TITLE
404 Not Found on admin/login

### ISSUE THREAD

**Issue by franciscoluiz** [crocodic-studio/crudbooster#283]
I recently formatted my notebook. And installed the crudbooster from scratch.

The installation and all its steps occurred without errors.

When accessing at http://127.0.0.1/project/public, the laravel page appears.

But when I try to access http://127.0.0.1/project/public/admin/login, appears "401 - Not Found", "The requested URL /project/public/admin was not found on this server."

If the question is too simple... forgive my ignorance.

**Comment by franciscoluiz** [comment]
PHP Version 7.1.3-3 / MariaDB 10.1.21 / Apache 2.4.25 / Mint 18.1-mate / all 64bits.

**Comment by fedeverdi** [comment]
Same issue here ...

**Comment by fedeverdi** [comment]
try to http://127.0.0.1/project/public/index.php/admin

Rewrite problem for me.

**Comment by franciscoluiz** [comment]
worked perfectly. thank you...

how did you solve the problem with -rewrite-?

**Comment by franciscoluiz** [comment]
I found the solution here:
http://www.jarrodoberto.com/articles/2011/11/enabling-mod-rewrite-on-ubuntu

Thank you again @fedeverdi

**Comment by versatilegurung** [comment]
ya found it with permissions of folders around... anyway many thanks guys !

**Comment by akuthedeveloper** [comment]
thanks guys

**Comment by emgg2222** [comment]
thanks a lot guys, I´ve spent a lot of time with this problem. It does work .
