### ISSUE TITLE
CrudBooster allow us to work with Mysql database Views?

### ISSUE THREAD

**Issue by lsmoro** [crocodic-studio/crudbooster#286]
Hi guys,
Is there some way to work with database "View" instead a "Table" from MySQL? 
I'm asking because I need to develop a simple page (just to display data) and these information come from a View in the database. I followed the instructions is this section: How To Make A Custom View Of Index Method, and it works fine with tables, so I tried to set a View instead and got the following error: 
FatalErrorException in DatabaseManager.php line 317:
Call to undefined method Illuminate\Database\MySqlConnection::View()

P.S: I know this is not exactly an issue, but I didn't find a forum to discuss this topic. 
I appreciate if someone can help me.

Thank you, Lorena.

**Comment by lsmoro** [comment]
I discovered how to work with SQL Views in Crudbooster. Just change the following parameter in the file config/database.php. It was true, so I changed to false and everything worked. Thanks.

'strict' => false,

**Comment by joismar** [comment]
I have some problem and this dont work for me 😢
