### ISSUE TITLE
Sorting table not working

### ISSUE THREAD

**Issue by yosie123** [crocodic-studio/crudbooster#289]
To be sure, i made a new fresh install and face this issue where sorting is not working. Can you confirm this?

![sortingnotworking](https://cloud.githubusercontent.com/assets/23457607/24456489/75f7cbea-1493-11e7-8ac3-081f01634208.png)

**Comment by fherryfherry** [comment]
it should working fine, please try with real your module

**Comment by yosie123** [comment]
I tried on different modules, on server, on local pc, on the 2 demo sites, different browsers. Everywhere same issue. Are there othere people expect fherryfherry with this issue?

**Comment by antoniobaptista** [comment]
It's true, it does not work

**Comment by aldrinc7** [comment]
mine does not work too. This issue was closed, is it already fixed? thanks.
