### ISSUE TITLE
readLink() Invalid Argument

### ISSUE THREAD

**Issue by connormcwood** [crocodic-studio/crudbooster#290]
> [ErrorException]              
>   readlink(): Invalid argument                                
> 
>  Script php artisan optimize handling the post-update-cmd event returned with error code 1
> 
> Installation failed, reverting ./composer.json to its original content.

Composer.json

>         "crocodicstudio/crudbooster": "5.3.2.20",
>         "laravel/framework": "5.4.*",
>         "laravel/tinker": "~1.0",
>         "laravelcollective/html": "~5.0"

>     "require-dev": {
>         "fzaninotto/faker": "~1.4",
>         "mockery/mockery": "0.9.*",
>         "phpunit/phpunit": "~5.7"

if crudbooster is set to 5.3.2.19 then this error does not occur.

**Comment by antoniobaptista** [comment]
In the file:
\yourproject\vendor\crocodicstudio\crudbooster\src\CRUDBoosterServiceProvider.php
Replace the two occurrences of the word readlink with the word realpath. That's it!

**Comment by sndpl** [comment]
I had the same problem, I removed the public/vendor/crudbooster directory (because it was a directory instead of symlink). After the `./artisan crudbooster:update` the symlink was created and no errors anymore.

**Comment by shemul** [comment]
I'm also having the same occurrence when I deployed on server. In my local server it works but in my server it return this

http://i.imgur.com/au2jr4b.jpg

**Comment by wa7eedem** [comment]
I had this issue after update to latest version
also when run :  `artisan crudbooster:update` I get 

```
[ErrorException]              
  readlink(): Invalid argument 
```

I did : `sudo chmod -R 777 public/vendor`
and its fixed

**Comment by shemul** [comment]
@wa7eedem it didn't work for me ..
Any solution yet ? I tried realpath instead of readlink but it creates problem with download any file from app url

**Comment by esdayehezkiel** [comment]
I have this error to, help.

**Comment by fherryfherry** [comment]
about permission, there are two factors
first is directory permission must be set 0777 (public/vendor)
second is directory owner/group must be suited with your public access permission

**Comment by shemul** [comment]
I found a way to get ride of it. first replace readlink() with realpath() then try 
`php artisan crudbooster:update`

after successful update , then revert to old readlink()
