### ISSUE TITLE
How i can do this?

### ISSUE THREAD

**Issue by fabiopesaju** [crocodic-studio/crudbooster#292]
what is the better way to do this?

on click, at category combo, will load the subcategory combo...

![a](https://cloud.githubusercontent.com/assets/20627847/24471812/b641562a-1499-11e7-80a7-2bd8b1284c02.png)
![b](https://cloud.githubusercontent.com/assets/20627847/24471814/b9422ca0-1499-11e7-830f-b3b5599e40cc.png)

**Comment by gfrodriguez** [comment]
You could try the following

	$this->form[] = ['label'=>'Category','name'=>'id_category','type'=>'select','width'=>'col-sm-10','datatable'=>'category,maincategory'];
	$this->form[] = ['label'=>'Sub Category','name'=>'id_subcategory','type'=>'select','width'=>'col-sm-10','datatable'=>'subcategory,id','parent_select'=>'id_category'];
	$this->form[] = ['label'=>'Article','name'=>'id','type'=>'text','validation'=>'required','width'=>'col-sm-10'];

In 

	public function hook_before_add(&$postdata) {
				unset($postdata['id_category']);
	    }

**Comment by fabiopesaju** [comment]
Thankyou @gfrodriguez 

i corrected some columns name: 
category.name_maincategory to category.name_category
article.id_subcategoty to article.id_subcategory

well, my code:
			$this->form = [];
			$this->form[] = ['label'=>'Category','name'=>'id_category','type'=>'select','width'=>'col-sm-10','datatable'=>'category,name_category'];
			$this->form[] = ['label'=>'Sub Category','name'=>'id_subcategory','type'=>'select','width'=>'col-sm-10','datatable'=>'subcategory,name_subcat','parent_select'=>'id_category'];
			$this->form[] = ['label'=>'Article','name'=>'id','type'=>'text','validation'=>'required','width'=>'col-sm-9'];

and my data:
![a](https://cloud.githubusercontent.com/assets/20627847/24623086/a755ce56-187d-11e7-9f54-73e08d3941fd.png)

when i select the second item, Category B, the combo loads ok:
![b](https://cloud.githubusercontent.com/assets/20627847/24623390/9ec6ad5e-187e-11e7-8543-c7f5a67f3f78.png)

but when i select the First Item, Category A, not appears on combo:
![b](https://cloud.githubusercontent.com/assets/20627847/24623397/a7e4c7d6-187e-11e7-86bb-0d18e5ab8a48.png)



some tips to me?  thank you

**Comment by fabiopesaju** [comment]
anyone can help me? @fherryfherry ?  

the pattern of the names is correct?

**Comment by fabiopesaju** [comment]
ideas?

**Comment by fherryfherry** [comment]
Try to avoid category id as 0
Pada tanggal 8 Apr 2017 01.50, "fabiopesaju" <notifications@github.com>
menulis:

**Comment by fabiopesaju** [comment]
ok. work...
 but... why?

how to avoid this, if the field is auto-increment, and always starts from zero?

**Comment by fabiopesaju** [comment]
well...

1) why works now? how to avoid this, if the field is auto-increment, and always starts from zero?

2) when i click on form, to edit a record... the combos are not set correctly. what is the procedure to make it work?

3) how do I add information from these two combos in the form?

**Comment by fabiopesaju** [comment]
anyone??? sorry my ignorance.

**Comment by fabiopesaju** [comment]
help???

**Comment by fherryfherry** [comment]
sorry what's your problem exactly ?
`why works now? how to avoid this, if the field is auto-increment, and always starts from zero?`
it should working fine with autoincrement

**Comment by fabiopesaju** [comment]
1) you said to avoid the category id as 0. well, i changed from 0 to 1, and work... why can not use 0 ? 

2) how to make, to do a form for this? when i open a record, the combos are not set correctly. they are empty.

**Comment by fherryfherry** [comment]
I think you should update, and try

**Comment by fherryfherry** [comment]
I've fixed it
but you still can't use 0 as a default combo

**Comment by fabiopesaju** [comment]
well... was a mistake mine... sorry...  

well, and the second doubt? when i open a record, the 2 combos, are not set correcyl

**Comment by fabiopesaju** [comment]
well... about the 0/autocincrment, was a mistake mine... sorry...  

well, and the second doubt? when i open a record, the 2 combos, are not set correctly... the first was loaded, but not in the correct record, and the second combo, are empty

**Comment by fherryfherry** [comment]
It should working fine on the latest version

**Comment by fabiopesaju** [comment]
now appears "column not found: 1054 unknown column 'category_id' in 'field list'... 

I think it's trying to insert the "category_id" column in the "article" table, but it does not have to, there I will only register the id_subcategory...

the combo (select field)  appears only to feed the sub-category combo (another "select field") ... 
 
how to solve... ?
