### ISSUE TITLE
seems bit slow

### ISSUE THREAD

**Issue by shemul** [crocodic-studio/crudbooster#293]
I deployed fresh crudbooster [ with some module added ] in my digital ocean server which  running php 7.0 and mysql 5.7. I feel a lot slower performance.
anyone noticed?

**Comment by yosie123** [comment]
**System Requirement**

-     LARAVEL 5.3.x or higher
-     PHP >= 5.6.x (you are running php 7.0)
-     Mcrypt PHP Extension
-     OpenSSL PHP Extension
-     Mbstring PHP Extension
-     Tokenizer PHP Extension
-     FileInfo PHP Extension

If your setup meet the system requirements then i think you should be alright.
I have no performance problems on local device or servers.

**Comment by franciscoluiz** [comment]
@shemul how many cores? ghz? ram? debian/ubuntu/centos? ssd? hd?

**Comment by shemul** [comment]
Okay , It may happened for first time load into a fresh deployment. It may require to gather caches of its resource. It looks my project faster than previous. 

thanks
