### ISSUE TITLE
Need laravel query

### ISSUE THREAD

**Issue by pappu2017** [crocodic-studio/crudbooster#294]
My categories and subcategories data are in one table named categories 
![table](https://cloud.githubusercontent.com/assets/26432541/24499966/3a82741a-1561-11e7-89ae-0b24a63ed8cc.jpg)
need query to retrieve the main category?
need query to retrieve the subcategories of corresponding category?

**Comment by yosie123** [comment]
something like:
`DB::table('categories')->where('parent_categories_id', '0')->get()` shows Category A, B and C
`DB::table('categories')->where('parent_categories_id', '1')->get()` shows Subcategory A.1, A.2 and 1.3

there is more detailed information on laravel query. [https://laravel.com/docs/5.4/queries](https://laravel.com/docs/5.4/queries)
