### ISSUE TITLE
Weired problem with SQLSTATE[42000]

### ISSUE THREAD

**Issue by shemul** [crocodic-studio/crudbooster#297]
I didn't change any config so far , even I replaced my old fresh backup , still the error when I want to add new data to a module. And there is no option available in 'generate new module' where it should show table list

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') as max FROM contracts' at line 1 (SQL: SELECT MAX() as max FROM contracts)`

Crudbooster latest 5.3.2
Laravel 5.4

**Comment by fherryfherry** [comment]
php artisan config:clear
Pada tanggal 31 Mar 2017 04.37, "Shemul Hossain" <notifications@github.com>
menulis:

**Comment by shemul** [comment]
I did it and config:clear too. but it was still there. Had to rollback previous backup

**Comment by tomatoe45** [comment]
its your query structure.. would you mind posting your screenshot of your query/structure? so we can figure out.

**Comment by neerajsinghsonu** [comment]
I am facing same error while using maridb as mysqldropins, php 7 in save action. Its says sql violation in query on linux server, using latest laravel with latest CB. Its all working fine on windows with mysql pdo. But breaking on Mysql Pdo as mariadb. Its working on server while editing but not for inser or save action.

**Comment by fherryfherry** [comment]
try to update
