### ISSUE TITLE
multi-select functionality 

### ISSUE THREAD

**Issue by azarzaza** [crocodic-studio/crudbooster#298]
Does the form input have multi-select functionality

**Comment by fherryfherry** [comment]
Ofcourse, but only available if you use it for many to many relationship
so you need to add key 'relationship_table'

**Comment by azarzaza** [comment]
Does curdbooster have feature for generate tables like laraadmin

**Comment by fherryfherry** [comment]
No, you need to use migration
Pada tanggal 31 Mar 2017 21.27, "azarzaza" <notifications@github.com>
menulis:

> Does curdbooster have feature for generate tables like laraadmin
>

**Comment by azarzaza** [comment]
In future any update there because I like your package and code style

**Comment by azarzaza** [comment]
how to implement multi-select functionality.please help me with this
