### ISSUE TITLE
Problem with sub domain

### ISSUE THREAD

**Issue by ninthz** [crocodic-studio/crudbooster#299]
i did sub domain in laravel and include crudbooster

but when i call http://www.crudbooster.local/admin/login

i got error like this :

`file_put_contents(/var/www/crudbooster/storage/framework/cache/data/35/93/35934fa0f35283d503b87c7e355072e3a314ca45): failed to open stream: No such file or directory (View: /var/www/crudbooster/vendor/crocodicstudio/crudbooster/src/views/login.blade.php)`

Could you have some suggestion for me?

**Comment by yosie123** [comment]
try http://www.crudbooster.local/public/admin
