### ISSUE TITLE
Primary Key

### ISSUE THREAD

**Issue by endytc** [crocodic-studio/crudbooster#3]
Primary keynya yang menggunakan kode (varchar) belum bisa dihandle. sementara harus menggunakan  kolom id.
btw terimakasih buat aplikasinya. :dancers:

**Comment by rikiarofiq** [comment]
iya memang untuk saat ini crudbooster menggunakan field id sebagai primary key, bila anda memang mau menggukan karakter tertentu, anda bisa membuat field lagi untuk menampungnya
