### ISSUE TITLE
Error during admin login: Route [NotificationsControllerGetLatestJson] not defined

### ISSUE THREAD

**Issue by dameety** [crocodic-studio/crudbooster#300]
`Route [NotificationsControllerGetLatestJson] not defined. (View: /srv/users/serverpilot/apps/stablenaija/vendor/crocodicstudio/crudbooster/src/views/admin_template_plugins.blade.php) (View: /srv/users/serverpilot/apps/stablenaija/vendor/crocodicstudio/crudbooster/src/views/admin_template_plugins.blade.php) (View:  #/srv/users/serverpilot/apps/stablenaija/vendor/crocodicstudio/crudbooster/src/views/admin_template_plugins.blade.php)`

I get this error during admin login after uploading it to live server. It works fine on local server but it does not on production. I am using a windows dev machine and ubuntu live server. Thanks. #

**Comment by fherryfherry** [comment]
you must check on the database, especially at cms_moduls table, filled with data or empty ?
