### ISSUE TITLE
The x- authorization- token field is required

### ISSUE THREAD

**Issue by yosantos** [crocodic-studio/crudbooster#301]
Hello,

I'm new to laravel and api,
I've created API using crudbooster, but Unfortunately i got error "The x- authorization- token field is required" when test the api using POSTMAN.
Could you guys help me ?

**Comment by fherryfherry** [comment]
By the way, Please "be careful" you need to learn more about laravel. And remember CRUDBooster is a small part of Laravel Framework.

The Answer, you need to generate the key for first at the API Page. And in the Documentation API Page you will get how to put the token.

**Comment by iMokhles** [comment]
and for developments set API debug to YES/TRUE to test your API without authorization key
don't forget to disable it for the production version

**Comment by charles-tainui** [comment]
hello,
may i re-open to ask @yosantos for precision about how he succeeded in providing the token from POSTMAN ?
thanks a lot
