### ISSUE TITLE
crudbooster relation_ship table 

### ISSUE THREAD

**Issue by pappu2017** [crocodic-studio/crudbooster#302]
Does crudbooster form input have multi-select functionality? can you show with the help of relationship_table example?

**Comment by fherryfherry** [comment]
![image](https://cloud.githubusercontent.com/assets/6733315/24620863/8f87b496-18c9-11e7-80b1-cbe4d8913ba3.png)
For sample you can download crudbooster sample at the store

for short answer, just add relationship_table attribute at the form scaffolding with your relation ship table
