### ISSUE TITLE
"Where" condition to module table

### ISSUE THREAD

**Issue by AndresOchoaS** [crocodic-studio/crudbooster#304]
Hi, everyone,

I want add a condition to module for table data display.

```sql
SELECT * FROM User WHERE status != -1
```

How I should proceed?

**Comment by fherryfherry** [comment]
you can do that by using the hook_query_index method, 
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-put-custom-condition-grid-data.md
