### ISSUE TITLE
Need query and code to display the table details in the below menulist

### ISSUE THREAD

**Issue by pappu2017** [crocodic-studio/crudbooster#307]
![sa](https://cloud.githubusercontent.com/assets/26432541/24642141/c8e2f36e-1922-11e7-8b95-2e644d77b9b8.jpg)
![samp](https://cloud.githubusercontent.com/assets/26432541/24642143/c8e63916-1922-11e7-8e90-0216f00ecfc9.jpg)
![sampled1](https://cloud.githubusercontent.com/assets/26432541/24642142/c8e3299c-1922-11e7-87bb-9ca73aee0586.jpg)
![sampled](https://cloud.githubusercontent.com/assets/26432541/24642153/d7918088-1922-11e7-8c3e-4d2aabf4115a.jpg)

**Comment by fherryfherry** [comment]
You can find out at the google, front end is out of crudbooster area, it was general question
