### ISSUE TITLE
How to add default value on text field?

### ISSUE THREAD

**Issue by davodavodavo3** [crocodic-studio/crudbooster#308]
How to add default value on text field?

**Comment by wa7eedem** [comment]
edit the controller by adding 
`'value'             => 'dVal',`

to 

`$this->form[]`

**Comment by davodavodavo3** [comment]
Hmmm. And every time when i update the module i have to manuali put that value?

**Comment by davodavodavo3** [comment]
And there is an error in PrivilegesController.php on getDelete method
deleteE(); instead of delete();
