### ISSUE TITLE
How to validate field type is float

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#311]
I have a field type in float [ eg. 443.56 ]
In the controller, i use 'type'=>'number' but I am not sure how to put in 'validation'.
So I do not put any validation.
When I click save, I always got the popup tooltip something like 'Please select a valid value. The two nearest valid values are 443 and 444'

**Comment by fherryfherry** [comment]
you could use text types, and fill the validation rule in the validation attribute

**Comment by limbiz** [comment]
I saw this issue was fixed in v5.3.2.22
Can you give an example of code how to deal with it?

**Comment by fherryfherry** [comment]
add attribute step like a html5 input type number with step

**Comment by limbiz** [comment]
Yes, wow!
$this->form[]=['label'=>'Length(Km)','name'=>'length','type'=>'number','validation'=>'min:0','step'=>'any'
,'width'=>'col-sm-10'];
