### ISSUE TITLE
Graded selected Province->District->Commune->Village

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#312]
My table structure are:
Province[id, pro_name], District[id, pro_id, dis_name], Commune[id, dis_id, com_name], 
Village[id, com_id, vil_name].
Problems:
- When i go to module Commune and click edit, Province and District dropdown not show data.
- When i go to module Commune and View, Province name not show.
- How to create module for Village? show Province name, District name, Commune name in the index list.
- And also how to deal with Edit and View for Village?

**Comment by fherryfherry** [comment]
first, please rename your relationship field with the correct format 
example : 
province_id instead pro_id
district_id instead dis_id

**Comment by limbiz** [comment]
i have change my structure to province[id, province_name], district[id, province_id, district_name], commune[id, district_id, commune_name], village[id, commune_id, village_name].
For crud of province and district, it works find.
But for commune, i want to show all province and district in table list as well as edit.
And also for village, i want to show all province, district and commune in table list as well as edit.
Any example code for that?
