### ISSUE TITLE
Change confirm message of Bulk Actions

### ISSUE THREAD

**Issue by sndpl** [crocodic-studio/crudbooster#314]
When I create a new bulk actions like:

`$this->button_selected[] = ['label'=>'Change status to Sold','icon'=>'fa fa-money','name'=>'changeToSoldStatus'];`

The action is shown in the bulk actions dropdown, but the confirm message is: 

> Are you sure want to delete all selected data ?

When I look in the crocodicstudio/crudbooster/src/views/default/table.blade.php I see it always uses the translation of the delete (`if(confirm("{{trans("crudbooster.alert_delete_selected")}}"))`

What would be the best way to change this?

**Comment by fherryfherry** [comment]
please update
