### ISSUE TITLE
Request::fullUrl()?

### ISSUE THREAD

**Issue by davodavodavo3** [crocodic-studio/crudbooster#315]
Why in action.blage.php url return  return_url=".urlencode(Request::fullUrl()

Example: 

```
@if(CRUDBooster::isRead() && $button_detail)         		
        	<a class='btn btn-xs btn-primary' title='{{trans("crudbooster.action_detail_data")}}' href='{{CRUDBooster::mainpath("detail/$row->id")."?return_url=".urlencode(Request::fullUrl())}}'><i class='fa fa-eye'></i> {{trans("crudbooster.action_detail_data")}}</a> 
        @endif
```

**Comment by davodavodavo3** [comment]
All works without that ugly rows in url of page
Simple url 
http://demo/admin/plans/detail/1?return_url=http%3A%2F%2Fdemo%2Fadmin%2Fplans

**Comment by yosie123** [comment]
I agree with you. 
When you go and view a detail this return_url parameter is not needed. When you are on the edit page, I think it's usefull for the form or any custom return path.
