### ISSUE TITLE
Form Display Type is Select2

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#321]
In form display type, if i use Select2, so that in the form i need to key in something in order to show data.
Is that any solution to show those data so that the user can select. And the user still can key in to search data.

**Comment by fherryfherry** [comment]
You may try dataenum attribute
e.g : 
"dataenum"=>"a|Android;b|Ios;c|Website"

**Comment by limbiz** [comment]
But I need to get data from another table.
