### ISSUE TITLE
cms_users got problem in CRUD after Adding new field and add the field in the cms_users controller

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#323]
pardon... i want ask, i make new field in cms_users using migration with name "username" after i php artisan migrte:refresh its running normal. the field username is in, but after i get into the CRUD GUI i  got problem for adding new users and list users..

![image](https://cloud.githubusercontent.com/assets/24912478/24796044/a4a543b8-1bb5-11e7-85b8-1983364f3fe2.png)

and i got notify after i click save

![image](https://cloud.githubusercontent.com/assets/24912478/24796084/ca698ae6-1bb5-11e7-9059-53f44502b573.png)

after i check the cms_privilages that i make before using seeder for 3 level that is Super admin, admin and member didn't show in tha form

![image](https://cloud.githubusercontent.com/assets/24912478/24796122/f8d6071a-1bb5-11e7-884e-af7ac9274971.png)

versi seeder

![image](https://cloud.githubusercontent.com/assets/24912478/24796147/0bf8eaf6-1bb6-11e7-9b83-6d4165fb32df.png)

and when i click list users i got notify

![image](https://cloud.githubusercontent.com/assets/24912478/24796185/2db5c218-1bb6-11e7-9a7e-54ccfbe8f4c4.png)

and in the database too

![image](https://cloud.githubusercontent.com/assets/24912478/24796206/44483358-1bb6-11e7-8edf-0231b1404050.png)

cms_users_controller

![Uploading image.png…]()

please help....

**Comment by yosie123** [comment]
I might help you if it was in English.

**Comment by AdnanSyarief** [comment]
done....

**Comment by jdredondo** [comment]
I have the same error, this issue occurs every time the user module is updated!

**Comment by fherryfherry** [comment]
@AdnanSyarief I saw you didn't set the privilege before click save button ?

**Comment by AdnanSyarief** [comment]
yeah.. i already solved it.. thankk you

**Comment by AdnanSyarief** [comment]
i opened module controller and set privilages for superadmin, admin, and member
also for division by zero solving by open again module generator cms_users and in the end (step-4) i set limit data to 20
