### ISSUE TITLE
How to edit privilages "User Management" from Superadmin and Admin using Seeder or GUI ?

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#324]
NEED HELP !!
i make 3 level users that is Superadmin, Admin, and Member... but the center is the Admin. i want make privilages role User Management not just Superadmin but admin too that can manage it...

![image](https://cloud.githubusercontent.com/assets/24912478/24810565/e67d63c4-1bec-11e7-9ab2-b29c86383761.png)

**Comment by fherryfherry** [comment]
how about creating a same module in module generator ?

**Comment by AdnanSyarief** [comment]
is that save for make same module ? how about the controller ? must same too ?
