### ISSUE TITLE
Perform join on SQL Query Line Statistic

### ISSUE THREAD

**Issue by ergxpr0xy** [crocodic-studio/crudbooster#327]
could you please point me out how to perform join on statistic's SQL query line? i need to show `name` from `categoris` instead of `category_id` from `posts`

i have done normal `inner join` but it's just not working

thank you in advance

**Comment by fherryfherry** [comment]
What type of widget do you use?
Pada tanggal 8 Apr 2017 16.02, "ergxpr0xy" <notifications@github.com>
menulis:

**Comment by ergxpr0xy** [comment]
panel area

**Comment by ergxpr0xy** [comment]
panel area
