### ISSUE TITLE
Menu Management  error

### ISSUE THREAD

**Issue by davodavodavo3** [crocodic-studio/crudbooster#328]
JS error:
An invalid form control with name='module_slug' is not focusable.

**Comment by fherryfherry** [comment]
100% can't create a menu or, with any condition ?

**Comment by davodavodavo3** [comment]
# Reproduce
Select URL type of menu then try to save it

**Comment by davodavodavo3** [comment]
you will see in console logs and error

**Comment by shemul** [comment]
this is what happening http://i.imgur.com/xYfdyiV.jpg @fherryfherry

**Comment by fherryfherry** [comment]
just paste your image to this comment area @shemul

**Comment by fherryfherry** [comment]
I got it, and fixed on my last commit

**Comment by shemul** [comment]
thank you. Just a quick question. How to apply this update to my project ? I did php artisan crudbooster:update but still the error
