### ISSUE TITLE
Module Generation in Step3 error with Select2 When go back to update

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#329]
In step 3, When i change my select to select2 and also change datatable with [tablename, fieldname] and then go next. Yes everything work find in Add and Edit interface.
But there is an error when i go back to update in step 3 of module.
![screenshot-localhost 8000 2017-04-10 09-57-07](https://cloud.githubusercontent.com/assets/26919884/24844472/ff5c4f24-1dd4-11e7-92d1-bc0cd7297205.png)

**Comment by fherryfherry** [comment]
Please open its controller file and screenshot the form scaffolding

**Comment by limbiz** [comment]
![controller](https://cloud.githubusercontent.com/assets/26919884/24844646/83479b12-1dd6-11e7-9957-af8fb180b070.png)

**Comment by davodavodavo3** [comment]
I have that issue too.Fortunately I'm testing for now and i delete that module and create new)))))

**Comment by limbiz** [comment]
Yes, updated already.

**Comment by picaso133** [comment]
The same problem after last update. :)

**Comment by gudomau** [comment]
Same thing here:

<img src="http://i.imgur.com/a1KE31T.png"/>
