### ISSUE TITLE
How to put defualt value of Select and Select2 to zero(0)

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#330]
How to put the zero value(0) to the first row [**Please select a xxxxxxxxx].
![screenshot-localhost 8000 2017-04-10 10-09-49](https://cloud.githubusercontent.com/assets/26919884/24844773/4c7481bc-1dd7-11e7-8bfc-3d794c6e0d49.png)
When this field is not required, so that it will post empty sting to database and then it would raise the error 
since the field is integer.

**Comment by fherryfherry** [comment]
for quick solution, you can use hook before add, and override the postdata
```
if($postdata['road_type_id']=='') {
$postdata['road_type_id'] = 0;
}
```

**Comment by limbiz** [comment]
Yes, it works now! Thanks.

**Comment by limbiz** [comment]
Is there any option or method to overide value of the first selected row[**Please select....] to 0 or -1?
