### ISSUE TITLE
How to reload data into Select or Select2 in Edit mode?

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#336]
I have a graded select box as Province->District->Commune->Village
$this->form[] = ['label'=>'Province','name'=>'province_id','type'=>'select','validation'=>'required'
,'width'=>'col-sm-10','datatable'=>'province,province_name'];
$this->form[] = ['label'=>'District','name'=>'district_id','type'=>'select','validation'=>'integer|min:0'
,'width'=>'col-sm-10','datatable'=>'district,district_name','parent_select'=>'province_id'];
$this->form[] = ['label'=>'Commune','name'=>'commune_id','type'=>'select','validation'=>'integer|min:0'
,'width'=>'col-sm-10','datatable'=>'commune,commune_name','parent_select'=>'district_id'];
$this->form[] = ['label'=>'Village','name'=>'village_id','type'=>'select','validation'=>'integer|min:0'
,'width'=>'col-sm-10','datatable'=>'village,village_name','parent_select'=>'commune_id'];

Province is required, but other no need.
Everything fine in Add mode since it loads data very nice when select Province, District and Commune.
But the problem is when user save only Province, in Edit mode, the District not have any data inside.
This is because it loads data only when the user select Province. 
So how to reload data into District with the existed data in Province?
And the same as Commune and Village?

**Comment by fherryfherry** [comment]
please screenshot the error

**Comment by limbiz** [comment]
There is no data in District. But If I re-select(change Province value) the Province, then the data will load into District as normal.
![no_data_in_district](https://cloud.githubusercontent.com/assets/26919884/24891131/01adc7ac-1e9e-11e7-9b1f-25a12675f4d6.png)

**Comment by fherryfherry** [comment]
in your current table need to add those all fields

**Comment by limbiz** [comment]
Yes, I have updated my table style in order list data when user select accordingly.
![province_district_commune_village](https://cloud.githubusercontent.com/assets/26919884/24891424/eb896d30-1e9f-11e7-9bcc-7f9c2964dc94.png)

My question is how to reload data of District or trigger data of District when there is an existing data in Province.

**Comment by fherryfherry** [comment]
I got your issue

**Comment by limbiz** [comment]
This problem happened only when I save only Province.
If I save Province and District, then the Commune select box is loaded as normal.
