### ISSUE TITLE
How to add custom filter with Select or Select2

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#337]
Any solution on how to add a select box before search box?
For example I want user to select a province name from select box.

**Comment by yosie123** [comment]
this might help: https://github.com/crocodic-studio/crudbooster/issues/273

**Comment by limbiz** [comment]
Here is what i want:
![add_more_search_filter](https://cloud.githubusercontent.com/assets/26919884/24940583/2bd086d4-1f6e-11e7-9f8c-1c42c1ea3ee9.png)

**Comment by idFourteen** [comment]
does anyone did this thing too ? please help

**Comment by vicheanath** [comment]
you can create your own custom index view https://github.com/crocodic-studio/crudbooster/blob/v5.6/docs/en/how-to-custom-index.md
