### ISSUE TITLE
After turning button_bulk_action to false, there is no gap between

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#338]
By turning $this->button_bulk_action = true;
I found something that make interface not good.
![no_gap](https://cloud.githubusercontent.com/assets/26919884/24892748/129ef4a4-1ea9-11e7-8570-f24640c73795.png)

**Comment by yosie123** [comment]
I can confirm this. It's a CSS issue.

I checked the code line:
https://github.com/crocodic-studio/crudbooster/blob/master/src/views/default/index.blade.php#L73
Fixed the issue by changing the code to:
`style="position:relative;"`

Maybe @fherryfherry can update this.
