### ISSUE TITLE
laravel 5.3

### ISSUE THREAD

**Issue by osmosiz** [crocodic-studio/crudbooster#34]
not compatible with laravel 5.3, could you please update?thank you.

**Comment by harimayco** [comment]
+1 :+1:

**Comment by qcol** [comment]
+1

**Comment by mohammedibrahim** [comment]
+1

**Comment by fherryfherry** [comment]
Thank you for your appreciate about CRUDBooster, your request will be considered in the future of CRUDBooster version.
By the way, Before the version 5.3 laravel developed, I hope you really understand and can use CRUDBooster well at this 5.2 version laravel
