### ISSUE TITLE
Add New Table

### ISSUE THREAD

**Issue by rameezte** [crocodic-studio/crudbooster#340]
i can not add new table after users table. how can i do so. please tell me. thanks.

**Comment by yosie123** [comment]
What steps do you follow? What are the error messages?

**Comment by rameezte** [comment]
how should i add new table? is it anyway possible without adding table manually in my database ??

**Comment by yosie123** [comment]
So far I know, this is something you have to do manually. Here is good method with laravel https://laravel.com/docs/5.4/migrations

**Comment by rameezte** [comment]
okay thanks.

**Comment by Muhanna02** [comment]
to add new table in laravel : 
`php artisan make:migration create_table --create=table `
then you can edit some columns by edit the file in database/migrations    save the file
then 
`php artisan migrate `
