### ISSUE TITLE
CB doesn't work with laravel 5.4 and php 7

### ISSUE THREAD

**Issue by tabakocl** [crocodic-studio/crudbooster#342]
Hi,

I am trying to run CB but not have any lucky. In the process of installation following the intro intructions, all run fine but the system isn't work.

for example there is no routes added in the web.php file so, i am unable to view the admin/login.
Also, there is nothing in /public folder.

Please can you help me? i really want to try this!

Thanks in advance...

**Comment by fherryfherry** [comment]
Make sure you have enable rewrite engine on your apache server
Pada tanggal 11 Apr 2017 21.36, "tabakocl" <notifications@github.com>
menulis:

**Comment by tabakocl** [comment]
you right!! all good now!

thanks a lot! love CB!!
