### ISSUE TITLE
How to update to latest CRUD

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#344]
i just install new Laravel and my version is 5.3.1.* i read that there is latest update to 5.3.2.*. but when in try it my latest update is .11

![image](https://cloud.githubusercontent.com/assets/24912478/24921107/e8a7577a-1f13-11e7-9e00-92fb521f679a.png)

**Comment by jdredondo** [comment]
See
http://crudbooster.com/doc/5.3/upgrade-guide

**Comment by fherryfherry** [comment]
what command do you use ?
