### ISSUE TITLE
Problem googlemaps form type: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by marseca** [crocodic-studio/crudbooster#345]
Hi!
I try to select a latitude, longitude and andress using the googlemaps type:
`$this->form[] = ["label"=>"Map","name"=>"map","latitude"=>"latitude","longitude"=>"longitude","address"=>"address","type"=>"googlemaps"];`

I fill the KEY API for Google Maps in the menu "Settings -> Application Settings" with a correct key.

Does anyone use this input type?

**Comment by jdredondo** [comment]
try
`$this->form[] = ['label'=>'Address','name'=>'address','type'=>'googlemaps'];`

See
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/form-googlemaps.md

**Comment by marseca** [comment]
Nope, it doesn´t work.

Now I get new errors and css is not working:

> 2?return_url=http%3A%2F%2Flaravel.peregrinolebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&paren…:1 GET http://laravel.peregrinolebaniegodigital.com/admin/information/edit/2?retur…ebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&parent_id=&parent_field= 500 (Internal Server Error)
> lfm.js:22 Uncaught ReferenceError: jQuery is not defined
>     at lfm.js:22
> (anonymous) @ lfm.js:22
> summernote.js:431 Uncaught TypeError: Cannot read property 'fn' of undefined
>     at summernote.js:431
>     at summernote.js:21
>     at summernote.js:23
> (anonymous) @ summernote.js:431
> (anonymous) @ summernote.js:21
> (anonymous) @ summernote.js:23
> select2.full.min.js:1 Uncaught ReferenceError: jQuery is not defined
>     at select2.full.min.js:1
>     at select2.full.min.js:1
> (anonymous) @ select2.full.min.js:1
> (anonymous) @ select2.full.min.js:1
> 2?return_url=http%3A%2F%2Flaravel.peregrinolebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&paren…:100 Uncaught ReferenceError: $ is not defined
>     at 2?return_url=http%3A%2F%2Flaravel.peregrinolebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&paren…:100
> (anonymous) @ 2?return_url=http%3A%2F%2Flaravel.peregrinolebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&paren…:100
> 2?return_url=http%3A%2F%2Flaravel.peregrinolebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&paren…:112 Uncaught ReferenceError: $ is not defined
>     at 2?return_url=http%3A%2F%2Flaravel.peregrinolebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&paren…:112
> (anonymous) @ 2?return_url=http%3A%2F%2Flaravel.peregrinolebaniegodigital.com%2Fadmin%2Finformation%3Fm%3D5&paren…:112
![captura de pantalla 2017-04-11 a las 20 34 58](https://cloud.githubusercontent.com/assets/6795828/24924820/6db632ec-1ef6-11e7-84f5-570fd06bdc88.png)

**Comment by fherryfherry** [comment]
please make sure your API KEY is correct

**Comment by marseca** [comment]
I am sure that my API KEY is correct. I created this API KEY on Google API Console Developer. I enabled the Google Maps Javascript API and created it without restrictions. 
I check that it works in this jsfiddle:
https://jsfiddle.net/user2314737/7cfpxpf7/
