### ISSUE TITLE
how to create new table for the new module using module generator?

### ISSUE THREAD

**Issue by asimshazad** [crocodic-studio/crudbooster#346]
When i am trying to generate new module,i get cms_users table in dropdown!How can i assign a new table for the module?

**Comment by andersondeoliveiramachado** [comment]
You should create a table first to a table using migration or else via another way. In mysql you can use the command line or phpmyadmin for example.

**Comment by asimshazad** [comment]
Yes,i have other table in my database,but when i create new module it does't show up at all.i am using laravel5.4 and php7

**Comment by franciscoluiz** [comment]
exactly. the module generator does not create the tables in your db.

de onde tu é, @andersondeoliveiramachado ?

**Comment by andersondeoliveiramachado** [comment]
Sou do Rio de Janeiro.

**Comment by azarzaza** [comment]
is there any way to create table via module generated ?
bcoz i was working other crud things they have create table when creating modules
 do have any future plan for this ?
