### ISSUE TITLE
Step 2 of creating new model 

### ISSUE THREAD

**Issue by Muhanna02** [crocodic-studio/crudbooster#347]
I'm facing an issue with creating new model after I did migration then go to admin to create new model after i pressed step 3 it crashing !!

<img width="1052" alt="screen shot 2017-04-12 at 12 32 17 am" src="https://cloud.githubusercontent.com/assets/19315628/24931888/b91d7cb0-1f17-11e7-99aa-ac695d1995cd.png">

ErrorException in helpers.php line 532:
htmlspecialchars() expects parameter 1 to be string, object given (View: /Applications/MAMP/htdocs/booster2/vendor/crocodicstudio/crudbooster/src/views/module_generator/step3.blade.php)

!!

**Comment by fherryfherry** [comment]
Make sure to click watch this github and you will get update notify,

Please update yours
Pada tanggal 12 Apr 2017 04.36, "Muhanna02" <notifications@github.com>
menulis:
