### ISSUE TITLE
[ASK] what is better. using "foreign" or using "join" ?

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#348]
I have many table migration and each table are relating . what is better for relating each table ?
using foreign key in migration table or using join and datatable in controller ?

example  for foreign key
$table->integer('id_semester', false, true)->length(2);
$table->foreign('id_semester')->references('id')->on('semesters'); 

example for join
$this->col[] = ["label"=>"Semester","name"=>"id_semester","join"=>"semesters,semester"];
$this->form[] = ['label'=>'Semester','name'=>'id_semester','type'=>'select','validation'=>'required','width'=>'col-sm-10','datatable'=>'semesters,semester'];

**Comment by fherryfherry** [comment]
foreign and join are a different case. If you create a foreign in your table structure, it does not make auto-join on the CRUDBooster view.
