### ISSUE TITLE
List of table not displaying in module manager dropdown.

### ISSUE THREAD

**Issue by asimshazad** [crocodic-studio/crudbooster#349]
List of tables not displaying while creating a new module using module manager ? I have added couple of tables in mysql,but only i see csm_users table while adding a new module.
I am using Laravel 5.4 with php 7

**Comment by fherryfherry** [comment]
Do not use cms_ as prefix on your tables name
Pada tanggal 12 Apr 2017 12.37, "Asim Shahzad" <notifications@github.com>
menulis:

**Comment by asimshazad** [comment]
Ok thank you.
