### ISSUE TITLE
Mysql Error dbname.INFORMATION_SCHEMA.Tables

### ISSUE THREAD

**Issue by harimayco** [crocodic-studio/crudbooster#35]
I'm facing this error when trying to edit a module.

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.Tables WHERE TABLE_TYPE = 'BASE TABLE'' at line 1 (SQL: SELECT TABLE_NAME FROM dbname.INFORMATION_SCHEMA.Tables WHERE TABLE_TYPE = 'BASE TABLE') (View: D:\xampp\htdocs\testing\vendor\crocodicstudio\crudbooster\src\views\default\form.blade.php)

i'm using XAMPP for windows
- Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8
- PHP Version : 7.0.8
- MariaDB 10.1.13

**Comment by fherryfherry** [comment]
solved at version [5.2.11.0](https://github.com/crocodic-studio/crudbooster/releases/tag/v5.2.11.0)
