### ISSUE TITLE
Remove Checkbox field and Show Row number field

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#350]
How could I remove checkbox field? It is not useful in case of bulk action button is not show. 
And I want to show the row number field, how?
![remove_checkbox_field_show_rownumber](https://cloud.githubusercontent.com/assets/26919884/24944180/36b02b5c-1f84-11e7-9055-9fc23f25affd.png)

**Comment by fherryfherry** [comment]
Unfortunately there is no way,instead you create your own grid data
Pada tanggal 12 Apr 2017 13.31, "limbiz" <notifications@github.com> menulis:

**Comment by limbiz** [comment]
How about removing checkbox field?

**Comment by franciscoluiz** [comment]
@fherryfherry, i know it's not the priority, but it could be implemented, right?

**Comment by jdredondo** [comment]
You must try modify the getIndex method in the CBController, at line 434 replace 
`$html_content [] = "<input type = 'checkbox' class = 'checkbox' name = 'checkbox []' value = '$ row-> id' /> ";`
by
`$html_content [] = ($this->button_bulk_action) ?"<input type = 'checkbox' class = 'checkbox' name = 'checkbox []' value = '$ row-> id' /> " : "";`

**Comment by jdredondo** [comment]
in your case, replace by:
`$count_item = 1;
$html_content[] = ($this->button_bulk_action) ? "<input type='checkbox' class='checkbox' name='checkbox[]' value='$row->id'/>" : $count_item++;`

**Comment by limbiz** [comment]
Now I make it work with row number. Here the code:
CBController.php
....
$page = (Request::get('page'))?Request::get('page'):1;                                    
$count_item = ($page-1)*$limit+1;
foreach($data['result'] as $row) {
$html_content = array();
$html_content[] = ($this->button_bulk_action) ? "<input type='checkbox' class='checkbox' name='checkbox[]' value='$row->id'/>" : $count_item++;
.....

in table.blade.php (views->default)
Line 51: <th width='3%'><?php $data['button_bulk_action']?"<input type='checkbox' id='checkall'/>":'' ?></th>

**Comment by fherryfherry** [comment]
Editing the core might a danger for update, Please be carefull when you
update the CB, you should make sure always backup your CB unless your
edited file will be replaced
Pada tanggal 13 Apr 2017 08.27, "limbiz" <notifications@github.com> menulis:

**Comment by limbiz** [comment]
Hope you can put this feature in the next version.
