### ISSUE TITLE
Set minimum value to zero(0) not work

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#351]
$this->form[] = ['label'=>'Length (Km)','name'=>'length','type'=>'number','validation'=>'required','min'=>0,'value'=>0,'width'=>'col-sm-10'];
But I still can put -5 value and save it.

**Comment by fherryfherry** [comment]
Put laravel validation rule to prevent
Pada tanggal 12 Apr 2017 14.30, "limbiz" <notifications@github.com> menulis:

**Comment by limbiz** [comment]
I still can save with -5 after update to this:
$this->form[] = ['label'=>'Length (Km)','name'=>'length','type'=>'number','validation'=>'required|min:0','min'=>0,'value'=>0,'width'=>'col-sm-10'];

**Comment by limbiz** [comment]
Did anyone have problem with input value <0 (-5) to a field with 'validation'=>'min:0' ?
`$this->form[] = ['label'=>'Length (Km)','name'=>'length','type'=>'number','validation'=>'required|min:0','width'=>'col-sm-10'];`

**Comment by fherryfherry** [comment]
try 
`$this->form[] = ['label'=>'Length (Km)','name'=>'length','type'=>'number','validation'=>'required|integer|min:0','width'=>'col-sm-10'];`

**Comment by limbiz** [comment]
But I need to input a float number like 5.5

**Comment by fherryfherry** [comment]
Try to looking for more about laravel validation.  Find the rule type that
suit with your need.
Pada tanggal 17 Apr 2017 08.11, "limbiz" <notifications@github.com> menulis:
