### ISSUE TITLE
Top Bar not follow default position when follow using Custom View Of Index Method

### ISSUE THREAD

**Issue by salehinRafi** [crocodic-studio/crudbooster#352]
- Using Laravel 5.4

I follow step/code using in [Custom View Of Index Method](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-custom-index.md#how-to-make-a-custom-view-of-index-method).

However, view become as perusal. 

<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/20961380/24948411/d2e1386e-1f9c-11e7-92d2-f45f4f710091.PNG">

**Comment by fherryfherry** [comment]
There is an error on the back side, you can see the error at source page
