### ISSUE TITLE
Reference table issue

### ISSUE THREAD

**Issue by asimshazad** [crocodic-studio/crudbooster#353]
When i try to add a data in "posts"  table that have a reference to other table name brands i get this error

Base table or view not found: 1146 Table 'crudbooster.brand' doesn't exist ,however i have created a brands table,and then reference it in the foreign key using module generator.

**Comment by FabiGjuzi** [comment]
Did you find the solution because I am facing the same problem...... it searches for table in singular but laravel migration generates the table name in plural

**Comment by jingjinjingjin** [comment]
Me too. Need help.

**Comment by jingjinjingjin** [comment]
I have resolved it. You need to change table name at step two when generate module.
For example,  my database table name is `customers`, but step two `join` column, it's  `customer`.
So, what you need to do is modify customer to customers.
