### ISSUE TITLE
After Update my auto increment for 'id' didn't work 

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#354]
i just updating my crud and after i migrate my table, the 'id' is not auto increment to primary key....

![image](https://cloud.githubusercontent.com/assets/24912478/24960539/4b38e3d4-1fc0-11e7-93bc-463ac6ab56e6.png)

![image](https://cloud.githubusercontent.com/assets/24912478/24960514/37a9abf0-1fc0-11e7-919f-8680daad22bd.png)

**Comment by fherryfherry** [comment]
migration is laravel feature
