### ISSUE TITLE
Nice Names for Fields ( Application Multi Language ) 

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [crocodic-studio/crudbooster#355]
Would a Pull Request for this feature be accepted?

vendor/crocodicstudio/crudbooster/src/controllers/CBController.php 

![image](https://cloud.githubusercontent.com/assets/1152426/24975476/2bef2142-1f9c-11e7-81dc-eebe4b2bcc83.png)

![image](https://cloud.githubusercontent.com/assets/1152426/24975697/f3a875a8-1f9c-11e7-853e-2a2b3f4612e3.png)

![image](https://cloud.githubusercontent.com/assets/1152426/24977614/03523ab4-1fa4-11e7-834c-ca2c9636c55e.png)

**Comment by fherryfherry** [comment]
can you give me an English example of your proposal?
I still consider your proposal, it would be easy to use or not
