### ISSUE TITLE
Child Form intergration

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#356]
I have found that the child form demo on your site is different from the current version.
From Demo:
![crudbooster_demo](https://cloud.githubusercontent.com/assets/26919884/24990713/14fd91fe-2040-11e7-849e-c8d8a9e461cf.png)
My own:
![child_test](https://cloud.githubusercontent.com/assets/26919884/24990717/1d667356-2040-11e7-8966-19e56ba8ba00.png)

in Form interface:
![demo_stock](https://cloud.githubusercontent.com/assets/26919884/24990813/b83ee106-2040-11e7-9006-f2f18f0698dc.png)
![road_sign](https://cloud.githubusercontent.com/assets/26919884/24990878/416ccf9c-2041-11e7-9a0f-00d0273b4ee9.png)

**Comment by fherryfherry** [comment]
it has been deprecated

**Comment by limbiz** [comment]
How can i put those child form in Tabs?

**Comment by fherryfherry** [comment]
There is no way to do that instead of create your own view by overriding
Pada tanggal 13 Apr 2017 12.13, "limbiz" <notifications@github.com> menulis:
