### ISSUE TITLE
insert

### ISSUE THREAD

**Issue by kinzangnamgyal** [crocodic-studio/crudbooster#357]
i have a two table, visit and prescription. i have data already data in visit table, 

 so how i can update data into visit table from prescription controller form. visit table have 3 column but i want to update only one particular column called is_active ( i have already data 0 and want to update in to 1). i want to insert data in prescription table as well into particular column of visit table. below is image of visit table field. i want to change  0 to 1 in is_active column form prescription controller form.

![capture](https://cloud.githubusercontent.com/assets/26356806/25000104/d898e890-2061-11e7-8778-4d7bdf159244.PNG)
   

regards 

kinzang

**Comment by fherryfherry** [comment]
Have you take a look "hook"
Pada tanggal 13 Apr 2017 17.02, "kinzangnamgyal" <notifications@github.com>
menulis:

**Comment by kinzangnamgyal** [comment]
i have used below hook form prescription controller. but not working.


public function hook_after_add($id) {        
	        		
	    		 $visit = DB::table('visit')->where('id',$id)->first();

  				  $data = array();
   				 $data['is_active'] = '$is_active';
   				 DB::table("visit")->insert($data);
	    }


below is controller form that is prescription controller
$this->form[] = ['label'=>'Prescriptions','name'=>'prescriptions','type'=>'wysiwyg','validation'=>'required|min:1|max:255','width'=>'col-sm-10'];......... (this data should insert into prescription table)
			
$this->form[] = ['label'=>'Status','type'=>'checkbox','validation'=>'required','width'=>'col-sm-9','dataenum'=>'1'];........(this should update into visit table column called is_active )

**Comment by fherryfherry** [comment]
you forgot to assign the relation field
