### ISSUE TITLE
"created_at"  , column required for each table at CB?

### ISSUE THREAD

**Issue by renzocastilloc** [crocodic-studio/crudbooster#359]
Whoops, looks like something went wrong.

3/3
QueryException in Connection.php line 647:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'field list' (SQL: insert into `Estado` (`nombre`, `Descripcion`, `created_at`, `id`) values (Entregado, BLSKFJSLK LKJGDFLKGJL, 2017-04-14 01:23:30, 1))
in Connection.php line 647
at Connection->runQueryCallback('insert into `Estado` (`nombre`, `Descripcion`, `created_at`, `id`) values (?, ?, ?, ?)', array('Entregado', 'BLSKFJSLK LKJGDFLKGJL', '2017-04-14 01:23:30', 1), object(Closure)) in Connection.php line 607

* I'm wondering if there's an option to deactivate having a created_at column when using module generator for data-grid. I mean, it doesn't show at the module generator,  but it appears at the SQL query as if I am supposed to have it at my table . Does crudbooster assume this or am I able to modify this statement.

**Comment by fherryfherry** [comment]
unfortunately yes for at this time
