### ISSUE TITLE
insert value it self

### ISSUE THREAD

**Issue by kinzangnamgyal** [crocodic-studio/crudbooster#360]
HI,

how to insert value(CID_Number) itself not id. i have two table, patient and visit. in patient table i have column called CID_Number and in visit table also i have column called CID_Number. so i used join and also i use datamodal. The problem is that when i insert this, it insert 'id' of patient table not the CID_Number column Value of Patient table. So i want to insert the CID_Number Value of patient table  into CID_Number column of visit table..... please help me to get answer.

below is code. 

$this->table = "visit";
$this->col[] = ["label"=>"Patient CID","name"=>"CID_Number","join"=>"patient,CID_Number"];
'
			$this->form = [];
			$this->form[] = ['label'=>'Patient CID','name'=>'CID_Number','type'=>'datamodal','validation'=>'required','width'=>'col-sm-7','datamodal_table'=>'patient','datamodal_columns'=>'CID_Number','datamodal_size'=>'small'];

**Comment by fherryfherry** [comment]
you can modify the value by using hook method after add / after edit

**Comment by kinzangnamgyal** [comment]
hi fherryfherry....

can i have cod, how i can used in hook method.

**Comment by fherryfherry** [comment]
```
public function hook_before_add(&$postdata) {
$patient_id = $postdata['CID_Number'];
$patient = DB::table('patient')->where('id',$patient_id)->first();
$postdata['CID_Number'] = $patient->CID_Number;
}
```

**Comment by kinzangnamgyal** [comment]
Thanks FherryFherry.. it work now...
