### ISSUE TITLE
Parent_select don't work [HELP]

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#361]
I make relating parent child table from tutorial that i saw, 
i have 2 table parent is "semester" and child is "mata_praktikums" so, when i select ganjil or genap in semester fielad, mata praktikums will chance based on ganjil or genap

![image](https://cloud.githubusercontent.com/assets/24912478/25038718/2d5f40b8-212a-11e7-9c21-c7872f6397ce.png)

my controller

![image](https://cloud.githubusercontent.com/assets/24912478/25038744/592eb5d4-212a-11e7-9f36-b332e64908db.png)

my migrations

![image](https://cloud.githubusercontent.com/assets/24912478/25038757/6f8285fe-212a-11e7-8b41-bb110b52e76b.png)

**Comment by fherryfherry** [comment]
try to update the latest version

**Comment by RobinHoo1973** [comment]
I also encountered same issue, and I found problem is a "&" sign missing in the vendor/crocodicstudio/crudbooster/src/views/default/type_components/child/component.blade.php at line 280, which is an ajax get url appended with datable_where
previous line is 
`$.get("{{CRUDBooster::mainpath('data-table')}}?table=" + table + "&label=" + label + "&fk_name=" + fk_name + "&fk_value=" + fk_value + "datatable_where=" + encodeURI(datatableWhere)`

and you could see there is & missing before datable_where, modify the file with & added. problem solved.
