### ISSUE TITLE
Class '' not found

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#362]
i just make new laravel and new crud, and then i make new table in cms_users as name"username". when i migrate refresh i found this error. [Symfony\Component\Debug\Exception\FatalThrowableError]  Class '' not found

![image](https://cloud.githubusercontent.com/assets/24912478/25043141/eae5d684-2147-11e7-90e2-cb5593b611df.png)

i try to search but not found the right answer...

**Comment by fherryfherry** [comment]
migration is laravel feature
