### ISSUE TITLE
showing two column in single join @ $this->col

### ISSUE THREAD

**Issue by kinzangnamgyal** [crocodic-studio/crudbooster#365]
how we can join table with  two column but display in one coulmn

**Comment by fherryfherry** [comment]
you could try : 
```
$this->col[] = ['label'=>'Category','name'=>'categories_id','join'=>'categories,name','callback_php'=>'$row->categories_name."_".$row->categories_id'];
```

**Comment by tegarwahyu** [comment]
how to showing three relationship column in single join @ $this->col
`$this->col[] = array("label"=>"Jabatan","name"=>"profil_id","join"=>"profils,jabatan_id", "join"=>"jabatan,nama_jabatan");`

**Comment by achrafscoorpion22** [comment]
i found a solution this day 
$this->col[] = ["label"=>"Architect","name"=>"(select CONCAT( cms_users.name ,' ',cms_users.surname ) from cms_users where folder.id_architect = cms_users.id) as id_architect"];

**Comment by fherryfherry** [comment]
You can try like this
$this->col[] = array("label"=>"Jabatan","name"=>"profil_id","join"=>"profils,jabatan_id",
"visible"=>false);
$this->col[] = array("label"=>"Jabatan","name"=>"profils.jabatan_id",
"join"=>"jabatan,nama_jabatan");

**Comment by achrafscoorpion22** [comment]
this works form me perfect ! 
concat the field that you want 
$this->col[] = ["label"=>"Architecte","name"=>"(select CONCAT( cms_users.name ,' ',cms_users.surname ) from cms_users where folder.id_architect = cms_users.id) as id_architect"];
