### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by gsi-yunier** [crocodic-studio/crudbooster#366]
How I can define custom layouts and add css and javascript without modify the crudbooster package.

**Comment by andersondeoliveiramachado** [comment]
In the generated controls it is possible to make these settings. Already the question of layout of forms I do not know to inform.

Example :
$this->load_js[] = asset("myfile.js");
$this->style_css = ".style{....}";
$this->load_css[] = asset("myfile.css");

**Comment by gsi-yunier** [comment]
I need to change the app layout not only for generated modules.

Thanks for your answer.

**Comment by fherryfherry** [comment]
Unfortunately, there is no way to custom the whole layout, except, you want to override the index, add, edit form, so you can override it

**Comment by gsi-yunier** [comment]
I was afraid of that response, unfortunately I had to modify crudbooster files to achieve my goal.

Thanks for your answer.

**Comment by fherryfherry** [comment]
last, make sure to backup your modified files before updating cb
