### ISSUE TITLE
unique field

### ISSUE THREAD

**Issue by kinzangnamgyal** [crocodic-studio/crudbooster#368]
While editing the filed with unique email, it says the email already exists.

**Comment by fherryfherry** [comment]
I can't figure out, you need to explain more
please read this
![image](https://cloud.githubusercontent.com/assets/6733315/25093355/240d93ae-23bc-11e7-96d1-b927f3269a18.png)

**Comment by kinzangnamgyal** [comment]
I have table called  employee, in that table i have 7 column and in that 7 column i have email column and it made unique, i can insert with unique email but while i editing some data and keep email same, it says the email already exists and i can't edit. so i want to edit and update in same table. 


please help me.

**Comment by fherryfherry** [comment]
how can I more figure out, if you don't include some screenshots of your code

**Comment by kinzangnamgyal** [comment]
Below is the screenshot of unique field editing. Here i have CID column is unique.  

![capture](https://cloud.githubusercontent.com/assets/26356806/25115299/04090dd4-2427-11e7-8782-29f5f577c7ba.PNG)

**Comment by fherryfherry** [comment]
your code please

**Comment by kinzangnamgyal** [comment]
$this->form[] = ['label'=>'CID','name'=>'CID','type'=>'text','validation'=>'digits_between:5,15|unique:patient','width'=>'col-sm-5'];

**Comment by fherryfherry** [comment]
Can you make sure that your CB has been updated to the latest version ?

**Comment by kinzangnamgyal** [comment]
ok thanks but i had updated last Wednesday (13 April 2017). even then i ll update once again.

**Comment by kinden** [comment]
Dear fherry, 
i have update latest version but my problem is still remain same.

![um](https://cloud.githubusercontent.com/assets/27999833/25554585/890c7b1e-2cf2-11e7-80cc-f13ed1e13e9b.PNG)
