### ISSUE TITLE
Non-Numeric Value

### ISSUE THREAD

**Issue by tomatoe45** [crocodic-studio/crudbooster#370]
hi @fherryfherry . after creating a module it work perfectly but when i click the link from the module ive created.. it gives me this error., any help?

![capture](https://cloud.githubusercontent.com/assets/17925294/25077578/e798c744-235d-11e7-9b34-1d4d98a6a774.PNG)

Thanks @fherryfherry .

**Comment by tomatoe45** [comment]
Its working now @fherryfherry .. Thanks.. its the limit.

**Comment by lsobral** [comment]
How did you solve this issue?

**Comment by tomatoe45** [comment]
Its the pagination limit of your  data..
