### ISSUE TITLE
How to make API calls on custom button click event ?

### ISSUE THREAD

**Issue by technoartista** [crocodic-studio/crudbooster#373]
Hi,
I have to use API calls to fill database. I tried to use API calls using custom button adding in top of grid.

`$this->index_button = array();

$this->index_button[] = ['label'=>'Product Sync','url'=>CRUDBooster::mainpath("productSync"),"icon"=>"fa fa-print"];`

How to use onclick event to call API ?

Example API:
`var form = new FormData();
form.append("ref", "11111");
form.append("label", "product 4");
form.append("description", "new life");
form.append("tobuy", "1");
form.append("tosell", "0");
form.append("weight", "1000");
form.append("weight_units", "1");
form.append("length", "100");
form.append("length_units", "1");
form.append("price", "5000.00");
form.append("price_min", "10000.00");

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://localhost/xxx/public/api/products",
  "method": "post",
  "headers": {
    "cache-control": "no-cache",
    "postman-token": "XYZ"
  },
  "processData": false,
  "contentType": false,
  "mimeType": "multipart/form-data",
  "data": form
}

$.ajax(settings).done(function (response) {
  console.log(response);
});`

**Comment by fherryfherry** [comment]
unfortunately, basicaly, there is no way to assign the javascript to index_button

**Comment by technoartista** [comment]
Is there any other way to make an appointment call on button click

**Comment by technoartista** [comment]
Can I create a view blade in crudbooster or a stage something like welcome page that support js, if so how to do it?

**Comment by fherryfherry** [comment]
Why you didn't read the documentation 
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/index.md

**Comment by fherryfherry** [comment]
![image](https://cloud.githubusercontent.com/assets/6733315/25115222/e96124a0-242e-11e7-8023-6a7cbc5c1d7b.png)
