### ISSUE TITLE
QUESTION: How to call seeder?

### ISSUE THREAD

**Issue by davodavodavo3** [crocodic-studio/crudbooster#374]
How to run  custom seeder ,its rewritten when we call artisan crudbooster:update.
I need to create custom modules , and seed them to DB .

**Comment by tomatoe45** [comment]
hi @davodavodavo3 you may try this

> https://laravel.com/docs/5.4/seeding#running-seeders

or this

>php artisan db:seed --class=YourClass 
OR 
>php artisan db:seed

**Comment by tomatoe45** [comment]
https://cloud.githubusercontent.com/assets/6733315/25093355/240d93ae-23bc-11e7-96d1-b927f3269a18.png

**Comment by fherryfherry** [comment]
of course, your seed should be run after crudbooster:update command

**Comment by davodavodavo3** [comment]
It will be good if you make a separate file for the CB seeder.A good practice to not  overwrite user seeder calls in DatabaseSeeder

**Comment by tomatoe45** [comment]
hi @davodavodavo3.. it is a good practice to know the laravel basics including the seeding function before using the CB.. ive also create my own DatabaseSeeder and CB did not overwrite it..

**Comment by davodavodavo3** [comment]
And where did you get that I do not know basics of laravel ?

**Comment by davodavodavo3** [comment]
Probably it's your seeding logic.
You understand what the essence of what I wrote? The user does not have to enter the DatabaseSeeder file every time after the CB update(user maybe want to create symlink for CB venodos on HOSTING ) and add a seeder class call, and should not call 10 separate seeds

**Comment by tomatoe45** [comment]
well since you know more about the laravel.. you should know how to execute your seeder..

**Comment by tomatoe45** [comment]
custom seeder rather.

**Comment by tomatoe45** [comment]
well its your project .. its your logic.. the answer is there..

**Comment by davodavodavo3** [comment]
Yes @tomatoe45 ,I see you're not from the developers or contributors.
The question is not whether the user can make a seed or not, the question is that CB user did not make unnecessary movements, this is the essence of using such applications.DatabaseSeeder file does not belong to CB

**Comment by davodavodavo3** [comment]
Well, see this is my proposal, and in the future, be more polite with other users(It does not concern me), and then the stars do not accumulate. And I think that CroodBooster is better than Voyager https://github.com/the-control-group/voyager
Why do they have so many stars on alpha versions?

**Comment by tomatoe45** [comment]
Yes mate im not one of the contributors nor developer of this app.. im one of the user of the app.. you posted your queries here means you need help or sugestion.. answers are posted mate ..

**Comment by tomatoe45** [comment]
im very polite mate.. helping who needs help/answers.. you can make a request for it if you want.. good luck..

**Comment by davodavodavo3** [comment]
Do better, do not make bicycles @tomatoe45.
I just wanted to hear the developers' opinion, and not that go and read the documentation of Laravel.
