### ISSUE TITLE
QUESTION: Can I move Show Data and Add Data to another place?

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#376]
![move_button](https://cloud.githubusercontent.com/assets/26919884/25112623/9678dfba-241c-11e7-81bd-1be74bf1f53b.png)

**Comment by fherryfherry** [comment]
Unfortunately, you can not do that
Pada tanggal 18 Apr 2017 09.53, "limbiz" <notifications@github.com> menulis:
