### ISSUE TITLE
datatable_format for select2 not work

### ISSUE THREAD

**Issue by becca0330** [crocodic-studio/crudbooster#378]
I want to load value from my table "system_options" for a column called "Active?" and the dropdown items' label should be with the format "display_name(value)" , eg. "Not Active(0)".

(Both display_name and value are columns of system_options.)

So I have the following:

`$this->form[] = ['label'=>'Active?','name'=>'is_active','type'=>'select2','validation'=>'required','width'=>'col-sm-10','datatable'=>'system_options,value','datatable_where'=>'option_group_id = 1', 'datatable_format'=>"display_name(value)"];
`

But my dropdown list only shows the 'value' of system_options as option labels.
Anyone knows how to do it right?

**Comment by fherryfherry** [comment]
Where do you get it? `datatable_format`=>"display_name(value)" ???

Have you looked at?
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/form-select2.md

**Comment by becca0330** [comment]
@fherryfherry I've also tired the one from documentation, but the option label still shows only the value of 'datatable'=>'system_options,value' <-- this value,  not "id,' - ',display_name".  

`$this->form[] = ['label'=>'Active?','name'=>'is_active','type'=>'select2','validation'=>'required','width'=>'col-sm-10','datatable'=>'dafu_system_options,value','datatable_format'=>"id,' - ',display_name"];`
