### ISSUE TITLE
Multilanguage admin

### ISSUE THREAD

**Issue by luisdiaswiz** [crocodic-studio/crudbooster#379]
Hello,

Is there any way crudbooster supports multi language and content translations?

Regards,

Luis Dias

**Comment by fherryfherry** [comment]
Of course, you can do that
`config/app.php`
there are some languages 
![image](https://cloud.githubusercontent.com/assets/6733315/25159796/547e57f0-24dc-11e7-8e5a-4935fc7b93a7.png)

**Comment by luisdiaswiz** [comment]
@fherryfherry Hello,

Thanks for the reply, but that is for the app strings, how about the content? Is there any way that crudbooster supports multi language content in models out of the box?

Regards,

Luis Dias

**Comment by imanghafoori1** [comment]
We will consider adding it for the next version.
Thanks for reporting.
