### ISSUE TITLE
Hi,and thank for your supporting, I have a problem with updating record. I have users and when I want to update the user records all record updated except for user privileges. The select box values are not updated

### ISSUE THREAD

**Issue by mommand** [crocodic-studio/crudbooster#38]

**Comment by fherryfherry** [comment]
thanks for your correction, please update yours to latest version [5.2.12.6](https://github.com/crocodic-studio/crudbooster/releases/tag/v5.2.12.6)

**Comment by mommand** [comment]
How to update?

**Comment by mommand** [comment]
I Update to current version, but still I faced with one problem 
![screen shot 2016-09-21 at 4 56 07 pm](https://cloud.githubusercontent.com/assets/4653953/18710862/892d2ef0-801c-11e6-9c4c-c43a7034c97c.png)

The image is not uploading
