### ISSUE TITLE
Removal of eval

### ISSUE THREAD

**Issue by davodavodavo3** [crocodic-studio/crudbooster#383]
Eval is widely considered to be bad practice for a multitude of reasons, many of which can be found on various forums and other relevant areas.

It is highly recommended that this code be changed to remove any and all instances of eval where its use is avoidable.
Eval is evil)))

**Comment by fherryfherry** [comment]
Of course, it would be appreciated if you give us an alternative idea rather than eval

**Comment by davodavodavo3** [comment]
Try this.It's a fast solution and  need tobe testet.
Maybe I missed something, but it works without an eval().
CBController change
```
if($col['callback_php']) {
     $value = call_user_func($col['callback_php']);
 }
```
And naw user should use anonymous functions like this:
$this->col[] = ["label"=>"Status","name"=>"status","callback_php"=>function() {
      if($row->status=="Active") {
                return "<span class='label label-success'>Active</span>";
       }else{
               return "<span class='label label-warning'>Unactive</span>";
       }
 }];
Long but protected!!
Solve yourself friends

**Comment by fherryfherry** [comment]
Hi it's good
![image](https://cloud.githubusercontent.com/assets/6733315/25160940/4eef76a0-24e3-11e7-8093-6ae76e6901c7.png)
can you put $row as the function parameter,

also, if we want to deprecate this attribute (callback_php), so we should replace it with  '**callback**'

**Comment by davodavodavo3** [comment]
yes you can put parameter and use:
if isset paramm
call_user_func($col['callback_php'],$row);

**Comment by davodavodavo3** [comment]
And will be nice if place button for callback function like popup window where user will write his code

**Comment by fherryfherry** [comment]
very good

You mean in step 3 of module generator, option button?

**Comment by davodavodavo3** [comment]
IN step 2 of module generator will be button named callback, on click open an popup window with texarea and write your function

**Comment by davodavodavo3** [comment]
Example:
```
$functions = array(
  'function1' => function($echo) {
        echo $echo;
   }
);
```
`call_user_func($functions['function1'], 'Hello world!');`

Output: Hello World

**Comment by fherryfherry** [comment]
good, by the way, you can commit your changes about the callback function

**Comment by davodavodavo3** [comment]
For now I'm goint to sleep friend))))My brain will explode

**Comment by fherryfherry** [comment]
In my country it is morning :D

**Comment by davodavodavo3** [comment]
In my, it's 7 morning

**Comment by davodavodavo3** [comment]
@fherryfherry we need to remove callback_php from 2 step if we want to use that way.
Probem is that we cant represent that function as plain text in step 2 for edit.
Have any ideas?

**Comment by fherryfherry** [comment]
of course, actually GUI its shit enough 😆
