### ISSUE TITLE
Menu become messy after update Privilege

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#384]
![menu_messup](https://cloud.githubusercontent.com/assets/26919884/25159215/7819f5f6-24d8-11e7-92db-12e6e7e97772.png)

**Comment by fherryfherry** [comment]
if you check the privilege item that had previously not checked, the privilege will create a new menu of what you've checked

**Comment by limbiz** [comment]
I just updated only the skin of Super Admin privilege.

**Comment by yosie123** [comment]
pEZfP

**Comment by yosie123** [comment]
I can confirm this issue on FireFox v52.0.2 (32-bits)
On Google Chrome and Microsoft Edge it's looking good.

**Comment by trisuliswanto** [comment]
Yeah I got the same problem after update the Privilege Settings...
