### ISSUE TITLE
Don't Show Records

### ISSUE THREAD

**Issue by darioajr** [crocodic-studio/crudbooster#39]
When I create a new record don't show the columns and records.

![captura de tela 2016-09-22 as 06 48 23](https://cloud.githubusercontent.com/assets/7606/18743767/f10a056a-8090-11e6-9462-45c3b95473aa.png)

**Comment by darioajr** [comment]
My Table was created by Migrations

public function up()
    {
        Schema::create('user_cores', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name',100);
            $table->string('code',50)->nullable();
            $table->timestamps();
        });
    }

**Comment by fherryfherry** [comment]
open the controller related your module (user cores) in app/Http/Controllers/ ...
Make sure that the controller in accordance with CRUDBooster Index Scafolding Rules
$this->col .....

**Comment by fherryfherry** [comment]
Sorry that was an error at module generator, so please update the [latest version](https://github.com/crocodic-studio/crudbooster/releases/tag/v5.2.12.11l)
