### ISSUE TITLE
ErrorException: View [crudbooster.admin_template] not found

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#391]
I create my own custom edit
custom_edit_view_communes.blade.php

```
@extends('crudbooster.admin_template')
@section('content')
<div>I love your</div>
@endsection
```
But i got error.
![crudbooster_admin_template_not_found](https://cloud.githubusercontent.com/assets/26919884/25222721/73618ed2-25e3-11e7-8e1b-8aec44a57e5e.png)

**Comment by tomatoe45** [comment]
hi @limbiz try this

>@extends('crudbooster::admin_template')

instead of

>@extends('crudbooster.admin_template')

**Comment by limbiz** [comment]
Yes, that's it. Thanks.

**Comment by andrinda** [comment]
try it
and save custom_edit_view_communes.blade.php

@extends('crudbooster::admin_template')
@section('content')
  
  <div class='panel panel-default'>
    <div class='panel-heading'></div>
    <div class='panel-body'>
        <div class='form-group'>
          <label>Name</label>
          <p>{{$row->name}}</p>
         
        </div>

        

      </form>
    </div>
  </div>
@endsection
