### ISSUE TITLE
Auth::user()->photo

### ISSUE THREAD

**Issue by davodavodavo3** [crocodic-studio/crudbooster#392]
### First 
Useing Auth::user()->photo instead of Session::get('admin_photo') for updating Admin photo wihout flashing current session.
And why storing admin photo in Session?
And maybe for admin Nick Name too, use auth user.

### Second
Data Export showing on edit page and doesnt work. Maybe want to remove from edit pages that button?

**Comment by fherryfherry** [comment]
1. If you found the best way you can keep submit of your idea
2. Of course, data export should be on index page / grid data
