### ISSUE TITLE
API generator issue

### ISSUE THREAD

**Issue by fedeverdi** [crocodic-studio/crudbooster#394]
Hello !
I have a issue with API generator ...

If I modify an already created api ... All response values goes to 'null'...
Any Idea ?

Bug ? Permissions problems ?

Thanks !!!

**Comment by fherryfherry** [comment]
please include the screenshots (before, after)

**Comment by davodavodavo3** [comment]
Yes @fherryfherry there is issue in API, generate one , and then open it for edit, you will see null values

**Comment by fedeverdi** [comment]
After first save ....
<img width="793" alt="schermata 2017-04-21 alle 10 32 11" src="https://cloud.githubusercontent.com/assets/16398917/25269712/207d04e4-267e-11e7-934c-f47dbd0ceb26.png">

After second save ....
<img width="794" alt="schermata 2017-04-21 alle 10 32 30" src="https://cloud.githubusercontent.com/assets/16398917/25269721/2a61b28e-267e-11e7-9ed6-fb316112e25e.png">

**Comment by yosie123** [comment]
I can confirm this. There is a null issue when you edit an api.

**Comment by fedeverdi** [comment]
I discovered that the bug is in $posts passed to postSaveApiCustom() method in ApiCustomController. 

When you save an Api already exists, the values of ['responses_subquery'] are all 'null' ... 
I fixed with a little foreach for the moment .. at line 309 of ApiCustomController.php

**It seems that instead of null, the field saves the string**

foreach($responses_subquery as $key => $value){
   if($value == 'null'){
   $responses_subquery[$key] = '';
   }
}

Thanks to all.

**Comment by wonderful60** [comment]
Click reset button also solve the problem.
![image](https://user-images.githubusercontent.com/2291007/28603832-23cdb44c-71f9-11e7-9eb3-d7643c60cec2.png)

**Comment by topo79** [comment]
@fedeverdi Thanks!!! In my case, it only works with null without the ''

if($value == null{
