### ISSUE TITLE
QUESTION: Correct approach for sync changes with team

### ISSUE THREAD

**Issue by heribertusk** [crocodic-studio/crudbooster#396]
While using crudbooster I found some of the config are placed on db tables. So to keep everything synced between me and my team, I'm using https://github.com/orangehill/iseed for backup my progress on cms_moduls, cms_menus, cms_privileges_roles, cms_privileges.

`$this->call('iseed', ['tables'=>'cms_menus,cms_moduls,cms_privileges_roles,cms_privileges', '--force'=>true]);`

After keep them as seeder file and push to git, my other team member can pull and get recent changes. Is this a correct approach or you have better suggestion?

**Comment by fherryfherry** [comment]
It's a good idea,
I think you are correct

**Comment by heribertusk** [comment]
i'm making my own package especially for handling backup seeder using idea above. But maybe we could add new feature included on your package for handling those situation (backup config using seeder).

Anyway thanks for sharing a nice and useful package, salam dari Yogyakarta untuk dev Semarang.

**Comment by fherryfherry** [comment]
Yes, you may look at our sample project on the store http://crudbooster.com/store, I'd include artisan command for backup (as seeder). But it will be my consider to including this in the future

"Salam kembali, kapan - kapan kita bisa kopdar untuk sharing"
