### ISSUE TITLE
How to isolate records by users

### ISSUE THREAD

**Issue by darioajr** [crocodic-studio/crudbooster#40]
I need a option that each user view your records only.

**Comment by fherryfherry** [comment]
You can do that by modifying the hook query index 

for example in hook query index
```
if(!get_is_superadmin()) {
$query->where('id_cms_users',get_my_id());
}
```

get_my_id() = will be return your current id user
get_is_superadmin() = to determine whether you are super admin or not, as we knew the super admin privilege should view all records.
