### ISSUE TITLE
How to know if I'm in ADD or EDIT or INDEX from controller ?

### ISSUE THREAD

**Issue by abenzakour** [crocodic-studio/crudbooster#405]
Hello, 

Can you please tell me How to know if I'm in ADD or EDIT or INDEX from controller  ?

**Comment by andersondeoliveiramachado** [comment]
Copy from vendor/crocodicstudio/crudbooster/src/controllers/CBController.php and place inside your controller.

getAdd in line 959 + - 
getEdit in line 1089 + - 

`
	public function getAdd(){
.
.
.
	}

public function getEdit($id){
.
.
.
}
`

**Comment by fherryfherry** [comment]
or you using the helper CRUDBooster::getCurrentMethod()
