### ISSUE TITLE
Required validation not working on "datetime" field

### ISSUE THREAD

**Issue by Muhammadinaam** [crocodic-studio/crudbooster#408]
Required validation is not working on datetime field. When I saved the form without entering anything in the datetime field. It raised SQL exception that datetime field value is not correct. I had already set required for the datetime field in module generator.

![1](https://cloud.githubusercontent.com/assets/22542738/25317563/65bf20b0-2894-11e7-84d4-029dc7c7b5f9.png)

**Suggestion to fix this issue**

I fixed this issue by commenting following line in CBController.php, in validation() function

if( !isset($request_all[$name]) ) continue;

above line is line Number 744. Comment out it or remove this line to fix this issue

**Comment by Muhammadinaam** [comment]
Please make necessary changes in master branch so that other users don't get into this problem.

**Comment by fherryfherry** [comment]
error screenshot, please

**Comment by limbiz** [comment]
I also have the same problem with datetime validation set to required, and also radio validation set to required.
*Immediate_budget is radio with `'dataenum'=>'1|Yes;0|No'`
And how to set default value 0 to radio?
![date_radio_required_not_work](https://cloud.githubusercontent.com/assets/26919884/25424728/a135afdc-2a93-11e7-8e17-ef9b208c219e.png)

**Comment by Muhammadinaam** [comment]
I created a PR #447 to solve this issue along with another bug.

**Comment by Muhammadinaam** [comment]
Following code added through commit https://github.com/crocodic-studio/crudbooster/commit/5a0ad421d59426430ffc3c30bc353520b049613b is causing a BUG that images or files are not getting uploaded.
```
if(CB::isColumnNULL($this->table,$name)) {
 	continue;
}else{						
 	$this->arr[$name] = "";
}
```
