### ISSUE TITLE
Uploading image with same name

### ISSUE THREAD

**Issue by Muhammadinaam** [crocodic-studio/crudbooster#409]
I created a module for news in which I added a form field for image. I saved a news with image name news_image.png. It was saved successfully without any issue.

However, when I saved second image with same name (i.e. news_image.png), it replaced image for the previous news.

**Suggestion to fix this issue**

I fixed this issue by adding  . uniqid(); at the end of line No. 928 in CBController.php in input_assignment() function.

`$filename = str_slug(pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME)) . uniqid();`

**Comment by Muhammadinaam** [comment]
Please make necessary changes in master branch so that other users don't get into this problem.

**Comment by fherryfherry** [comment]
If you found an issue and you can solve that issue, it better to pull request, so you can make contribution to  crudbooster works well

**Comment by davodavodavo3** [comment]
there is functionality for that , for now no need to create PR request while whe update CB

**Comment by davodavodavo3** [comment]
From your controller you can set upload_encrypt => 'true' to upload that file with random name generation

**Comment by davodavodavo3** [comment]
@fherryfherry dont say that you didnt know that))))

**Comment by Muhammadinaam** [comment]
Very nice. Crudbooster is very nice package. keep up the good work

**Comment by faraztanveer** [comment]
this issue can be solved by adding the following line of code after line 1093

` if (@$ro['type'] == 'upload') {
                if($this->table == desired_table_name){
  $this->arr[$name] =  request()->file('image')->store('/uploads/1/desired_folder_name');
                    
                }

else{
                $this->arr[$name] = CRUDBooster::uploadFile($name, $ro['encrypt'], $ro['resize_width'], $ro['resize_height'], CB::myId());
}
                if (! $this->arr[$name]) {
                    $this->arr[$name] = Request::get('_'.$name);
                }
            }`
this is how you can store files in organized manner

**Comment by faraztanveer** [comment]
you can replace code from line 1091 like this to solve this issue



 if (@$ro['type'] == 'upload') {
                if($this->table == desired_table_name){
  $this->arr[$name] =  request()->file('image')->store('/uploads/1/desired_folder_name');   }

else{
                $this->arr[$name] = CRUDBooster::uploadFile($name, $ro['encrypt'], $ro['resize_width'], $ro['resize_height'], CB::myId());
}
                if (! $this->arr[$name]) {
                    $this->arr[$name] = Request::get('_'.$name);
                }
            }
