### ISSUE TITLE
form_sub controller

### ISSUE THREAD

**Issue by EduGilPrades** [crocodic-studio/crudbooster#41]
I define a new subform with:
        $this->form_sub     = array();
        $this->form_sub[]   = array(
            'label'         =>  'Addresses',
            'controller'    =>  'AdminAddressesController',
            'foreign_key'   =>  'customer_id');

But CRUDBooster wants read controller from 'crocodicstudio\crudbooster\controllers\'

ErrorException:
Class 'crocodicstudio\crudbooster\controllers\AdminAddressesController' not found

**Comment by fherryfherry** [comment]
I recommend you to update the latest version since the form_sub was deprecated, replaced with **sub_module** , see the documentation.

about the error, did you create the controller by manual ? , or from **Module Generator** ?

**Comment by EduGilPrades** [comment]
I created by Module Generator. 
My version is 5.2.x-dev.

I try this code, but nothing:
        $this->sub_module   = array();
        $this->sub_module[] = array(
            'label'         =>  'Addresses',
            'icon'          =>  'fa fa-truck',
            'path'          =>  'App\Http\AdminAdressesController',
            'foreign_key'   =>  'address_id'
        );

I try with 'path' => 'AdminAdressesController' too with same result.
