### ISSUE TITLE
mail setting 

### ISSUE THREAD

**Issue by kinzangnamgyal** [crocodic-studio/crudbooster#416]
I am working in password forgot page. i have set gmail smtp server. 
SMTP:smtp.gmail.com
Gmail SMTP port (TLS): 587
UserName: My gmail
password: My gmail password.

below is image of error

![capture](https://cloud.githubusercontent.com/assets/26356806/25374895/e124926c-29c0-11e7-857a-e3ab84c9929c.PNG)

**Comment by fherryfherry** [comment]
open the email template, correct the email sender

**Comment by andrinda** [comment]
same problem :(

**Comment by wonderful60** [comment]
modify .env first
