### ISSUE TITLE
status

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#417]
Hi, i m new in laravel, i found in your demo, there is a status column in Product Data. When we click on Set Active it change status column value into active.  below is your demo page image:
i want same like this.
![status](https://cloud.githubusercontent.com/assets/27999833/25378865/1a27e670-29cd-11e7-9ac7-22e84894bf87.PNG)

below is my project page which i have done.   
i added below code in callback. can i have your code. 
($row->is_active=="Active")?"<span class=\"label label-success\">Active</span>":"<span class=\"label label-warning\">Unactive</span>"

![my](https://cloud.githubusercontent.com/assets/27999833/25379037/7a21aebc-29cd-11e7-9cd6-9f0d4c14604d.PNG)

**Comment by davodavodavo3** [comment]
Check this example:
http://crudbooster.com/doc/5.3/action-button

**Comment by kinden** [comment]
Thanks Davo, but i had add this code in my project, it dose display the button.

**Comment by davodavodavo3** [comment]
Can you show where you add that code?

**Comment by kinden** [comment]
this the code i added  

 $this->addaction = array();

	        $this->addaction[] = ['label'=>'Set Paid','icon'=>'fa fa-money','color'=>'warning','url'=>CRUDBooster::mainpath('set-paid').'/[id]','showIf'=>'[status] == "Active"'];

**Comment by kinden** [comment]
When i click on 'Set Active' Button , status should change in to Active. And when i click on 'Set Unactive' Button, status should change into Unactive. please help me

**Comment by fherryfherry** [comment]
#434 duplicate
