### ISSUE TITLE
Assets not getting loaded

### ISSUE THREAD

**Issue by farghana** [crocodic-studio/crudbooster#421]
I installed crudbooster but somehow, it does not load any assets and my pages are all messed up.
!
![screen shot 2017-04-25 at 5 13 13 pm](https://cloud.githubusercontent.com/assets/4697999/25383650/a330d7b2-29da-11e7-8d6d-5802aac73a80.png)

**Comment by farghana** [comment]
FYI, I removed public directory from url. I would not like my url to have public. So what should i do?

**Comment by davodavodavo3** [comment]
Tell how to reproduce the problem step by step.
What version of laravel?

**Comment by fherryfherry** [comment]
remove the public directory manually is not a right way, you need to use like virtual host

**Comment by arilla** [comment]
you have to review your directory link public/vendor -> vendor/crocodicstudio/crudbooster/src/assets

**Comment by fherryfherry** [comment]
re run : `php artisan crudbooster:update`

**Comment by farghana** [comment]
i am using laravel 5.3. I did not remove directory, I just do not want public in my urls.

**Comment by davodavodavo3** [comment]
@farghana go to vendor\crocodicstudio\crudbooster\src\userfiles\views
get folder named vendor and copy it in where is your pablic directory

**Comment by davodavodavo3** [comment]
I really don't understand your problem.

**Comment by davodavodavo3** [comment]
or create symlink for that that folder in your public(maybe you www) directory

**Comment by davodavodavo3** [comment]
Does your Laravel App working, do you see laravel welcome page?

**Comment by farghana** [comment]
@davodavodavo3 yes i can see my laravel welcome page

**Comment by davodavodavo3** [comment]
))))))

**Comment by davodavodavo3** [comment]
@farghana sorry if i offended you
