### ISSUE TITLE
how to insert color status?

### ISSUE THREAD

**Issue by andrinda** [crocodic-studio/crudbooster#428]
![screen shot 2017-04-26 at 3 08 10 pm](https://cloud.githubusercontent.com/assets/4930514/25424417/7bc56b58-2a92-11e7-81bc-a5b3d5446f76.png)
haii how to insert color status ?pending or done
if success done color green and if pending color yellow
how implementasi ?

thanks

**Comment by tomatoe45** [comment]
hi @andrinda try this link

> https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-custom-color-row.md

you can also check in the documentation or from the Demo CB.

**Comment by andrinda** [comment]
yes i has can add 
$this->table_row_color[] = ['condition'=>"[status] == 'Done'","color"=>"success"];
but not work

**Comment by tomatoe45** [comment]
try this from the callback in module wizard
> ($row->status=="Active")?"<span class=\"label label-success\">Active</span>":"<span class=\"label label-warning\">Unactive</span>"...

try to refer also the Demo and Documentation.. you can get most of the answers of your question.

https://crudbooster.com/demoo/public/admin/login

**Comment by andrinda** [comment]
Ok guys DONE thanks before

**Comment by kinden** [comment]
Please andrinda, can u help me to get same like yours. i also want same like you, but i can't and i had tried a lot. or can u share your code and screen shoot for result.

**Comment by andrinda** [comment]
Oke mr. Kinden i share code .. 👍 

`$this->col[] = ["label"=>"Status","name"=>"status","callback_php"=>'($row->status=="Active")?"<span class=\"label label-success\">Active</span>":"<span class=\"label label-danger\">UnActive</span>"'];
			`

**Comment by kinden** [comment]
Thanks andrinda

**Comment by soraaa** [comment]
What if there are 3 or more options?

How can we handle that?
I tried with code below but the first option did not executed

```php
"callback_php"=>'($row->result=="Approved")?"<span class=\"label label-success\">Approved</span>":($row->result=="Pending")?"<span class=\"label label-warning\">Pending</span>":"<span class=\"label label-danger\">Denied</span>"'
```

**Comment by abenzakour** [comment]
Try this : 

`
"callback_php"=> '(($row->result=="Approved")?"<span class=\"label label-success\">Approved</span>":(($row->result=="Pending")?"<span class=\"label label-warning\">Pending</span>":"<span class=\"label label-danger\">Denied</span>"):"")'

`

**Comment by soraaa** [comment]
It throw me an error

![error](https://cloud.githubusercontent.com/assets/28080386/25478210/6db88cc4-2b6a-11e7-9272-b866cc8a76d4.png)

**Comment by fherryfherry** [comment]
You can use hook_row_index to modify : 
```
public function hook_row_index($column_index,&$column_value) {	        
//find which the column you want to override, let say status column position number 3
if($column_index == 3) {

switch($column_value) {
   case 'approved':
     $column_value = "<span class='label label-success'>Approved</span>";
   break;
   case 'pending':
    $column_value = "<span class='label label-warning'>Pending</span>";
   break;
   case 'denied':
    $column_value = "<span class='label label-danger'>Denied</span>";
   break;
   default:
    $column_value = "<span class='label label-default'>".$column_value."</span>";
   break;
}//endswitch

} //endif

}
```

**Comment by soraaa** [comment]
It works like charms. Thanks @fherryfherry :smiley:

**Comment by azarzaza** [comment]
issues i cleared

**Comment by topo79** [comment]
@fherryfherry is there a way to add a row number to the grid? if so will that work when applying filters? TY
