### ISSUE TITLE
Unique validation doesn’t work properly

### ISSUE THREAD

**Issue by soraaa** [crocodic-studio/crudbooster#431]
- **Operating system:** _Windows 10 Pro x64_
- **Server**: _Xampp with PHP 7.1.1_
- **CRUDBooster version**: _5.3.2.20_

### ISSUE:

![heroes list](https://cloud.githubusercontent.com/assets/28080386/25467458/83187db8-2b38-11e7-9fb1-09794fe71a21.png)

I have put unique validation rule on ID column but when I add new data with the same ID, the validation didn’t work properly. I add more data with same ID, and now the validation works normally.
It only happened when I type **_“g7h8i9”_** twice. On my third attempt adding new data with same **_“g7h8i9”_** ID, everything is OK.
If I type **_“a1b2c3”_** or **_“d4e5f6”_**, the unique validation works just fine

```php
$this->form[] = ['label'=>'ID','name'=>'id','type'=>'text','validation'=>'required|unique:heroes,id','width'=>'col-sm-10','placeholder'=>'Heroes ID'];
```

Is it bug or what? and How to solve this?

### QUESTIONS:

![heroes edit](https://cloud.githubusercontent.com/assets/28080386/25467686/4af0ce8e-2b3a-11e7-81c0-a649ad061357.png)

1. How to remove Export Data button in Edit Data?
2. How to make ID field “readonly” in Edit Data?

Thanks in advance :-)

**Comment by tomatoe45** [comment]
hi @soraaa you may try this

Validation 
>'validation'=>'required|unique:heroes' (remove the id),'readonly'=>'1'
Export Button
> you can go to your controller and change the $this->button_export = false;
when creating a module you have the option there if you want to show the export button.

**Comment by soraaa** [comment]
'validation'=>'required|unique:heroes' (remove the id) ---> Same problem occur

If I put 'readonly'=>'1' then I can't type the ID when I add new data. What I want to achieve is that I can type ID when add new data but in edit mode, field ID can't be edited (readonly)

Same thing with Export button, If change $this->button_export = false;. It won't show in everywhere (list data, add, edit, detail view). I want export button still show in list data and detail view but hidden in add & edit mode

Do you have any other suggestion? @tomatoe45

**Comment by tomatoe45** [comment]
can u show ur code in a row that has unique? and for that reason the readonly in edit mode and the export button.. i think there is no option for that..

**Comment by abenzakour** [comment]
You can do like this 

`	$this->form = [];

			if(CRUDBooster::getCurrentMethod() == "getAdd")
			{


			$this->form[] = ['label'=>'Nom','name'=>'nom','type'=>'text','validation'=>'required|min:1|max:255','width'=>'col-sm-10'];

			}elseif(CRUDBooster::getCurrentMethod() == "getEdit")
			{


			$this->form[] = ['label'=>'Nom','name'=>'nom','type'=>'text','validation'=>'required|min:1|max:255','width'=>'col-sm-10','readonly'=>1];

			}`

**Comment by soraaa** [comment]
Here is your suggestion. Am I placing the code correctly?

![heroes code](https://cloud.githubusercontent.com/assets/28080386/25477937/6e80a0b6-2b69-11e7-9476-65d6df586ab4.png)

When I try to add new data, here is the result

![heroes list-1](https://cloud.githubusercontent.com/assets/28080386/25477777/e2d64ca0-2b68-11e7-87ff-513f9eca9cae.png)

And this is when I edit the data

![heroes edit-1](https://cloud.githubusercontent.com/assets/28080386/25477814/01ea25da-2b69-11e7-99a4-bbdff93f0b27.png)

When I look at module generator, the ID column is gone. So, there's only 2 column left (Name and Role). I think this is why the data in ID was not added

**Comment by abenzakour** [comment]
When you do this kind of changes in code; don't use the module generator again for this module  because it will erase all your code; 

> 'validation'=>'required|unique:heroes' (remove the id)

**Comment by soraaa** [comment]
The validation works properly now. Thanks @tomatoe45 and @abenzakour :smiley: 

How about my last 2 questions:

1. How to remove Export Data button in Edit Data?
2. How to make ID field “readonly” in Edit Data?

I tried your suggestion above but I wonder why the data was not added. Any other suggestion?

**Comment by fherryfherry** [comment]
to remove the export data you can override value of button_export : 
```
$this->button_export = true;
if( CRUDBooster::getCurrentMethod() == 'getEdit') {
$this->button_export = false;
}
```

**Comment by soraaa** [comment]
That did the trick. Thanks @fherryfherry :+1: 

How about readonly field in edit mode. Do you have any idea?

**Comment by tomatoe45** [comment]
how about using that same trick?

getAdd $this->form = [''];
getEdit $this->form = ['readonly'=>'1']

**Comment by soraaa** [comment]
It has been suggested by @abenzakour and fail to meet my requirement. You can see the result above
