### ISSUE TITLE
Issue with Status

### ISSUE THREAD

**Issue by ngazangs3** [crocodic-studio/crudbooster#432]
Dear Sir,
Please help me..
I am doing project using laravel 5.4 but now stuck as in one case i have to update status from prescription controller form to visit table using hook..since i dont have much idea about it.
Please do help me so that i can proceed to next step.

**Comment by fherryfherry** [comment]
Sorry I don't really understand what you want
![image](https://cloud.githubusercontent.com/assets/6733315/25480695/13358676-2b74-11e7-8ed7-0d8c35f74731.png)
