### ISSUE TITLE
change status

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#434]
sorry... this is same as i ask before but issue not solved........When i click on 'Set Active' Button , status should be change in to Panding from Done. please help me.
i have done this much. below is image
![capture](https://cloud.githubusercontent.com/assets/27999833/25478553/58923f86-2b63-11e7-9db3-ac3174936ec1.PNG)

code i used:

$this->col[] = ["label"=>"Status","name"=>"is_active","callback_php"=>'($row->is_active=="Done")?"<span class=\"label label-success\">Done</span>":"<span class=\"label label-danger\">Panding</span>"'];

$this->addaction[] = ['label'=>'Set Active','icon'=>'fa fa-money','color'=>'warning','url'=>CRUDBooster::mainpath('......what should i put here......').'/[id]','showIf'=>'[is_active] == "Done"'];

**Comment by fherryfherry** [comment]
You need to create your own method in the controller which will process the provided id

`CRUDBooster::mainpath('update-status')`

**Comment by kinden** [comment]
Thanks Fherry. now my issue resolved. 
by this code
  $this->addaction[] = ['label'=>'Set Active','url'=>CRUDBooster::mainpath('set-status/pending/[id]'),'icon'=>'fa fa-check','color'=>'success','showIf'=>"[is_active] == 'pending'"];
			$this->addaction[] = ['label'=>'Set Pending','url'=>CRUDBooster::mainpath('set-status/active/[id]'),'icon'=>'fa fa-ban','color'=>'warning','showIf'=>"[is_active] == 'Done'"];
	        /* 

if needed in future i ll contact you.
