### ISSUE TITLE
Multicolumn form

### ISSUE THREAD

**Issue by chhetripurna** [crocodic-studio/crudbooster#436]
I want to make the form as shown below in CB. Any help please?
![image](https://cloud.githubusercontent.com/assets/18228974/25512154/72d3169c-2bed-11e7-8e0a-1326d41bc2d4.png)

**Comment by fherryfherry** [comment]
Unfortunately you can't instead of create your own view by overriding the edit / add view

**Comment by chhetripurna** [comment]
thank you for the info

**Comment by topo79** [comment]
@fherryfherry I was reading the documentation to override the add/edit methods, my question here is if there is any way that I can create a new add button, so I can have the normal add and a new add that will show me the new view.
