### ISSUE TITLE
can i show data in public

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#439]
i have table called 'employee'.  can i show data to public without login,  which is inside the employee table.

please help me to show data in public

**Comment by davodavodavo3** [comment]
You want show data wich is inside table employee.
Where you want show that data(what is public?)

**Comment by kinden** [comment]
i want see the data without login.  or how can i show data in this page. 

![public](https://cloud.githubusercontent.com/assets/27999833/25553051/434b6166-2ccb-11e7-8f38-856043503cf7.PNG)

**Comment by kinden** [comment]
Any Idea davodavodavo3  and Fherry.

**Comment by fherryfherry** [comment]
Why you didn't create it self since crudbooster is a backend
Pada tanggal 1 Mei 2017 10.06, "kinden" <notifications@github.com> menulis:
