### ISSUE TITLE
Module builder don't  see the mysql tables created by myself

### ISSUE THREAD

**Issue by FastHarryson** [crocodic-studio/crudbooster#44]
When I trying to add a new module and form let me to choose previously created table there is no any table created by myself in phpyadmin. Objectively they are, but CrudBooster module builder not update this information. How can I initiate CB to refresh tables from the database? Thanks in advance!

**Comment by fherryfherry** [comment]
What is your specification ? OS, Xampp, CRUDBooster version ?

**Comment by FastHarryson** [comment]
Debian 8 x86_64, Apache 2.4.10,  MySQL 5.5.46, PHP 5.6.17, PERL 5.20.2, CRUDBooster v5.2.12.1

**Comment by fherryfherry** [comment]
I think you must check your laravel database credential at .env file, maybe you've set incorrect database..

**Comment by fherryfherry** [comment]
Also please update the latest CRUDBooster

**Comment by FastHarryson** [comment]
Thnx for the right direction! It was my mistake: edited localhost db, but checking results from the remote).
