### ISSUE TITLE
unique 

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#441]
i know this is repeated issue rise.  when i edit with unique column, it say already taken.  it is latest update version.  when edit it should not give such message 

![um](https://cloud.githubusercontent.com/assets/27999833/25554640/f0cc1312-2cf3-11e7-9ca9-c135674c8d82.PNG)

**Comment by soraaa** [comment]
It would be better if unique field is given option to set to readonly when in edit mode. Just suggestion

**Comment by fherryfherry** [comment]
all inputs can set readonly by using "readonly"=>true

**Comment by soraaa** [comment]
If I put **"readonly"=>true**, the field will be readonly also in _add data mode_. What I'm trying to say is, is there any way to set certain field to readonly in _edit mode only_, while in add mode user can input text?
Once user input text, the field can't be edited.

**Comment by fherryfherry** [comment]
```php
if(CRUDBooster::getCurrentMethod() == 'getEdit' && CRUDBooster::getCurrentId()) {
$this->form[] = ['label'=>'Label','name'=>'name','readonly'=>true];
}else{
$this->form[] = ['label'=>'Label','name'=>'name'];
}
```

**Comment by soraaa** [comment]
Thanks, that's what I'm looking for :smiley::+1:

**Comment by kinden** [comment]
where should i put validation, 
'validation'=>'required|unique:patient'. 
when i put in second form it give same as before.

**Comment by kinden** [comment]
i have put like this 


if(CRUDBooster::getCurrentMethod() == 'getEdit' && CRUDBooster::getCurrentId()) {
	$this->form[] = ['label'=>'CID','name'=>'CID','readonly'=>true];
	}else{
	$this->form[] = ['label'=>'CID','name'=>'CID','type'=>'text','validation'=>'required|unique:patient','width'=>'col-sm-4'];
	}

but it give CID already taken ,,,, while i edit. actually it should except.

**Comment by soraaa** [comment]
@fherryfherry has made commit to **_src/controllers/CBController.php_** you should do the same thing to your file
Here is the source, [click me](https://github.com/crocodic-studio/crudbooster/commit/29c5dbe0043364aad8b9856ad90006937949d0ca)

**Comment by kinden** [comment]
should i add this CBController code to My project CBController

**Comment by kinden** [comment]
Dear Soraa And Fherry,

i have download your NEW CBContoller.php and pest on my project, but still it give same like before : " CID already taken". while edit


![unique](https://cloud.githubusercontent.com/assets/27999833/25649612/c57e9506-2ff8-11e7-828f-08fa2abdda01.PNG)

code in controller:

if(CRUDBooster::getCurrentMethod() == 'getEdit' && CRUDBooster::getCurrentId()) {
$this->form[] = ['label'=>'CID','name'=>'CID','readonly'=>true];
	}else{
$this->form[] = ['label'=>'CID','name'=>'CID','type'=>'text','validation'=>'required|unique:patient','width'=>'col-sm-4'];
	}

please help me

**Comment by fherryfherry** [comment]
```php
if(CRUDBooster::getCurrentMethod() == 'getEdit' && CRUDBooster::getCurrentId()) {
$this->form[] = ['label'=>'CID','name'=>'CID','validation'=>'required|unique:patient','readonly'=>true];
}else{
$this->form[] = ['label'=>'CID','name'=>'CID','type'=>'text','width'=>'col-sm-4'];
}
```

**Comment by kinden** [comment]
but it except while i add Data with same CID. actually it should not except

**Comment by fherryfherry** [comment]
add validation into both of form

**Comment by kinden** [comment]
if i put in both form, it work while i add new data with same CID, But it dose not work in editing

**Comment by kinden** [comment]
if(CRUDBooster::getCurrentMethod() == 'getEdit' && CRUDBooster::getCurrentId()) {
$this->form[] = ['label'=>'CID','name'=>'CID','validation'=>'required|unique:patient','readonly'=>true];
}else{
$this->form[] = ['label'=>'CID','name'=>'CID','type'=>'text','validation'=>'required|unique:patient','width'=>'col-sm-4'];
}

**Comment by kinden** [comment]
actually i want that, when i add new data with same CID, it should not except but when i edit that same data it should except .

**Comment by kinden** [comment]
Any Idea, Dear Fherry

**Comment by fherryfherry** [comment]
wait it seems I got that bug, I'm on it

**Comment by kinden** [comment]
1.    i have copy your CBController  and PrivilegeController  and pest on my project.  but it give error. 

![erro](https://cloud.githubusercontent.com/assets/27999833/25690412/d40cca7e-30b2-11e7-9a27-dfa64f8d4ad8.PNG)

2. i used below form 	

if(CRUDBooster::getCurrentMethod() == 'getEdit' && CRUDBooster::getCurrentId()) {
$this->form[] = ['label'=>'CID','name'=>'CID','validation'=>'required|unique:patient','readonly'=>true];
}else{
$this->form[] = ['label'=>'CID','name'=>'CID','type'=>'text','validation'=>'required|unique:patient','width'=>'col-sm-4'];
}

**Comment by fherryfherry** [comment]
I suggest you update to the latest version instead of copy file by file

**Comment by kinden** [comment]
how to use form in validation

**Comment by soraaa** [comment]
Try this one

```php
if(CRUDBooster::getCurrentMethod() == 'getEdit' && CRUDBooster::getCurrentId()) {
$this->form[] = ['label'=>'CID','name'=>'cid','readonly'=>true,'type'=>'text','validation'=>'required|unique:patient','width'=>'col-sm-4'];
}else{
$this->form[] = ['label'=>'CID','name'=>'cid','type'=>'text','validation'=>'required|unique:patient','width'=>'col-sm-4'];	
}
```

**Comment by kinden** [comment]
Thanks Fherry and Soraaa, it work now, but i have got other problem in  datamodal_column after update latest.

**after update**
1.before click on brows

![modal](https://cloud.githubusercontent.com/assets/27999833/25694115/c237c8c8-30ce-11e7-8cf2-632515abd9a3.PNG)

2. after clicking on brows

![modal1](https://cloud.githubusercontent.com/assets/27999833/25694118/c3a34214-30ce-11e7-811b-df5202f3b36a.PNG)


**before update:**

![b](https://cloud.githubusercontent.com/assets/27999833/25694199/46781804-30cf-11e7-8126-30ad390bee40.PNG)

![b1](https://cloud.githubusercontent.com/assets/27999833/25694200/48070324-30cf-11e7-93d0-c8d0ca3ae0dc.PNG)

**Comment by fherryfherry** [comment]
If you think this issue was solved please close, and open with your new issue

**Comment by kinden** [comment]
ok thanks...
