### ISSUE TITLE
Filter to check if field is empty

### ISSUE THREAD

**Issue by Muhammadinaam** [crocodic-studio/crudbooster#451]
in grid (table) view, filter does not work correctly if we apply filter to check if column is empty.

**Suggested fix**

**I added following on line 330 in table.blade.php**

`<option {{ (CRUDBooster::getTypeFilter($col["field_with"]) == 'empty')?"selected":"" }} value='empty'>Empty ( or Null)</option>`

Then Please see the following code in CBController.php

`
```
$filter_column = Request::get('filter_column');
$result->where(function($w) use ($filter_column,$fc) {
	foreach($filter_column as $key=>$fc) {

```
		$value = @$fc['value'];
		$type  = @$fc['type'];

//**********************************
// new code below

if($type == 'empty')
{
  $result->whereNull($key)->orWhere($key,'=', '');
  continue;
}

//**********************************

		if($value=='' || $type=='') continue;

		if($type == 'between') continue;

		switch($type) {
			default:
				if($key && $type && $value) $w->where($key,$type,$value);
			break;
			case 'like':
			case 'not like':
				$value = '%'.$value.'%';
				if($key && $type && $value) $w->where($key,$type,$value);
			break;
			case 'in':
			case 'not in':
				if($value) {
					$value = explode(',',$value);
					if($key && $value) $w->whereIn($key,$value);
				}
			break;
		}

	}
`});`

CRUDbooster is very nice project and I want to contribute to it. But right now I am very busy for next 6 months (so cannot create Pull Request)
`

**Comment by fherryfherry** [comment]
ok I wil add, but it would better like bellow: 
```
$result->where(function($w) use ($key) {
$w->whereNull($key)->orWhere($key,'');
});
```

**Comment by Muhammadinaam** [comment]
Thanks for committing but I think,  your following code will not work:

`case 'empty':							
$w->whereNull($key)->orWhere($key,'');	
break;`


**because of following code on line No. 329**

if($value=='' || $type=='') continue;

as above line is skipping the loop and your new add code will not be executed.

**Comment by fherryfherry** [comment]
Oh i see
