### ISSUE TITLE
problem when I insert null value second date

### ISSUE THREAD

**Issue by hunterbit** [crocodic-studio/crudbooster#456]
In this pic there in problem when I use two date field and second I want set a NULL.
![error](https://cloud.githubusercontent.com/assets/3189486/25599183/61ec36f2-2eda-11e7-85de-beaebaf35e9a.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/3189486/25599184/61ef4d42-2eda-11e7-842e-f1f51dbc6ddb.png)

**Comment by davodavodavo3** [comment]
what is your database platform? mysql?

**Comment by hunterbit** [comment]
Yes my database is MySql

Il 02 Mag 2017 02:10, "Scorpion" <notifications@github.com> ha scritto:

**Comment by davodavodavo3** [comment]
ok, use in your controller hook_before_edit method like this
```
public function hook_before_edit(&$postdata,$id) {

            if($postdata['date_saldo']==''){

                $postdata['date_saldo'] = null;

            }
}
```

**Comment by davodavodavo3** [comment]
if that work for you?

**Comment by hunterbit** [comment]
Yes, thanks with your code I have to resolve problem.

**Comment by davodavodavo3** [comment]
Super if you dont have an questions please close the issue
