### ISSUE TITLE
Session is getting out too fast

### ISSUE THREAD

**Issue by faizan-shah** [crocodic-studio/crudbooster#460]
Once i logged in session get out i n just few seconds , i am using laravel 5.4 and latest crudbooster

**Comment by fherryfherry** [comment]
If you open browser tab with crudbooster page more than one, it might cause
that issue, maybe session in other tab had timeout, and you tried to login
on the other browser tab
Pada tanggal 3 Mei 2017 01.29, "faizan-shah" <notifications@github.com>
menulis:
