### ISSUE TITLE
Klik show Password 

### ISSUE THREAD

**Issue by andrinda** [crocodic-studio/crudbooster#462]
hai guys,how to click show password if this click show password if not and not show password 
how to implementation and generate insert password :) ?
![screen shot 2017-05-03 at 12 02 33 pm](https://cloud.githubusercontent.com/assets/4930514/25648696/f1aa1c22-2ff8-11e7-8cd9-65ced904c92e.png)

**Comment by fherryfherry** [comment]
password must be a hash (as we know a security reason), 
it means you can't see the password in a plaintext

**Comment by andrinda** [comment]
yes i know must be a hash but how to input password modified just crud and generate password :)
and show password if just want show

**Comment by kinden** [comment]
Your can used MD5 in database, if you use php myadmin(Mysql)
