### ISSUE TITLE
Custom Page

### ISSUE THREAD

**Issue by hunterbit** [crocodic-studio/crudbooster#465]
Hello to all,
I wanted to ask how you can do to add a custom page to crudbooster without using the modules. Also can you use custom queries for the tables that are created with crudbooster?

Thank you.

**Comment by fherryfherry** [comment]
have you read the documentation?

**Comment by hunterbit** [comment]
I have read the documentation but I want an index that uses the same type of table used in the default index. Also maybe in my case it would just be enough to just change the query.

In practice I have a list of transactions and each transaction is linked to a customer.
I would like to create a page where my table does not have to see individual movements but I must give the total for each customer.

I hope I have explained myself better.

Thank you.

**Comment by hunterbit** [comment]
Hello,
maybe I explained myself wrong. I would like to use the getIndex method not a simple table but I would like to use my own query and for the data display part I would like to use Datatables.

Thanks

**Comment by fherryfherry** [comment]
1. You can modify the current query by using hook_query_index method (read the doc)
2. Unfortunately, you can't implement the Datatables plugins as default grid data table, since CB just implement the bootstrap table

**Comment by hunterbit** [comment]
Hello,
I've seen the method but from the example I can only see how to add conditions, but how can I edit the query with my custom? I would need to enter a query that I need to run a GROUP BY to get totals per customer.

While for the table I would like to use the same table used by CB and so does Bootstrap well.

**Comment by hunterbit** [comment]
Hello to all,
I would like to do such a thing in the method to have the table with the data I want.
`/*
	    | ---------------------------------------------------------------------- 
	    | Hook for manipulate query of index result 
	    | ---------------------------------------------------------------------- 
	    | @query = current sql query 
	    |
	    */
	    public function hook_query_index(&$query) {
	        //Your code here
			
	        $query->groupBy('cliente')
   				->selectRaw('sum(euro) as sum, cliente, movimento.id');
	    }`

**Comment by Wayaans** [comment]
have you solve this issue? i been getting this issue too
