### ISSUE TITLE
Question: Add registeration function

### ISSUE THREAD

**Issue by royhudayana** [crocodic-studio/crudbooster#467]
Can i add or enable so that users can register for an account?
And how do i make it so that when a user enters data in one of the modules, that data belongs only to that users and is not viewable by other users?

Please make some tutorials on Youtube.
Thanks.

**Comment by fherryfherry** [comment]
1. Unfortunately, CB had no registration feature, instead of creating it by your self
2. Of course, you can by using hook_query_index, for more tutorial you can learn by watching the video that related to it, check it out at youtube channel crudbooster

**Comment by royhudayana** [comment]
Please make some tutorials on about how to make registeration feature that embeded with CB. 

and thanks for your response.
