### ISSUE TITLE
CB.php helper not loaded

### ISSUE THREAD

**Issue by Dmarthaller** [crocodic-studio/crudbooster#469]
Hi, I'm working with CrudBooster for the first time and have installed the product. While attempting to add a new user I have encountered the following error:

FatalErrorException in CBController.php line 800:
Class 'crocodicstudio\crudbooster\controllers\CB' not found

I believe that the CB.php helper is not being loaded. Any ideas?

**Comment by fherryfherry** [comment]
please update to the latest version

**Comment by Dmarthaller** [comment]
As the current update instructions suggest 
 composer require crocodicstudio/crudbooster=5.3.2.*

Would I use instead 
 composer require crocodicstudio/crudbooster=dev-master

Is the correct?

**Comment by Dmarthaller** [comment]
Thank you this solved my problem
