### ISSUE TITLE
After Generate Modul, Add Data and Edit Data Error

### ISSUE THREAD

**Issue by ireene83** [crocodic-studio/crudbooster#470]
1/1
FatalErrorException in 00679f6cfaba495d65b764c1e11adaad63486c88.php line 2:
syntax error, unexpected 'text' (T_STRING)

**Comment by ireene83** [comment]
I Found that error if data type set money

Please, give me solution...thanks..

**Comment by davodavodavo3** [comment]
@ireene83 are you here?

**Comment by davodavodavo3** [comment]
You update CB to last version or you install fresh?

**Comment by ireene83** [comment]
Yes, I have used the last version ( v5.3.2.28 ) and fresh install..it's bug?

**Comment by davodavodavo3** [comment]
yes
