### ISSUE TITLE
How to add search field in CB dashboard

### ISSUE THREAD

**Issue by chhetripurna** [crocodic-studio/crudbooster#474]
![image](https://cloud.githubusercontent.com/assets/18228974/25688984/771e98ea-30a5-11e7-9af4-59f928d657a3.png)

**Comment by fherryfherry** [comment]
Unfortunately, you can't do that, instead of creating your own view

**Comment by chhetripurna** [comment]
thanks

**Comment by devamit2018** [comment]
how to get crud booster search in view page?from crud booster i used search field from index.blade.php but after running it returns nothing
