### ISSUE TITLE
How to make a checkbox correctly?

### ISSUE THREAD

**Issue by FastHarryson** [crocodic-studio/crudbooster#49]
Hi!
I'm trying to create simple todo module.
I create a table migration with a finish status field:
`$table->boolean('complete')->default(false); // in DB it have a type tinyint(1)`
Then in controller I trying to add a checkbox not checked by default:
`$this->form[] = array("label"=>"Done","name"=>"complete","type"=>"checkbox","required"=>FALSE,"dataenum"=>array(0,1),"default_value"=>0);`

But it gives me 2 checkbox labled 0 and 1. I was playing with different variants, but without success. If I set array(0) it shows only one checkbox, but no value is setted. Please, direct me to the right way!

**Comment by fherryfherry** [comment]
You may want try this
```
$this->form[] = array('label'=>'Done','name'=>'completed','type'=>'checkbox','required'=>true,'dataenum'=>['0|Not Yet','1|Completed'],'value'=>'0');
```

**Comment by fherryfherry** [comment]
Sorry, if you decide to make a checkbox, you should define your table columns as varchar / string instead integer

In CB, checked checkbox values will be implode and sparate with " ; "

If you decide to make something status, you must be use "radio" instead "checkbox"
