### ISSUE TITLE
Documentation error: how-to-many-to-many

### ISSUE THREAD

**Issue by faustol** [crocodic-studio/crudbooster#493]
Dear,
In the example https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-many-to-many.md

$this->form[] - ['label'=>'Name','type'=>'text','name'=>'name'];
$this->form[] = ['label'=>'Description','type'=>'textarea','name'=>'description'];
$this->form[] = ['label'=>'Actors','type'=>'select2','datatable'=>'actors,name','relationship_table'=>'films_actors'];

In the select2 row, the name attribute must be set to work.
The correct is:
$this->form[] = ['label'=>'Actors','name'=>'Actors','type'=>'select2','datatable'=>'actors,name','relationship_table'=>'films_actors'];

**Comment by topo79** [comment]
@faustol how do you present this on the columns?
