### ISSUE TITLE
Allow member to change own profile

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#498]
i make different privilages for admin and member, i want member can edit their own profile such a password or name, but in profile menu of member privilages there is save button appear. how i can show it to member to allow it change their profile ?

![image](https://cloud.githubusercontent.com/assets/24912478/25788850/5922d746-33d6-11e7-8c1a-8d2a8427a304.png)

**Comment by chhetripurna** [comment]
you can set the privilege role of the member for users to edit and update.

**Comment by AdnanSyarief** [comment]
It Works....
many thanks to you chhetripurna 

![image](https://cloud.githubusercontent.com/assets/24912478/25833427/7a0faa5e-349b-11e7-82f3-f597bd69d91b.png)

**Comment by AdnanSyarief** [comment]
i Have problem to in here... can you help me ...
[https://github.com/crocodic-studio/crudbooster/issues/503 ](url)

**Comment by fherryfherry** [comment]
Hi @AdnanSyarief please close this issue if you found this solved, you can follow up your other issue at its page

**Comment by AdnanSyarief** [comment]
okay... 👍
