### ISSUE TITLE
After upadate from 5.3.2.28  SummerNote cannot insert image

### ISSUE THREAD

**Issue by limbiz** [crocodic-studio/crudbooster#500]
![summernote_cannot_insertimage](https://cloud.githubusercontent.com/assets/26919884/25797274/adf42d6c-3406-11e7-89e8-3f8736e1f0fe.png)
And i found that the file is stored in `storage/app/2017-05/blahblahblah.jpg`
In summernote script: `url:'{{CRUDBooster::mainpath("upload-summernote")}}',`

**Comment by fherryfherry** [comment]
Do you still face this issue?

**Comment by limbiz** [comment]
New version work great!
