### ISSUE TITLE
Again, help with Helpers function ..

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#508]
i want using helper to get data automatically for each user in my fom... 
for get name i can already use `CRUDBooster::myName()` ...

![image](https://cloud.githubusercontent.com/assets/24912478/25843355/5275c768-34d1-11e7-9833-1a0a5d1e6ff9.png)

now i want get other data from cms_users that different for each member. before i use `DB::Table('cms_users')->first()->username` . but, the data i got for each member is same.

i have some clue that same with me, that is in Profile Menu...
it can get the username different for each member...

![image](https://cloud.githubusercontent.com/assets/24912478/25843549/e4d30cb0-34d1-11e7-9463-05f047797062.png)

i already search where is the function come, but still don't find it.... what is the right script that i must use in my form value=>???? to get that too....

**Comment by fherryfherry** [comment]
To get the current user data you can use 
```php
$currentUser = DB::table('cms_users')->where('id',CRUDBooster::myId())->first();
```

**Comment by AdnanSyarief** [comment]
i try in put like this one

![image](https://cloud.githubusercontent.com/assets/24912478/25852676/5be38524-34f4-11e7-92e6-4f1d642c0e3d.png)

i got this error

![image](https://cloud.githubusercontent.com/assets/24912478/25852696/6c937104-34f4-11e7-9e7d-60a2f6e5748f.png)


i try to change id to 'username', but still not showing

**Comment by fherryfherry** [comment]
Dont put it on value attribute instead put at the previous of array, you
know that the query is just for get the row data object.
Pada tanggal 9 Mei 2017 20.17, "AdnanSyarief" <notifications@github.com>
menulis:

**Comment by AdnanSyarief** [comment]
i still confuse how to use it, so i try make new public function like this one
![image](https://cloud.githubusercontent.com/assets/24912478/25883494/64cd134a-3575-11e7-9608-bfb0762041bb.png)

and call it in value
![image](https://cloud.githubusercontent.com/assets/24912478/25883511/7f94b142-3575-11e7-9632-53435dc0bca6.png)

but, still wrong.. i don't know what is the right.....

**Comment by fherryfherry** [comment]
For example
```php
$currentUser = DB::table('cms_users')->where('id',CRUDBooster::myId())->first();
$this->form[] = ['label'=>'Label','name'=>'label','value'=>$currentUser->label];
```

**Comment by AdnanSyarief** [comment]
it works....

**Comment by kinden** [comment]
Dear AdnanSyarief, i also want similar to yours, can i get your code.

**Comment by AdnanSyarief** [comment]
same with code above, but i just change the targeting of my table

`$currentUser = DB::table('cms_users')->where('id',CRUDBooster::myId())->first();
			$this->form[] = ['label'=>'NIM','name'=>'id_nim','value'=>$currentUser->username,'readonly' => true,'validation'=>'required','width'=>'col-sm-10'];`

**Comment by kinden** [comment]
should i put in array function

public function array($row ){
	$currentUser = DB::table('patient')->where('id',CRUDBooster::myId())->first();
}

**Comment by kinden** [comment]
i have table called patient and visit. i am getting Name and CID  from patient table in visit controller form.

my code below.. what is the wrong, it is not working
# for Name
$currentUser = DB::table('patient')->where('id',CRUDBooster::myId())->first();
			
$this->form[] = ['label'=>'Name','name'=>'Name','width'=>'col-sm-6','value'=>$currentUser->Name,'readonly'=>true];

#for CID
$currentUser = DB::table('patient')->where('id',CRUDBooster::myId())->first();
			
$this->form[] = ['label'=>'Name','name'=>'CID

','width'=>'col-sm-6','value'=>$currentUser->Name,'readonly'=>true];

![11](https://cloud.githubusercontent.com/assets/27999833/26101338/9c0075fa-3a52-11e7-94c1-7a2ea98b8d8a.PNG)


please help me

**Comment by AdnanSyarief** [comment]
![image](https://cloud.githubusercontent.com/assets/24912478/26101748/72f81744-3a5c-11e7-9234-f9cccd0daea4.png)

this is just i use in my case

**Comment by kinden** [comment]
what about getting from other table,  not user table. i think $currentUser function is used only in user Table. 
i tried same like yours from users table it work, but when i change table Name which i have, it does not work.. do u have nay idea

**Comment by AdnanSyarief** [comment]
how about the value, are you also change it with colomn in yours other table ?
how about try new helpers https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/helpers.md

if it still not work,, you can open new issue

**Comment by kinden** [comment]
my database: patient Table

![12](https://cloud.githubusercontent.com/assets/27999833/26102525/2b540678-3a57-11e7-87d9-6fa77fe7d6c9.PNG)

thanks... AdnanSyarief....  but problem not solved ....
