### ISSUE TITLE
datamodal_where

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#510]
i have another issue in datamodal_where. 

Here i am using datamodal and using 'datamodal_where' condition. when i click next page, it give error.

![pp](https://cloud.githubusercontent.com/assets/27999833/25849450/5ab8cc90-34e0-11e7-8f23-2b7fdb9f9f47.PNG)

code.
	$this->form[] = ['label'=>'PR No','name'=>'Patient_Visit_ID','type'=>'datamodal','validation'=>'required','width'=>'col-sm-7','datamodal_table'=>'visit','datamodal_columns'=>'Patient_Register_ID,Level,Room_Num,Bed_Num','datamodal_columns_alias'=>'Patient Register ID, Level ,Room No,Bed No','datamodal_size'=>'smallda','datamodal_where'=>'is_active != "Examined"'];

first page

![pppp](https://cloud.githubusercontent.com/assets/27999833/25849517/a3235dce-34e0-11e7-8704-8c65661629f9.PNG)

 when i click on next page it give below error.

![ppppp](https://cloud.githubusercontent.com/assets/27999833/25849523/a701a090-34e0-11e7-8e3c-56edf3567f6c.PNG)

but when  i delete 'datamodal_where' condition, it work for next page, but my requirement is needed datamodal_where to show only not equal to "Examined"

**Comment by kinden** [comment]
is this issue resolved ?..

**Comment by fherryfherry** [comment]
yes

**Comment by kinden** [comment]
i have updated latest version just now, but issue does not resolved...please help me

**Comment by fherryfherry** [comment]
I didn't update yet for hours ago, just a minutes ago, please note that end user only can get the latest version only released version.

**Comment by kinden** [comment]
now can i update new version

**Comment by kinden** [comment]
i have updated latest one just now, but still problem not resolved....

**Comment by kinden** [comment]
Thanks fherryfherry.... now it work by changing file.
