### ISSUE TITLE
soft delete problem

### ISSUE THREAD

**Issue by FruitCak3** [crocodic-studio/crudbooster#516]
if i add fieled "deleted_at" in table for use soft delete feature 

everything is work

but when i remove "deleted_at" field in that table

now when i click delete button i have error

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'field list' (SQL: update `test` set `deleted_at` = 2017-05-10 10:30:59 where `id` = 1)

and this problem is appear in some another module (another table/module never have "deleted_at" field)

**Comment by FruitCak3** [comment]
thank you

**Comment by nyelnyelnyel** [comment]
@fherryfherry  hey mate
I'm still having problems with using soft delete even though I already cleared my cache and config
