### ISSUE TITLE
Translation not working for admin/privileges/edit

### ISSUE THREAD

**Issue by maxtzg** [crocodic-studio/crudbooster#518]
seems that translations are not loaded in admin/privileges/edit

![screen shot 2017-05-10 at 20 57 30](https://cloud.githubusercontent.com/assets/28607706/25918437/546bc322-35c3-11e7-888e-d037a602b242.png)

**Comment by andersondeoliveiramachado** [comment]
What language is set in your application?

By default crudbooster has the following:

@dev: ~ $ ls resources/lang /
ar en es id pt_br tr

**Comment by maxtzg** [comment]
en, seems that translations were missing from there, i found them in localization folder and copied. now they are working. file in resources/laong/en/crudbooster.php did not have it. I did upgrade crudbooster using composer to the newest version before the error occured.
