### ISSUE TITLE
Hi, I upload the pdf document via upload_standard. It uploaded successfully how I can show it the datatable like image => true

### ISSUE THREAD

**Issue by mommand** [crocodic-studio/crudbooster#52]

**Comment by fherryfherry** [comment]
You can't show the pdf like image type. But you can show the download
button by using download => true

**Comment by mommand** [comment]
That is great. But I want to change the download btn link.

**Comment by fherryfherry** [comment]
Unfortunately there is no attribute for that.
But you can still custom much more by using hook_row_html method

**Comment by mommand** [comment]
Ok, thanks
