### ISSUE TITLE
value insert 

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#523]
this issue might b repeated,  sorry for that.

i am using data modal, 

![2](https://cloud.githubusercontent.com/assets/27999833/26032539/cc154d02-38b7-11e7-9a58-a0d5451e3a2f.PNG)

Above one is datamodal page in table2 controller form.

![3](https://cloud.githubusercontent.com/assets/27999833/26032540/cd81c634-38b7-11e7-9f7c-56fd30ae58f1.PNG)

when i brows the data it show ID, Name and CID. this data is collected from "table1"

![4](https://cloud.githubusercontent.com/assets/27999833/26032541/cfc07616-38b7-11e7-9b5d-bbbbebe13caa.PNG)

now when i select particular data, i should get 'Name' in Patient Name filed, 'CID' in CID filed and 'ID' in ID filed, but i am only getting Name only, not getting ID and CID. how i can do?...help me

After select above one, now i should insert this all  particular row data in table2.  i have column called PID, CID, and Name in table2.

**Comment by tomatoe45** [comment]
hi there.. try this one..

> https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-make-a-child-form.md

**Comment by kinden** [comment]
without using child form.....
i am getting only same value that is first value. actually i should get particular value when i click in particular row. 

![6](https://cloud.githubusercontent.com/assets/27999833/26041745/290a9ac8-3951-11e7-88fe-21c712238d70.PNG)


![5](https://cloud.githubusercontent.com/assets/27999833/26041693/b50ed756-3950-11e7-8305-1e6f15439e00.PNG)

code:

$Name = DB::table('patient')->value('Name');........(i don;t know how i can get with id)
$CID = DB::table('patient')->value('CID');.................(i don;t know how i can get with id)
			
$this->form = [];$this->form[] = ['label'=>'CID', 'name'=> 'CID','type'=>'number','width'=>'col-sm-6','readonly'=>true,'value'=>$CID];
	
$this->form[] = ['label'=>'Name','name'=>'Name','type'=>'text','width'=>'col-sm 6','readonly'=>true,'value'=>$Name];
			

please help me
