### ISSUE TITLE
Stastics Builder For Non-Superadmin

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#531]
i want make stastics builder that can use for non-superadmin such as admin who have lower level than super admin... i already make their moduls and Menus but, when i start to builder i got alert from CB "Sorry you do not have privilege to access this area ! "

![image](https://cloud.githubusercontent.com/assets/24912478/26070066/672fff38-39cd-11e7-9d15-89569870c4f4.png)

**Comment by tomatoe45** [comment]
try to re-login after assigning your dashboard to specific privileges.

**Comment by AdnanSyarief** [comment]
i try to make in cms_menus that static builder is_dashboard = 1 for privilage 2
when i re-login my dashboard show like this

![image](https://cloud.githubusercontent.com/assets/24912478/26085715/61e749f8-3a10-11e7-8c8b-753d5205db95.png)

but, when i try to click Builder its rollback to dashboard not to the builder...
i think it's wrong 

i also search in database for menus and moduls for dashboard, but i don't find it. just the table of cms_dashboard.... you have any suggest for me to set cms_dashboard for specifics privilages ?

**Comment by AdnanSyarief** [comment]
I've try re-login it but still not change... can you tell me what step by step you use ?
