### ISSUE TITLE
Stastics Builder won't show in dashboard

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#537]
i just make simple panel text in stastics builder in Superadmin buat, when i go to dashboard the panel i make won't show...

![image](https://cloud.githubusercontent.com/assets/24912478/26142825/7f53893c-3b0c-11e7-8b5e-79ad2401fb67.png)

in dashboard

![image](https://cloud.githubusercontent.com/assets/24912478/26142860/a3fb0ae4-3b0c-11e7-93c3-71b49b4310ae.png)

**Comment by tomatoe45** [comment]
have to try to re-login?

**Comment by AdnanSyarief** [comment]
yeah but still wont show... i can solve it now, just make new moduls and menus and i set it to dashboard [ 1 ] in menu management.. thank you

**Comment by fabuhelow** [comment]
Go to **menu management** tab:
Look at **Add Menu** form
Fill the name field 
set the **Type** field to "**Statistic**"
Fill other fields "Color, Icon"
Set Active to **Active**.
Dashboard value **YES**

Then save it and go to dashboard, you should be able to see your widget(s).
![screen shot 2017-06-17 at 1 05 37 am](https://user-images.githubusercontent.com/6513214/27246300-5f50124a-52f9-11e7-917c-f1f78a94225b.png)
