### ISSUE TITLE
[Improvement] Data type time filter

### ISSUE THREAD

**Issue by jdredondo** [crocodic-studio/crudbooster#538]
Hi @ferryferry could you add the filters of "<=", "> =", ">", "<" to the time data type?
![2017-05-17](https://cloud.githubusercontent.com/assets/22225860/26156381/c04961ea-3adb-11e7-87a0-1e27bb55648d.png)

**Comment by ferryferry** [comment]
@jdredondo I thin you mentioned the wrong "Ferry"?

**Comment by jdredondo** [comment]
I'm sorry, you're right @ferryferry , I meant @fherryfherry

**Comment by fherryfherry** [comment]
sorry @jdredondo I don't really understand ....
