### ISSUE TITLE
Date format and value format

### ISSUE THREAD

**Issue by pankaspe** [crocodic-studio/crudbooster#54]
Hi all, how can i customize the output of date format like **d/m/Y** and the value format adding euro symbol? 
The image show my quertion, I want display the column data as **16/10/2016** and the column **Tot. Vendita** as 1230,60€ (or EUR). It's possible?

![format2](https://cloud.githubusercontent.com/assets/7622507/19071281/90f4c5d6-8a2f-11e6-9239-24d44e53f93b.png)

**Comment by fherryfherry** [comment]
Hi,
You can use attribute "callback_php" to modify in each column

example :
``` 
$this->col[] = array('label'=>'Date','name'=>'date','callback_php'=>'date("d/m/Y",strtotime($row->date))');
```

Other example 
``` 
$this->col[] = array('label'=>'Total','name'=>'total','callback_php'=>'$row->total." EUR"');
```

Please make sure while using callback_php, you use the single quote instead of the double quote to avoid PHP execution.

**Comment by pankaspe** [comment]
great! nice man, thank you so much!
it is possible to do inside the form with datepicker field? Now it looks like this, but i want same d/m/Y

![format3](https://cloud.githubusercontent.com/assets/7622507/19078889/07939510-8a52-11e6-8b5d-4b3428495dd0.png)

**Comment by JEEVAN28** [comment]
> great! nice man, thank you so much! it is possible to do inside the form with datepicker field? Now it looks like this, but i want same d/m/Y
> 
> ![format3](https://cloud.githubusercontent.com/assets/7622507/19078889/07939510-8a52-11e6-8b5d-4b3428495dd0.png)

Yes I am also looking for this
