### ISSUE TITLE
How to send mail with attachment files?

### ISSUE THREAD

**Issue by caweb** [crocodic-studio/crudbooster#546]
I am trying to send an email with file attachment. This is my code:
$files = [];
$files[] = public_path(). '/uploads/2017-04/rimac.png';
$data = ['name'=>'John Done','email'=>'john@gmail.com', 'attachments'=>$files];   CRUDBooster::sendEmail(['to'=>'calebsc@gmail.com','data'=>$data,'template'=>'send_quotation']);

but i cant figure out how to do it. Please could you give me an example?

**Comment by fherryfherry** [comment]
try this one
```php
$files = [];
$files[] = public_path(). '/uploads/2017-04/rimac.png';
$data = ['name'=>'John Done','email'=>'john@gmail.com']; 
CRUDBooster::sendEmail(['to'=>'calebsc@gmail.com','data'=>$data,'template'=>'send_quotation','attachments'=>$files]);
```

**Comment by caweb** [comment]
Excellent, thank you very much!

**Comment by akashindolytics** [comment]
hello, I have used this but attachment not getting..is there any variable need for assign in template.
thank you in advance.
$files = [];
$files[] = public_path(). '/uploads/2017-04/rimac.png';
$data = ['name'=>'John Done','email'=>'john@gmail.com']; 
CRUDBooster::sendEmail(['to'=>'calebsc@gmail.com','data'=>$data,'template'=>'send_quotation','attachments'=>$files]);
