### ISSUE TITLE
Relation in chart

### ISSUE THREAD

**Issue by picepice** [crocodic-studio/crudbooster#55]
Good day!

How can i join my tables in chart? Example type= 1 should be type= books, type = 2 should be type = pdf..

and also how to callback date in chart, bar?

Thanks

**Comment by fherryfherry** [comment]
what you mean is joining the table ? you can use "join" attribute
e.g : 
```
$this->col[] = ['label'=>'Book Type','name'=>'type','join'=>'booktypes,name'];
```
or, if you mean like this, so you will be using this 
```
$this->col[] = ['label'=>'Book Type','name'=>'type','callback_php'=>'($row->type==1)?"Books":"PDF"'];
```
unfortunately there is no way to callback function in chart/bar, but you still can try by using mysql query CONCAT in GROUP

**Comment by picepice** [comment]
thanks for the answer.. anyway all of my questions are on chart/bar..

how can i implement this in the chart/bar?

$this->db->select('users.work_id,work.id_worker');     <-- joining users and work table
$this->db->from('users');
$this->db->join(SOME SQL);

its from my codeigniter code and im new to laravel..

**Comment by fherryfherry** [comment]
unfortunately at this time there is no way to do that, but maybe you may try create view for that table

**Comment by picepice** [comment]
ok thanks..
