### ISSUE TITLE
Question: Adding a custom filter button on grid table

### ISSUE THREAD

**Issue by jmbatty** [crocodic-studio/crudbooster#562]
Hello,
First I have to say I think crudbooster is a fantastic product. I'm new at laravel programming and this helps me a lot.

I have built a set of modules to display/edit my data, and I would like to add a button at the top of the grid to toggle a filter to show my records where active = 1 ( my grid shows a bunch of mixed records where active =0 or active =1)

I can add the button thanks to the instructions here
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-add-button-top-grid-data.md

but  I don't know what my next step should be  ? can you provide some guidance ?
Many thanks.

**Comment by arilla** [comment]
You can filter using the hook_query_index function on controller, for the query clause use a session variable o similar.

**Comment by jmbatty** [comment]
Thanks
that's what I ended up doing: set a cookie from the top button
`public function actionButtonSelected($id_selected,$button_name) {
 //cookie setting logic here
}`

and use the hook to define the query accordingly

` public function hook_query_index(&$query) {
	        // only show active employees based on cookie
	        if (Request::cookie('hide_inactive')==1){
	        	$query->where('active', 1);
	        }	
`
 
I just need to find a way now to make a clean transition between clicking the button and refreshing the page.

**Comment by jmbatty** [comment]
i do realize now that actionButtonSelected is not the right place for this.

**Comment by jmbatty** [comment]
ok my solution:

create a function in the controller to handle the cookie
`
public function toggle(){
  ... cookie management code here
}
 `

add a route to handle this function
`
Route::get('admin/employees/toggle', 'AdminEmployeesController@toggle');
`

in the controller, 
`
 public function hook_query_index(&$query) {
        if (Request::cookie('hide_inactive_employee')==1){
	        	$query->where('active', 1);
	        }	
}
`

Thanks for the pointers.
