### ISSUE TITLE
Many to many relation

### ISSUE THREAD

**Issue by picepice** [crocodic-studio/crudbooster#57]
hi.. how to make may to many relation with crudbooster?

**Comment by fherryfherry** [comment]
hi, what do you mean many to many ? in join attribute ?

**Comment by picepice** [comment]
i have a calendar table then in the last field i want to select responsible persons to attend.. then save it to another table the list of users.. and in the view i want to join  users + the list in the calendar table..

calendar + users + list_table
attached is the sample
![relation-n-n](https://cloud.githubusercontent.com/assets/8589745/19219072/5ee63348-8e3c-11e6-957c-56da3db8759f.png)

**Comment by fherryfherry** [comment]
To use the select in form with many to many relationship of table, for example : 
You should create relation module : 
```
$this->form[] = ['label'=>'Film','type'=>'select','name'=>'film_id','type'=>'select','datatable'=>'film,title'];
$this->form[] = ['label'=>'Actor','type'=>'select','name'=>'actor_id','type'=>'select','datatable'=>'actor,fullname'];
```
Then, in film modules you can add "sub_module"
```
$this->sub_module[] = ['label'=>'Film Actors','path'=>'film_actor','icon'=>'fa fa-bars','foreign_key'=>'film_id'];
```
in other hand, at actor module you also can add "sub_module", almost the same value, the different is foreign key
```
$this->sub_module[] = ['label'=>'Film Actors','path'=>'film_actor','icon'=>'fa fa-bars','foreign_key'=>'actor_id'];
```

**Comment by picepice** [comment]
thank you for the reply.. i will try later..

**Comment by Athuli7** [comment]
@fherryfherry, Not working.
ErrorException in 45e73c314bcec9fbacd5efc34d498c1d2e691c3f.php line 36:
Cannot access empty property 
H:\PLCCKochi\AdminPro\vendor\crocodicstudio\crudbooster\src\views\default\index.blade.php)

(View: 
[sub_module.txt](https://github.com/crocodic-studio/crudbooster/files/693290/sub_module.txt)

**Comment by katarot** [comment]
@Athuli7 I also got the same error.
Sooo @fherryfherry  what's up, any ideas?
