### ISSUE TITLE
ID or PRIMARY KEY in single column, always auto incrementing, even it's a string/varchar

### ISSUE THREAD

**Issue by aseptilena** [crocodic-studio/crudbooster#576]
I have been getting a weird problem with the primary key in my tables (for every table that could be added with new records). Every time I insert new record with desired new primary key value, I always got different primary key value inserted. Here are the examples.

![1](https://cloud.githubusercontent.com/assets/6253788/26491545/4ab6cd12-423a-11e7-932a-1798f07b04b8.png)
![2](https://cloud.githubusercontent.com/assets/6253788/26491546/4abbb606-423a-11e7-8696-725ee2729927.png)
![3](https://cloud.githubusercontent.com/assets/6253788/26491547/4ac10282-423a-11e7-9d07-123a6ab820a0.png)
![4](https://cloud.githubusercontent.com/assets/6253788/26491549/4adb3fee-423a-11e7-8ff0-be9542484821.png)
![5](https://cloud.githubusercontent.com/assets/6253788/26491554/4b5ad222-423a-11e7-8789-0b16748d3855.png)
![6](https://cloud.githubusercontent.com/assets/6253788/26491552/4b0696ee-423a-11e7-8a32-ca666028f9be.png)
![7](https://cloud.githubusercontent.com/assets/6253788/26491550/4af968c0-423a-11e7-89e6-eaac9a9fa4a7.png)
![8](https://cloud.githubusercontent.com/assets/6253788/26491551/4afc6b60-423a-11e7-9579-ba75d7a50cd3.png)
![9](https://cloud.githubusercontent.com/assets/6253788/26491553/4b0a0f54-423a-11e7-85b5-1ebd9fef29ba.png)

The further problem is if I changed the primary key column name, I still got the same result of primary key insertion, but if I used an app like the phpMyAdmin to insert new record, I got the desired primary key value. So, I think it's the problem of crudbooster, not my database nor my tables. Here is the example of the table that I have changed (primary key column name, to nomor_register, not id anymore).

![9_1](https://cloud.githubusercontent.com/assets/6253788/26491566/5c4f6fe8-423a-11e7-82fa-e65ad7f29155.png)
![9_2](https://cloud.githubusercontent.com/assets/6253788/26491568/5c67cf2a-423a-11e7-98ab-79b452477165.png)
![9_3](https://cloud.githubusercontent.com/assets/6253788/26491567/5c56c2ca-423a-11e7-9133-36ef7b91932e.png)

Anyone could help me to find the solution?

**Comment by aseptilena** [comment]
Is it the core of the problem?
`public static function insert($table,$data=[]) {
			$data['id'] = DB::table($table)->max('id') + 1;
			if(!$data['created_at']) {
				if(Schema::hasColumn($table,'created_at')) {
					$data['created_at'] = date('Y-m-d H:i:s');
				}
			}`
I found it in...
![screenshot at 2017-05-26 18-13-58](https://cloud.githubusercontent.com/assets/6253788/26492643/5e6b4cb6-423f-11e7-9eec-4f774c5a96c9.png)

**Comment by aseptilena** [comment]
Finally, I found the newId function in the CRUDBooster.php...
`		public static function newId($table) {
			$key = CRUDBooster::findPrimaryKey($table);
			$id = DB::table($table)->max($key)+1;
			return $id;
		}`
So, could I make it normal? I don't need max($key)+1. I just need the value from data input.

**Comment by fherryfherry** [comment]
If you make a deal with a code field, I suggest you to make a diffrent
field between default PrimarKey as we know that is id and Code field
Pada tanggal 26 Mei 2017 20:04, "Ahmad Afief Amrullah" <
notifications@github.com> menulis:

**Comment by aseptilena** [comment]
So, is it enough if I make a primary key that is not in "id" field?

**Comment by aseptilena** [comment]
I have tried that recently, and it won't make my desired result of insertion.

**Comment by aseptilena** [comment]
Oh, I get it. I'm so sorry. I have just realized that I need to make special field for the code and let the id field auto increment.

**Comment by aseptilena** [comment]
Wow, finally, I could make my desire true. Using one of helpers function, g($name). I just SET the $id to g('id'), it could make $id same as the data from GET / POST. Here is my code inside the CRUDBooster.php...
`public static function newId($table) {
			//$key = CRUDBooster::findPrimaryKey($table);
			$id = g('id');//DB::table($table)->max($key)+1;
			return $id;`
Finally..., I got the function from the documentation.
