### ISSUE TITLE
ErrorException in UrlGenerator.php line 314:

### ISSUE THREAD

**Issue by tanjilbhuiyan** [crocodic-studio/crudbooster#58]
installed everything watching youtube video for crud booster, at login page, after entering credential if i click sign in, this error show.
![capture](https://cloud.githubusercontent.com/assets/4042154/19219617/999b21f4-8e39-11e6-87af-42b3dcd774b3.JPG)

**Comment by nealmarques** [comment]
I have the same problem.

**Comment by fherryfherry** [comment]
Its look like the Route file of Crudbooster is missing, you can make sure
the file is already exists in vendor/crocodicstudio/crudbooster/src/

In other hand i will check it

**Comment by nealmarques** [comment]
vendor/crocodicstudio/crudbooster/src/routes.php exists, but the NotificationsControllerGetLatestJson is not in it.

**Comment by fherryfherry** [comment]
Ok, can you describe your php, mysql and laravel version

**Comment by nealmarques** [comment]
php 5.6.10 ( command line in mac) , Laravel 5.2.45, MySQL 5.5.42 - Source distribution

**Comment by fherryfherry** [comment]
please update to [5.2.13.2](https://github.com/crocodic-studio/crudbooster/releases/tag/v5.2.13.2)

**Comment by nealmarques** [comment]
That fixed it for me. Thanks!
