### ISSUE TITLE
Syntax error or access violation: 1066 Not unique table/alias: 'cms_menus'

### ISSUE THREAD

**Issue by harimayco** [crocodic-studio/crudbooster#59]
Hi,
Please help,
I found this error when accessing http://localhost:8000/admin/cms_menus

SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'cms_menus' (SQL: select count(*) as aggregate from `cms_menus` left join `cms_menus` as `cms_menus` on `cms_menus`.`id` = `cms_menus`.`parent_id_cms_menus`)

- laravel fresh install
- crudbooster fresh install
run with php artisan server on windows 10
 
Thank you

**Comment by fherryfherry** [comment]
thanks, fixed in latest version
