### ISSUE TITLE
Displaying data from 2 table in 1 controller and 1 view

### ISSUE THREAD

**Issue by arif-awaludin** [crocodic-studio/crudbooster#595]
i try to make a simple front end, and fortunately there is video tutorial how to create blog home page from crudbooster, and its work well.
But currently i'am trying to display data from 2 different table (its not join).
i think its should be in same function because it will be displayed in home page.
my code is here

      

```
>             Public function getIndex() {
>         	$data['page_tittle'] = 'BERANDA '. $this->web_name;
>         	$data['page_description'] = 'Percobaan test test';
>             $data['blog_name'] = $this->web_name;
> 
>             $data['result'] = DB::table('post')
>         	->join('categories','categories.id','=','categories_id')
>         	->join('cms_users','cms_users.id','=','cms_users_id')
>         	->select('post.*','categories.nama as name_categories','cms_users.name as name_author')
>         	->orderby('post.id','desc')
>         	->take(4)
>         	->get();
> 
>             $data['result'] = DB::table('tagline')
>             ->select('tagline.title as tag')
>             ->orderby('tagline.id','desc')
>             ->take(4)
>             ->get();
```

but it only show one of them, if i put tagline in the top of tagline in the blade template (view) it will only display tagline. and if i put post in the top of page (above the tagline) it will display post only..
i hope somebody can help me 
Thanks

**Comment by tomatoe45** [comment]
hi @arif-awaludin  try to use $data['result1'] and $data['result2'];
