### ISSUE TITLE
Graded Select Boxes In A Form (Parent Select -> Child Select -> Child Select)

### ISSUE THREAD

**Issue by arif-awaludin** [crocodic-studio/crudbooster#598]
I have 3 tables
1. provinsi => id, nama, created_at
2. city => id, provinsi_id, nama, created_at
3. member => id, nama, provinsi_id, city_id, created_at

i want to make graded select box in a form and select it into member table
here is my code:
`
$this->form[] = 		$this->form = [];
			$this->form[] = ['label'=>'Name','name'=>'name','type'=>'text','validation'=>'required|string|min:3|max:70','width'=>'col-sm-10','placeholder'=>'You can only enter the letter only'];
			$this->form[] = ['label'=>'Provinsi','name'=>'provinsi_id','type'=>'select','validation'=>'required','width'=>'col-sm-10','datatable'=>'provinsi,nama','datatable_format'=>'id,\'-\',nama'];
			$this->form[] = ['label'=>'City','name'=>'city_id','type'=>'select','validation'=>'required','width'=>'col-sm-10','datatable'=>'city,nama','datatable_format'=>'id,\'-\',nama','parent_select'=>'provinsi_id'];`

but unfortunately no things show in City fowm when i choose one of Provinsi,
when i change type to select 2 in City, its show all city, not city based on parent_select
i hope anyone can advise me
thanks

**Comment by aseptilena** [comment]
Have you make the foreign keys?

**Comment by aseptilena** [comment]
like using ALTER TABLE

**Comment by aseptilena** [comment]
ALTER TABLE member ADD CONSTRAINT member_provinsi_id FOREIGN KEY (provinsi_id) REFERENCES provinsi(id);

ALTER TABLE member ADD CONSTRAINT member_city_id FOREIGN KEY (city_id) REFERENCES city(id);

and also for city table

ALTER TABLE city ADD CONSTRAINT city_provinsi_id FOREIGN KEY (provinsi_id) REFERENCES provinsi(id);

**Comment by aseptilena** [comment]
just use something like PHPmyadmin or MySQL CLI.

**Comment by arif-awaludin** [comment]
Its Works
Makasih banyak kang
