### ISSUE TITLE
Tried cloning from github, lots of errors

### ISSUE THREAD

**Issue by magusd** [crocodic-studio/crudbooster#6]
1 - It has no server.php for the command php artisan serve
2 - It does not find the execute.php file, so the wizard fails
3 - I've found an htaccess, so you are assuming everyone uses apache and completely ignoring the way laravel does things, I, for instance, do not use xampp or any of those stacks, I run every project from the command line using Laravel Valet or vagrant/docker with NGINX or PHP built in web server.

You have a nice idea and it seems to be going nicely, but if you don't make your installer better and more platform independent, people will just ignore your project and will not even bother to come here and give you a feedback like I'm doing.

**Comment by fherryfherry** [comment]
Thank you for your suggestion, you sure we have modified the laravel so htaccess is important for CRUDBooster at this time. But we will fix it as soon as posible. Thank You.
