### ISSUE TITLE
Edit ERROR

### ISSUE THREAD

**Issue by pepe3lsr** [crocodic-studio/crudbooster#610]
Hi ! First of all, thanks a lot for CRUDBooster!!
Im having trouble with the edit function, when i try to edit some module, i have a 404 error. 
Here is the screenshot.. 
Thanks in advance!

![errorcb](https://user-images.githubusercontent.com/11242034/27167982-fcdea426-5179-11e7-83d3-30abb6a586ed.png)

**Comment by pepe3lsr** [comment]
![image](https://user-images.githubusercontent.com/11242034/27186614-4626991e-51bf-11e7-99b5-5412fbbbb17a.png)

**Comment by richardverolme** [comment]
I have the exact same problem.

**Comment by pepe3lsr** [comment]
Hi @richardverolme !!!
i solve it. 
You have to create the tables by migrations (like you see in the youtube tutorial), when i create the tables by MySql in Phpmyadmin, i get that error. 
https://www.youtube.com/watch?v=nL0h72DJAs0&t=326s

**Comment by mahfoudfx** [comment]
Hello,
I have the same issue. I used migration to create tables, but still get the same problem.
Please help !

**Comment by cagcak** [comment]
I created tables by migrations but still it is throwing exception

**Comment by saeedphr** [comment]
I have this problem too . tables created by migration.
any help ?
