### ISSUE TITLE
cant access admin/login

### ISSUE THREAD

**Issue by versatilegurung** [crocodic-studio/crudbooster#613]
i jus freshly installed laravel on my apache2 and installed crudbooster everything works fine when i use php artisan serve, but when i want to access through apache (ie: localhost) its shows (Not Found The requested URL /admin was not found on this server.)

i tried changing all the .htaccess files as per the documentation of laravel but still am not able to get out of it.

can anyone help me ?

**Comment by franciscoluiz** [comment]
When you access the public folder, appears the Laravel start page?
![laravel](https://user-images.githubusercontent.com/506510/27224121-e40f6da4-5269-11e7-9215-92509ea19204.png)
???


If it did not appear, it means something is wrong and you will not be able to access the admin/login folder...

May be problem with permissions of folders...

Try to put in google "laravel installation blank page" or "laravel installattion permission folders"

I do not remember perfectly but it is related to the permissions of the <project-root>\ public and <project-root>\storage\

Can also be some problem with mod_rewrite: #283

**Comment by adelorenzo** [comment]
I have the same issue and am quite sure it is not a permissions problem. my project folders are all owned by www-data. I use ubuntu and am working on a project on my computer. in my case the Laravel start page does appear but when I add the /admin/login path to the url the same happens to me as described by **versatilegurung** user. The only way I can get access to crudbooster is with the **php artisan serve** command too.

**versatilegurung** did you manage to solve this?

thanks!

**Comment by vitorbrussi** [comment]
test...
localhost/index.php/admin/login

**Comment by adelorenzo** [comment]
ok, so let's say you installed laravel and crudbooster on a folder named **test**, the access on your browser should be:

http://localhost/test/public/admin/login
