### ISSUE TITLE
Question: how to use google analitic in CB

### ISSUE THREAD

**Issue by metinbulak** [crocodic-studio/crudbooster#617]
please anyone help me.
how can I use google analitic with chart and statistic in crudbooster admin panel
or how can I add a controller and view to admin panel

**Comment by rodrigotxt** [comment]
I'm using the [laravel-analytics](https://github.com/spatie/laravel-analytics)
After installing it, through the composer. Just call inside the controlller.
	use Analytics;
	use Spatie\Analytics\Period;

$analyticsData = Analytics::performQuery(Period::create($dateStart,$dateEndf), 'ga:uniqueEvents');

I use this package to fetch data in Analytics and write to my database. But, I also have doubts about generating the chart stats. I'm trying to learn now.
