### ISSUE TITLE
Hi, how I can resize my image when I want to upload it?

### ISSUE THREAD

**Issue by mommand** [crocodic-studio/crudbooster#62]

**Comment by fherryfherry** [comment]
You can resize the image by add url param "w" and or "h"
Eg : /image.jpg?w=300&h=300

**Comment by aagastya-sid** [comment]
how this will work with crudbooster can you please explain?

**Comment by kyphokkinn** [comment]
to resize image
you need to modify function `private static function resizeImage` inside file CRUDBooster.php helper
`private static function resizeImage($fullFilePath, $resize_width = null, $resize_height = null, $qty = 75, $thumbQty = 75)` by change $qty from 100 to 75

and one more step
add `$ext = end(explode('.',$filename));` upper line
 `if (in_array(strtolower($ext), $images_ext)) {`

DONE
