### ISSUE TITLE
Transferring the project to Keenetic Entware error 500

### ISSUE THREAD

**Issue by lybimiy86** [crocodic-studio/crudbooster#622]
I created the project on localhost. Now I want to transfer it to the server on Keenetic Entware. The server is running nginx, php7, mariadb. Projects not on laravel working.
I transfer the project to a folder and when I try to go to the page I get:
`http://192.168.2.1:88/insta/public/ 500 (Internal Server Error)`
Help me run the project. Nginx Settings:
`user  nobody;
worker_processes  1;

#error_log  /opt/var/log/nginx/error.log;
#error_log  /opt/var/log/nginx/error.log  notice;
#error_log  /opt/var/log/nginx/error.log  info;

pid        /opt/var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    index index.php index.html index.htm;

    sendfile        on;
    keepalive_timeout  65;
    gzip on;

    server {
    listen 88;
    root   /opt/share/www;
    location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info   ^(.+?\.php)(/.*)$;
            if (!-f $document_root$fastcgi_script_name) {
         return 404;
      }
    root          /opt/share/www;
           fastcgi_pass   unix:/opt/var/run/php7-fpm.sock;
           fastcgi_index  index.php;
           include        fastcgi_params;
        }
    }	
}
`

**Comment by ryzhovau** [comment]
Looks like nginx mis-configuration. Turn on logging and see `/opt/var/log/nginx/error.log to find out whats wrong`.
