### ISSUE TITLE
How to Hash file upload

### ISSUE THREAD

**Issue by nakamuraagatha** [crocodic-studio/crudbooster#638]
How to hash file upload?

example : file.jpg

result : 6281212.jpg

file or image

**Comment by Equruler** [comment]
In the admin controller, add 'upload_encrypt'=>'true' to the column, the upload file name would become uuid.

For example:
$this->form[] = ['label'=>'Image','name'=>'image','type'=>'upload','upload_encrypt'=>'true','width'=>'col-sm-10'];

**Comment by nakamuraagatha** [comment]
ok thanks. 

but for file pdf can't do that. any setup for pdf file ?

**Comment by nakamuraagatha** [comment]
this issue was solved

**Comment by pl6226** [comment]
how to upload pdf file?
