### ISSUE TITLE
Wrong date on profile window

### ISSUE THREAD

**Issue by topo79** [crocodic-studio/crudbooster#649]
![date](https://user-images.githubusercontent.com/30064865/28049775-8b48e6fc-65c7-11e7-84b4-849bc8354502.JPG)
 and today is July 10th ( also on the server)

**Comment by jdredondo** [comment]
Have you already configured your timezone in the config/app.php file?

**Comment by topo79** [comment]
yes, it is UTC, same as the server, and I am accesing it from a EST so no clue, I think that was a bug since I am not seeing that since I ran an update. will make some comments later

**Comment by pa1more** [comment]
It's standard timezone issue.  
Please update the timezone on hosting server(apache/nginx) and/or on config/app.php . 
It should resolve.

**Comment by topo79** [comment]
I change it and that fixed the issue.
