### ISSUE TITLE
How can I be testing the project

### ISSUE THREAD

**Issue by mozgbrasil** [crocodic-studio/crudbooster#65]
Hello

Good Morning

How can I be testing the project

For now I created a test folder and ran the command to install via composer

How do I run the project?

![captura de tela de 2016-10-18 18-02-08](https://cloud.githubusercontent.com/assets/17202780/19494257/037cf866-955d-11e6-9d14-e8df4c4675bc.png)

**Comment by fherryfherry** [comment]
Hi you may watch the video of How To Install Crudbooster
