### ISSUE TITLE
PLAN TO DEPRECATING "CHILD" TYPE

### ISSUE THREAD

**Issue by fherryfherry** [crocodic-studio/crudbooster#651]
I plan on deprecating/removing "child" in the next version
You know, the child type is still immature, can cause many bugs
I hope you guys may use **[custom view](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-custom-view-add.md)** to create master - detail module

I hope by deprecating this feature, so all of the new users don't get caught in the trouble of this type of child, If they want the feature like this, they can use [custom the view](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-custom-view-add.md)

Maybe we can add this child in the future version, with new concept

What do you think?

**Comment by abenzakour** [comment]
Child compoement  is the most used type in crudbooster.  If you remove it,  crudbooster will be one of all the normal system that create basic application;  not advanced one's. 

In my opinion we leave it and we start another type child2 we work together on it to make it good without problems because we all need master details in our projects.

**Comment by abenzakour** [comment]
Or we can do a good thing 👍 

Child type will be a select with all created module; so if we choose a module it will be shown as a child in the main module. ( all the getadd... ) will be used from the child module controller.

What do you think ?

**Comment by fherryfherry** [comment]
Yes it like a "child" before the existing version, it use any other controller and will be shown in the bellow of main module

**Comment by jdredondo** [comment]
> Child type will be a select with all created module; so if we choose a module it will be shown as a child in the main module. ( all the getadd... ) will be used from the child module controller.

What do you think ?

I think it's a very good idea

**Comment by jdredondo** [comment]
Hello @fherryfherry, can you tell us a little about what is coming for the new version?

**Comment by fherryfherry** [comment]
@jdredondo especially about form structure remake, menu management improvement, bug fixes

**Comment by franciscoluiz** [comment]
I totally and completely agree with @abenzakour  nothing more to say...

@fherryfherry, do you have any idea when all these new changes come out?

**Comment by fherryfherry** [comment]
@franciscoluiz sorry, what idea for do you mean?

**Comment by jdredondo** [comment]
@fherryfherry qué piensas acerca de un comentario que te hice anteriormente de mejorar el listado de datos, esto ayudaría en gran medida a hacer más funcional el componente tipo niño.

> Hi @fherryfherry.
I appreciate your efforts to make CRUDBooster better every day.
I would like that in future versions the data will be listed with Datatables plugins (https://datatables.net/) you can use the yajra datatables-laravel package (https://yajrabox.com/docs/laravel-datatables/6.0) Which would greatly facilitate paging, filtering and search options.
Alternatively you can use the jqwidgets jqgrid plugin (http://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/index.htm)
I leave it to your consideration.
regards

**Comment by fherryfherry** [comment]
@jdredondo I am not sure it can be done in short time especially in next version
The think that I knew that datatables use more complex condition/configuration to customize the columns and or row. You know that HTML is more simply to customize columns and or row. But your suggestion will also note for future

**Comment by abenzakour** [comment]
@jdredondo @fherryfherry   I always suggest to leave current one as a choice in application setting for example, and then add datatable; because there is some people ( speacialy beginers ) who needs HTML version to customize it easly.

**Comment by fherryfherry** [comment]
@abenzakour @jdredondo it's good idea if we can choose in the application if we want to implement the datatable in CB, the homework is we need to make sure all of the features in a regular HTML version are work too in datatable version. For now, I can't image how long code or how hard ist for datatables. Why I say this early because we need to make a priority what we have to build ASAP or not

**Comment by furqon** [comment]
as @abenzakour mention, I think the earlier version using module as child is a better, since component type no need to be re-write and capability is still the same as non-child component.
I'm wondering why the capabilities is dropped.

another thought also, is it better(?) if we kept all variable inside $form in form_body.blade.php and not re-declare.  $form['value'] = instead of $value = 
later on if we want to make call component, we only need to call the $form and get rid of $value, $disabled, $required... etc and use $form['value'], $form['disabled'], $form['required']..

```
<?php
$form = call_value_for_$form['with some column name'];
?>
-- call component type manually, let say select2
@include('crudbooster::default.type_components.select2.component')
```

easier in making custom form page or custom child form
what do you think?

**Comment by Muhammadinaam** [comment]
Please don't remove 'child' component. Otherwise it will become like other Crud generators like Voyager, AdminPanel, Backpack etc. 'Child' component is one of the best things about CRUDbooster. i shifted from Voyager to CRUDBooster because of child component.

I agree with @abenzakour 

> Child compoement is the most used type in crudbooster. If you remove it, crudbooster will be one of all the normal system that create basic application; not advanced one's.
> 
> In my opinion we leave it and we start another type child2 we work together on it to make it good without problems because we all need master details in our projects.

**Comment by fherryfherry** [comment]
Thank you, for your attention guys, I think this discussion is enough. I decided to keep using child, I am looking for the right recipe. 

> Child type will be a select with all created module; so if we choose a module it will be shown as a child in the main module. ( all the getadd... ) will be used from the child module controller.

Will be nice idea

Thanks.

**Comment by Muhammadinaam** [comment]
Again, please don't remove current child component, add child2 component which will be a select with all created module; so if we choose a module it will be shown as a child in the main module. ( all the getadd... ) will be used from the child module controller

I modified current child component a little bit and it looks very nice (Please check **recording.zip** attached.
[recording.zip](https://github.com/crocodic-studio/crudbooster/files/1150367/recording.zip)

I have also attached my modified code. (Please see the attachments)

[crocodicstudio.zip](https://github.com/crocodic-studio/crudbooster/files/1150369/crocodicstudio.zip)
