### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by topo79** [crocodic-studio/crudbooster#653]
I there any plans or if someone already did to integrate LDAP to crud booster it is the ONLY thing I need to put this in production in my environment. Can someone help or recommend any lib package that I may use. much thanks!

and as usual, I am amazed at how good this is!!! it save me TON of time

**Comment by topo79** [comment]
@fherryfherry can you share any way to integrate to ldap, I used the adldap2 on top of crudbooster but I cannot transfer the logged sesssion to the auth on crudbooster. of where I can look fro the session class variables and how to do it. it is the only thing I need to put this on production!!! many thanks!

**Comment by fherryfherry** [comment]
@topo79 the session name that CB used is 'admin_id'

**Comment by topo79** [comment]
@fherryfherry I got that, but the point is that using the adldap2 I was able to authenticate trough ldap, and now I need to connect the authentication on CB or to let the CB that I have a session opened. ( note the adldap2 pulls the user from ldap and place it into the cms_user table, so if I log after that I can do it) do get my point here... I will really reaaaally appreciate if you can help me sort this

**Comment by topo79** [comment]
@fherryfherry any clue on how I can make both coexists or better pass to the crudbooster login the ldap credentials.

**Comment by topo79** [comment]
@jdredondo do you have any idea on how crudbooster manage the session, how can I tell the crudbooster that I am logged in using ldap already and bypass the login page ( crudbooster one ) so I can use only the one that auth use ( I am using Adldap2 and it is working fine, but not telling CB that I am logged in) hope you know since @fherryfherry is ignoring me :( haha

**Comment by jdredondo** [comment]
You should implement your own login to be compatible with Adldap2, currently CRUDBooster is not supported on this feature.

**Comment by topo79** [comment]
thanks for the reply @jdredondo I do have the adldap2 working fine, but one I am logged in I need to let CB that there is an active session ( adldap2 place the users and pwds on the cms_users table too ) so let say that I log in using AD then log out, then try to log in using CB it works since the user and the hashed pwd are on the DBs. so basically m,y point is to know how to let CB get that there is a session there.

**Comment by jdredondo** [comment]
Check the "vendor/crocodicstudio/crudbooster/src/controllers/AdminController.php" file
To guide you.
Specifically in the postLogin method you can guide, so you know how to handle the sessions crudbooster

**Comment by topo79** [comment]
I make it work, I used https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md then I edited the login page the home page and changes the routes, of course, I have to edit the postlogin function. there were so so many changes and trial and error that I cannot identify ( at this time ) the actual changes, I should used git for tracking.

**Comment by Sharmilasrini95** [comment]
@topo79    What is the solution found out?
