### ISSUE TITLE
Chart bar empty

### ISSUE THREAD

**Issue by adelorenzo** [crocodic-studio/crudbooster#656]
I am having trouble with the Chart Bar statistic. I am quite sure the SQL I am using is good but the chart is blank. Any suggestions of what I might be doing wrong?

The SQL code:
`SELECT COUNT(country) AS value, country AS label  FROM  `jobs`  GROUP BY country ORDER BY value DESC`

Thank you!

**Comment by catfishseo** [comment]
Your SQL looks weird: `FROMjobsGROUP` (all together)

**Comment by adelorenzo** [comment]
It's because I am using the github markup to highlight the code. The original SQL statement is:

SELECT COUNT(country) AS value, country AS label  FROM  jobs  GROUP BY country ORDER BY value DESC

and it works ok.  I am still banging my head trying to figure out what is wrong with my chart bar.

Thanks anyway.

**Comment by caweb** [comment]
did you find the solution? I am having the same problem

**Comment by rodrigotxt** [comment]
I was able to make my chart work, in that issue.
#https://github.com/crocodic-studio/crudbooster/issues/778
