### ISSUE TITLE
Doctrine\DBAL\Schema\SchemaException There is no column with name 'created_at' on table 'cms_apicustom'.

### ISSUE THREAD

**Issue by BinSilva** [crocodic-studio/crudbooster#66]
Hi,

Error when migrate
![image](https://cloud.githubusercontent.com/assets/10469144/19573341/a7dc45c8-96e4-11e6-9afb-2a71c0840b23.png)

Any help will be welcome!

**Comment by fherryfherry** [comment]
You must set database credential at .env file,  before migrating...
