### ISSUE TITLE
how can I specify upload folder

### ISSUE THREAD

**Issue by metinbulak** [crocodic-studio/crudbooster#660]
hi,
how can I  specify each upload folder?
for example; upload  all galeria images to GALERIA folder and all slider images to SLIDER folder.

thanks.

**Comment by pbeltrand** [comment]
@topo79 
i have to modify the CBController.php
line 1092: 
$this->arr[$name] = CRUDBooster::uploadFile($name, $ro['encrypt'], $ro['resize_width'], $ro['resize_height'], CB::myId()); 
to
$this->arr[$name] = CRUDBooster::uploadFile($name, $ro['encrypt'], $ro['resize_width'], $ro['resize_height'], CB::myId(), $ro['path']); 

and 

Helpers:CRUDBooster

line 48: 
public static function uploadFile($name, $encrypt = false, $resize_width = null, $resize_height = null, $id = null)
to 
public static function uploadFile($name, $encrypt = false, $resize_width = null, $resize_height = null, $id = null, $path = null)

and 

$file_path = 'uploads/'.$userID.'/'.date('Y-m');   

to

if ($path != null){
                $file_path = 'uploads/'.$path;
}else{
                $file_path = 'uploads/'.$userID.'/'.date('Y-m');    
}


now you can put and extra type in your controller..
path = 'avatars' for example and the code upload the image to that folder.

hope it helps
