### ISSUE TITLE
update or clean install not working

### ISSUE THREAD

**Issue by adelorenzo** [crocodic-studio/crudbooster#662]
Hello Folks,

I just tried updating my project and it crashed. I tried a fresh install of crudbooster and it crashed too. On both cases right after the login page I get the message below:

```
(1/1) InvalidArgumentException
Route [AdminControllerGetIndex] not defined.
```
My environment:

- Ubuntu 17.04
- mysql 14.14
- php 7.0.18
- apache 2.4.25
- running on localhost

Please advise. Thank you!!

**Comment by fherryfherry** [comment]
whoops I'm trying to figure out

**Comment by adelorenzo** [comment]
Cool!! Working now! Thank you so much.
