### ISSUE TITLE
Api Login Problem

### ISSUE THREAD

**Issue by azmigit** [crocodic-studio/crudbooster#664]
I have a problem when i list through API registers everything is normal, but when i login via API always issue the wrong password message like the one in the picture how do i solve it?

If I enter the normal data is not through the API can login, why ?

i used laravel 5.3

<img width="1680" alt="screen shot 2017-07-21 at 11 38 59" src="https://user-images.githubusercontent.com/12572109/28449331-3fa6da8e-6e09-11e7-83bf-05f914034ab0.png">
<img width="1680" alt="screen shot 2017-07-21 at 11 38 38" src="https://user-images.githubusercontent.com/12572109/28449333-3ff00b1e-6e09-11e7-93d6-265a69b88fed.png">

<img width="666" alt="screen shot 2017-07-21 at 11 40 13" src="https://user-images.githubusercontent.com/12572109/28449353-6a400644-6e09-11e7-80df-ab8717b79946.png">

<img width="1680" alt="screen shot 2017-07-21 at 11 36 37" src="https://user-images.githubusercontent.com/12572109/28449312-f6c4ef36-6e08-11e7-973f-e1689583fb24.png">
<img width="1680" alt="screen shot 2017-07-21 at 11 36 46" src="https://user-images.githubusercontent.com/12572109/28449313-f6c6fa88-6e08-11e7-865f-2066c9776066.png">

**Comment by fherryfherry** [comment]
1. Please make sure the password field set to 255
2. Try again to register new data

Note : 
For testing the POST method, you have to use Body params instead of URL Params.

**Comment by azmigit** [comment]
Still can not login why?

<img width="1680" alt="screen shot 2017-07-21 at 12 46 59" src="https://user-images.githubusercontent.com/12572109/28450635-b6527766-6e12-11e7-87ed-5c82b4301777.png">

and i try register from API

<img width="1680" alt="screen shot 2017-07-21 at 12 44 09" src="https://user-images.githubusercontent.com/12572109/28450640-c2c72118-6e12-11e7-9828-4bfc4ee49410.png">
<img width="1680" alt="screen shot 2017-07-21 at 12 43 50" src="https://user-images.githubusercontent.com/12572109/28450676-fad67658-6e12-11e7-9b8b-069bd5a94046.png">

and try login, and still result wrong password..

<img width="1680" alt="screen shot 2017-07-21 at 12 43 50" src="https://user-images.githubusercontent.com/12572109/28450618-984db1ea-6e12-11e7-9db1-39b923e78866.png">
<img width="1680" alt="screen shot 2017-07-21 at 12 44 12" src="https://user-images.githubusercontent.com/12572109/28450718-43e292c8-6e13-11e7-94f8-c4fed5daa72a.png">

but if regis from here:

<img width="1680" alt="screen shot 2017-07-21 at 12 45 36" src="https://user-images.githubusercontent.com/12572109/28450732-6516a3d0-6e13-11e7-8dd3-a6298ad39e6e.png">

and login it's work why ?

<img width="1680" alt="screen shot 2017-07-21 at 12 45 57" src="https://user-images.githubusercontent.com/12572109/28450742-74e72366-6e13-11e7-8b33-f31955da1a4d.png">

**Comment by azmigit** [comment]
@fherryfherry can you help me ? Maybe my feelings happen the difference when making password hashes via API or I wrong setting ?

**Comment by fherryfherry** [comment]
Please update yours I've released new

**Comment by azmigit** [comment]
@fherryfherry how to update ?

**Comment by azmigit** [comment]
how to update ? @fherryfherry

**Comment by azmigit** [comment]
solved Thx 👍 👍 👍 👍  @fherryfherry

**Comment by catfishseo** [comment]
This issue can be closed?

**Comment by waffi** [comment]
@fherryfherry how do you solved this? i have a same problem

**Comment by azarzaza** [comment]
i have updated 5.4.* but still i am getting same error
