### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by lucian-lcr** [crocodic-studio/crudbooster#667]
I have a issue with crudbooster v5.2.13.9 e Laravel 5.2. It happens mostly on Dashboard where some of the dashboard widgets show correctly and others are replaced by the login panel. The "missing widgets" are not always the same, but they generally are the last ones. See attach for details.

When I try to navigate the other pages, sometimes they load and sometimes I am shown the login page. I discovered that the called method is AdminController->getStatisticDashboard($id), which is called for each widget that loads correctly. For the widgets not loaded, it is not called.

![session-problem](https://user-images.githubusercontent.com/8222895/28472544-4935d090-6e41-11e7-884e-54e67d8e13da.png)

**Comment by fherryfherry** [comment]
try to change 'cookie_name' with unique name at config/session.php

**Comment by lucian-lcr** [comment]
I changed the cookie name, cleared all my browser cookies and retried. The problem is still there. Do you have any other suggestion I may try?

**Comment by lucian-lcr** [comment]
I solved the problem. It seems that Laravel 5.2 has some problems with session handling, so the session was closing suddenly after the login. I changed the session engine from file to Redis and this solved my problem. In the .env file, I updated the lines below:

```
CACHE_DRIVER=redis
SESSION_DRIVER=redis
REDIS_PASSWORD=*******

```
