### ISSUE TITLE
Error When i add user

### ISSUE THREAD

**Issue by nakamuraagatha** [crocodic-studio/crudbooster#670]
```
(3/3) QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause' (SQL: select count(*) as aggregate from `cms_users`

```
Any Solution?

**Comment by abenzakour** [comment]
Add delete_at column to cms_users table

**Comment by jdredondo** [comment]
run 
`php artisan config:clear`
and
`php artisan cache:clear`
command in cli

**Comment by nakamuraagatha** [comment]
i use c9io for development.  see my other issue https://github.com/crocodic-studio/crudbooster/issues/669

**Comment by pa1more** [comment]
Add 'deleted_at' in cms_users table

**Comment by nakamuraagatha** [comment]
thanks all.
