### ISSUE TITLE
How to get parameters on API

### ISSUE THREAD

**Issue by azmigit** [crocodic-studio/crudbooster#675]
why i can't get specialis_id from URL parameter ?
look my query on the pic

<img width="1680" alt="screen shot 2017-07-25 at 17 09 29" src="https://user-images.githubusercontent.com/12572109/28567446-7ba530f2-715c-11e7-8c74-9b1c766ddabf.png">
<img width="1376" alt="screen shot 2017-07-25 at 17 09 57" src="https://user-images.githubusercontent.com/12572109/28567452-7f5acfd6-715c-11e7-97c6-1565a27307d5.png">

**Comment by fherryfherry** [comment]
you don't need to add "SQL where query "

**Comment by azmigit** [comment]
@fherryfherry bukan gitu maksud saya mas
jadi gini saya mau ngambil field klasifikasi yg ada di klinik cara ngisi di parameternya kaya gimana ya ?

<img width="1680" alt="screen shot 2017-07-26 at 10 12 12" src="https://user-images.githubusercontent.com/12572109/28602915-1d216d18-71eb-11e7-9ec1-fc1de645125c.png">

sedangkan kalo ngisi kata yg di atas kenanya `pelayanan_klinik`.`klasifikasi` sedangkan field klasifikasi ada di table klinik..

<img width="1680" alt="screen shot 2017-07-26 at 10 12 31" src="https://user-images.githubusercontent.com/12572109/28602954-59be52cc-71eb-11e7-8e6f-f4db9c23fb3c.png">

**Comment by wonderful60** [comment]
@azmigit please modify the type of the klasifikasi field to search

**Comment by azmigit** [comment]
thank you very much it's work @wonderful60

**Comment by catfishseo** [comment]
@azmigit if you don't have more question, you might want to close the issue
