### ISSUE TITLE
edit-save Error Problem

### ISSUE THREAD

**Issue by Cecios0** [crocodic-studio/crudbooster#682]
Hello,
I have installed the latest version and created tables by migrating.
When I editing a field:
Url    http://127.0.0.1/project/public/admin/module-name/edit/id

![1](https://user-images.githubusercontent.com/30531812/28725762-c51f3eda-73be-11e7-9583-dd38b75c3b04.JPG)

Clicking on "save" button returns to an incorrect url and record not saved

http://127.0.0.1/admin/module-name/edit-save

![2](https://user-images.githubusercontent.com/30531812/28725763-c51f592e-73be-11e7-86a2-de40f0bbb989.JPG)

In the previous version this did not happen.
Can you help me ? Thank you

**Comment by catfishseo** [comment]
Can you set your document root to `your-root/public` ?

**Comment by mahfoudfx** [comment]
Hello,
I have the same issue. I used migration to create tables, but still get the same problem.
UPDATE:
After inspecting the generated source of preinstalled cruds (like for roles managment), I found a number after "edit-save/NUMBER"
Here the code who generates error
<form class="form-horizontal" method="post" id="form" enctype="multipart/form-data" action="http://crud.dev/admin/rnd_continent/edit-save/">
And here's the code that works
<form class="form-horizontal" method="post" id="form" enctype="multipart/form-data" action="http://crud.dev/admin/rnd_continent/edit-save/1">
Please, how to correct this issue.

**Comment by mahfoudfx** [comment]
Hello,
I have the same issue. I used migration to create tables, but still get the same problem.
UPDATE:
After inspecting the generated source of preinstalled cruds (like for roles managment), I found a number after "edit-save/NUMBER"
Here the code who generates error
`<form class="form-horizontal" method="post" id="form" enctype="multipart/form-data" action="http://crud.dev/admin/rnd_continent/edit-save/">`
And here's the code that works
`<form class="form-horizontal" method="post" id="form" enctype="multipart/form-data" action="http://crud.dev/admin/rnd_continent/edit-save/1">`
Please, how to correct this issue.

**Comment by sahrulmustakim** [comment]
How solve this bro ?

**Comment by danielraysa** [comment]
![image](https://user-images.githubusercontent.com/24839306/123356120-489aa280-d591-11eb-9db6-b462d04b38d7.png)
I have the same issue, and then trying to read some code behind it. I tried to change $row->id into $id so that value can be read, and it worked.
