### ISSUE TITLE
Change redirect url after login

### ISSUE THREAD

**Issue by ishitat** [crocodic-studio/crudbooster#687]
How do I change the redirect url after login ? Where ? Which file?

**Comment by fherryfherry** [comment]
you can usw CBHook controller at controller dir
Pada tanggal 30 Jul 2017 02.47, "Ishita Thaker" <notifications@github.com>
menulis:

**Comment by ishitat** [comment]
I tried putting redirect in afterLogin function in CBHook. But that doesnt work as there is no return in AdminController getLogin function where the hook is called.

**Comment by fherryfherry** [comment]
You can look my comment at [#683](https://github.com/crocodic-studio/crudbooster/issues/683#issuecomment-318818495)

**Comment by ishitat** [comment]
It worked. For those who are facing the same issue. I am showing what I did.

    public function afterLogin()
    {
        $dashboard = CRUDBooster::sidebarDashboard();
        if ($dashboard && $dashboard->url) {
            return redirect($dashboard->url)->send();
            exit;
        }
    }
