### ISSUE TITLE
Broken image upload on setting page

### ISSUE THREAD

**Issue by harimayco** [crocodic-studio/crudbooster#691]
**Preconditions**
- Fresh install Laravel 5.4.30
- Crudbooster v5.4.0.5

**Steps to reproduce**
- Go to admin > settings > application setting
- Upload image logo
- save

**Expected result**
- logo changed in login screen 

**Actual result**
- image not found. 
Tried to open image in browser "http://cb.dev/uploads/2017-07/1933638857be50f4d180cc5c6db6ae56.jpg"
**Result:** FileNotFoundException
The file "/home/vagrant/code/cb.dev/storage/app/uploads/2017-07/1933638857be50f4d180cc5c6db6ae56.jpg" does not exist
[![screenshot_20170730_154337.jpg](https://s11.postimg.org/3z9c5tlpv/screenshot_20170730_154337.jpg)](https://postimg.org/image/v9undqomn/)

I already cleared the cache, config cache, ran "php artisan crudbooster:update".
Nothing change.

Thanks

**Comment by joxper** [comment]
Hi @harimayco,

I sent a pull request with the fix, the upload path was wrong, #692

**Comment by harimayco** [comment]
Thank you @joxper 👍

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
