### ISSUE TITLE
Change login logo

### ISSUE THREAD

**Issue by ishitat** [crocodic-studio/crudbooster#694]
I want to change the logo in login screen. How should I do it ?

I tried doing this. But it didn't work.
http://crudbooster.com/doc/5.3/override-method-view

**Comment by harimayco** [comment]
you don't need to override any view if you just want to change the login screen logo.
you can go to admin > settings > application setting > Upload Logo.

**Comment by ishitat** [comment]
Thanks

**Comment by ishitat** [comment]
Anyway, I understood that it solves by the way you told me. But why the override method not working. What should be the class name? What class it should extend ? Do I need to change the route for it ?

**Comment by fherryfherry** [comment]
Unfortunately, there is no login view override feature at this time, so you can't override it @ishitat

**Comment by ishitat** [comment]
ok thanks
