### ISSUE TITLE
Images on doc site

### ISSUE THREAD

**Issue by rodrigotxt** [crocodic-studio/crudbooster#698]
Please, correct the url of images in doc site .
e.g: http://crudbooster.com/doc/5.3/create-statistic

Images are directed to:
http://crocodic.net/cbv2/public/uploads/2016-12/cb53cb574c1198482cdc057c061c412f.

The correct would be:
/uploads/2016-12/cb53cb574c1198482cdc057c061c412f.
or
http://crudbooster.com/uploads/2016-12/cb53cb574c1198482cdc057c061c412f.

Thank you.

**Comment by fherryfherry** [comment]
The documentation in the github only
