### ISSUE TITLE
Hi, I want upadate the crudbooster by running composer require crocoicstudio/crudbooster command I get this error message ([InvalidArgumentException]                                                      Could not find package crocoicstudio/crudbooster at any version for your mi     nimum-stability (stable). Check the package spelling or your minimum-stabil     ity  ) 

### ISSUE THREAD

**Issue by mommand** [crocodic-studio/crudbooster#70]
![screen shot 2016-11-12 at 5 15 00 pm](https://cloud.githubusercontent.com/assets/4653953/20237857/b35faef2-a8fb-11e6-96a3-ad74715f3620.png)

**Comment by fherryfherry** [comment]
Hi,
First, please always write the problem detail at description instead in title column sir,

the package should be "crocodicstudio" instead crocoicstudio
