### ISSUE TITLE
[Tanya] Buat link dalam custom view

### ISSUE THREAD

**Issue by andrinda** [crocodic-studio/crudbooster#709]
Salam Sobat CB 👍 

Saya membuat custom view dan ingin membuat link agar menuju link yg input,sudah saya coba tetapi malah tidak bekerja 

`
@extends('crudbooster::admin_template')
@section('content')
  

        

      </form>

      <div class="container">
      <div class="row">
          <div class="col-xs-10">
              <div class="panel panel-primary">
                  
                  <div class="panel-heading">
                      <h2 class="panel-title">
                          Detail Password
                      </h2>
                  </div>
                  <div class="panel-body">
                      <h3>
                          Category : {{$row->category}}
                      </h3>
                  </div>
                      <ul class="list-group">

                      <li class="list-group-item">
                      <h4></h4>
                      <table class="table table-hover">
                          <thead>
                              <tr>
                                  <th>Created</th>
                                  <th>Username</th>
                                  <th>Password</th>
                                  <th>Link</th>
                                  <th>Last Update</th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                  <td>{{ date('d M Y',strtotime($row->created_at))}}</td>
                                  <td>{{ $row->username}}</td>
                                  <td>{{$row->password}}</td>
                                  <td><a href={{("$row->url")}}>link text</a></td>
                                  <td>{{ date('d M Y',strtotime($row->updated_at))}}</td>
                              </tr>
                              <tr>

                              </tr>

                          </tbody>
                      </table>
                      <table class="table table-hover">
                          <thead>
                              <tr>
                                  <th>Notes</th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                  <td><div class="well">{{$row->notes}}</td>

                              </tr>
                          </tbody>
                      </table>

                    </div>
                    <a href='{{g("return_url")}}'{{trans("crudbooster.form_back_to_list",['module'=>CRUDBooster::getCurrentModule()
                    ->name])}} class="btn btn-primary" >Back to List</a></p>

                      </li>
                  </ul>
              </div>
          </div>

@endsection
`
terima kasih semoga ada yg bisa membantu saya :)

**Comment by fherryfherry** [comment]
You have duplicate post, please delete this one :)

**Comment by andrinda** [comment]
Oke Bro @fherryfherry
