### ISSUE TITLE
Hi, my api generator not working give this message (500, Internal Server Error Date: Sat, 12 Nov 2016 12:56:41 GMT Server: Apache X-Powered-By: PHP/5.5.10 Transfer-Encoding: chunked Content-Type: text/html; charset=UTF-8 X-RateLimit-Remaining: 59 Cache-Control: no-cache, private X-RateLimit-Limit: 60 Connection: close  Time taken (in milliseconds): 827) please help me

### ISSUE THREAD

**Issue by mommand** [crocodic-studio/crudbooster#71]
![screen shot 2016-11-12 at 5 28 20 pm](https://cloud.githubusercontent.com/assets/4653953/20237934/79f29cf4-a8fd-11e6-81e8-3f633cb0e513.png)

**Comment by fherryfherry** [comment]
Hi 
please first check by your self to your log server / storage log / etc, you should log the error, then if you found the error location, put them into this issue / create the issue

thanks
