### ISSUE TITLE
insert from different control form

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#718]
i have once table called booking, and its had many column. some column are insert from booking1 control form and once column  are insert from booking2 control form. 

![sss](https://user-images.githubusercontent.com/27999833/29111388-e2bf7a30-7d0b-11e7-9fa0-7fe1ffa353c1.PNG)

above is my table, i can insert data into from booking1 control from... but when it came to booking2 control form,,, i can't insert. i want to insert data to  'Remarks' column from booking2 control form. it give error that other column are not NULL.

code:
$this->form = [];
$bookingt = DB::table('bookingt')->where('id', Request::get('id'))->first();if(!Request::get('id')) {
$this->form[] = ['label'=>'EmployeeID','name'=>'E_Name','type'=>'datamodal','readonly'=>true,
'width'=>'col-sm-6'];
			
	}	

if(CRUDBooster::getCurrentMethod() == 'getAdd') {
$this->form[] = ['label'=>'Name','type'=>'text','name'=>'E_Name','value'=>$bookingt->E_Name,
'readonly'=>true,'width'=>'col-sm-6'];
			}else {
$this->form[] = ['label'=>'Name','type'=>'text','name'=>'E_Name','readonly'=>true,'width'=>'col-sm-6'];
			}
		
$this->form[] = ['label'=>'Remarks','name'=>'Remarks','type'=>'textarea', 'validation'=>'required
|min:1|max:1000','width'=>'col-sm-7'];
		
![dddd](https://user-images.githubusercontent.com/27999833/29111659-f570bbfc-7d0c-11e7-8b0e-d433934e1c0b.PNG)

please help me

**Comment by jdredondo** [comment]
change
`if(CRUDBooster::getCurrentMethod() == 'getAdd')`
by
`if(CRUDBooster::getCurrentMethod() == 'getAdd' and CRUDBooster::getCurrentMethod() == 'postAddSave')`
try it

**Comment by kinden** [comment]
Its not working by change also...i want to insert only Remark not Name. Name is also ready insert from booking1 control. 
![ww](https://user-images.githubusercontent.com/27999833/29153707-d940b1ea-7db0-11e7-9227-9c5e4d3117f7.PNG)

when i click on remarks Button it show below image
![wwwwwwwwww](https://user-images.githubusercontent.com/27999833/29153749-1efa9052-7db1-11e7-96c9-801a12a8f8e2.PNG)


code: 

$this->form = [];
$bookingt = DB::table('bookingt')->where('id', Request::get('id'))->first();
if(!Request::get('id')) {
  $this->form[] = ['label'=>'Employee ID','name'=>'E_Name','type'=>'datamodal',
      'readonly'=>true,'width'=>'col-sm-6'];
			
				}

			

if(CRUDBooster::getCurrentMethod() == 'getAdd') {
        $this->form[] = ['label'=>'Name','type'=>'text','name'=>'E_Name',
     'value'=>$bookingt->E_Name,'readonly'=>true,'width'=>'col-sm-6'];
	}else {
$this->form[] = ['label'=>'Name','type'=>'text','name'=>'E_Name','readonly'=>true,'width'=>'col-sm-6'];
			}

		.....................................	
$this->form[] = ['label'=>'Remarks','name'=>'Remarks','type'=>'textarea', 'validation'=>'required|min:1|max:1000','width'=>'col-sm-7'];.........................(i want to insert only this Remarks data)
