### ISSUE TITLE
Error Bug sub select bertingkat 3

### ISSUE THREAD

**Issue by pandanaran** [crocodic-studio/crudbooster#72]
Saat menggunakan sub_select untuk 3 tingkat misal Provinsi -> Kota/Kab -> Kecamatan, maka pada saat klik edit data atau  detail data, kolom kedua (kota/Kab) tidak muncul datanya.

Terima kasih.

**Comment by fherryfherry** [comment]
halo sudah saya perbaiki pada versi v5.2.13.10 , silahkan diupdate, semoga berhasil

**Comment by aseptilena** [comment]
Maaf, bisa tolong berikan contohnya untuk 2 level, misal ada tabel kategori produk: sayur dan buah

tabelnya...

kat_produk
id | kategori
1 | sayur
2 | buah

produk
id | nama | id_kat
1 | bayam | 1
2 | semangka | 2
3 | wortel | 1
4 | pepaya | 2

**Comment by aseptilena** [comment]
sudah dicoba belum ada efek.

**Comment by fherryfherry** [comment]
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-make-graded-select-box.md
