### ISSUE TITLE
Error using crudbooster:install

### ISSUE THREAD

**Issue by Luizgpp** [crocodic-studio/crudbooster#720]
Hello guys.

when use that command return a error.

` php artisan crudbooster:install

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "crudbooster" namespace.`

I follow the guide and thats happen.

Sorry for the English.

**Comment by harimayco** [comment]
you need to Add the following class, to "providers" array in the file config/app.php
crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class,

https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/installation.md

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Luizgpp** [comment]
I aready Add that line and not work.
This work only a fresh laravel?
Thanks!

**Comment by Sunrise91** [comment]
Same issue, any updates?

**Comment by Luizgpp** [comment]
I did install in other pc and send to Github, and clone it on my PC and its work.

**Comment by vomojola** [comment]
Pls can you share the repository? I will like to clone it as I could not get it to install.
Thank you.

**Comment by Hieunc81** [comment]
Hello,
I have just met the error like yours and fixed it.
Here is the solution:
- Go to & read vendor\crocodicstudio\readme.md
- Don't run php artisan crudbooster:install. Instead, Run:
-> php artisan vendor:publish
-> php artisan vendor:publish --force --provider="crocodicstudio\crudbooster\CRUDBoosterServiceProvider"
-> php artisan migrate --seed
==>Done

Go to domain/admin
or your-local-host /laravelfolder/public/index.php/admin

**Comment by dpmontero** [comment]
php artisan config:cache
php artisan cache:clear

**Comment by dpmontero** [comment]
Try this,

```
php artisan config:cache
php artisan cache:clear
```
