### ISSUE TITLE
how to show many to many relationship data in gird view

### ISSUE THREAD

**Issue by azarzaza** [crocodic-studio/crudbooster#724]
i want to show many to many relotionship data to my gird 

here i am use the film concept 

 i want to retirve the actors add in the flim should display in gird 
how to make this ?

**Comment by azarzaza** [comment]
i have use the hook_query_index
```
$query->join('flim_actor','film.id',"=","flim_actor.film_id")
			->join('actor','actor.id',"=","flim_actor.actor_id")
			;
```

its show tow records in gird

**Comment by azarzaza** [comment]
any one have idea?

**Comment by fherryfherry** [comment]
you mean show the film actors in a single cell, separated with a comma ?

**Comment by azarzaza** [comment]
Yeah

**Comment by fherryfherry** [comment]
```
$this->col[] = ['label'=>'Actors','name'=>"(select GROUP_CONCAT(actor.name) from film_actor join actor on actor.id = film_actor.id_actor where film_actor.id_film = film.id GROUB BY film_actor.id_film) as actors"];
```
have you try subquery with group concat ?

**Comment by azarzaza** [comment]
I will try this

**Comment by azarzaza** [comment]
its working but we can remove the Groupby to avoid Syntax error or access violation:

**Comment by rizkytester** [comment]
> its working but we can remove the Groupby to avoid Syntax error or access violation:

can you give the code for me sir?
