### ISSUE TITLE
Add new, edit form in relationship one-many (not select)

### ISSUE THREAD

**Issue by taimaiduc** [crocodic-studio/crudbooster#73]
Can we set for add and edit a model in a relationship? 
For example. I have a car with many sub-image. When adding new a car the system will load all filed in sub-image table. 

`$this->form[] = array("label"=>"Sub Image 1","name"=>"sub_image1","type"=>"upload_standard","required"=>FALSE,"validation"=>"max:1024|image"); // Load in table relational`

![screenshot-localhost-2016-11-19-22-57-24](https://cloud.githubusercontent.com/assets/10907980/20456563/9282204c-aeab-11e6-9b2a-66b8bcb17fb0.png)

![screenshot-localhost 8000-2016-11-19-22-47-25](https://cloud.githubusercontent.com/assets/10907980/20456566/9baad876-aeab-11e6-852e-69e7bdf949b0.png)

**Comment by fherryfherry** [comment]
Unfortunately, this crudbooster version doesn't have that feature. You may use "sub_module" feature to solve this problem. But it will be an input for us, to available for next version in CRUDBooster 5.3
