### ISSUE TITLE
Add variable value to email content

### ISSUE THREAD

**Issue by topo79** [crocodic-studio/crudbooster#730]
Hi I am sending emails fine, but I need to add to the content a value of a variable. how can I do this?

Is there an additional parameter I can add to this?

$data = [];
				CRUDBooster::sendEmail(['to'=>'myemail@mydomain.com','data'=>$data,'template'=>'templatename','attachments'=>[]]);

**Comment by topo79** [comment]
@fherryfherry, @jdredondo is this possible inside CB or I will need to customize it?

**Comment by jdredondo** [comment]
see this doc
[old doc](http://crudbooster.com/doc/5.3/email-templates)

**Comment by jdredondo** [comment]
you can add more recipients, add to $data array 
`$data = ['name'=>'John Done','email'=>'john@gmail.com' ...];`

**Comment by topo79** [comment]
@jdredondo thanks! I will test that out, now the most important thing I need in order to implement the emails is adding a variable to the email body, basically, I want to include the values of the changes made. Any clue on how to do that?

**Comment by joxper** [comment]
same thing you can pass any variable inside the $data array.

```
$data = ['name'=>'John Done','email'=>'john@gmail.com','changes'=>'text' ...];
```

And then use the variable changes inside the body template

**Comment by topo79** [comment]
@jdredondo @joxper I cannot make this work, this is the code: ( I put fake emails here but real ones on the app) I am getting just one email to whatever address I use on the 'to'=>'' whatever I add to the $data array is just being ignored

$data = ['name'=>'tester','email'=>'tester@tester.com','testresults'=>$testperformed];
					CRUDBooster::sendEmail(['to'=>'test@test.com','data'=>$data,'template'=>'newsubnet','attachments'=>[]]);

here is the email template.

![image](https://user-images.githubusercontent.com/30064865/29433994-54ced22e-836f-11e7-8eb3-4ecda6275fcb.png)

**Comment by topo79** [comment]
@jdredondo @joxper guys any ideas here?

**Comment by fherryfherry** [comment]
You can use alias in the template content. E.g : [customer_name]

Pada tanggal 23 Agt 2017 07.25, "Luis" <notifications@github.com> menulis:

**Comment by topo79** [comment]
@fherryfherry this just work!!! but what I cannot add is the multiple recipients.. 

$data = ['name'=>'tester','email'=>'tester@tester.com','testresults'=>$testperformed];
CRUDBooster::sendEmail(['to'=>'test@test.com','data'=>$data,'template'=>'newsubnet','attachments'=>[]]);

No matter what I put in Data, the email is sent only to the 'to'=>email.

**Comment by topo79** [comment]
Ok this is finally fixed, what I have done is:

edit the CRUDBooster.php line 512 and replaced this

 //$to = $config['to'];
$to = explode(',',$config['to']);

This way you can call the send email like
CRUDBooster::sendEmail(['to'=>'user@email.com,user2@gmail.com','data'=>$data,'template'=>'templateName','attachments'=>[]]);
