### ISSUE TITLE
Package Translation

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [crocodic-studio/crudbooster#74]
Would it be possible for you to accept a pull request to enable package translation ?

Below is an example of what I'm doing, this is the  translation.

vendor/crocodicstudio/crudbooster/src/controllers/AdminController.php

``

ex vendor/crocodicstudio/crudbooster/src/controllers/AdminController.php << END_EX_COMMANDS
/class AdminController
-1
i
use Lang;
.
:%s/'<strong>Dashboard<\/strong> '/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.dashboard_title_strong')
:%s/'Sorry The Configuration Dashboard only Available for Super Admin'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.sorry_the_configuration_dashboard_only_available_for_super_admin')
:%s/<label>LABEL NAME<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.label_name') }}<\/label>
:%s/<label>ICON<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.icon') }}<\/label>
:%s/<label>COLOR<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.color') }}<\/label>
:%s/Select a Table/{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.select_a_table') }}
:%s/<label>TABLE<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.table') }}<\/label>
:%s/<label>AGGREGATE TYPE<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.aggregate_type') }}<\/label>
:%s/<label>COLUMN<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.column') }}<\/label>
:%s/You can use alias session, e.g :/{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.you_can_use_alias_session') }}
:%s/<label>WIDTH<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.width') }}<\/label>
:%s/required select label (for label each side chart), value (for value each side chart), color (for color each side chart). Sparate with comma/{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.required_select_label') }}
:%s/<label>MODULE<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.module') }}<\/label>
:%s/<label>LIMIT<\/label>/<label>{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.limit') }}<\/label>
:%s/title='Edit'/title='{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.title_edit') }}'
:%s/title='Delete'/title='{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.title_delete') }}'
:%s/title='Click for more'/title='{{ Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.title_click_for_more') }}'
:%s/'Your session was expired, please login again !'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.your_session_was_expired_please_login_again')
:%s/'message', 'Sorry your password is wrong !'/'message', Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.sorry_your_password_is_wrong')
:%s/'Sorry, Your password is wrong !'/'".Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.sorry_your_password_is_wrong')."'
:%s/<b>Login<\/b> Page/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.login_page')
:%s/Hi \$user->name, <br\/>/".Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.hi')."  \$user->name, <br\/>
:%s/We're heard that you requested password, this bellow is your new password :<br\/>/".Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.were_heard_that_you_requested_password')."
:%s/You can use this password to login at/".Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.you_can_use_this_password_to_login_at')."
:%s/"Forgot Password/"".Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.forgot_password')."
:%s/'We have sent new password to your email, check inbox or spambox !'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.we_have_sent_new_password')
:%s/'Sorry, unfortunately register is closed !'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.sorry_unfortunately_register_is_closed')
:%s/'Thanks for email confirmation. You can sign in !'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.thanks_for_email_confirmation')
:%s/'Email confirmation failed, please make sure the URL is correct, if this issue continue, please contact Administrator'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.email_confirmation_failed')
:%s/'Register Confirmation Email at '/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.register_confirmation_email_at')
:%s/'Welcome Registration at '/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.welcome_registration_at')
:%s/'Thanks for register, please check your email at inbox or spambox. We have sent an email confirmation, follow the instruction at email'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.thanks_for_register_please_check')
:%s/'Thanks for register, please sign in to start your session'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.thanks_for_register_please_sign')
:%s/'Thank You, See You Later !'/Lang::get('vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.thank_you_see_you_later')
.
w!
q
END_EX_COMMANDS

cat <<EOF > resources/lang/pt-BR/vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.php
<?php

return [

    'dashboard_title'   => 'Painel de Controle',
    'dashboard_title_strong' => '<strong>Painel de Controle</strong> ',
    'sorry_the_configuration_dashboard_only_available_for_super_admin' => 'Desculpe , O Painel de Configuração está disponível apenas para SuperAdmin',
    'label_name' => 'NOME DA ETIQUETA',
    'icon' => 'ICONE',
    'color' => 'COR',
    'select_a_table' => 'Selecione uma Tabela',
    'table' => 'TABELA',
    'aggregate_type' => 'TIPO AGREGADO',
    'column' => 'COLUNA',
    'you_can_use_alias_session' => 'Você pode usar apelidos de sessões, exemplo :',
    'width' => 'TAMANHO',
    'required_select_label' => 'Etiqueta de seleção obrigatória (Para rotular cada gráfico lateral), valor (Para o valor de cada gráfico lateral), cor (Para a cor de cada lado gráfico). Separado com vírgula',
    'MODULE' => 'MÔDULO',
    'limit' => 'LIMITE',
    'title_edit' => 'Editar',
    'title_delete' => 'Excluir',
    'title_click_for_more' => 'Clique para mais',
    'please_wait_loading_datatable' => 'Aguarde o carregamento dos dados',
    'your_session_was_expired_please_login_again' => 'Sua sessão expirou, faça o login novamente!',
    'sorry_your_password_is_wrong' => 'Desculpe, sua senha está errada !',
    'login_page' => 'Página de <b>Login<\/b>',
    'hi' => 'Olá',
    'were_heard_that_you_requested_password' => 'Recebemos um pedido de geração de uma nova senha, esta é sua nova senha:<br\/>',
    'you_can_use_this_password_to_login_at' => 'Você deve utilizar esta senha para conectar em',
    'forgot_password' => 'Recuperação de Senha',
    'we_have_sent_new_password' => 'Enviamos a nova senha para seu e-mail, verifique a caixa de entrada ou de spam !',
    'sorry_unfortunately_register_is_closed' => 'Desculpe, infelizmente o registro está fechado !',
    'thanks_for_email_confirmation' => 'Obrigado pela confirmação por e-mail. Você pode fazer login!',
    'email_confirmation_failed' => 'Falha na confirmação de e-mail, verifique se o URL está correto, se este problema continuar, entre em contato com o Administrador',
    'register_confirmation_email_at' => 'E-mail de confirmação do registro ',
    'welcome_registration_at' => 'Registro de boas-vindas em ',
    'thanks_for_register_please_check' => 'Obrigado por se registrar, por favor, verifique seu e-mail na caixa de entrada ou spambox. Enviamos um e-mail de confirmação, siga as instruções do e-mail',
    'thanks_for_register_please_sign' => 'Obrigado por se registar, inicie sessão',
    'thank_you_see_you_later' => 'Obrigado vejo você mais tarde !'
];
EOF

cat <<EOF > resources/lang/en/vendor_crocodicstudio_crudbooster_src_controllers_admincontroller.php
<?php

return [

    'dashboard_title'   => 'Dashboard',
    'dashboard_title_strong'   => '<strong>Dashboard</strong> ',
    'sorry_the_configuration_dashboard_only_available_for_super_admin' => 'Sorry The Configuration Dashboard only Available for Super Admin',
    'label_name' => 'LABEL NAME',
    'icon' => 'ICON',
    'color' => 'COLOR',
    'select_a_table' => 'Select a Table',
    'table' => 'TABLE',
    'aggregate_type' => 'AGGREGATE TYPE',
    'column' => 'COLUMN',
    'you_can_use_alias_session' => 'You can use alias session, e.g :',
    'width' => 'WIDTH',
    'required_select_label' => 'required select label (for label each side chart), value (for value each side chart), color (for color each side chart). Sparate with comma',
    'module' = > 'MODULE',
    'limit' => 'LIMIT',
    'title_edit' => 'Edit',
    'title_delete' => 'Delete',
    'title_click_for_more' => 'Click for more',
    'please_wait_loading_datatable' => 'Please wait loading datatable',
    'your_session_was_expired_please_login_again' => 'Your session was expired, please login again !',
    'sorry_your_password_is_wrong' => 'Sorry, Your password is wrong !',
    'login_page' => '<b>Login<\/b> Page',
    'hi' => 'Hi',
    'were_heard_that_you_requested_password' => 'We\'re heard that you requested password, this bellow is your new password :<br\/>'
    'you_can_use_this_password_to_login_at' => 'You can use this password to login at',
    'forgot_password' => 'Forgot Password',	
    'we_have_sent_new_password' => 'We have sent new password to your email, check inbox or spambox !',
    'sorry_unfortunately_register_is_closed' => 'Sorry, unfortunately register is closed !',
    'thanks_for_email_confirmation' => 'Thanks for email confirmation. You can sign in !',
    'email_confirmation_failed' => 'Email confirmation failed, please make sure the URL is correct, if this issue continue, please contact Administrator',
    'register_confirmation_email_at' => 'Register Confirmation Email at ',
    'welcome_registration_at' => 'Welcome Registration at ',
    'thanks_for_register_please_check' => 'Thanks for register, please check your email at inbox or spambox. We have sent an email confirmation, follow the instruction at email',
    'thanks_for_register_please_sign' => 'Thanks for register, please sign in to start your session',
    'thank_you_see_you_later' => 'Thank You, See You Later !'
];
EOF
``

**Comment by fherryfherry** [comment]
We will include the translation / localization in upcoming CRUDBooster 5.3
