### ISSUE TITLE
how to graded Province -> District 

### ISSUE THREAD

**Issue by azmigit** [crocodic-studio/crudbooster#742]
How to create a provincial district level using select2 or select box ?

<img width="292" alt="screen shot 2017-08-15 at 10 52 11" src="https://user-images.githubusercontent.com/12572109/29301644-dc9604a8-81a7-11e7-97ed-242027b32e7f.png">
<img width="372" alt="screen shot 2017-08-15 at 10 52 27" src="https://user-images.githubusercontent.com/12572109/29301645-dc9a3ce4-81a7-11e7-807e-3d2a3c8b7e1a.png">

**Comment by jdredondo** [comment]
[see the doc](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-make-graded-select-box.md)
