### ISSUE TITLE
export data with a custom function - how

### ISSUE THREAD

**Issue by jmbatty** [crocodic-studio/crudbooster#744]
Hello
I have a module called reports
in which I have a function to generate a specific report, I want to be able to use the export data button.

```
public function modelHomes(){
$data = [];
$data['export'] = true;
$data['report'] = 'modelHomes';
$data['report_name'] = 'Model Homes';
$data['page_title'] = 'Reports: Model Homes';
$data['result'] = DB::table('report_modelHomes')->orderby('dev_name','asc');
return $this->cbView('admin_reports',$data);
}
```

i have my route set this way

`
Route::get('admin/reports/model-homes', 'AdminReportsController@modelHomes');
`

the export data will always send to admin/reports/ which doesn't have my data set populated

`
form method='post' target="_blank" action='{{ CRUDBooster::mainpath("export-data?t=".time()) }}' 
`

How can I get the export-data to work in this context ? I tried to hardcode the mainpath("admin/reports/ model-homes/export-data...") as a test but ran into routing issues.

Can anyone point me in the proper direction ?
Thanks

**Comment by jdredondo** [comment]
try this
public function modelHomes(){
$this->cbLoader();
$data = [];
$data['export'] = true;
$data['report'] = 'modelHomes';
$data['report_name'] = 'Model Homes';
$data['page_title'] = 'Reports: Model Homes';
$data['result'] = DB::table('report_modelHomes')->orderby('dev_name','asc');
return $this->cbView('admin_reports',$data);
}

**Comment by fherryfherry** [comment]
> $data['result'] = DB::table('report_modelHomes')->orderby('dev_name','asc');

you forgot put ->get() method at the end

**Comment by foubian** [comment]
hello can you help me if you resolve it? i have the same issue

**Comment by marcq64** [comment]
Hi @jmbatty
Would be nice if you could share your solution. It might help us, thanks
