### ISSUE TITLE
how to setting uploads folder path crudbooster on my cPanel

### ISSUE THREAD

**Issue by azmigit** [crocodic-studio/crudbooster#745]
For my assets pindakahkan from vendor to public_html/backend is okay, but to upload image how to do?

<img width="211" alt="screen shot 2017-08-16 at 10 50 18" src="https://user-images.githubusercontent.com/12572109/29351319-73d59f6a-828c-11e7-853d-5212426c9eba.png">
<img width="1680" alt="screen shot 2017-08-16 at 14 06 44" src="https://user-images.githubusercontent.com/12572109/29351320-74117cb0-828c-11e7-9422-30ba9da58873.png">

**Comment by DeveloperOnCall** [comment]
In CPanel the only way I've seen symbolic links added are by using the cron to do it.

Here is an article that might help you get through it.
