### ISSUE TITLE
How do i disable image compression on upload?

### ISSUE THREAD

**Issue by anuj509** [crocodic-studio/crudbooster#753]
how do i disable image compression and resizing on upload button after i created a module using module generator?

**Comment by fherryfherry** [comment]
Please update to the latest and set DEFAULT IMAGE THUMBNAIL to 0, at config/crudbooster.php

**Comment by anuj509** [comment]
and how do i have multiple image uploads and is it possible to integrate dropzone instead? @fherryfherry

**Comment by anuj509** [comment]
by the way thank you for your kind reply. :)

**Comment by fherryfherry** [comment]
Unfortunately, there is no multiple uploads at this time

**Comment by anuj509** [comment]
Ohh this is the only reason i have switch to other crud generator. I hope you integrate multiple uploads feature and much more i wish your team luck and i will also try to contribute in project once i understand whole arch. Thank you for such great platform.
