### ISSUE TITLE
Document for API usage 

### ISSUE THREAD

**Issue by azarzaza** [crocodic-studio/crudbooster#756]
Need a clear document for Api Usage like how to use types validation and how the listing and detail returning the records 
I am working on this is still confusing to retrieve the values

**Comment by topo79** [comment]
API BASE URL + API URL + ? + PARAM NAME = PARAM VALUE & SECOND PARAM NAME = SECOND PARAM VALUE

Read / List API
GET CUSTOMERS

URL: /get_customers
METHOD: GET
PARAMETER NAME: id
PARAMETER TYPE: integer
MANDATORY: yes
DESCRIPTION: based on the customer id responds with all the corresponding information
RESPONSE:

Number | Type | Response Name
-- | -- | --
1 | Integer | api_status
2 | String | api_message
3 | integer | id
4 | String | CustomerName
5 | String | CustomerShortName
6 | String | CustomerDomain

EXAMPLE

Call URL: http://APIBASEURL/get_customers?id=78
Response:
{
•	"api_status": 1,
•	"api_message": "success",
•	"id": 78,
•	"CustomerName": "google",
•	"CustomerShortName": "gl",
•	"CustomerDomain": "google.com"
}

**Comment by azarzaza** [comment]
I am using the read action type when retrieve the particular row of value it's not returning just show the first value of the table

**Comment by topo79** [comment]
@azarzaza post some screenshots, this should not be a problem, also check that you have applied this correction #394

**Comment by azarzaza** [comment]
How to validate the value using types there is no explanation  for type

**Comment by topo79** [comment]
not getting your question.

**Comment by azarzaza** [comment]
Request option has so many validation so how to use the validation to play
with record

**Comment by topo79** [comment]
validation for the params is the type of param, then the response will be either the table column or a SQL subquery with its own type. you need to play with it and find out how this is working
