### ISSUE TITLE
API generator Error !

### ISSUE THREAD

**Issue by azarzaza** [crocodic-studio/crudbooster#757]
I have found the error in API generator
![image](https://user-images.githubusercontent.com/23259321/29531460-42c4c11a-86c6-11e7-9f51-8c558782e4f3.png)
here i am generated the api for reading the details once I generated and editing means the response sub query column  all are to be null for this way none of the value can't return 
only reset the response to retrieve the value 

when you reload the the api edting page the respone part sub query column all to be null. so value return when execute the api 

need to fix this

**Comment by fherryfherry** [comment]
Please update
.
Remove and create again the api

Pada tanggal 22 Agt 2017 00.47, "Mohamed Azarudeen" <
notifications@github.com> menulis:

**Comment by topo79** [comment]
I fixed with this #394
