### ISSUE TITLE
how do not show superadmin on users table?

### ISSUE THREAD

**Issue by vinnyparker** [crocodic-studio/crudbooster#758]
Hi, I dont want to show the superadmin on users table, for it can be update by a non superadmin user.
![captura de tela em 2017-08-22 00-20-52](https://user-images.githubusercontent.com/1207567/29547860-28510eb2-86d3-11e7-860f-35dc55e7dc08.png)

**Comment by vinnyparker** [comment]
I did this on AdminUserController, but  it didn't work. My code

`# START COLUMNS DO NOT REMOVE THIS LINE
		$this->col = array();
		$this->col[] = array("label"=>"Name","name"=>"name");
		$this->col[] = array("label"=>"Email","name"=>"email");
		$this->col[] = array("label"=>"Privilege","name"=>"id_cms_privileges","join"=>"cms_privileges,name","datatable_where"=>"is_superadmin=0");
		$this->col[] = array("label"=>"Photo","name"=>"photo","image"=>1);		
		# END COLUMNS DO NOT REMOVE THIS LINE

		# START FORM DO NOT REMOVE THIS LINE
		$this->form = array(); 		
		$this->form[] = array("label"=>"Name","name"=>"name",'required'=>true,'validation'=>'required|alpha_spaces|min:3');
		$this->form[] = array("label"=>"Email","name"=>"email",'required'=>true,'type'=>'email','validation'=>'required|email|unique:cms_users,email,'.CRUDBooster::getCurrentId());		
		$this->form[] = array("label"=>"Photo","name"=>"photo","type"=>"upload","help"=>"Recommended resolution is 200x200px",'required'=>true,'validation'=>'required|image|max:1000');											
		$this->form[] = array("label"=>"Privilege","name"=>"id_cms_privileges","type"=>"select","datatable"=>"cms_privileges,name",'required'=>true,'datatable_where'=>'is_superadmin=0');						
		$this->form[] = array("label"=>"Password","name"=>"password","type"=>"password","help"=>"Please leave empty if not change");
		# END FORM DO NOT REMOVE THIS LINE`

**Comment by DeveloperOnCall** [comment]
In AdminCmsUsersController.php

After the getProfile() : Add the method:

`public function hook_query_index(&$query) {
        
        if(!CRUDBooster::isSuperadmin()) { // This allows the SuperAdmin to still see himself in the list
            $query->where('cms_users.id_cms_privileges', '<>', '1'); // Adds the restriction 
        }

    }`


Hope that helps...

**Comment by vinnyparker** [comment]
Thank you it works just as I imagine. Thanx a lot

**Comment by ameenhexwhale** [comment]
This works fine. But how to prevent users from creating a new superuser. Thanks

**Comment by DeveloperOnCall** [comment]
Just off the top of my head - I'd recommend using the hook_before_add() method to check user access to adding an account with that privilege.

D

**Comment by dagalumin** [comment]
another simple way could be showing in the privileges combo in the form just the non-superadmin privileges, filtering the query to the privileges table that populates the dropdown:

in file AdminCmsUsersController.php line 34 modify to:
`$this->form[] = array("label"=>"Privilege","name"=>"id_cms_privileges","type"=>"select","datatable"=>"cms_privileges,name",'required'=>true,"datatable_where"=>"is_superadmin<>1");`

in this super simple way nobody (not even the superadmin) can create new superadmins, that in most cases can be ok.
if this is an issue the `datatable_where` can be inserted conditionally just to normal users, checking the helper `isSuperadmin` like explained previously.
