### ISSUE TITLE
Upload on share hosting blank page. 

### ISSUE THREAD

**Issue by taimaiduc** [crocodic-studio/crudbooster#76]
composer create-project --prefer-dist laravel/laravel blog "5.2.*"
Upload on share hosting run ok 
but install crudbooster it gives a blank page any like me ?

**Comment by fherryfherry** [comment]
has successfully install the crudbooster ?

**Comment by taimaiduc** [comment]
yep. In localhost run ok but upload on share hosting blank page. 
Hosting PHP Version 5.6.13.
I have been zip file and upload. Core laravel 5.2.x is ok
Any suggest Sir ?

**Comment by fherryfherry** [comment]
I suspect that the storage folder needs set as writable
/storage
/storage/framework/views
/storage/framework/cache
/storage/logs

**Comment by taimaiduc** [comment]
I have been set 0777 for storage folder and bootstrap folder,
Can we set disable some extensions below ?

> Barryvdh\DomPDF\ServiceProvider::class,
> Collective\Bus\BusServiceProvider::class,
> Maatwebsite\Excel\ExcelServiceProvider::class,
> Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class,
> Intervention\Image\ImageServiceProvider::class,
> crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class,

**Comment by fherryfherry** [comment]
No, you can't, it is how CRUDBooster connects with Laravel

**Comment by taimaiduc** [comment]
So said, I don't know what is wrong. Just blank page when upload. Have you ever upload in share hosting ?

**Comment by fherryfherry** [comment]
yes of course, based on my experience, the problem is some extension/function at the shared hosting are disabled

**Comment by taimaiduc** [comment]
But hard to know what is not correct because it just shows blank page. No error no log :(

**Comment by fherryfherry** [comment]
Hi, try clear these folders
/storage/framework/views
/storage/framework/cache
/storage/logs
