### ISSUE TITLE
Grid Update rate

### ISSUE THREAD

**Issue by topo79** [crocodic-studio/crudbooster#760]
Hey I have to start by saying I am so so impressed on how much I have done with CB, I am having a pro level app in days... 

Now I am facing some situations that I would like to address:

I notice that the grid tables is refreshing every 10 seconds or so, this is nice BUT I am having a small web server with a limited BW and a lot of customers, so I want to stop the refresh or increase the time and then  make users push the show data button to refresh. How can I do that??

I notice that if the user is not using the app for a very long period of time then, based on this update it tries to redirect to login and make ton and tons of request with almost caused a DoS. Help please

**Comment by jdredondo** [comment]
Currently in Crudbooster what is updated every 10 seconds are notifications.
![2017-08-24 1](https://user-images.githubusercontent.com/22225860/29673433-c96ba8f6-88b4-11e7-8df1-b9765f972ad8.png)
If you want to change the update time, you can edit the file `vendor\crocodicstudio\crudbooster\src\assets\assets\js\main.js`
on the line 137.
`$(function() {
  loader_notification();
  setInterval(function() {
	  loader_notification();
  },10000);
});`
regards

**Comment by topo79** [comment]
@jdredondo I found that after some debugging nights lol Thanks!
