### ISSUE TITLE
helper function not working

### ISSUE THREAD

**Issue by azarzaza** [crocodic-studio/crudbooster#762]
helper function ->isColumnExists not working properly when working with api generaotor 
when retireve value thourgh api its only return first value of the table 
the problem is 

in Apicontroller.php

```
if ( $required == '1' ) {
						if ( CRUDBooster::isColumnExists( $table, $name ) ) {
							$w->where( $table . '.' . $name, $value );
						} else {
							$w->having( $name, '=', $value );
						}

```
when checking the columnexists its return false. Because the isColumnExists 
line 706
`$table = CRUDBooster::parseSqlTable($table);`
it returns array so the function return false value 
```
what is the problem in this function ?
```

**Comment by fherryfherry** [comment]
Update your CB

Pada tanggal 23 Agt 2017 17.31, "Mohamed Azarudeen" <
notifications@github.com> menulis:

**Comment by azarzaza** [comment]
i am working with latest version

**Comment by fherryfherry** [comment]
What CB version do you use?

Pada tanggal 23 Agt 2017 17.33, "Mohamed Azarudeen" <
notifications@github.com> menulis:

**Comment by azarzaza** [comment]
5.4.0.7

**Comment by azarzaza** [comment]
Latest version cb

**Comment by azarzaza** [comment]
In crudbooster helper class
IsColumnExists  that's not work in apicontroller
