### ISSUE TITLE
Rename uploaded file

### ISSUE THREAD

**Issue by kezern** [crocodic-studio/crudbooster#763]
I have a module which allows to upload files.
I would like to rename the uploaded file.
I have searched in hook_before_add and I can access posted data, but file is already stored in final location.
Is it possible to rename the file before it is stored?

**Comment by fherryfherry** [comment]
Open the data at hook after add then rename it both of file and data and
save the data

Pada tanggal 23 Agt 2017 18.29, "kezern" <notifications@github.com> menulis:

**Comment by kezern** [comment]
Thanks, I wanted to do without moving, but finally I have used the before hook and moved the file and changed the url in the postdata.
It works!
