### ISSUE TITLE
error after update v5.4.0.8

### ISSUE THREAD

**Issue by caweb** [crocodic-studio/crudbooster#765]
I am getting this error after update v5.4.0.8
please help me to fix it

(3/3) QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'details' in 'field list' (SQL: insert into `cms_logs` (`created_at`, `ipaddress`, `useragent`, `url`, `description`, `details`, `id_cms_users`) values (2017-08-24 04:27:48, ::1, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36, http://creditos.dev:8888/admin/bancos/edit-save/3, Actualizar información Banco Continental en Bancos, <table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody></tbody></table>, 1))

![image](https://user-images.githubusercontent.com/13665382/29649729-a13dbfe4-885b-11e7-9a04-db032282344c.png)

**Comment by fherryfherry** [comment]
Have you run php artisan crudbooster:update ?

Pada tanggal 24 Agt 2017 11.39, "caweb" <notifications@github.com> menulis:

**Comment by caweb** [comment]
Yes I followed this instructions:

Update
Open the terminal, navigate to your project directory.
$ composer require crocodicstudio/crudbooster
Run the following command at the terminal
$ php artisan crudbooster:update

But I just run the following command again:
$ php artisan crudbooster:update

and not it works, for some reason was corrected in the second execution

thank you for your help
