### ISSUE TITLE
users images dont load

### ISSUE THREAD

**Issue by vinnyparker** [crocodic-studio/crudbooster#768]
Hi, I have a issue. when I  send my software to cpanel, my users avatar dont load anymore. 
may it be something with permissions?

![captura de tela em 2017-08-24 11-32-50](https://user-images.githubusercontent.com/1207567/29671465-ff8a97ac-88bf-11e7-88bf-88f4304dc84f.png)

**Comment by pablo-dave** [comment]
Hi @vinnyparker, You should note that the uploads folder inside the public folder hosts a link to the storage folder.
In cpanel you must create a symbolic link of name uploads, that solves the problem

**Comment by chrisowooahr** [comment]
In the crudBooster App go on "Setting" -> "Settings" -> "Application Setting", there you can download the Logo File, if you uploaded one. In my case I got a fatal error 
> FatalErrorException in UploadsController.php line 28: Class 'Image' not found


The Solution that helped in my case, to show all uploaded pictures:

1. Go to config/app.php
2. In _$providers_ add this: _Intervention\Image\ImageServiceProvider::class_
3. in _$aliases_ add this line _'Image' => Intervention\Image\Facades\Image::class_
4. now write in the console: _composer update_

**Comment by vinnyparker** [comment]
I'm gonna try it  thanx a lot
