### ISSUE TITLE
Using the "sub_select" in the forms returns ID on select

### ISSUE THREAD

**Issue by mvscoelho** [crocodic-studio/crudbooster#77]
When use **sub_select**, find-data returns the text with the value of the id, and it is not possible to label the id of the relationship.

Example usage:

```
$this->form = array();
$this->form[] = array('label'=>'Cores','name'=>'id_cores','type'=>'select','datatable'=>'cores,name',"sub_select"=>"id_users", );
$this->form[] = array('label'=>'Usuário','name'=>'id_users','type'=>'select');
```

Result find-data:

```{"items":[{"id":1,"created_at":"2016-11-22 14:39:08","updated_at":"2016-11-22 16:37:10","is_enable":0,"id_cores":1,"name":"My name","email":"email@email.com","password":"","is_admin":1,"text":1}]}```

form_detail.blade.php

```
$.each(resp.items,function(i,obj) {
  var selected = (val && val == obj.id)?'selected':'';
  if(val && val == obj.id) {
    $('#txt_select_{{$name}}').text(obj.text);
  }
})
```

Tks
Marcus Coelho
mococa@gmail.com

**Comment by fherryfherry** [comment]
Hi, you may update to the latest version
make sure sub_select changed to parent_select, you must also set the datatable attr at the children select
