### ISSUE TITLE
Error Widget table statistic

### ISSUE THREAD

**Issue by dagarweb** [crocodic-studio/crudbooster#778]
Hi, I'm working with the latest updated version of crudbooster, I've created a statistic table widget for a very simple view with only two fields and it does not work, it shows nothing at all, just the empty div:

```
<div class='statistic-row row'>
    <div id='area5' class="col-sm-12 connectedSortable">
    </div>
</div>
```

What could be the problem?
Others without, however, like the smallbox if they work without any problem.
Thanks;

**Comment by dagarweb** [comment]
Solvent:
Not found with view database, have direct query of database:
select cms_users.name AS Autor, count(posts.author_id) AS 'Número de posts' from (cms_users left join posts on((cms_users.id = posts.author_id))) Group by cms_users.name Order by count(posts.author_id) desc
Thanks

**Comment by rodrigotxt** [comment]
I know very little about blade templates.
But there is a relationship between these codes and the non-functioning of the graphics.
@push ('bottom')
..... (code)
@endpush

I removed these two codes and my graphics are working now. Before they were only "blank".

Remove @push in the chartbar, chararea, etc.. (components of statistics)
![image](https://user-images.githubusercontent.com/7013329/29902938-7cbd8600-8dd7-11e7-93b3-b463df6d40c6.png)

![image](https://user-images.githubusercontent.com/7013329/29902971-b1165814-8dd7-11e7-810a-8434114cc4be.png)

So, my charts are working now.
![image](https://user-images.githubusercontent.com/7013329/29903084-57290832-8dd8-11e7-9c98-7a68c8472c9e.png)

**Comment by rodrigotxt** [comment]
For those who need SQL example to generate chart, there is mine (it is not how I want it yet, but it works).
```
SELECT SUM(leaf_videos_stats.views) AS 'value', leaf_videos.titulo AS 'label'
FROM leaf_videos_stats
LEFT JOIN leaf_videos ON leaf_videos.id_video = leaf_videos_stats.id_video
GROUP BY leaf_videos_stats.id_video
ORDER BY value DESC
```
![image](https://user-images.githubusercontent.com/7013329/29903192-f1ef925a-8dd8-11e7-906a-4c8868a1b327.png)

![image](https://user-images.githubusercontent.com/7013329/29903204-ff0ac072-8dd8-11e7-9630-ae42f52c14a1.png)

**Comment by paulchicago74** [comment]
@rodrigotxt 
Valeu Rodrigo! Estou tentando utilizar o "file manager" pra fazer o upload the mais the um arquivo ao mesmo tempo. Voce tem conhecimento com o Laravel File Manager? O crudbooster tem a funcao instalada mas nao consigo fazer funcionar.. :(

**Comment by rodrigotxt** [comment]
@paulchicago74 Olha, eu tive problema com o FileManager também, só que não lembro exatamente o que fiz pra resolver. Se não me engano, eu atualizei vários pacotes do laravel pelo composer.
