### ISSUE TITLE
Bulk delete fail if no checkboxes are selected

### ISSUE THREAD

**Issue by topo79** [crocodic-studio/crudbooster#781]
Hi @fherryfherry  I found a bug related to the subject, so if I do not select any checkbox and hit delete on the bulk action I got 
![image](https://user-images.githubusercontent.com/30064865/29802183-c5b4df80-8c41-11e7-8339-3f9c131662cb.png)

So I fixed it by adding the following code to the CBController line 1526 function postActionSelected() 
if ($id_selected==''){
  CRUDBooster::redirect(CRUDBooster::mainpath(),"You must select at least one row","warning");
}

BTW my CB is: 5.3.2.30 and I think that on 5.4 is the same.

**Comment by jdredondo** [comment]
This issue is already fixed in the latest version
