### ISSUE TITLE
Add Row# at tables

### ISSUE THREAD

**Issue by wahidcahyo** [crocodic-studio/crudbooster#787]
Hi, i just want to put some grid number at the left of table.
I try this code
$this->col[] = ["label"=>"Nomor","name"=>"(SELECT @nomor:=@nomor+1 Nomor,a.* FROM antrian a, (SELECT @nomor:=0) b)as Nomor"];
But i cant make it. Its Error.
Can u help me?

**Comment by jdredondo** [comment]
Just add `$this->show_numbering = true;` At the beginning of the cbInit method
