### ISSUE TITLE
Hanging on install

### ISSUE THREAD

**Issue by jerauf** [crocodic-studio/crudbooster#799]
I confirmed that my database setting was in my .env file and my terminal says "Publishing CRUDBooster needs file...". It doesn't go any further.

What could be the problem?

**Comment by pytesin** [comment]
Same here, i can confirm that behavior. 
Tested with Laravel 5.5, PHP 7.0 , fresh install.

**Comment by wa7eedem** [comment]
yes it's in laravel 5.5 , I ended up doing the publishing manual .

**Comment by jerauf** [comment]
Publishing manual?

Mine is in 5.4.

**Comment by wa7eedem** [comment]
yes .. its not Ideal but its did the job ..

you need to run 
`php artisan vendor:publish`

and create`symlink` for the folders `storage/app` and `vendor/crocodicstudio/crudbooster/src/assets` 

then run Migrating and seeding .

**Comment by wa7eedem** [comment]
> Mine is in 5.4.

so I think its because php 7.0 !
@jerauf  what is your php version ?

**Comment by cerelli** [comment]
Same here.
Tested with Laravel 5.5, PHP 7.1.9 , fresh install.

I run 

> php artisan vendor:publish

Then ???

**Comment by wa7eedem** [comment]
its should give you a list , choses as in the image : 
![screen shot 2017-09-04 at 6 53 39 pm](https://user-images.githubusercontent.com/1952412/30033242-dcbfdbce-91a2-11e7-96d0-db44328fa638.png)

then `php artisan migrate`
then `php artisan db:seed`

its should be working now ,, hoping @fherryfherry will find a solution soon .

**Comment by cerelli** [comment]
Okay, now works, but after login this is the answer:
The page has expired due to inactivity. 

Please refresh and try again.

**Comment by wa7eedem** [comment]
try to delete the files
'database/migrations/2014_10_12_000000_create_users_table.php' ,
'database/migrations/2014_10_12_100000_create_password_resets_table.php'
and  delete all the tables in the database
 
then do it again ..
`php artisan vendor:publish`
`php artisan migrate`
then `php artisan db:seed`
again

**Comment by cerelli** [comment]
I refresh all installation. The problem is in CrudboosterinstallationCommand.php at line 56: 
$this->callSilent('vendor:publish');
requires confirmation.

**Comment by imanghafoori1** [comment]
I had the same problem after upgrading to 5.5
downgrading to 5.4 solved the problem

**Comment by jalal-haider-makki** [comment]
I also had the same problem. Need to follow couple of steps to make it work (Steps are tested on fresh install)

**Prerequisites**
1. New Project is created
2. Installed CrudBooster from Composer
3. Added Class in config/app.php
4. Database configurations are updated as per your local environment

**Installation**
1. First of all publish LFM using following commands (LFM is installed as a dependency of CrudBooster)
` php artisan vendor:publish --tag=lfm_config`
 `php artisan vendor:publish --tag=lfm_public`
2. Now modify Line No. 56 (Thanks to @cerelli ) in `~\vendor\crocodicstudio\crudbooster\src\commands\CrudboosterInstallationCommand.php`
it should be this
`$this->callSilent('vendor:publish',['--provider'=>'crocodicstudio\crudbooster\CRUDBoosterServiceProvider','--force'=>true]);`
3. Now run the install command in terminal
`php artisan crudbooster:install`

It will work fine on Laravel 5.5 ;)

**Comment by kusnadi99** [comment]
thank you.. it work as well..

**Comment by asharekh** [comment]
i found it in line 99 instead of 56. and it is working well.

**Comment by tranghaviet** [comment]
thanks @jalal-haider-makki 
I think it should has change on source code or documents.

**Comment by abmcr** [comment]
thanks @jalal-haider-makki

**Comment by vin33t** [comment]
> I also had the same problem. Need to follow couple of steps to make it work (Steps are tested on fresh install)
> 
> **Prerequisites**
> 
> 1. New Project is created
> 2. Installed CrudBooster from Composer
> 3. Added Class in config/app.php
> 4. Database configurations are updated as per your local environment
> 
> **Installation**
> 
> 1. First of all publish LFM using following commands (LFM is installed as a dependency of CrudBooster)
>    ` php artisan vendor:publish --tag=lfm_config`
>    `php artisan vendor:publish --tag=lfm_public`
> 2. Now modify Line No. 56 (Thanks to @cerelli ) in `~\vendor\crocodicstudio\crudbooster\src\commands\CrudboosterInstallationCommand.php`
>    it should be this
>    `$this->callSilent('vendor:publish',['--provider'=>'crocodicstudio\crudbooster\CRUDBoosterServiceProvider','--force'=>true]);`
> 3. Now run the install command in terminal
>    `php artisan crudbooster:install`
> 
> It will work fine on Laravel 5.5 ;)

Thanks It works
