### ISSUE TITLE
Not working load external js and css

### ISSUE THREAD

**Issue by azmigit** [crocodic-studio/crudbooster#808]
<img width="606" alt="screen shot 2017-09-07 at 12 54 31" src="https://user-images.githubusercontent.com/12572109/30148035-d26f2ac8-93cb-11e7-947f-5370ae8294d6.png">

<img width="282" alt="screen shot 2017-09-07 at 12 56 57" src="https://user-images.githubusercontent.com/12572109/30148087-1021fa76-93cc-11e7-9e5b-2e77f6d2e538.png">

**Comment by tomatoe45** [comment]
Hi @azmigit in myfile.css it should be your_file_filename.css

example $this->load_css = array("main.css");

because myfile.css  file not exist in your project..
