### ISSUE TITLE
sub_module error

### ISSUE THREAD

**Issue by mtran0281** [crocodic-studio/crudbooster#81]
Hi,

I am getting an error `Illegal string offset 'path'` when I use the sub_module function in the controller.

I have AdminFromCasesController and AdminFromCasedetailsController controllers, I set the sub_module in the AdminFromCasesController.

```
$this->sub_module     = array(
            'label'=>'Case Details',
            'icon'=>'fa fa-bars',
            'path'=>'from_casedetails',
            'foreign_key'=>'CaseId'
        );
```

Could you point me in the right direction to troubleshoot this error

**Comment by fherryfherry** [comment]
The truth is : 
`$this->sub_module[] = array( .......`

not
`$this->sub_module = array( ....`
