### ISSUE TITLE
Uncaught TypeError: $(...).fancybox is not a function (All Javascript From MainJS not working)

### ISSUE THREAD

**Issue by esdayehezkiel** [crocodic-studio/crudbooster#824]
I get this error when i upload my project to Live Hosting, all javascript not working in live site but my localhost working perfectly. Anyone can help?

**Comment by harimayco** [comment]
please make sure you have 'crudbooster' symlink file inside your public/vendor folder.
![screenshot_20170913_094713](https://user-images.githubusercontent.com/5478980/30357442-d2952c40-9868-11e7-9743-36865d00c04d.png)

**Comment by esdayehezkiel** [comment]
Solved, thanks bro @harimayco
