### ISSUE TITLE
how show only data of connected user_id

### ISSUE THREAD

**Issue by oneill78** [crocodic-studio/crudbooster#828]
Hello,
I want to display only the data of the logged-in user in his dashboard.
How to use CRUDBooster :: myId () and where to add it to the controller ?
or is it possible to select it in module creation.
Thank you for your help

**Comment by jdredondo** [comment]
you can use 'hook_query_index' method:
`public function hook_query_index(&$query) {
	        $query->where('id_cms_users',CRUDBooster::myId());
	    }`

**Comment by oneill78** [comment]
Thank you very much jdredondo.
it work.

**Comment by jpliraa** [comment]
Is deprecated on v6? i found on crudbooster page this "cb()->session()->id()"

In wihch file i need to place this?:
public function hook_query_index(&$query) { $query->where('id_cms_users',CRUDBooster::myId()); }
I trying to put it on the associated controller for the table i want to show
Please help me

Thanks you!!!
