### ISSUE TITLE
Can't retrieve data from admin app after uploading it to server

### ISSUE THREAD

**Issue by suprex29** [crocodic-studio/crudbooster#837]
please help me, admin apps can not retrieve database after uploading it to server (Centos 7, nginx web server, php5.6) but it works perfectly on my linux localhost,  thank you for your helps (sorry for my bad english), 
![trs](https://user-images.githubusercontent.com/31305703/30474080-a9dab660-9a2c-11e7-9886-5f994a2da224.png)

**Comment by suprex29** [comment]
nevermind, just changing the nginx configuration and its work again, thanks

**Comment by akuthedeveloper** [comment]
what about on the Apache server
