### ISSUE TITLE
Nested Select

### ISSUE THREAD

**Issue by GlobalSolutions2018** [crocodic-studio/crudbooster#844]
Hello
is it possible to have nested select in one form, how the could be achived 
 example:  country, region, city 

using latest versions of laravel & crudbooster

**Comment by harimayco** [comment]
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-make-graded-select-box.md

**Comment by GlobalSolutions2018** [comment]
thank you , i guess that will solve it,
