### ISSUE TITLE
Problem with assets directory on exFAT (symlink not work)

### ISSUE THREAD

**Issue by mindonline** [crocodic-studio/crudbooster#850]
Symlink not work on exFAT file system, (as result the public/vendor/croodbooster is not exist) is possible to overcome this wth out converting fs to other format?

**Comment by DeveloperOnCall** [comment]
You could - altho not recommended:

Copy/Move all of the files from... 
`/vendor/crocodicstudio/crudbooster/src/userfiles/views/vendor/crudbooster`

Into the public location...
`/public/vendor/crudbooster`

Hope that helps.

**Comment by mindonline** [comment]
Its not work because every time I go into /admin/ it remove /vendor/crocodicstudio/ from public dir.

**Comment by DeveloperOnCall** [comment]
Just so I am clear -- going to /admin/ - ends up deleting the files you copied to that location?

I am not sure if that is even possible - but I will do some digging tonight and see if I can find something that would make that happen.

D

**Comment by mindonline** [comment]
Yes, its rename "crocodicstudio" folder from public  and try to create symlink.
The problem in default installation for laravel 5.4 -
`composer require crocodicstudio/crudbooster`
 Every time when laravel serve pages it call **symlinkFixed** in [CRUDBoosterServiceProvider](https://github.com/crocodic-studio/crudbooster/blob/5.4.0/src/CRUDBoosterServiceProvider.php)

However, in latest dev-master it don't rename old "crudbooster", and manually moving assets work.
