### ISSUE TITLE
can not login to crudbooster after create users

### ISSUE THREAD

**Issue by zendzo** [crocodic-studio/crudbooster#859]
i followed the instruction and open localhost:8000/admin/login

after i open terminal and run artisan tinker
factory(App\User::class,1)->create(); (successfully)

but still i can't login

**Comment by DeveloperOnCall** [comment]
Do not use Laravel to generate the user - follow the[ install directions for CRUDBooster](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/installation.md). Namely the command.

`php artisan crudbooster:install`

This will set up the admin login and you should be able to login.

D
