### ISSUE TITLE
5.3 version

### ISSUE THREAD

**Issue by num3r06** [crocodic-studio/crudbooster#86]
Hi,
this it's a very great job.
Two question for you: dev-master version is compatible with laravel 5.3 version?
After generate module it's can i use laravel Models based on db table?
Thx

**Comment by fherryfherry** [comment]
yes its support with laravel 5.3
yes,  you can, just create a model as usually.
You can use dev master as test only :D , because in future update still there are a lot of changes,and there is no documentation for it.

**Comment by dikobagda** [comment]
Hi,

Awesome project. I using laravel 5.3 try to generate the database using migrate command, but there is error in query builder::lists() not found. i read in some article laravel 5.3 deprecated method builder::lists(). 

But it works in 5.2.*

**Comment by fherryfherry** [comment]
CRUDBooster 5.3 just released, thanks
