### ISSUE TITLE
Disabling Generator on production site

### ISSUE THREAD

**Issue by tqooze** [crocodic-studio/crudbooster#87]
I've come across this module while searching for the fastest way to develop website for clients using laravel. It was a great effort from you guys. salute from me. But I have one question. Is there any way for me to disable module/api generator on production site? I would love to have this kind of features to help me in future. 

Thanks in advance.

**Comment by fherryfherry** [comment]
Hi, unfortunately, there is no way for 5.2, you may use CRUDBooster 5.3
You may use the API Documentation by visiting /public/api-documentation
