### ISSUE TITLE
Image displaying as thumbnail on the view

### ISSUE THREAD

**Issue by arthurzeras** [crocodic-studio/crudbooster#879]
I have a table with a image field, and when i upload a image and try to show it on the application view (not admin panel), is displaying on low resolution like a thumbnail. I want to show the image in the real size and resolution.

**Comment by anuj509** [comment]
You can disable this behavior from config file. Ie we can set thumbnail size to 0 in order to keep image size as original as it was uploaded.

**Comment by anuj509** [comment]
https://github.com/crocodic-studio/crudbooster/issues/753   this might help

**Comment by arthurzeras** [comment]
Thanks anuj509, it works!

**Comment by anuj509** [comment]
Great 👍
