### ISSUE TITLE
Issue after deleting module.

### ISSUE THREAD

**Issue by edemir206** [crocodic-studio/crudbooster#88]
Hi,

First, awesome job, this tool has all features I ever wanted for a backend.

The issue happens when I created a module, after deleting the created module it says 
"Route [AdminPessoaControllerGetAdd] not defined."

**Comment by fherryfherry** [comment]
Hi, tell me your CRUDBooster version ?

**Comment by edemir206** [comment]
it's the latest version, just installed from tutorial. Laravel 5.3

**Comment by fherryfherry** [comment]
You should delete the menu at table cms_menus

**Comment by edemir206** [comment]
Perfect, it worked, but shouldn't the menu be excluded automatically ?

**Comment by fherryfherry** [comment]
I'll try to find the best way to solve this problem
