### ISSUE TITLE
multiple column dropdown select2 error.

### ISSUE THREAD

**Issue by edemir206** [crocodic-studio/crudbooster#89]
After selection two columns on select2 dropdown it gives an error: Call to undefined function crocodicstudio\crudbooster\controllers\get_columns_table()

		$this->form[] = array("label"=>"Marca - Modelo","placeholder"=>'sadsadd',"name"=>"id_modelos","type"=>"select2","required"=>TRUE,"validation"=>"required|integer|min:0","datatable"=>"modelos,id_marcas,marcas,id",'datatable_format'=>'marcas.nome,\' \',modelos.nome');

in previous version this worked, but now the error is shown.

**Comment by edemir206** [comment]
Hi,

I managed to solve this problem by doing this:

opened file vendor\crocodicstudio\crudbooster\src\helpers\Helper.php

Pasted the below code after start of <?php :

```
if(!function_exists('get_columns_table')) {
function get_columns_table($table) {
    $cols = DB::getSchemaBuilder()->getColumnListing($table);
    $result = array();
    $result = $cols;

    $new_result = array(); 
    foreach($result as $ro) {
        if($ro=='created_at' || $ro=='updated_at' || $ro=='id' || $ro=='deleted_at') continue;        
        $new_result[] = $ro;
    }
    return $new_result;
}
}
```

**Comment by fherryfherry** [comment]
Hi you are right I have fixed it at master
