### ISSUE TITLE
updater not found

### ISSUE THREAD

**Issue by juliocesarcr** [crocodic-studio/crudbooster#9]
I followed step by step installation guide , at the end when you are installing , fails,

Not Found

The requested URL /myapp/updater was not found on this server.
Apache/2.4.9 (Win32) PHP/5.5.12 Server at localhost Port 80

**Comment by fherryfherry** [comment]
Please make sure with your folder apps

if you make a folder "MyApp" , 
url should be http://localhost/MyApp/install/index.php instead http://localhostl/myapp/install/index.php

**Comment by juliocesarcr** [comment]
That's right, and fails ...
![error 1](https://cloud.githubusercontent.com/assets/20862155/17442575/544e05e8-5b04-11e6-88e1-6f73a233d73d.jpg)
![error 2](https://cloud.githubusercontent.com/assets/20862155/17442576/545391ac-5b04-11e6-936d-7740cc35caba.jpg)

**Comment by fherryfherry** [comment]
May i see your folder app name in _win explore_ ?

**Comment by juliocesarcr** [comment]
![folder](https://cloud.githubusercontent.com/assets/20862155/17443472/d1aa45ac-5b08-11e6-9f81-632bdd9568b9.jpg)

**Comment by fherryfherry** [comment]
try new folder name and try write folder name in lowercase

**Comment by juliocesarcr** [comment]
Ready, and everything is written in lowercase , continues mistake, as I see the error is looking for a file or a folder called updater that is not nowhere .

**Comment by Ogiaja** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20460954/17454687/b90d804c-5bc9-11e6-90c4-8c41a566e2eb.png)
Heyy... so how to fix it? thks
