### ISSUE TITLE
Menu dashboard always /admin 

### ISSUE THREAD

**Issue by Max75010** [crocodic-studio/crudbooster#913]
It seems that the first menu "dashboard" is not the right one.
The problem : I created 2 privileges and 2 dashboards (1 dashboard by privilege un the database) and the first item menu dashboard always redirects on /admin.

I managed to correct this in the crudbooster sidebar.blade.php view by replacing CRUDBooster::adminpath() by $dashboard->url:

<?php $dashboard = CRUDBooster::sidebarDashboard();?>
                @if($dashboard)
                    <li data-id='{{$dashboard->id}}' class="{{ (Request::is(config('crudbooster.ADMIN_PATH'))) ? 'active' : '' }}"><a href='{{$dashboard->url}}' class='{{($dashboard->color)?"text-".$dashboard->color:""}}' ><i class='fa fa-dashboard'></i> <span>{{trans("crudbooster.text_dashboard")}}</span> </a></li>
                @endif

Is it a bug ? Or did I missed something ?
 (by the way thank you, really nice job)

**Comment by imanghafoori1** [comment]
You can submit a PR for it.

**Comment by imanghafoori1** [comment]
fixed On master branch
