### ISSUE TITLE
concatenate two fields

### ISSUE THREAD

**Issue by edu17** [crocodic-studio/crudbooster#924]
I would like to Concatenate two entries,
Example
Name (s
surnames
full name = first names + last names

which is executed in real time at the time of writing

Can someone help me?

![image](https://user-images.githubusercontent.com/23388245/31916564-857068d6-b810-11e7-8b4a-117b9884189a.png)

**Comment by imanghafoori1** [comment]
what do you mean by : 
executed in real time at the time of writing ?!

**Comment by abenzakour** [comment]
You want to concat ( Nombres and Apellidos ) in Nombre Completo at the same time of writing ? 

If it is your need; yes you can do it using Javascript and keyup event; check this link 

https://api.jquery.com/keyup/
