### ISSUE TITLE
use join in form data modal type?

### ISSUE THREAD

**Issue by azarzaza** [crocodic-studio/crudbooster#933]
how to implement join in data modal

**Comment by abenzakour** [comment]
You can use sql view

**Comment by azarzaza** [comment]
share me some code how to implement

**Comment by abenzakour** [comment]
https://www.w3schools.com/sql/sql_view.asp

**Comment by azarzaza** [comment]
thanks man !

**Comment by squidv3** [comment]
tanks man

**Comment by rizkytester** [comment]
can you share me some code for my reference?

**Comment by rizkytester** [comment]
> 
> 
> https://www.w3schools.com/sql/sql_view.asp

i have try to your referrence but i got error in "order by" bcause table view have no id auto increment. can i got solution sir??

**Comment by sispan** [comment]
do you fix this problem? i got this error too
