### ISSUE TITLE
How do I allow user registration ??

### ISSUE THREAD

**Issue by edemir206** [crocodic-studio/crudbooster#96]
in the 5.2 version I remeber I could easily allow user registration from login screen, but now I can't seem to find this option. am I missing something ?

**Comment by fherryfherry** [comment]
User regist was deprecated

**Comment by edemir206** [comment]
Are you serious? Why?

Em sex, 16 de dez de 2016 18:52, Ferry Ariawan <notifications@github.com>
escreveu:

> User regist was deprecated

**Comment by fherryfherry** [comment]
Yes i think its better we create manually if we need

**Comment by DeveloperOnCall** [comment]
Deprecating such a basic feature is unbelievable!
