### ISSUE TITLE
fails date validation in dd/mm/yyyy format

### ISSUE THREAD

**Issue by fsclaro** [crocodic-studio/crudbooster#960]
- Operating system (name, version and architecture): Mac High Sierra
- Web server (name, version and architecture): Apache 2.4.29
- Browser (name, version and architecture): Chrome and Safari
- CRUDBooster version: 5.4.0.10
- Laravel version: 5.4.*
- What is the problem?

I have a date field in a form that is in the format dd / mm / yyyy and I need to do its validation.
I analyzed the framework and realized that crudbooster uses the Validator class of laravel and uses the trait ValidatesAttributes.
In the function validateDate the php date_parse () function is used, which analyzes the date.
However, this function uses the mm / dd / yyyy format.
And because of this the validation fails.
How can I make my date validations in the format dd / mm / yyyy?

**Comment by imanghafoori1** [comment]
is "validateDate" part of crudbooster code ? or laravel's internals ???

**Comment by goranculibrk** [comment]
@fsclaro I'm not really great with Laravel, but can't you do a workaround by using Carbon to convert your date from dd/mm/yyyy to mm/dd/yyyy and then use validateDate?

**Comment by fsclaro** [comment]
[SOLVED]

I change the validation rule in form array in my Controller, using dateformat:d/m/Y the validation work well. i.e.

$this->form[] = ['label'=>'Start Date','name'=>'start_date',  'type'=>'date','validation'=>'required|dateformat:d/m/Y','width'=>'col-sm-2'];
