### ISSUE TITLE
Problem in add method with Primary Key ID as a string

### ISSUE THREAD

**Issue by fdigennaro** [crocodic-studio/crudbooster#962]
I've a table with ID as varchar(8) Primary Key.

When use Add method, the correct value in the table is not entered

![cattura1](https://user-images.githubusercontent.com/2597427/32784661-bd8f15d2-c94f-11e7-9b38-d9d8bdddc0b1.PNG)

![cattura2](https://user-images.githubusercontent.com/2597427/32784676-c29aab18-c94f-11e7-8fc9-17c4c9d555f0.PNG)

After use Edit Method to correct, and correct value is stored

**Comment by fdigennaro** [comment]
I found the problem.

The system auto-increments the id field. how to disable it?

**Comment by imanghafoori1** [comment]
You can install the dev-master branch
I think I have fixed it already

**Comment by fdigennaro** [comment]
I've issue #759 when upgdating to master branch

**Comment by imanghafoori1** [comment]
You can go to the source code of crudbooster and comment out does lines which increment the id +1
when inserting

**Comment by fdigennaro** [comment]
I changed my tables by inserting integer id as primary key, but now I have a relation type:

TableA (many)->(one) TableB (many)->(one) TableC.

![image](https://user-images.githubusercontent.com/2597427/33079655-74a994be-ced6-11e7-9956-7976660a79a5.png)

When use Add method i need to insert with select2 in cambioreel the id_jobs but i need to show nr_commessa related in commesse.

In Grid view i've make a custom sql code and i show nr_commessa:

`$this->col[] = ["label"=>"Nr Commessa","name"=>"(select nr_commessa from commesse where jobs.id_commesse = commesse.id) as nr_commessa"];`

![image](https://user-images.githubusercontent.com/2597427/33079928-1cef7b2a-ced7-11e7-9ac4-c63563d0d1a8.png)

How to show nr_commessa in Add form ?
