### ISSUE TITLE
No Id in a table - results in error when trying to display all rows?

### ISSUE THREAD

**Issue by shez1983** [crocodic-studio/crudbooster#968]
I am trying to create a module for a table which has no primary Id (just has a user_id, its supposed to be a belongsTo a User table..   

i created the module fine - but when i try to go to it (ie list all rows) - i get an error saying shops.id doesnt exist.. 

so am i guessing that each table NEEDS to have an id column? 

Version:    v5.4.0.10

**Comment by renzocastillo** [comment]
Yes. It's a must.
