### ISSUE TITLE
impossible to install crudbooster 

### ISSUE THREAD

**Issue by iCobra11** [crocodic-studio/crudbooster#976]
Hi,
I'm working on the following system

- Operating system: Linux Mint 18.2
- Web server: Apache/2.4.18 (Ubuntu) 
- Browser: 53.0.3 (64-bit)
- CRUDBooster : 5.4.0.10
- Laravel version: 5.5

Is the first time for me to work with Laravel and crudbooster so, I tested the example "Simple stock" and it work fine.
At this point I want create a new project but, despite i followed a lot of video and howto, is impossible install CB, I have the error below:

[.....]
 You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
Installation failed, deleting ./composer.json.

I read #866 but nothing, The same thing happened and the command file is correct to "call" else "callSilent"

No problem from Laravel itself.

what do you think about?

Thank you for your attention and suggests

**Comment by renzocastillo** [comment]
Have you checked this #799 ?

**Comment by iCobra11** [comment]
Hi renzocastillo
thank you for your suggest I solved as below.
I followed jalal-haider-makki step but:
step 1: new project successfully created
step2: inside the new project I run "# composer require crocodicstudio/crudbooster"
command but I stopped with the "Installation failed, reverting ./composer.json to its original content." message
So The problem for me is  I'm not able to install crudbooster and not to run the app after installation.
I read also this : https://laracasts.com/discuss/channels/forge/error-while-updating-to-php-70-on-forge this explain a similar trouble so after this, #797 help me to understand: missing php-dompdf package was the problem.
#apt-get install php-dompdf 
solved the troble and crudbooster now is install.
Thank you very much for your attention.
