### ISSUE TITLE
DatePicker on Child Add Data Modal

### ISSUE THREAD

**Issue by h3ndro** [crocodic-studio/crudbooster#98]
hi, great job on the new version, quick question, i've setup my form to have a child field type. It works well but, when i try to add new data to it via parent form, the date picker is not working,....

![image](https://cloud.githubusercontent.com/assets/570127/21305946/f3285742-c600-11e6-8a09-1e77aa3e7fa0.png)

maybe you could add a reference to datepicker lib on the modal?thx

**Comment by fherryfherry** [comment]
bug fixed in master
