### ISSUE TITLE
How to override functionality

### ISSUE THREAD

**Issue by Muhammadinaam** [crocodic-studio/crudbooster#99]
If I want to override any functionality.

For example
if I have a module or Model called brand.php and I want to change the controller function for any route. How can I do that? For example I want to create my own function for any url or route how can I do that??

??

**Comment by fherryfherry** [comment]
You may use __contruct

**Comment by Muhammadinaam** [comment]
Please explain with little example.

**Comment by ishitat** [comment]
There is no detailed explanation.

**Comment by Devamit2016** [comment]
how can we override controller?
