### ISSUE TITLE
Email validation not working. Email being saved even if email already exists.

### ISSUE THREAD

**Issue by nyel-dev** [crocodic-studio/crudbooster#990]
I am currently making a create user API using CrudBooster API generator. I am successful in creating the API, however, I found out that the email validation is not working. It is creating the user but it is saving the user even though the email already exists. Can someone pls guide me on this one? Thanks so much!

**Comment by nyelnyelnyel** [comment]
@fherryfherry may I ask if you know how to do this? thanks mate!
